### ISSUE TITLE
Allowing users to upload activities in CSV and XML with errors

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1005]
Currently, if a user uploads activities in CSV and XML format with errors, the users is shown the issues and not allowed to upload the activities. 

The user should be allowed to upload the activities with errors but the upload goes in following flow:

- [ ] Divide the errors in three categories: Critical, Errors and Warnings
- [ ] Show the critical, errors and warnings to user and also mention in critical section that 'The activity cannot be imported to our system', error section that 'These will not be uploaded in the activity' and in warnings section, ' These will be uploaded but you have to fix it in the system before publishing it'.
- [ ] After the activities are uploaded excluding the errors, show the list of warnings in the activity detail page and let the user check and remove the items in the list by clicking 'Delete'
- [ ] Once all the items are checked, remove the list of warnings from the detail page.

**Comment by praweshsth** [comment]
cc: @DaveEade49 @k8hughes Please suggest on this.

**Comment by SauravSilwal10** [comment]
@sriza  Issue found in this branch 

- [ ] **Issue 1: The user cannot import the existing file.**


![Image](https://user-images.githubusercontent.com/78422663/220289307-558ea9e8-8368-4251-ad82-c93955de8aaa.png)


- [ ] **Issue 2: When a user does not enter the IATI-identifier in the XML file error message doesn't error.**


https://user-images.githubusercontent.com/78422663/220297093-561dc486-c909-4df6-8d5e-4fb9384604ce.mp4

- [ ] **Issue 3: A different title appears on the detail page and listing page.**


https://user-images.githubusercontent.com/78422663/220291615-41a19a81-bb1c-4746-8686-cfb0a8c21865.mp4


- [ ] **Issue 4: General value occurs as default value in the description.**


https://user-images.githubusercontent.com/78422663/220293378-471bdfdb-df4d-4585-b961-56554e1684c4.mp4


- [ ] **Issue 5: Default language narrative value disappear if two language gets matched.** 


https://user-images.githubusercontent.com/78422663/220296160-2a96da95-13e8-4b69-953e-be6122c9dbbf.mp4



- [ ] **Issue 6: Same error message is displayed as a warning in the title and error in the description.**


![Image](https://user-images.githubusercontent.com/78422663/220295054-a0e67fd9-9929-41a3-bc49-ebf12bf346dd.png)


- [ ] **Issue 7: NO validation message for zero in activity status and activity scope.**


https://user-images.githubusercontent.com/78422663/220294040-1409245a-9877-4923-a792-c54d6fa13412.mp4

**Comment by sriza** [comment]
Merged to main branch. Closed manually
