### ISSUE TITLE
Rules for recipient country and recipient region in activity level

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1006]
**Rules for the recipient country and recipient region in activity level:**

- [x] If the Recipient Country’s percentage is 100% then the Recipient Region’s percentage must be either 0% or empty otherwise show an error message below Recipient Region’s percentage that ‘Recipient Country’s percentage is already 100%. The sum of the percentages of Recipient Country and Recipient Region must be 100% ’. In this case, consider the Recipient Region as complete so that the completion of the Recipient Region is also added to the progress of the activity’s completeness.  
- [x] If the Recipient Region’s percentage is 100% then the Recipient County’s percentage must be either 0% or empty otherwise show an error message in Recipient Country that ‘Recipient Region’s percentage is already 100%. The sum of the percentages of Recipient Country and Recipient Region must be 100%. ’ In this case, consider the Recipient Country as complete so that the completion of the Recipient Country is also added to the progress of the activity’s completeness.
- [x] If Recipient Country’s percentage is less than 100%, let's say 20%, then 

Conditions | Percentage Value | Error Message if the conditions are not met
-- | -- | --
There is only one recipient region | RR1 = 80% | The sum of the percentages of Recipient Country(ies) and Recipient Region(s) must always be 100%
There are multiple recipient regions with same vocabulary (e.g. OECD DAC) | RR1 (OECD DAC) = 30%<br>RR2 (OECD DAC) = 40% <br>RR3 (OECD DAC) = 10% | 1. If the sum of percentages of the recipient country and the recipient regions are not equal to 100% then show error ‘ The sum of percentages of Recipient Country and Recipient Regions with same Region Vocabulary must be equal to 100%’
There are multiple recipient regions with different Region Vocabulary | RR1(OECD DAC) = 40%<br>RR2(OECD DAC) = 40%<br>RR3(UN) = 80%<br>RR4(Reporting organisation) = 80% | 1. If the sum of percentage of the recipient country and the recipient regions (within the same Region Vocabulary) is not equal to 100% then show error ‘ The sum of percentage of Recipient Country and Recipient Regions (within the same Region Vocabulary) must be equal to 100%’ <br>2. The percentages of different recipient region vocabularies must be equal to one another.<br>3. If percentages of different recipient region vocabularies is equal to one another but not equal to 100-percentage of Recipient country then show ‘The sum of recipient country and recipient region of a specific vocabulary must be 100%.

- [x] If the Recipient Region’s percentage (of single or sum of multiple) is x%, the sum of percentages of the Recipient Countries should be equal to (100-x)% otherwise show an error message ‘The sum of percentages of Recipient Region(s)  and Recipient country must be 100%’
- [x] If the Recipient Region or Recipient County is added at the transaction level, then show the error message in activity level that ‘Recipient Region and/or Recipient Country is(are) already added at transaction level. You can add a Recipient Region and/or Recipient Country either at activity level or at transaction level but not at both.’ If transaction level is used then completeness of Recipient Region and Recipient Country should be considered not adding them in this level.

**Comment by SauravSilwal10** [comment]
@A4family Issue found in this branch.
 

- [ ] Issue 1 : Recipient country should not be duplicated.

 
![Image](https://user-images.githubusercontent.com/78422663/218381498-cf256869-321c-4e91-82fb-2ad4ffc2a036.png)

- [ ] Issue 2 :  Improve error message just display "The recipient country percentage must be at least 0. "



![Image](https://user-images.githubusercontent.com/78422663/218381843-c4aae061-e8f4-4548-baac-a4a5dea8acd5.png)

- [ ] **Issue 3 : Complete status is not working properly.**


![Image](https://user-images.githubusercontent.com/78422663/218383754-ac93d66a-22f3-46d2-965a-abf70ce601a9.png)

- [ ] **Issue 4 : The sum of the percentages of Recipient Country(ies) and Recipient Region(s)  is not 100.**

The sum of the percentages of Recipient Country(ies) and Recipient Region(s) must always be 100%

**Comment by sriza** [comment]
Merged to main branch and closed manually.
