### ISSUE TITLE
Rules for recipient country and recipient region at transaction level

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1007]
- [x] If the Recipient Region or Recipient Country is added at the activity level, then show the error message ‘Recipient Region or Recipient Country is already added at activity level. You can add a Recipient Region and or Recipient Country either at activity level or at transaction level.’ If activity level is used then completeness of transaction should consider not adding Recipient country or Recipient Region in transaction level. 
- [x] If a user has already added a Recipient Region or a Recipient Country in a transaction then each transaction added later must have either a recipient country or recipient region. Each transaction can only have either a recipient country or a recipient region and not both. Otherwise show the error message that ‘You must add either recipient country or recipient region’

**Comment by SauravSilwal10** [comment]
@A4family  Issue found in this branch.

- [ ] **Issue 1:  "You must add either recipient country or recipient region." validation is not working.**


https://user-images.githubusercontent.com/78422663/217764022-97854940-40a5-400a-bfea-0137f3c8d86a.mp4

**Comment by SauravSilwal10** [comment]
@A4family **When user tries to save the transaction edit form Server Error occurs**

https://user-images.githubusercontent.com/78422663/218396473-017a3d8d-e2d5-43bb-ab75-083ed155937c.mp4

**Comment by sriza** [comment]
Merged to the main branch. Closed manually.
Rule changes for import are done in issue #1082 .
