### ISSUE TITLE
Rules for sector in activity level

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1008]
- [x] When multiple sectors with the same vocabulary are used, the percentage of each sector must not be empty and the sum of those percentages must be 100%. If one of the sector’s percentage is not added then show the error message ‘The percentage can not be empty’. If the sum of all the percentages is not equal to 100%, then show the error ‘The sum of percentages of same vocabulary must be equal to 100%’
- [x] When a single sector is used, the percentage must be either 100% or empty (which means it is assumed as 100%). Otherwise show an error ‘The percentage must be 100% or left empty, which is assumed as 100%’
- [x] If no vocabulary is declared, OECD DAC 5-digit is assumed. When user publish the activity without anything in sector in activity level or transaction level, add OECD DAC 5-digit in vocabulary and 99810 in the code and then create XML. 
- [x] If vocabulary code 98 or 99 is declared, the user must enter a narrative for it. The narrative is only for 98 or 99 vocabulary codes.
- [x] If sector is already declared at transaction level then show an error message ‘Sector has already been declared at transaction level. You can’t declare a sector at the activity level.’ Also consider the completeness of the activity since the sector in activity level will not be completed.
- [x] Remove the restriction to 'must add OECD DAC 5-digit'

**Comment by praweshsth** [comment]
@A4family I have updated the criteria. Go ahead with the development and if you have any queries or confusion, we can discuss it.

**Comment by SauravSilwal10** [comment]
@A4family Issue found in this branch 

- [ ] **Issue 1:  A negative value in percentage is not allowed.**


![Image](https://user-images.githubusercontent.com/78422663/217989968-60dc8baf-2dd1-4e92-95a4-7a9555c2a3ba.png)


- [ ] **Issue 2: Complete status not working properly.**


https://user-images.githubusercontent.com/78422663/217990281-59600f11-a227-4cad-8916-17364573f3b7.mp4

**Comment by sriza** [comment]
Merged to the main branch. Closed manually.
Rule changes for import are done in issue #1082 .
