### ISSUE TITLE
Rules for sector in transaction level

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1009]
- [x] If sector is already declared at activity level, then show an error message ‘Sector has already been declared at activity level. You can’t declare a sector at the transaction level. To declare at transaction level, you need to remove sector at activity level.’
- [x] If a sector is declared at transaction level and the user leaves the sector empty in another transaction, then show an error message ‘You have declared sector at transaction level so you must declare sector for all the transactions.’ consider the completeness of the transaction since the sector in the transaction will not be completed.

**Comment by sriza** [comment]
Merged to the main branch. Closed manually.
Rule changes for import are done in issue #1082 .
