### ISSUE TITLE
Rules for activity budget in activity level

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1010]
- [x] The period of a budget should not exceed more than a year. 
- [x] If budget-not-provided is used then the user doesn’t have to add budget. Consider the progress of activity completeness in this case.
- [x] The periods of multiple budgets with the same ‘@type’ should not be the same or overlap. In this case each period with the same ‘@type’ should be unique. 
- [x] The budget with type ‘Revised’ should match period with one of the budgets with type ‘Original’
- [x] Budget value should not be negative.
- [x] If  ‘@type’ is empty, it is assumed as ‘Original’.
- [x] If ‘@status’ is empty, it is assumed as ‘Indicative’.

**Comment by SauravSilwal10** [comment]
@A4family  Issue Found in this branch.

- [ ] **Issue 1 : The periods of multiple budgets with the same ‘@type’ should not be the same or overlap. In this case each period with the same ‘@type’ should be unique. This issue is not working properly.**
![Screenshot](https://user-images.githubusercontent.com/78422663/218377501-2a118444-d5e3-4ea2-92ee-db40a711d880.png)

**Comment by praweshsth** [comment]
Error messages: 

- [ ] If the period of a budget exceeds a year then show error "The period must not exceed a year."
- [ ] The periods of multiple budgets with the same ‘@type’ should not be the same or overlap. In this case each period with the same ‘@type’ should be unique. If it happens, show error "The periods with same @type must not be same or overlap". Show this error in all the periods that are same or overlap.
- [ ] The budget with type ‘Revised’ should match period with one of the budgets with type ‘Original’, if not then show error "The revised budget's period must match with an original budget's period."
- [ ] If budget value is negative then show error "Budget value must not be negative."
