### ISSUE TITLE
Rules for reporting-org

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1011]
### Requirements:
1. [x]  Use @ref,  @type, @secondary_reporter and @narrative of reporting_org from organisation for reporting_org of activitiy 
2. [x]  Ensure the following fields are uneditable on an activity level: 
    - [x] ref
    - [x] type
    - [x] narrative
3. [x]  Ensure the following on the organisation level:
    - [x] ref cannot be edited through reporting_org
    - [x] change in organisation identifier results in change in ref of reporting org.
4. [x] secondary_reporter is editable on an activity level. secondary_reporter on the organisation level is not affected by change in secondary_reporter in activity level.

**Comment by SauravSilwal10** [comment]
@PG-Momik   Issue found in this branch.

- [ ] **Issue 1 : Whenever user click on save button of reporting org , server error occurs.**


https://user-images.githubusercontent.com/78422663/221514977-9cf41935-3ce5-4e59-bb8c-f7b8a061f697.mp4


- [ ] **Issue 2 :Secondary reporter field differences in activity and organizational level**

![image](https://user-images.githubusercontent.com/78422663/221514475-3274913f-1d29-454d-b6b9-df884e637402.png)
![image](https://user-images.githubusercontent.com/78422663/221514581-db0bc9a5-7327-45c5-aa2d-b0932686dd92.png)
