### ISSUE TITLE
Develop script for migration from AidStream to IATI Publisher

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1012]
Prepare scripts for migration users and activities from AidStream to IATI Publisher.

- [ ] Database migration
  - Organization Migration
  - User Migration
  - Settings Migration
  - Activities Migration
    - Activity migration
    - Transaction migration
    - Result migration
    - Published data migration
    - Document data migration
    - Snapshot migration

- [ ] File migration
  - XML Migration
    - List Org and activity Specific XML file
    - Download those files
    - Upload those files
    - Link those files to IATI
  - Document Migration
    - List Org and activity Specific image, pdf file
    - Download those files
    - Upload those files

- [ ] Unpublish organisation data and activity in AidStream and publish them in IATI Publisher
- [ ] Migration of 50 organisation at once

**Comment by man-git007** [comment]
https://docs.google.com/spreadsheets/d/1FG7ZxmQdJe9oTjNgui_9PHtPNvYUGTOWG0F-L69IXzU/edit#gid=0

**Comment by SauravSilwal10** [comment]
@Sanilblank  Issue found in the organization and setting migrations.

- [ ] **Issue 1: Reporting org( reference and type) is not displaying on the activity detail page after migration.**

https://user-images.githubusercontent.com/78422663/225301192-25122fe2-cf96-4068-8ab0-6171c01cf552.mp4


- [ ] **Issue 2: A blank page is displayed when a user tries to view the organization detail page after the migration(org-id = 9 and 12).**

https://user-images.githubusercontent.com/78422663/225305736-838c791c-4f1a-4b8e-b4d2-f067f8146e24.mp4


- [ ] **Issue 3: API key is not verified in IATI publisher after the migration(org-id =150).**

https://user-images.githubusercontent.com/78422663/225301926-bb0336be-94c0-459a-be3a-0671097d6157.mp4


- [ ] **Issue 4: In org-id = 150 default language is not displayed on the organization detail page.** 

https://user-images.githubusercontent.com/78422663/225302686-0c6f4497-f2ae-4cdf-b797-d0254dbf95b4.mp4


- [ ] **Issue 5: When an organization is published in aidstream,  but the unpublish button doesn't appear in IATI Publisher after migration.**

https://user-images.githubusercontent.com/78422663/225303010-8166a015-b988-4125-9ee7-689b819c67e0.mp4

**Comment by sarinasindurakar** [comment]
- [ ] Even if the language is specified in override activity defaults, the setting default language is displayed.


https://user-images.githubusercontent.com/65848732/233953048-a880ef16-3d04-4812-bcac-38b376f55dbf.mp4

**Comment by sriza** [comment]
Merged to main branch. Closed manually.
