### ISSUE TITLE
Bug Related with Activity.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#1024]
- [x] **Issue 1: Bulk processing already in progress pop-up is displayed, when the user logged in through another organization.**

https://user-images.githubusercontent.com/78422663/215750297-a3a85b9c-8503-4f84-90df-51cf084137e4.mp4

- [x] **Issue 2: When a user is downloading a CSV file, the activity title name is not displayed on the downloaded CSV.**

https://user-images.githubusercontent.com/78422663/215751751-ce7f46e5-7843-4d76-b676-dc30eaa9e3c8.mp4

- [x] **Issue 3: Country code is not displaying on its identifier.**
![Screenshot from 2023-01-31 15-55-52](https://user-images.githubusercontent.com/78422663/215751887-fff04142-3464-4f9e-8a7b-bb817a0cb472.png)

- [x] **Issue 4: Before validating the core element, the activity couldn't be published popup should be shown.**

https://user-images.githubusercontent.com/78422663/215750297-a3a85b9c-8503-4f84-90df-51cf084137e4.mp4

**Comment by sriza** [comment]
@SauravSilwal10 
The title in the downloaded CSV is the title corresponding to the default language of the activity. If the activity doesn't contain title with default language, the title is empty in CSV file.

**Comment by sriza** [comment]
Merged to main branch. Closed manually.
