### ISSUE TITLE
DanChurchAid (Production) Errors on bulk publishing and request on single-publish

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1026]
We have two concerns, the first is about bulk publishing.
01:
When we are in our activities on IATI publisher and have ticked of e.g. two activities and tried to publish these via the “publish selected” button, we get an error saying we have another bulk-publish in progress. (which we don’t)
02:
When publishing a single activity it goes through the validator, see image 02A.

In the case where there is no errors, nothing seems to happen after validation, see image 02B.
Then we need to press “publish” again, before were met with a window that allows us to publish the activity, see image 02C.
The second issue is not as crucial as the first, it just confused us, because we wasn’t sure if it was already published, or what was going on.

I hope you can help in these matters

![01_Error_-_bulk_publishing_thumb](https://user-images.githubusercontent.com/110898894/215824673-bf0ae6eb-b082-41c5-a013-d0bd2752
![02A_-_error-free_publish_thumb](https://user-images.githubusercontent.com/110898894/215824694-5b8a1467-d34c-481e-9adc-0175b6ab348b.png)
cdcb.PNG)
![02B_-_Error-free_publish_thumb](https://user-images.githubusercontent.com/110898894/215824711-247e58b8-b1a0-4a29-ae64-f456fe78ef09.png)
![02C_-_Error-free_publish_thumb](https://user-images.githubusercontent.com/110898894/215824736-39c0ea9a-3a8c-4dab-a287-f9c9efe13b72.png)

**Comment by praweshsth** [comment]
Bulk publishing is an organization-level activity i.e if the bulk publishing is being done by any user of the organization, the bulk publishing in progress is shown to other users within the organization. An additional feature ‘cancel bulk publish’ has been added that allows the user can cancel bulk publish that is currently taking place.

Issue 02:
This issue has been solved and merged into the main branch.
