### ISSUE TITLE
UI Issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#1031]
- [x] **Issue 1: A flickering issue exists while publishing the activity.**

https://user-images.githubusercontent.com/78422663/216004260-8e1bad2b-af6b-40d3-95ea-65350abc2040.mp4

- [x] **Issue 2: Tooltip is hiding.**
![Screenshot from 2023-02-01 15-16-11](https://user-images.githubusercontent.com/78422663/216004781-6cb52e55-5150-4c78-b52f-f36a04bd9aac.png)

- [x] **Issue 3: The unpublishing/publishing process is not smooth.**

https://user-images.githubusercontent.com/78422663/216005399-8043bf3e-fb2a-4df6-89e9-e656fe103645.mp4

- [x] **Issue 4: When an element is deleted, the element's toast message should correspond to the update toast message.**

https://user-images.githubusercontent.com/78422663/216007801-e00fcb63-543c-4ae9-8263-b641b11928c1.mp4

**Comment by rajkarnikar11** [comment]
- [ ]  add loader in activity table
