### ISSUE TITLE
Issue Related with Translation 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#1043]
- [x] **Issue 1: None of the activities and the org page is not working.**

https://user-images.githubusercontent.com/78422663/217150982-c6d473ee-ad80-4041-a1cd-a1355d8b3230.mp4

- [x] **Issue 2: Reporting org is not displaying on the activity detail page.**

![Screenshot from 2023-02-07 10-03-28](https://user-images.githubusercontent.com/78422663/217151024-3493cc04-4e19-4b6f-9194-994516c62a52.png)

- [x] **Issue 3: Incorrect text is displayed on the tooltip.**

![Screenshot from 2023-02-07 10-03-28](https://user-images.githubusercontent.com/78422663/217151072-52379037-9a11-436b-932c-851d8eae1197.png)

- [x] **Issue 4: Remove _en**

![Screenshot from 2023-02-07 10-35-17](https://user-images.githubusercontent.com/78422663/217151153-848c509f-75d7-48b9-bf2c-16bbacd5f8b9.png)

- [x] **Issue 5: UI Issue in import activity**

![Screenshot from 2023-02-07 10-51-15](https://user-images.githubusercontent.com/78422663/217153403-c2a4fe26-2282-41c4-9a8a-79e396f647c2.png)

- [x] **Issue 6: Navbar is missing on the About us page.**

![Screenshot from 2023-02-07 10-35-59](https://user-images.githubusercontent.com/78422663/217151248-a25f89ac-683a-4f30-97c3-8fb222629eac.png)

- [x] **Issue 7: Invalid toast message when an element is updated and deleted.**

![Screenshot from 2023-02-07 10-15-57](https://user-images.githubusercontent.com/78422663/217148815-b74b7a6d-64a0-422e-9bda-6e6ad373fc97.png)

- [x] **Issue 8:  The profile icon is hiding when a user hovers over the icon.**

https://user-images.githubusercontent.com/78422663/217152039-ba5e8454-08c3-4ec3-a32a-bb05eeeda4aa.mp4

- [x] **Issue 9: I am already signup page is not working.**

![Screenshot from 2023-02-07 10-16-54](https://user-images.githubusercontent.com/78422663/217148914-4aaf83be-45d6-451d-a622-34f66f4984db.png)

- [x] **Issue 10: User Manual is not working**

https://user-images.githubusercontent.com/78422663/217151735-89d8999c-cc2b-40ff-9944-0f86020d6b6a.mp4

- [x] **Issue 11: Nav bar is missing from the about us page.**

![Screenshot from 2023-02-07 10-13-47](https://user-images.githubusercontent.com/78422663/217148569-bafdc3d6-30b1-42cd-a7af-b856030d700b.png)

- [x] **Issue 12: Org name is not displaying during super admin**

![Screenshot from 2023-02-07 10-25-28](https://user-images.githubusercontent.com/78422663/217150049-2324c566-037a-477e-ba53-725cd8080e0c.png)

- [x] **Issue 13: HTML tag is displaying**

![Screenshot from 2023-02-07 10-28-14](https://user-images.githubusercontent.com/78422663/217150359-12e04b67-055c-41b2-b23e-8a2b8a8fad4c.png)

- [x] **Issue 14: UI Issue** 

![Screenshot from 2023-02-07 10-31-45](https://user-images.githubusercontent.com/78422663/217150779-2ab83298-97bd-4745-b993-0bb2ac96e324.png)

- [x] **Issue 15: Make sure all the links are open in the next tab** 

https://user-images.githubusercontent.com/78422663/217153105-916e911a-7e18-4dcf-a366-ff7411dc7258.mp4

**Comment by PG-Momik** [comment]
@SauravSilwal10 these have been fixed. new issues(if) faced when implementing SPANISH can be dealt in another issue.

**Comment by PG-Momik** [comment]
I'm closing this, since these issues have been solved. New issues can be created after implementation of remaining transalation lines.
