### ISSUE TITLE
Bulk publish ui related issues

### ISSUE THREAD

**Issue by rajkarnikar11** [younginnovations/iatipublisher#1058]
- [x] Displaying error toast message even when activities are succesfully published
- [x] loader keeps loading in even after the publishing activity has failed

**Comment by rajkarnikar11** [comment]
Unable to recreate issue hence closed

**Comment by SauravSilwal10** [comment]
@rajkarnikar11  Issue in this branch

- [ ] **Issue 1: The bulk publishing process does not stop.**

**Comment by sarinasindurakar** [comment]
@rajkarnikar11 
- [ ] Issue 1:
When user unpublish the activity and make changes in the activity and tries to bulk publish the activity, wrong pop up message is shown.
![image](https://user-images.githubusercontent.com/65848732/232712662-19448b81-d156-43a8-89d0-2bbf0ee581b5.png)

- [ ] Issue 2
These error message is shown in console.
![image](https://user-images.githubusercontent.com/65848732/232713369-1cc9445a-526c-4f9b-993b-a2ab59e747ad.png)

**Comment by sarinasindurakar** [comment]
- [ ] The support button and twitter icon is overlapping in the footer.
![image](https://user-images.githubusercontent.com/65848732/232999444-9b0cebb0-cb45-42a4-bfe1-fb8ae75abf3e.png)

**Comment by sarinasindurakar** [comment]
- [ ] The support button transition is quite fast.

https://user-images.githubusercontent.com/65848732/236384377-a8e30e2b-c4b9-4a99-89ba-35075a3c452e.mp4

- [ ] The bulk publish pop up must not be shown after the user logouts and login again.
https://user-images.githubusercontent.com/65848732/236386268-8389e737-66e5-4267-8a84-ef72537f6b21.mp4

- [ ]   When user refreshes the page support button appears for  second over the bulk publish popup.

https://user-images.githubusercontent.com/65848732/236386808-76c49b4b-68a8-42b8-9bfc-9f14472906e1.mp4
