### ISSUE TITLE
Organisation Registration Agency List

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1064]
Hi, the list for http://org-id.guide/list/CH_BS-CR is not showing on the relevant drop-down menu for Organisation Registration Agency on the sign-up pages

**Comment by praweshsth** [comment]
@DaveEade49 please provide us the final list of org-id in following manner:

S.no. | Org-ID | Description(can be useful for later)| Country

For some org-id there might not be countries. These will be common org-ids along with country's specific org-ids when user selects any country. 

cc: @sriza

**Comment by sriza** [comment]
@DaveEade49 
All the code lists used in the IATI Publisher are currently taken from the [IATI Standard Codelist](https://iatistandard.org/en/iati-standard/203/codelists/). 

Organization Registration Agencies showing in the dropdown menu of sign-up pages are the JSON data present in [organization registration agency](https://iatistandard.org/en/iati-standard/203/codelists/organisationregistrationagency/) page of the same code list. 'CH_BS-CR' seems to be missing in this code list.

cc @praweshsth

**Comment by sriza** [comment]
@DaveEade49 
Could you please provide us an update on the final list of the organization registration agency?

cc @praweshsth

**Comment by praweshsth** [comment]
No need to do now.
