### ISSUE TITLE
Live006 - How to response or resolve if users uses partial or full caps for language field in CSV and XML?

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1068]
**Issue from the user when uploading xml and CSV:**
When providing an xml:lang to a narrative, it doesn’t accept capital letters. It’s not a big issue, it’s just a bit of a nuisance if you don’t know it, as the error message tells you: “the xml:lang is not valid”, which could mean a whole lot of things.

- [ ] How can we resolve this issue? 
- [ ] Implement the resolution

**Comment by SauravSilwal10** [comment]
@A4family 
Uppercase conversion is not working in 

1. Format of document link
2. Format of Result(document link)
3. Format of  Indicator(document link)
4. Format of Period(document link)
5. Feature designation of location
https://user-images.githubusercontent.com/78422663/220574003-a7257f01-225b-469f-a8b7-f87533cabeb4.mp4

**Comment by sriza** [comment]
Merged to the main branch. Closed manually.
