### ISSUE TITLE
Live008 - adding negative value in a transaction

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1069]
**Issue from user:**
In transactions we are not allowed to provide negative values. Intuitively I can see why this makes sense. In our, and I assume many other organizations, there is a backflow of money often at the end of a year, when the budget is being evaluated. E.g., DCA provides money to our country-office in Libya, which distribute it to activities in the area.

**[Reference from IATI Standard guideline](https://iatistandard.org/en/guidance/standard-guidance/financial-transactions/):**
Transactions can be positive or negative. An example of a negative transaction would be money that was disbursed to a partner and is then being returned to the funder. The returned funds should be published as a disbursement transaction with a negative value, i.e. with a minus symbol in front of the figure, e.g. -1000.

- [x] Allow users to add negative value and make sure negative value is published and also in downloaded CSV and XML
- [x] Need to add this information in help section.

**Comment by sriza** [comment]
Merged to main branch . Closed manually.
