### ISSUE TITLE
Rules: Sector feedback

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1098]
- [x] When multiple sectors with the same vocabulary are used  and the percentages are empty then show the error ‘The sum of percentages of same vocabulary must be equal to 100%’
- [x] If there is only one transaction and sector is added, I can not delete the sector of the transaction so that i can add it in activity level. It shows me error'You have declared sector at transaction level so you must declare sector for all the transactions.' User should be able to remove the sector from the transaction. However, if there are multiple transactions, say n number of transactions then the user has to delete the n-1 transactions and when one transaction is left, the user can remove the sector from it.

**Comment by sriza** [comment]
Merged to the main branch. Closed manually.
