### ISSUE TITLE
UI issue while importing the csv file

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#1105]
- [x] **Issue 1: When a user tries to import a CSV file, the UI breaks down.**

![image](https://user-images.githubusercontent.com/78422663/221481504-0d1975d8-ce7b-4b8e-899b-cfd67eba6d1e.png)

- [ ] **Issue 2: When user click on the about page, the page is not displaying.**

https://user-images.githubusercontent.com/78422663/221519629-aa62fb65-3ca5-42d8-ab94-786fdb3c9b19.mp4

**Comment by sriza** [comment]
Merged to main branch. Closed manually
