### ISSUE TITLE
Issue related with title

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#1110]
- [x]  **Issue 1: There should be no first title validation, only title required validation.**

https://user-images.githubusercontent.com/78422663/222400988-53f4a196-f49d-47e6-a877-c67dd3c91f08.mov

- [x] **Issue 2: Drop down of the organization agency in sign-up doesn't match with the organization identifier in the edit form.**

https://user-images.githubusercontent.com/78422663/222407033-2545a084-2c1c-47dc-9c2b-1b258f55ddb8.mp4

**Comment by sriza** [comment]
When the user fails to enter the first title, and tries to submit the form, at times the laravel validator takes over and refills the form to the value similar to that of database. This only occurs when title has multiple narrative and user deletes them.

Merged to main branch. Closed manually.
