### ISSUE TITLE
support button and bulkpublish model overlapping

### ISSUE THREAD

**Issue by rajkarnikar11** [younginnovations/iatipublisher#1117]

**Comment by SauravSilwal10** [comment]
@rajkarnikar11 please fix this issue 

- [ ] **Issue when the user performs the publish/unpublish activity support button gets flickered.**

https://user-images.githubusercontent.com/78422663/224925366-4bd6ddc2-95aa-45e0-888d-1a5cc3e99cbf.mp4

**Comment by sriza** [comment]
Merged to main branch. Closed manually
