### ISSUE TITLE
Indicator ‘Reference’

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1154]
Email content below in relation to Zendesk Ticket 31460.

Under Indicator ‘Reference’ I have entered vocabulary 9 and code 10.3.1 but get a validation-error in response saying ‘The code is already defined in its result’ – which I honestly don’t understand the meaning of.

**Comment by praweshsth** [comment]
The validation ‘The code is already defined in its result’ occurs in the indicator when the result has a non-empty reference code. The validation is based on the rule(8.11.1) present in the [indicator reference standard page](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/reference/) which states that ‘A reference code must only be declared at result OR result indicator level.’. We can rephrase the error.
