### ISSUE TITLE
Upload csv error processing

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1157]
When uploading from csv if an error occurs the user is advised of this, and given the option to carry on upload or not upload, however there is no indication of what the error so it's hard to understand what needs to be rectified and if this can be down once the activity is uploaded. See screen shot:

![csvuploaderror](https://user-images.githubusercontent.com/110898894/229084618-599332ea-f88f-4c67-95f6-46bbbfb27e05.JPG)

**Comment by praweshsth** [comment]
The user needs to click on the ‘Error’ card to see details about the error.
The errors present in the activity are placed into 3 categories(critical, errors, and warnings). Clicking on ‘Show issues’ will only reveal these categories.

Details on errors present within each category can be seen by clicking on the category cards.
