### ISSUE TITLE
Your Activities Page

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1158]
I've just done an upload of 7 activities and am manually added / updating each one - it occured to me that a great addition would be have the % complete in the view ( if thats possible ) Thanks Dave

![image](https://user-images.githubusercontent.com/110898894/229093333-83678785-9bb9-4ecd-b025-caea81cc8675.png)

**Comment by sionverse** [comment]
UI Pages for review



![Image](https://user-images.githubusercontent.com/29434657/232416047-f09816ec-e9af-4e69-81be-9f74d7f4187d.png)

**Comment by sarinasindurakar** [comment]
- [ ]  According to the design, the sorting of the publishing progress bar on the activity listing page is incomplete in the system.

![image](https://user-images.githubusercontent.com/65848732/233896169-54387c78-7f80-4a5e-8f7d-f5e29df401f0.png)
