### ISSUE TITLE
Sector Completeness validation - Production.

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1162]
![image](https://user-images.githubusercontent.com/110898894/229465017-e20fbe41-7da3-4b67-922c-5bfd7b1595c8.png)

See above screen shot - from what I can see all the relevant data has been entered, and the % add up to 100% - I can't see what validation is failing to produce the waring"not complete"

Activity ID is ET-MFA-150317-ADF-ETH2101

**Comment by DaveEade49** [comment]
Hi, can you explain why this one has been resolved?

**Comment by DaveEade49** [comment]
Still showing as not completed: 
![image](https://user-images.githubusercontent.com/110898894/233955566-097afd99-b6ed-4235-8746-fa1c7f1fb5df.png)

**Comment by sriza** [comment]
@DaveEade49 
We have solved the issue with completeness and updated the complete status of the activities.
Please let us know if any other issue arises.

cc @praweshsth
