### ISSUE TITLE
Your Activities Page Update Date

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1163]
![image](https://user-images.githubusercontent.com/110898894/229512262-2af231e4-b9e5-42a6-9bec-5f1d5e89f1a0.png)
![image](https://user-images.githubusercontent.com/110898894/229512386-69b1bdcd-57ff-4c06-8ff7-a842ecfe3fbf.png)

See the two screenshots above - screenshot 1 says the last update was 31/3/2023, yet screenshot 2 shows the last update was minutes ago today 03/04/2023 - not sure if updates by Superuser are not counted?

**Comment by PG-Momik** [comment]
@DaveEade49 This issue will be addressed when working on the Dashboard. Can we close this issue until then?

**Comment by praweshsth** [comment]
Sure @DaveEade49

**Comment by praweshsth** [comment]
@DaveEade49 
The requested change has been made to the organization listing page while working on the dashboard.
