### ISSUE TITLE
Design: Superadmin Dashboard with Visualization

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#1169]
Superadmin dashboard summarizes the data within IATI publisher with the help of various visualization tools like charts and tables. Design should include visualization for following data: 

**1. Join Now (Filter by: date) - Registration** 
- [ ] total number of publishers/ organisation
- [ ] numbers of registration - previously registered in IATI
- [ ] numbers of registration - previously not registered in IATI
- [ ] numbers of registration - segregation by country
- [ ] numbers of registration - segregation by Publisher Type
- [ ] numbers of registration - segregation by Data License
- [ ] numbers of publishers (Registered but not verified)
- [ ] total number of organisation not active in 6 months
- [ ] publishers without activity
- [ ] publishers not published in last 6 months
- [ ] last publisher registration (name and date)
- [ ] new publisher this week / month

**2. Signed in** 
- [ ] number of publishers - incomplete setup - registry key only
- [ ] number of publishers - incomplete setup - default value only 
- [ ] number of publishers - incomplete setup - registry key and default value 

**3. Organisation data**
- [ ] organisation data incomplete and complete (100%)
- [ ] organisation data published and not published

**4. Activity data**
- [ ] total number of activities added
- [ ] total number of draft activities (doesn't include republish)
- [ ] total number of published activities
- [ ] total number of published activities but needs to republish
- [ ] total number of activity added manually
- [ ] total number of activity added by uploading CSV
- [ ] total number of activity added by uploading xml
- [ ] total number of activity added by uploading xls

**5. Users**
- [ ] total number of users
- [ ] total number of general users
- [ ] total number of admin users
- [ ] total number of active and inactive users
- [ ] current users logged on

**Comment by sionverse** [comment]
Dashboard pre design findings and exploration

https://docs.google.com/spreadsheets/d/18pOuGJocsSj0BnjankwEm8Bemp9itBWPk4VhsESlxuw/edit#gid=0

**Comment by sionverse** [comment]
First and second drafts completed, reworking on the comments from Prawesh dai today.

**Comment by sionverse** [comment]
Wirframes -> Acknowledged by David and Kate.

Moving to Final UI for Dashboard

**Comment by sionverse** [comment]
Final UI done

**Comment by sionverse** [comment]
![Image](https://user-images.githubusercontent.com/29434657/234512686-4ff01c2f-c9f3-4e8a-8c63-f3b5dcd78126.png)
![Image](https://user-images.githubusercontent.com/29434657/234512685-5e678305-84cb-4ed3-b609-5ef9583da513.png)
![Image](https://user-images.githubusercontent.com/29434657/234512692-45e313ba-c750-441a-9d2e-9a5c806e5d31.png)
![Image](https://user-images.githubusercontent.com/29434657/234512690-a3156835-d2ea-4f08-840a-090512403168.png)
![Image](https://user-images.githubusercontent.com/29434657/234512689-6e6957fc-461d-478c-a61f-3d22cfb07a67.png)
![Image](https://user-images.githubusercontent.com/29434657/234512687-2b1270f9-9556-4108-a4cf-49bc3b7183f4.png)
![Image](https://user-images.githubusercontent.com/29434657/234512701-ea317b8e-e036-43b4-99e2-5c753552e616.png)
![Image](https://user-images.githubusercontent.com/29434657/234512702-c5dd5717-af74-49ad-aaa2-3da0eba9a235.png)
![Image](https://user-images.githubusercontent.com/29434657/234512700-73bc8b2e-fa88-4056-8a53-91f56663a08f.png)
![Image](https://user-images.githubusercontent.com/29434657/234512697-868cb118-cb9c-4c99-836f-12f577b90853.png)
![Image](https://user-images.githubusercontent.com/29434657/234512691-42b19f62-d0f9-4855-b6fa-2adb5215ba73.png)
![Image](https://user-images.githubusercontent.com/29434657/234512698-075bb6bb-ae9e-464f-8179-8bb11bc1ee70.png)
![Image](https://user-images.githubusercontent.com/29434657/234512688-ac5040b6-b614-4f13-aeb6-0d4a472c9dae.png)
![Image](https://user-images.githubusercontent.com/29434657/234512699-39d094d4-636d-4167-9b4f-60f2ada33da6.png)
![Image](https://user-images.githubusercontent.com/29434657/234512695-0e37f005-86b3-4639-bc80-2b2d4f8fe3be.png)
![Image](https://user-images.githubusercontent.com/29434657/234512693-445ace5d-8c01-4e08-b97b-2880628bdea2.png)
![Image](https://user-images.githubusercontent.com/29434657/234512696-4faa3e40-7761-4f18-aa2c-746e827303d0.png)
![Image](https://user-images.githubusercontent.com/29434657/234512694-bca68c82-65b8-4595-9183-13ab91dbcee8.png)
