### ISSUE TITLE
Design: XLS Import for Activity, Result, Indicator and Period

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#1170]
Import of XLS uses xls file to bulk import activity elements. The process includes import of four distinct xls files: activity, result, indicator and period. The design for this import should include:

- [x] XLS import page
- [x] XLS import listing page
- [x] Designs to show uploading xls as background task
- [x] Warning Popup Pages
- [x] Error Showcase on Import

Figma file for review:
https://www.figma.com/file/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?node-id=12052%3A219980&t=BCmwqCejMnIbRPOZ-1

**Comment by sionverse** [comment]
@DaveEade49 I've updated the changes as per the comments on Figma file, please do check and let us know.
