### ISSUE TITLE
Display the dot sign in the truncated organization name.

### ISSUE THREAD

**Issue by sarinasindurakar** [younginnovations/iatipublisher#1183]
- [x] Display a dot sign to alert users that the organization's name is lengthy, as seen on the activity listing page.
![image](https://user-images.githubusercontent.com/65848732/233963801-1e272828-f520-4ced-b083-179d90653f7e.png)
Activity listing page
![image](https://user-images.githubusercontent.com/65848732/233963874-e619e1bf-c055-42d6-8f4a-672b7062c554.png)

**Comment by rajkarnikar11** [comment]
resolved in 1178-ui-issues
