### ISSUE TITLE
User Names in Publisher that have been Migrated

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1188]
User names in IATI Publisher all have to be in lowercase alpha - Aidstream users have different constraints.

User names that have been migrated then need to be changed if password is changed.

See HFHNL_EvaGrevinga ( although I am now amending this one )

**Comment by sarinasindurakar** [comment]
- [ ] Lowercase validation is shown  when user adds the new user in the organization.
![image](https://user-images.githubusercontent.com/65848732/234760187-58c35d4f-56ef-4e81-bb88-3e58a963b1aa.png)

**Comment by DaveEade49** [comment]
Hi, not sure if that's an answer - when the user executes the transaction the validation is fine, but when the user is created via a script the user id is created in it's erroneous condition and then fails when the user try to login.
This is issue is MIRGRATION only issue.

**Comment by praweshsth** [comment]
@DaveEade49 Sarina has commented on the issue that she found and now this issue has been resolved, all the users can login with username including uppercase letters. Also, during registration (My organisation has registered with IATI), user can choose uppercase for username. However, during registration (I'm new to IATI Registry), user can only user lowercase for username as the username is also used in registering in IATI Registry and it doesn't allow Uppercase.

Please check it and close this issue. Thank you.

**Comment by DaveEade49** [comment]
That's great - thanks
