### ISSUE TITLE
Migrating Pro Users

### ISSUE THREAD

**Issue by PG-Momik** [younginnovations/iatipublisher#1190]
Since Pro users have the ability to use custom vocabulary, we need to make sure custom vocab and its code are preserved in a sensible manner during migration.

**Comment by sarinasindurakar** [comment]
- [ ] Custom tag vocabulary is not migrated in IATI.
![image](https://user-images.githubusercontent.com/65848732/236380311-d78b73eb-6b1f-417b-b212-bdead72319c4.png)

**Comment by sarinasindurakar** [comment]
**Issues when migrating the existing pro organization**

- [ ] Vocabulary Uri not shown in policy, recipient organization, sector, humanitarian scope .
- [ ] The  result reference code not shown.
- [ ] The tag code not shown.

**Comment by PG-Momik** [comment]
I'm closing this since 1012-pro-user has been merged to main. Further issues can be handled through new branch(s).
