### ISSUE TITLE
Migrating organizations who have already registered on IATI Publisher

### ISSUE THREAD

**Issue by Sanilblank** [younginnovations/iatipublisher#1192]
Some organizations on AidStream have already created an account on IATI Publisher. The previous script will not work for migrating these organizations, so we need to prepare a different script that will use some parts from the existing script.

THINGS TO DO AND DECISIONS MADE
- The organization data will not be migrated i.e. the organization data present on IATI Publisher will stay the same. The only thing that will be changed will be the created_at date of the organization in the IATI Publisher.
- For migration of activities, if the activities present on AidStream (published or not published does not matter) are already present on IATI Publisher, they will not be migrated. Only the activities present on AidStream but not on IATI Publisher will be migrated. If the migrated activities are published via AidStream, they will be republished from IATI Publisher and their dates will remain the same as in AidStream.
- If the organization has settings information on AidStream but has no information on IATI Publisher, then the information will be migrated. If both have settings, if the settings information on IATI Publisher is valid, the information from AidStream will not be migrated.
- The users present on AidStream who are not present on IATI Publisher will be migrated. In case a user with the same email already exists on IATI Publisher, the user will not be migrated.

For the completion of the above-mentioned tasks, the already existing script will not be sufficient. We will need to create a different script that will perform the tasks. The new script will reuse some of the functionalities present in the current script and some functionalities will need to be created. Because of this, it will require some time to migrate the existing organizations. We will probably be able to migrate them around next week.

cc. @praweshsth @PG-Momik

**Comment by praweshsth** [comment]
@DaveEade49 This is what we will be going to do for migrating the organisations that have already registered in IATI Publisher.

**Comment by DaveEade49** [comment]
Ok, I have reviewed the logic and that is fine with me
