### ISSUE TITLE
Migration of Transaction for - Global Alliance for Livestock Veterinary Medicines

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1198]
Around 100 transactions have been migrated for the above.

I've downloaded the info, and as far as I can see for the 3 mandatory / core fields there are correct values for all transactions, yet the element at the higher level is showing as "incomplete"

From the Transaction List there is no indication of which transactions are triggering this message.

1. Could you please identify which / what Transactions are causing this issue.
2. Is it possible to add into the transaction list a flag or message to say whether the individual transaction is complete or incomplete.

**Comment by praweshsth** [comment]
@PG-Momik let's do the same for the lists of result, indicator, and period.
