### ISSUE TITLE
Recipient Country Budget Status field missing in Aidstream 

### ISSUE THREAD

**Issue by sarinasindurakar** [younginnovations/iatipublisher#1204]
AidStream doesn't have field for **@status** attribute in **recipient country budget** but IATI has the field for **@status** attribute in **recipient country budget**.

_If the @status attribute is not present, the budget is assumed to be indicative according to IATI Standard._
https://iatistandard.org/en/iati-standard/203/organisation-standard/iati-organisations/iati-organisation/recipient-country-budget/

**The recipient country budget status is currently shown as missing in IATI for migrated organization.**

What should we do for this case?

@DaveEade49

**Comment by sarinasindurakar** [comment]
The **recipient country budget status** is published as null for all the organization from the AidStream.
For live example, you can look into **Ghana Netherlands Business and culture council organization** in IATI and as well as IATI registry.
https://iatipublisher-prod.s3.amazonaws.com/organizationXmlFiles/gnbcc-organisation.xml

 You can have a look  in this xml file for reference as this organization is only on AidStream.
https://aidstream.s3.us-west-2.amazonaws.com/xml/unaids-org.xml

**Comment by DaveEade49** [comment]
Ok, thanks - as this is only for migrated organisations we should set it to indicative.

If possible we should mark this somehow - the only way I can see we could do this is using the Reference Field ( Narrative ) unless that is already populated.

**Comment by sarinasindurakar** [comment]
"If possible we should mark this somehow - the only way I can see we could do this is using the Reference Field ( Narrative ) unless that is already populated."

 I could not understand this. Can you clarify this again?

**Comment by DaveEade49** [comment]
Hi what I was trying to say is that if WE set a field to a particular value - there somewhere on that activity we should indicate that we have done so ( we must ensure that a data field that nas NOT been populated by the publisher is identified in that way ).

Can we discuss on next Tuesdays call @praweshsth
