### ISSUE TITLE
Freeze Input Fields based on Conditions

### ISSUE THREAD

**Issue by A4family** [younginnovations/iatipublisher#1209]
There are two levels of platform where some of the elements can be populated. i.e Activity Level and Transaction Level.

The elements present in Activity level which are: 
1. Sector
2. Recipient Region
3. Recipient Country

Can also be populated inside the transaction element. Currently, Only the Backend validation are thrown when a user try to pouplate data in both Activity Level and in Transaction level.
So, the task is to make a user aware about the fields that are already populated in any one of those platform. 

Tasks :

- [ ] if **Recipient Region** needs to be freezed then everything including borders, text, input fields, placeholder, helptext, add more button should be in "#A6B5BA (GREY)" color code.
- [ ] When Freezed cursor should not change and should not be clickable as well.  
- [ ] Add a note stating "already added on activity level or in transaction level" in the place of validation error message. 

Conditions are: 

1. if any of the  **Recipient Region** or **Recipient Country** is present in activity level then freeze both **Recipient Region** & **Recipient Country** in transaction level
2. if any of the **Recipient Region** or **Recipient Country** is present inside the transaction then both **Recipient Region** & **Recipient Country** field in activity level should be freeze
3. if **Sector** is present in activity level then freeze **Sector** inside the transaction level
4. if **Sector** is present inside the transaction level then freeze **Sector** in the activity level.

**Comment by sarinasindurakar** [comment]
### Complete status issue related to recipient country, region and transaction

- [ ]  When user adds the Recipient country ,it shows incomplete but when user adds the transaction ,both the Recipient region and country is shown completed.

**Comment by sarinasindurakar** [comment]
If user adds the recipient region and country in the activity level, and adds the transaction then deletes the recipient region and country from activity  level, then there will be no recipient region and activity level in transaction level too. Since recipient region or country  should be mentioned in transaction, so show some error message when user deletes the recipient region or country in activity level.

**Comment by sarinasindurakar** [comment]
- [ ]  when user adds the recipient region and country in transaction level , the recipient region and country  in the activity level is not shown complete.

- [ ]  when user adds sector in transaction level, the complete mark is not displayed in the activity level.

**Comment by sarinasindurakar** [comment]
- [ ]  The form validation of the recipient region and recipient country  message not shown.

https://github.com/younginnovations/iatipublisher/assets/65848732/2abd48fa-0584-4189-8d5f-a37d07c9e50f

**Comment by A4family** [comment]
Merge to main branch and closed manually
