### ISSUE TITLE
Feedback for Bulk Download / Upload 

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1218]
1. With the result upload - the result identifier is not populated from the activity id and the result number fields - this makes it hard especially if the result number has been truncated by excel. 
![image](https://github.com/younginnovations/iatipublisher/assets/110898894/bd59bb9e-9133-4c1a-849c-2a64ddf469d1)

**Comment by praweshsth** [comment]
@DaveEade49 we have resolved the issue converting the numbers into string. Please check and inform us if anything is to be done here.

**Comment by DaveEade49** [comment]
tested and all ok.
