### ISSUE TITLE
Locate IATI validator response error message

### ISSUE THREAD

**Issue by A4family** [younginnovations/iatipublisher#1219]
To publish the activities, first we need to hit the api of IATI Validator along with the activity information in XML format. And, based on that activity XML,  IATI validator return responses about the validation error messages and line number of the xml node.

Currently, We are just saving the responses to the database and showing it in the activity detail page to the users. 

And the task is to locate the exact element of that error messages thrown by IATI Validator.  i.e Error messages should be clickable and redirect users to the edit page of that element.

**Comment by sriza** [comment]
1. Only transaction, result, indicator and period have /edit route. Remove /edit route for other elements.

**Comment by sarinasindurakar** [comment]
- [ ]  The OECD DAC sector  error message is redirecting it's route to settings.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/fbd87657-6f83-4be7-b80b-59f31ba0b39e)
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/7d2ee679-2c6c-4d9d-980e-cce88d1beae4)

**Comment by sarinasindurakar** [comment]
- [ ] The activity planned date or actual date error is redirecting to settings.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/088bbe8d-e014-4613-8940-19e574bc2e1c)

**Comment by sarinasindurakar** [comment]
- [ ] The transaction value date is not scrolling to it's element.
- [ ] Recipient countries and region message of transaction level is not scrolling.
- [ ] " The actual must have a value when the indicator measure is non-qualitative (e.g. 1 = unit, 2 = percentage, 3 = nominal, 4 = ordinal).](https://iatipublisher-dev.yipl.com.np/indicator/6947/period/12006/edit#target[0][comment][0][narrative][0][language]" is scrolling to dimension.

**Comment by A4family** [comment]
@DaveEade49 With Iati Validator Responses we couldn't locate the exact location of an error due to some reasons.
Like missing line number, missing element, wrong line number and inconsistent validator responses. In detail, i have written here in the given docs. 
https://docs.google.com/document/d/1TIv-jyu9mYQoFk-rE20vP9_M_OOU0FhOPGPoSTaQpqg/edit?usp=sharing

cc @praweshsth

**Comment by sriza** [comment]
Merged to main branch. Closed manually.
