### ISSUE TITLE
reporting-org element showing as not complete

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1226]
See below - my understanding was that this element is populated automatically - in fact the fields are not editable?

![image](https://github.com/younginnovations/iatipublisher/assets/110898894/0b4df406-f861-4a59-b2ff-cf3e06c5e01b)

**Comment by sriza** [comment]
@DaveEade49 
The reporting organization along with its complete status is inherited from organization data. 
In the above case, it is ' not complete' since the narrative field is missing and user can complete it by editing the 'Reporting organization' edit form present at organization data. 

To ease the understanding of user regarding this process, we can add a help text stating that user can only edit secondary reporter in activity level and to edit other fields they would be required to edit the reporting org form present at organization level. The help text can be placed below the title of reporting-org in the activity detail page as well as the edit form of reporting org.

Please let us know if we should proceed with this approach.

cc @praweshsth

**Comment by DaveEade49** [comment]
Yes - please can you add some text which will help with this issue.

**Comment by praweshsth** [comment]
@sriza add message for users as discussed

**Comment by DaveEade49** [comment]
@praweshsth @sriza - Hi - I can't see this added yet in either Staging or Production?

**Comment by sriza** [comment]
@DaveEade49 
Hi David, 
We are yet to work on this issue. We will inform you as soon as this is deployed to the staging site.

**Comment by sarinasindurakar** [comment]
- [ ] Issue 1 
The  edit and delete button not shown in all the  organization element.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/c3fee837-e96e-4295-87aa-4d4ec0f37bf8)

**Comment by DaveEade49** [comment]
@sarinasindurakar @praweshsth - Hi not sure if your comment is related to this issue or not? Can you clarify? Thanks Dave

**Comment by sarinasindurakar** [comment]
Hi @DaveEade49, 
This issue was discovered when testing issue #1282  and was intended for @PG-Momik . I noticed that the edit and delete  were not visible on hover. So, I mistakenly mentioned this issue here. This issue has been addressed detailly in issue #1282 . Apologies for Confusion.

**Comment by rajkarnikar11** [comment]
The disabled fields in activity reporting org was not freezed. All fields except secondary reporter field have been disabled in activity level reporting org, also helper text has been added in reporting org element and in activity detail page

**Comment by DaveEade49** [comment]
I have seen the figma for the activity org text - It needs rewording - see figma

**Comment by rajkarnikar11** [comment]
Hi @DaveEade49 , we have deployed the changes regarding reporting org in the staging site, you can find info box in activity details reporting org section, and freezed reporting org  form on activity level. Please have a look and let us know if any other changes need to made.

**Comment by praweshsth** [comment]
@DaveEade49 please add the wording here as we discussed yesterday. Thank you.

**Comment by DaveEade49** [comment]
"Reporting Organisation data is managed via the Organisation Tab (this should be hyperlink to org tab ), except for value Secodnary Reporter that can be managed at each activity."

**Question** - Is the "secondary reporter" value inherited from Reporting Org, but still be editable at activity level?

**Comment by rajkarnikar11** [comment]
Hi @DaveEade49 the text has been updated as per your suggestion. Please have a look . 
Regarding your question , the secondary reporter value is inherited from Reporting Org , yet it can still be edited at the activity level. Thanks.

**Comment by DaveEade49** [comment]
all good - can you promote to production @rajkarnikar11
