### ISSUE TITLE
Reference Codes - Indicators and Results

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1228]
Hi, please see below comment from one of the organisations that we've migrated from Aidstream to IATI - I'd be grateful if you could take a look and  advise? Thanks Dave:

_**"I have a follow up question regarding the different publishing tools as they don’t seem to be aligned. I have different experiences with AidStream and the Publishing Tool, they seem to be set up according to different logics which makes it different for us to align our data across different systems.

For example, we are supposed to report the reference code on the indicator level, which is possible in AidStream but is restricted to only Outcome level in the Publishing Tool. The Publishing Tool is restrictive regarding the reference code because it is mandatory on the Outcome level but gives the error message “Reference code must only be declared at result OR result indicator level”.

In addition, Aidstream only has the relevant fields as mandatory while I noticed that in the Publishing Tool a lot of fields are mandatory that are repetitive or unnecessary, such as the document link.

Is there any way these can be adjusted? We would like to link the reference code on the indicator level for alignment."**_

**Comment by sriza** [comment]
@DaveEade49 
Hi David,
Regarding the reference code of Indicator and Results, the IATI Standard specifies that the reference code can be included either at the 'result level' or at the 'indicator level'. Reference below:
- https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/reference/
![image](https://github.com/younginnovations/iatipublisher/assets/24825118/7f276f4b-18e3-4da2-a9e8-51d5ce1e037b)
- https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/reference/
![image](https://github.com/younginnovations/iatipublisher/assets/24825118/02e2d36d-53da-4f09-a176-42457e19155c)

Both the IATI publisher and Aidstream have followed this rule:
- IATI Publisher
![image](https://github.com/younginnovations/iatipublisher/assets/24825118/edb427a5-6768-40dc-be3c-70379c233c1f)

- AidStream
![image](https://github.com/younginnovations/iatipublisher/assets/24825118/65b05f0f-72d8-4220-85e2-5f2850996e67)

Though the Publishing Tool has mandatory fields regardless of their relevance, these fields are not required and can be left empty. 

Should we adjust these rules ignoring the standards provided by IATI?

cc @praweshsth

**Comment by DaveEade49** [comment]
I think it's this bit of the logic they are having trouble with:
"For example, we are supposed to report the reference code on the indicator level, which is possible in AidStream **but is restricted to only Outcome level in the Publishing Tool.** The Publishing Tool is restrictive regarding the reference code because it is **mandatory on the Outcome level** but gives the error message “Reference code must only be declared at result **OR** result indicator level”.

So the things to address:
1. Can the reference code be added at anything other than "outcome" level?
2. If it' mandatory at outcome level how can we have an "or" option in the logic?

**Comment by sriza** [comment]
@DaveEade49 
1. The reference code can be added for types other than "outcome"
2. The user can choose to leave the reference code empty even when s/he has selected "outcome" option.

**Comment by praweshsth** [comment]
discussion done and completed
