### ISSUE TITLE
Budgets - Validation

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1229]
Hi, see screenshot below of validation of one of the migrated accounts - I think what the validation is saying is that "A revised Budget set of dates and figures must also have an ORIGINAL set of dates that match" - What the user is trying to do is update the data rather than create a new set - is this the correct way it should work?

https://publisher.iatistandard.org/activity/3139/budget

![image](https://github.com/younginnovations/iatipublisher/assets/110898894/52e2fb8f-4180-4263-9665-cef20c286a99)

**Comment by sriza** [comment]
@DaveEade49 
Hi David,
The IATI Standard requires 'original' budget whose period start and end dates are to be copied to budget of type revised. The data above seems to lack budget of type 'original'. The user should add 'original' budget then 'revised' budget incase the budget is updated.

Please refer to https://iatistandard.org/en/guidance/standard-guidance/activity-budgets/ : 
![image](https://github.com/younginnovations/iatipublisher/assets/24825118/f0cd4f70-4ecc-4898-90b5-b8bc7ddd3a35)

We had previous discussions regarding this rule at: https://docs.google.com/document/d/19YB3rIdyrl7eeDAIQaCMFVb5kftvxlyJdOx7IAlZ-88/edit?usp=sharing

**Comment by DaveEade49** [comment]
Ok, I have talked with the publisher - they are happy to manually delete and re-add the budgets as original and then add new ones of revised on the next revision piece. It is as I said something we should look to address in Aidstream to replicate th functionality, but also we need to be aware of this when we migrate in future so we can work out with each organisation how to overcome this issue if they have not published "original" budgets.
