### ISSUE TITLE
Budget - Value - Date

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1234]
Hi, it looks like we have some validation to ensure that the Budget Value Date is not <Budget Start Date or > Budget End Date.

I checked IATI Standard https://iatistandard.org/en/guidance/standard-guidance/activity-budgets/ but can't see any reference to this rule.

Can you check for me?

It makes sense that if you are entering a budget for 2026, the value date will be today, and therefore not within the start and end dates.

Can we check this out asap as I have a publishing waiting on guidence.

**Comment by DaveEade49** [comment]
Thanks Shreeja – any timescale on deployment?
Thanks
Dave

David Eade | IATI Business and Data Analyst
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505 | M: +44 (7855 946589)
devinit.org<http://www.devinit.org/> | ***@***.***<https://twitter.com/devinitorg>
Sign up<https://us11.list-manage.com/subscribe?u=a829237ca0cf1470615c7f059&id=ce30e2af0f> to our newsletter and topic updates

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
***@***.***

Read more about our work and its impact<https://devinit.org/what-we-do>
Development Initiatives is the trading name for: Development Initiatives Poverty Research Ltd, a not-for-profit company. Company No. 06368740 and DI International Ltd. Company No. 5802543, both registered in the UK.  Registered Address: First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK.
Development Initiatives Poverty Research America Inc, is a 501(c)3 charity registered in the US. Registration number 5737757. Registered Address: 1209 Orange Street, Wilmington, New Castle County, Delaware 19801, US.
DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives. If you have received this email in error, please delete it and notify the sender.

**Comment by sriza** [comment]
We are currently testing the changes. We will deploy it once our QA approves the changes, which might be by the end of the day.

**Comment by DaveEade49** [comment]
Confirmed as fixed.
