### ISSUE TITLE
Sector at Transaction and Activity Level

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1239]
We have an organisation Forests of the World that has an activity - https://publisher.iatistandard.org/activity/3323

They have sector declared at Transaction Level, but they want to remove these and declare at activity level.

When they try and remove the information at transaction level they get an error message "You have declared sector at transaction level so you must declare sector for all the transactions."

Is there ny way around this, other than deleting the three transactions ( or at least 2 ) and then re-inputting the data?

**Comment by praweshsth** [comment]
@DaveEade49 the user can download the particular activity and remove the sector from transactions and upload it again.

**Comment by DaveEade49** [comment]
Hiya, yes understood - just not the most "user friendly" solution!
