### ISSUE TITLE
Validator Error with XML creation see screenshot below

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1242]
Validator is returning an "element not expected error" - not sure how that happens using the publisher tool - any ideas?
Thanks Dave

![image](https://github.com/younginnovations/iatipublisher/assets/110898894/78cc94be-d1fe-47bf-80ed-294b7e694965)

**Comment by praweshsth** [comment]
Discussed with @DaveEade49 and finalized that the message from IATI Validator is not suitable to make it link to the exact form of an element.
