### ISSUE TITLE
Adding more than one Dimension to an Actual Value in an Indicator Period List

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1243]
When you try and add more than one Dimension like this:
![image](https://github.com/younginnovations/iatipublisher/assets/110898894/66608163-fda7-46e2-a032-3f1a8c34989b)

Once you then look at the list - the new value just added is not saved:

![image](https://github.com/younginnovations/iatipublisher/assets/110898894/f453e823-6e46-4df7-916f-700440435fb2)

**Comment by DaveEade49** [comment]
@praweshsth @sriza - Hi - is this one fixed?

**Comment by sriza** [comment]
Hi David,

We have fixed this issue and deployed it to the production site. Please have a look.

Thank you

cc @praweshsth

**Comment by DaveEade49** [comment]
all good
