### ISSUE TITLE
xml upload not being processed

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1261]
Danmission are trying to upload an xml file, but when the upload function completes, it neither adds the activities to the activity view or provides the user with an error message.

Can you take a look and see if there is an issue with XML file, and also can we see what can be done in terms of error messaging in the future?

I've added the file as a txt doc as I don't seem to be able to upload XML!

Thanks
[danmission.txt](https://github.com/younginnovations/iatipublisher/files/11915558/danmission.txt)

**Comment by DaveEade49** [comment]
Just checked back and it's now appeared in the upload list - there was a bit of a time-lag though - it's working ok but the timing is not great

**Comment by praweshsth** [comment]
The deployment of the new changes in the tool had caused this issue. This is working now.
