### ISSUE TITLE
Email Address to be added to Publishers white list

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1264]
Hi, can you provide the email address used by Publisher Tool to send out activation and resets for passwords?

Some publishers will need to know this so the email address can be added to a white list so their mail platforms and servers do not block it.

**Comment by praweshsth** [comment]
Need to change the email service to AWS's SES. Then we can look into this after that.

**Comment by siwhitehouse** [comment]
@praweshsth Can you please confirm the email address? When I signed up I received the email to verify my email address from no-reply@iatipublisher.com. Is this still the case?

**Comment by praweshsth** [comment]
@siwhitehouse we are in discussion with James to finalize the email address from which the users will get notification. So for now, it is no-reply@iatipublisher.com.

**Comment by sriza** [comment]
@siwhitehouse @DaveEade49 
The email address that is used to send mail is 'no-reply@notifications.publisher.iatistandard.org'.
 
The updates of the email configuration has been made in PR #1240.

cc @praweshsth
