### ISSUE TITLE
Organisation List - table pagination not working

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1265]
Unable to view all publishers in the "Organisation List" (https://publisher.iatistandard.org/list-organisations) as pagination at the bottom of the table does not work. Changing the page number or clicking "Next" does not update the table:

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/2e8c2f80-248c-4f72-9db1-a45352a7c964)

**Comment by praweshsth** [comment]
This has been fixed. This will be deployed along with Dashboard changes.

**Comment by sriza** [comment]
Merged to main branch with PR #1205 .

**Comment by emmajclegg** [comment]
This looks to be working as expected now on the production site, thanks - happy for the issue to be closed
