### ISSUE TITLE
Email verification error - user not receiving emails

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1267]
A user has reported not receiving their account verification email. When I (as an admin) log in and try to resend this to them I get the following error:

_Expected response code "250" but got code "530", with message "530 Authentication required"._

This is preventing the user (Arup International Projects Limited) completing their account set up.

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/0d411744-9b55-41a3-bd4d-a6e319f8a4d9)

**Comment by DaveEade49** [comment]
retested and working - new email sent.

**Comment by DaveEade49** [comment]
Do you know if they were logged in at the time?
