### ISSUE TITLE
Difficulty adding results

### ISSUE THREAD

**Issue by IsabelBirds** [younginnovations/iatipublisher#1268]
Summarised feedback from a publisher on adding results in IATI publisher:

-  **The process is very long and confusing**

A publisher wishing to add a result as described in[ understanding results data](https://iatistandard.org/en/guidance/standard-guidance/understanding-results/) has to create and save a result, then create and save an indicator, before getting to fields for period start, period end, target and actual values. This is leading to confusion as they cannot find these fields easily.

- **Mandatory fields**

It is not clear which fields are mandatory for a result, and which are mandatory for a field within a result (i.e. documents). This is stopping publishers from reaching the indicator entry page as they think they cannot complete the initial result page. Publisher suggests creating the result and indicator first, then adding documents etc if applicable. 

- **Lack of guidance**

The above distinction between results, indicators and mandatory fields is not described in the user manual.

**Comment by sriza** [comment]
We will start working on this issue by clarifying the process of adding result in the Publisher Tool in the user manual.
