### ISSUE TITLE
Delay when republishing

### ISSUE THREAD

**Issue by IsabelBirds** [younginnovations/iatipublisher#1269]
Publishers are reporting a very long delay when making small changes and republishing activities.

![image](https://github.com/younginnovations/iatipublisher/assets/44876111/a135c041-e1c2-4722-9524-8913c07ddc41)

**Comment by sriza** [comment]
@IsabelBirds 
We looked into this issue and found that the delay was caused during the creation of XML file. We are currently working on optimizing the workflow of XML creation. 

We will update once we decide on the optimized workflow.

Thank you

cc @praweshsth

**Comment by sriza** [comment]
The publishing/republishing of the activities is carried out in a series of steps namely,
1. checking for core element completion
2. creating XML files and validating them through the IATI validator
3. mapping response of IATI validator to their respective element URL
4. creating XML files and publishing them to the IATI validator

**Causes of delay:**
1. The creation of an XML file requires manipulating element data stored in the database to an array as required for creation of an XML file. The process contains multiple loops which added to the delay.
2. Mapping response to IATI validation requires conversion of xml file to an array. The element for each error message is located on this array and the URL is generated. Currently, for each error message, a new array from xml file was generated.
3. Creating xml file and publishing them to IATI Validator consist of:
    -  creating xml files for activities that are being published
    - bringing all the activities of the organization that were published together with the activities that are currently being published
    - merging them to form a single activity file

In the system, this process of merging was carried out once for every activity causing the merged file to be formed multiple times during the process. 

**Solution:**
1. We have replaced loops with generators to optimize the xml creation
2. We have updated the code to conduct the generation of an array from xml file only at the beginning. The error messages will now be located based on the pre-built array.
3. We have updated the creation of the merged activity file to occur only once, i.e. at the end of the process. Thus, all the activities to be published will form xml file. The files will be collected and merged to form activity at the end of bulk publishing, then they are published to IATI Registry.

The above solutions that we have implemented have made the process significantly faster. 

Step number 2 (creating xml file and validating) occurs as a foreground process. For activities that are huge and validating multiple activities as such can still result in delay. Thus, it would be reasonable to implement the validation step as a background task similar to step number 4 (creating xml files and publishing them).
Please let us know your view on the above.

**Comment by sriza** [comment]
@IsabelBirds @DaveEade49 @siwhitehouse @emmajclegg 

**Mechanism for creation of XML File**

The IATI Publisher tool creates XML file for activities and organization. These files are created aligning to the standards of IATI registry. 

**Steps for creation of a single XML File:**
- XML file creation starts with collection of data to be included in xml file. In case of activities, the data in subject are activity elements. Each of the elements of activities are JSON data stored as an individual column in the activity, transaction, result, indicator and period tables. The first step thus would be to fetch the row that is to be parsed from the table.
The collected activity along with transaction and result are send to `getXml()` method present in `XmlGenerator.php`.

- The collected data are send to `getXmlData()` method of `XmlGenerator.php` where the data for each elements are individually converted into array as required for the creation of XML. This manipulation of data can be seen in the `getXmlData()` method of service corresponding to each element (Eg: getXmlData() method of TransactionService.php file for Transaction).
These manipulated data are now placed along with other attributes required to form XML file as follows:
![image](https://github.com/younginnovations/iatipublisher/assets/24825118/7d15ed3f-e153-438b-8ecd-47f8775f3175)

- This array is now sent to `ArrayToXml.php` file which returns the XML data corresponding to this array.

- Once the XML file is created, it is stored at the AWS with the name format as {publisher-Id}-{activity-Id}.xml.

**Merging XML File for Publishing**
Merging of XML file is the process of bringing together multiple xml file corresponding to activities. The merged XML file is the one published to the registry.

Once the individual XML file for each activity is generated, these files are fetched from AWS and appended to form one within `getMergeXml()` method of `XmlGenerator.php`. The merged file is then uploaded to AWS server and the AWS url is published to IATI Registry.

**Comment by sriza** [comment]
@IsabelBirds @emmajclegg @DaveEade49 @siwhitehouse 
We have created design for the new workflow of publishing. The major changes are:
- Validation of activity is treated as background process
- Placement of background task in a background task tray (The background tasks were previously presented at the bottom of the screen)

Here is a [presentation](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=12826%3A250890&type=design&node-id=13655-293120&viewport=-8336%2C5544%2C0.52&t=eAL8RMD9CQWOitMB-1&scaling=scale-down&starting-point-node-id=13655%3A293107&show-proto-sidebar=1) showing the flow: https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=12826%3A250890&type=design&node-id=13655-293120&viewport=-8336%2C5544%2C0.52&t=eAL8RMD9CQWOitMB-1&scaling=scale-down&starting-point-node-id=13655%3A293107&show-proto-sidebar=1

We have tagged you in the figma frames containing the above changes. Please let us know your thoughts and suggestion in the figma comments.

Thank you

**Comment by praweshsth** [comment]
@DaveEade49 as discussed yesterday, please check the design and inform us if we are good to work on it.

**Comment by DaveEade49** [comment]
comment #527 not addressed in Figma

**Comment by emmajclegg** [comment]
For info - "DanChurchAid" is another publisher that's struggling to republish activities (likely due to their high number - 650+ - of activities), which is a good test case for the new workflow. Individual activities validate successfully but hang on the "Almost there" screen below for the last publishing step.

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/ce7147d5-ec14-45e3-9b62-86facc50a55e)
