### ISSUE TITLE
IATI Publisher organisation search not returning all results

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1271]
Using the top-right search bar on the IATI Publisher [Organisation List ](https://publisher.iatistandard.org/list-organisations)does not seem to be returning all results.

For example, 
- searching "forest" returns only 1 of 2 publishers listed (Forest Trends Association, Forests of the World).
- searching "swedish" or "genome" returns no results, despite there being publishers with these words in their name.

**Comment by sriza** [comment]
@emmajclegg 

This issue has been resolved and the fixes are now deployed to production branch. Please have a look and let us know if issue persists.

The fixes to this issue was merged to main branch with PR #1205.

Thank you

cc @praweshsth

**Comment by emmajclegg** [comment]
@sriza - thanks for the update. Can you give a bit more information on what the issue was and how it was fixed? (at a high level). This is hard to test otherwise as I'm not sure why certain organisations were being returned in the search and others weren't.

**Comment by PG-Momik** [comment]
@emmajclegg - hi. regarding your concerns : 
### Cause:
Before the fix, the search feature only returned organisation(s) if the search text existed in the 'organisation_name' or organisation admin's email.
### Solution: 
We extended the search query to also return organisation(s) if searched text exists in its 'publisher_name'.
### Conclusion
The search feature now returns organisation(s) if the searched text exists in either : publisher_name, organisation_name or organisation admin's email

**Comment by emmajclegg** [comment]
Thanks @PG-Momik - that makes sense. The search looks to be working as expected on the production site so happy to close this issue
