### ISSUE TITLE
Navigation bar UI changes made during translation

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#1278]
Translating IATI Publisher to French caused the navigation bar to look congested:
![image](https://github.com/younginnovations/iatipublisher/assets/24825118/42c84fad-c27a-4258-8b3e-5490437787ee)

We found the breakpoint for this UI issue to be 1457px, i.e for screen width of 1457 pixel or below the navigation bar would look congested as above.

Thus, we have made few changes to the UI of navigation bar :
- Shifted the buttons on navigation bar to sidebar for screen size 1457px or below
- Update on the design of sidebar
![image](https://github.com/younginnovations/iatipublisher/assets/24825118/4b9065de-dde5-48f8-b409-02442ceb62d6)

These changes are implemented in the staging site. Please have a look and let us know if you have any suggestions regarding them.

**Comment by DaveEade49** [comment]
I've had a quick look at this and it seems fine to me - but I'll also let @emmajclegg  comment as well.

**Comment by emmajclegg** [comment]
Thanks @DaveEade49. To check @sriza - will this sidebar change apply to small screens only (1457px or below), or all users? 

I think this is better than having congested menu text. It does hide the navigation though so we'll need to be conscious of helping existing users find the new menu.

**Comment by praweshsth** [comment]
@sarinasindurakar list out the screen sizes that shows the navigation bar and that doesn't show the navigation bar

**Comment by sarinasindurakar** [comment]
The navigation bar will appear on top if screen size width is larger than 1425. The following screen sizes will appear on the top.
- 1440 x 900
- 1536 × 864
- 1920 × 1080
- 2560 x 1440
- 3200 x 1800
- 3840 x 2160
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/d902802d-9a8c-4efc-9ea5-bf813692fc14)

If the width of the screen is less than 1420, then navigation bar will appear as a sidebar. The following screen sizes appeared as a sidebar.
- 390×844
- 360×800
- 428×926
- 820 x1180
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/04d65a5d-7073-486c-aed0-5b5560971de7)

We used the inspect  to adjust the screen's dimensions for testing. I've attached the video of how I tested.

https://github.com/younginnovations/iatipublisher/assets/65848732/60db52df-3e78-44e4-963c-deb63cbde74d
