### ISSUE TITLE
Organisation Data - non-mandatory fields cannot be deleted once started

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1282]
On the [Organisation Data](https://publisher.iatistandard.org/organisation) page I have noticed for publisher "Makerere University" that non-mandatory elements such as "total-budget", "recipient-org-budget", "document-link" cannot be deleted once started, and contribute to the 100% Publishing Progress score even though they are non-mandatory.

In this case, the publisher started completing them in error and now wants to clear these fields before publishing their organisation file. There is no way of doing this without the sections being marked as "not completed".

1) Can a "delete" option be added against non-mandatory fields?
![IATI Publisher - can't delete organisation fields](https://github.com/younginnovations/iatipublisher/assets/137316374/51f7db3a-c1bd-43e2-968d-6b8f282ce4d7)

2) Can the Publishing Progress score be reviewed so that only mandatory fields are included in the calculation? 
![IATI Publisher - can't delete organisation fields 3](https://github.com/younginnovations/iatipublisher/assets/137316374/2b516686-2f0b-4618-96a6-71227e597419)

**Comment by PG-Momik** [comment]
@emmajclegg

> *"Can a 'delete' option be added against non-mandatory fields?"*

Sure. We'll work on adding a delete option to mandatory elements.

> *"Can the Publishing Progress score be reviewed so that only mandatory fields are included in the calculation?"*

Currently organisation-identifier, total-budget, recipient-org-budget, recipient-region-budget,  recipient-country-budget, total-expenditure and document-link are not considered mandatory element on the organisation data level. 
However, said elements can have mandatory fields (sub-elements or attributes). The progress percentage is accounting for completion of such mandatory fields.

Please let us know if you are recommending not accounting for element level completion, when calculating progress percentage? This would mean that the progress percentage would only account for completion of mandatory elements: organisation-name and reporting-org.
cc: @praweshsth

**Comment by PG-Momik** [comment]
@emmajclegg,

We've added 'Delete' option to elements on the organisation detail page. Please note that some elements do not have 'Delete' option (organisation-identifier, name and reporting org) since they are core elements, deleting these elements would create issue when importing files.  
The changes have been deployed to staging.

**Comment by emmajclegg** [comment]
Thanks @PG-Momik - I can see the delete button working in staging. I don't think the Publishing Progress score is updating however?

e.g. below, the three core fields (organisation-identifier, name and reporting org) are completed and there's no non-mandatory fields started, yet the score top-left is not 100%.

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/e2fe6db2-1e25-456d-a9e4-32ff2cf9a0cd)

**Comment by emmajclegg** [comment]
After discussing the scoring with @DaveEade49 and @praweshsth, I understand how it's working and am happy for the changes to be moved to Production (and the issue closed)
