### ISSUE TITLE
Add new Niger Registration Agency (NE-DGI) to dropdown on registration page

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1287]
There is a new org-id registration agency for Niger ([NE-DGI](https://org-id.guide/list/NE-DGI)), which needs adding to the dropdown list on the IATI Publisher registration page (to allow a new publisher to register).

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/42b0059a-17ad-429b-9445-c096c13f396a)

**Comment by PG-Momik** [comment]
@emmajclegg ,

We've added Organisation registration Agency : NE-DGI for country : Niger. The change has been deployed to staging. 

![image](https://github.com/younginnovations/iatipublisher/assets/57512059/b8d359d5-3d79-487d-88b6-43acce12a2a6)
---

**Comment by emmajclegg** [comment]
Thanks - I've tested registering a new publisher with it but get the error message "The selected registration agency is invalid." after completing Step 1 and clicking "Next Step" at the bottom of the Publisher Information screen.

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/93bbd0ce-b9b3-4d68-965f-22591b156694)

Same with NE-COA:

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/1c0a74f8-36aa-4be1-a351-d3de14c3794f)

**Comment by PG-Momik** [comment]
Hi @emmajclegg, it appears that some changes related to this issue were accidentally omitted during the merge for deployment. Specifically, the modifications to the code that dealt with the validation of the organization registration agency were left out. We've now deployed the remaining changes required to address this issue. Please take a look and inform us if the problem continues. Thank you!

**Comment by emmajclegg** [comment]
Great - it looks to be working ok now, so happy for the changes to be pushed to production
