### ISSUE TITLE
Deletion of Organisation.

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1293]
Hi can we delete the organisation which has been set up as:

"To be Deleted - do not use"

Thanks
Dave

**Comment by praweshsth** [comment]
@DaveEade49, we need more context on this. Is the name of the organisation set up as "To be Deleted - do not use" or something else?

**Comment by sriza** [comment]
@DaveEade49 We have deleted the organization "To be Deleted - do not use". Please have a look.
