### ISSUE TITLE
Aidstream - Publisher Migration

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1297]
Can we please arrange to migrate the following organisation:

ORGANISATION NAME:
Abt Britain Ltd

ORGANISATION IDENTIFIER:
GB-COH-10633588

Can you let me know if there are any blockers or complications ASAP, and also when the processes complete.

Thanks

**Comment by Sanilblank** [comment]
@DaveEade49 We performed the migration on the testing server and the migration was successful. However, after the successful migration, it seems there are some validation issues. Could you tell us how to move forward with these?

```
GB-COH-10633588-PMEL
The Planned Disbursement Period must not be longer than three months.

GB-COH-10633588-PIN
Recipient Region’s percentage is already 100%. The sum of the percentages of Recipient Country and Recipient Region must be 100%.
Recipient Country’s percentage is already 100%. The sum of the percentages of Recipient Country and Recipient Region must be 100%.

GB-COH-10633588-GGFTAFEP
Recipient Country’s percentage is already 100%. The sum of the percentages of Recipient Country and Recipient Region must be 100%.
Budget with type revised must have period start and end same to that of one of the budgets having same type original for budgets elements at position 1, 2, 3, 4
The Planned Disbursement Period must not be longer than three months
The Planned Disbursement Period must not be longer than three months

GB-COH-10633588-SuNMaP2
The Planned Disbursement Period must not be longer than three months
The Planned Disbursement Period must not be longer than three months

GB-COH-10633588-Ascend
Budget with type revised must have period start and end same to that of one of the budgets having same type original for budgets elements at position 3, 4
The Planned Disbursement Period must not be longer than three months
The Planned Disbursement Period must not be longer than three months

GB-COH-10633588-MEOR
The Planned Disbursement Period must not be longer than three months
The Planned Disbursement Period must not be longer than three months
```

**Comment by DaveEade49** [comment]
For the planned disbursements - can we leave these blank.

For the Recipient Country / Regions - can we leave the recipient regions blank ( I think they have populated both in error )

For the budget revised one - can we create a duplicate line with the same details except change the type to original.

Thanks
Dave

________________________________

**Comment by DaveEade49** [comment]
@Sanilblank @praweshsth  - any update on this one?
Thanks
Dave

**Comment by Sanilblank** [comment]
@DaveEade49 The migration of the organisation has been done and the changes have been made according to your comment. Please have a look.
cc. @praweshsth

**Comment by DaveEade49** [comment]
Thats great. Thanks
