### ISSUE TITLE
Add organisation registry agency for Yemen

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1320]
A new organisation registry agency for Yemen (YE-CR - Commercial Registry) is not added in the publisher and IATI Registry. 

- [ ] Check if there will be issue for 'I am new to IATI' user registration using this new agency with IATI Registry without implementing it. If there is issue then it needs to be fixed in IATI Registry first. 
- [ ] Add the following agency in the system (YE-CR - Commercial Registry) in IATI Publisher

CC: @odscrachel

**Comment by odscrachel** [comment]
Thanks, are there any updates on when this will be added? If there are any issues, let us know, and we can try and add it to Org-Id first.

**Comment by praweshsth** [comment]
@odscrachel we will look into this as we are back from today.

**Comment by A4family** [comment]
It is acceptable to add (YE-CR - Commercial Registry), which is absent in both the publisher and the IATI Registry. However, we also require various other fields, as specified in the provided CSV file column, into our system. Also, the organization can be published but may not be visible in d-portal or any data visualization platform. 

[org-id-f038f0c21c.csv](https://github.com/younginnovations/iatipublisher/files/13406157/org-id-f038f0c21c.csv)

**Comment by odscrachel** [comment]
This has now been officially added to org-id. Could you add this as soon as is possible. Thanks. You can find the details here http://org-id.guide/list/YE-CR

**Comment by odscrachel** [comment]
@praweshsth @A4family has this been added to publisher?

**Comment by praweshsth** [comment]
@odscrachel this has been added to publisher.

**Comment by odscrachel** [comment]
Great, thanks
