### ISSUE TITLE
Add organisation registry agency for Palestine

### ISSUE THREAD

**Issue by IsabelBirds** [younginnovations/iatipublisher#1325]
A new organisation registry agency for Palestine (PS-TIN, Tax Identifier Number) is not added in IATI Publisher. http://org-id.guide/list/PS-TIN 

- [ ] Add the following agency in the system (PS-TIN, Tax Identifier Number) in IATI Publisher

cc @odscrachel

**Comment by praweshsth** [comment]
- [ ] Should be available in the list when palestine is selected or no country is selected. 
- [ ] Should be available for users who are creating account with both 'I'm new to IATI' and 'I have IATI Registry' 
- [ ] Should be available for users to make change the org-id in organisation data

**Comment by praweshsth** [comment]
@IsabelBirds @odscrachel This organisation has been added in IATI Publisher.

**Comment by IsabelBirds** [comment]
Great, thanks all.
