### ISSUE TITLE
As a user I want to see Org-id "CD-MJDH" for Democratic Republic of the Congo so that I can create account as new or old or make change in organisation data

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1326]
- [ ] Should be available in the list when Democratic Republic of the congo is selected or no country is selected. 
- [ ] Should be available for users who are creating account with both 'I'm new to IATI' and 'I have IATI Registry' 
- [ ] Should be available for users to make change the org-id in organisation data

**Comment by siwhitehouse** [comment]
This appears to be implemented by https://github.com/younginnovations/iatipublisher/pull/1327 - I can see the list in the dropdown at https://publisher.iatistandard.org/iati/register but the only way to identify it is the Democratic Republic of the Congo is by its two-digit ISO code: the country name does not appear.

**Comment by praweshsth** [comment]
The country name of the Congo is not listed as Democratic Republic of the Congo but it is listed as Congo (the Democratic Republic of).
