### ISSUE TITLE
Unable to add recipient countries  within document link of organization data under specific condition.

### ISSUE THREAD

**Issue by A4family** [younginnovations/iatipublisher#1332]
Within the organizational data, specifically in the document link section, the organization faced challenges in adding recipient countries.

In the system, due to the multi-nested structure, data is stored in JSON format. Initially, when the organization creates multiple document links, the links with recipient countries are stored in the correct format with appropriate indexing. However, issues arose when the organization decided to delete a document link from the middle, disrupting the indexing during database storage. The unordered indexing of document links resulted in difficulties when adding recipient countries in the middle, as there was no proper index to accommodate the addition. 

Consequently, the recently added recipient country could not be successfully saved to the database.

To address this problem, we have resolved it by re-indexing every time a user updates the document link in the organization data.

@odscrachel

**Comment by odscrachel** [comment]
Thanks, it sounds like this is now resolved. Should we tell the organisation to try again?

**Comment by odscrachel** [comment]
Confirmed in today's call that the issue should be resolved. I'll update the organisation. Thanks
