### ISSUE TITLE
User should not be able to edit the activity identifier once the activity is published.

### ISSUE THREAD

**Issue by sarinasindurakar** [younginnovations/iatipublisher#1341]
# Overview
Currently, the users are allowed to change/edit the activity identifier even after publishing the activity. So, once an activity is published, users will not be able to edit the activity identifier.

# QA Spec
- [x] Do not show the edit button in the activity identifier.
- [x] Freeze the activity identifier field.
- [x] Once the activity is published or is in the "previously published in IATI" state, the activity identifier cannot be edited.

**Comment by sarinasindurakar** [comment]
Issues:

**- [ ]  Existing published activities are updated when the user saves the IATI identifier.**

https://github.com/younginnovations/iatipublisher/assets/65848732/0129f105-5a61-430e-9cfc-c3ba948048ae

**- [ ] Hide the edit button of iati identifier text  in activity summary page .** @rajkarnikar11

**Comment by sarinasindurakar** [comment]
@odscrachel This issue has been fixed. Please check in staging .

**Comment by odscrachel** [comment]
This seems fine in staging.
