### ISSUE TITLE
Setup is not complete even after adding required fields

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1346]
" I've proxied the Open Cities Lab account (named account is Kim Harris) and I can see that all of the default values have been completed except for Linked Data URI, which I am interpreting as being an optional value. I checked the manual and it is not one of the values shown as being completed there."

Requested by @siwhitehouse

**Comment by emmajclegg** [comment]
I believe this issue is now covered by a newer one I've raised on default values (#1371), so we can close this. 

@siwhitehouse - shout if not the case.

**Comment by emmajclegg** [comment]
Closing this issue as no longer relevant. Default values were worked on in https://github.com/younginnovations/iatipublisher/issues/1371
