### ISSUE TITLE
Setup not completed because of Linked URI

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1348]
Setup is not considered completed when Linked URI is not added. 

@siwhitehouse mentioned that Linked URI is an optional value. And it should not contribute to the completeness of the setup.

**Comment by praweshsth** [comment]
We checked and currently, it is required to be filled to make the setup complete. What should we do regarding this? Do we change the logic to exclude Linked URI?

**Comment by siwhitehouse** [comment]
Thanks for raising this issue @praweshsth 

I have found examples of organisations entering values such as '-' and 'N/A' in this field and these values then appearing in their published files. We should avoid putting publishers in the position where they are publishing bad or nonsense data.

Can you tell me what the impact is of not completing the setup, please. For instance, can an organisation publish their activity files without completing the set up.

**Comment by praweshsth** [comment]
Added by @siwhitehouse in zendesk ticket:

In the Organisation list UI Open Cities Lab show as having completed their Default Values.  


![Image](https://github.com/younginnovations/iatipublisher/assets/2421695/627c1a7d-1e73-460a-83c6-e440fecb78de)

But, when I proxy their account I see this alert



![Image](https://github.com/younginnovations/iatipublisher/assets/2421695/73d1d9f3-0fda-4e90-af38-407878a8e50e)

**Comment by siwhitehouse** [comment]
> Added by @siwhitehouse in zendesk ticket:
> 
> In the Organisation list UI Open Cities Lab show as having completed their Default Values.
> 
> ![Image](https://private-user-images.githubusercontent.com/2421695/298458955-627c1a7d-1e73-460a-83c6-e440fecb78de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NjI1ODAsIm5iZiI6MTcwNTk2MjI4MCwicGF0aCI6Ii8yNDIxNjk1LzI5ODQ1ODk1NS02MjdjMWE3ZC0xZTczLTQ2MGEtODNjNi1lNDQwZmVjYjc4ZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMjIyNDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI4ZGUxYjlhNTE0NDk3ZmYyMWExZTg1MGU0NzI5NDQxNDE2YjkxZjc0MjM3OTBhN2YwZTliNzEwYTI3NmRmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lWfkizIWyKDaKLDesxm6cPjSY9Z2LK_PeiQ682oLfOU)
> 
> But, when I proxy their account I see this alert
> 
> ![Image](https://private-user-images.githubusercontent.com/2421695/298459188-73d1d9f3-0fda-4e90-af38-407878a8e50e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NjI1ODAsIm5iZiI6MTcwNTk2MjI4MCwicGF0aCI6Ii8yNDIxNjk1LzI5ODQ1OTE4OC03M2QxZDlmMy0wZmRhLTRlOTAtYWYzOC00MDc4NzhhOGU1MGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMjIyNDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjliZTdjNTMwYmY0MTg0YWQ1M2VjNGExZDQyODkwMjNjN2Q3ZmIwNTg1MzNjMDI0ODJkNjhlMzg3MzIwMzgxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T07xuj1KC0YGv5edx8TmKnrB-08Iqr-B0n_cMNhyyeU)

This is a separate issue that I will raise as another issue. I would like us to agree how we raise issues without naming individuals and their organisations, please.

**Comment by siwhitehouse** [comment]
> Can you tell me what the impact is of not completing the setup, please. For instance, can an organisation publish their activity files without completing the set up.

@praweshsth

**Comment by siwhitehouse** [comment]
Thank you @praweshsth We think this issue is wider than just Linked URI. 

Whether a value is mandatory or optional in the schema is not particularly relevant here. Publishers should be presented with an opportunity to create default values where they are appropriate. They should not be prompted to complete all of the default values to remove an alert as this is causing them to enter bad data.

This needs some editing of the wording on the Default Values tab of the Settings page, a change to how the system records whether default values have been entered and a change to how the system reports back whether default values have been set. We are happy to discuss alternative changes that achieve how we want publishers to be informed about default values.

Given that this involves a number of changes and choices to be made, how do you prefer to work on this, please? I've added @odscrachel and @dan-odsc to the issue to help us with scheduling, process and making the necessary decisions.

**Comment by praweshsth** [comment]
@siwhitehouse Please provide us the requirement on this after your discussion, we will go ahead with that.

**Comment by praweshsth** [comment]
@siwhitehouse @dan-odsc What should we do here?

**Comment by dan-odsc** [comment]
We want to look at in a more comprehensive way that will address fundamental issues behind this.

Simon is going to scope this out and share with you. Moving to 'no status' for now but this will most likely be closed down and superseded by a new issue.

**Comment by siwhitehouse** [comment]
Closing this issue. I will open other issues to describe the work once we have scoped this out amongst the team.
