### ISSUE TITLE
Make error message to user clearer when updating an organisation identifier in Publisher

### ISSUE THREAD

**Issue by siwhitehouse** [younginnovations/iatipublisher#1352]
I have set up an account in Staging to troubleshoot and replicate issues. The organisation name is 'simon-troubleshooting'. For the issue I am trying to troubleshoot I need to update the organisation reference.

I go to https://iatipublisher-staging.yipl.com.np/organisation/organisation_identifier and I change the country, the Organisation Registration Agency and the Registration Number. I see that the organisation-identifier field is updated to the correct identifier and I have checked that this identifier also appears in the IATI Registry Staging site,

When I click on "Save and Exit" I am presented with the error message "Please enter correct identifier as present in IATI Registry." and the organisation-identifier field changes to the previous/existing identifier. I am unable to update the organisation-identifier.

I have been able to replicate this with two other publishers, chosen at random, from the publishes listed at https://staging.iatiregistry.org/publisher/

**Comment by praweshsth** [comment]
@siwhitehouse Please send us the whole process and data and if possible a screen record of it so that we can understand the issue.

**Comment by siwhitehouse** [comment]
Logged in as user 'simon-troubleshooting I go to https://iatipublisher-staging.yipl.com.np/organisation/organisation_identifier

![image](https://github.com/younginnovations/iatipublisher/assets/1718090/fe96f9b0-18c6-4c56-89c1-caf8cc2be6bf)

I update the organisation identifier to the one whose error I want to replicate

![image](https://github.com/younginnovations/iatipublisher/assets/1718090/3b56be2f-449c-47fe-b9f6-32f3762f4917)

That publisher exists in the staging site of the Registry, with the same identifier I have constructed in Publisher.

![image](https://github.com/younginnovations/iatipublisher/assets/1718090/56e824be-9329-47f3-aa49-d513728c33d1)

When I click on "Save and Exit".

![image](https://github.com/younginnovations/iatipublisher/assets/1718090/ea5fd405-aa6b-4692-bf85-1271ee2d83ec)

I am presented with the error message "Please enter correct identifier as present in IATI Registry." and the organisation-identifier field changes to the previous/existing identifier. I am unable to update the organisation-identifier.

Please let me know when you have replicated this and I will obscure the organisation name from the images posted.

**Comment by praweshsth** [comment]
@siwhitehouse thank you for sharing the process. To change the organisation-identifier:

- publisher id associated with organisation-identifier in IATI Registry should match with the publisher id and organisation-identifier in IATI publisher. 

In your case the publisher id is not same as in IATI Registry staging. Hence it is not allowed to change.

**Comment by siwhitehouse** [comment]
@praweshsth They look exactly the same to me. What differences do you see, please?

**Comment by praweshsth** [comment]
@siwhitehouse the publisher ID of  'Simon-troubleshooting' is trouble and when you created the organisation in IATI Publisher, same ID was also created in IATI Registry. Both in publisher and registry, the publisher ID and organisation identifier are associated. 

You tried to change the organisation identifier of 'Simon-troubleshooting' but in IATI registry the organisation identifier is not changed. And when you tried to change, it is showing the error.

**Comment by praweshsth** [comment]
@siwhitehouse @dan-odsc 

Should we close this issue, because we have added JICA in staging which is mentioned in another issue #1340 ?

**Comment by dan-odsc** [comment]
Moving to proposed as there is further scoping/defining to so based on our call yesterday.

**Comment by emmajclegg** [comment]
We will likely de-prioritise this issue, but will suggest some improvements to the user feedback received when a user enters an organisation identifier that does not match their Registry account (for future UI enhancements).

e.g. an error message along the lines of "Your organisation identifier must match the identifier linked to your IATI Registry publisher ID"

**Comment by emmajclegg** [comment]
Closing this issue as allowing changes to organisation identifiers was successfully completed in #1364. This is not a user-facing action so further improvements to messages in the interface are not a priority
