### ISSUE TITLE
Update snyk and dependabot packages - January 2024

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1356]
Update snyk and depandabot packages for January 2024

**Comment by A4family** [comment]
- [Ts-loader from 9.5.0 to 9.5.1](https://github.com/younginnovations/iatipublisher/pull/1331)
- [[Snyk] Security upgrade php from 8.1-alpine to 8-alpine ( develop )](https://github.com/younginnovations/iatipublisher/pull/1355)
- [[Snyk] Security upgrade php from 8.1-alpine to 8-alpine ( production )](https://github.com/younginnovations/iatipublisher/pull/1354)
- [[Snyk] Security upgrade php from 8.1-alpine to 8-alpine ( staging ) ](https://github.com/younginnovations/iatipublisher/pull/1353)
- [[Snyk] Upgrade moment from 2.29.4 to 2.30.1](https://github.com/younginnovations/iatipublisher/pull/1349)
- [[Snyk] Upgrade ts-loader from 9.5.0 to 9.5.1](https://github.com/younginnovations/iatipublisher/pull/1331)
- [[Snyk] Upgrade @types/select2 from 4.0.58 to 4.0.60](https://github.com/younginnovations/iatipublisher/pull/1323)
- [[Snyk] Upgrade @vueform/multiselect from 2.6.3 to 2.6.6](https://github.com/younginnovations/iatipublisher/pull/1322)
- [Bump docker/build-push-action from 4.1.1 to 5.1.0](https://github.com/younginnovations/iatipublisher/pull/1321)
- [[Snyk] Upgrade apexcharts from 3.42.0 to 3.43.0](https://github.com/younginnovations/iatipublisher/pull/1316)
- [Bump docker/setup-qemu-action from 2 to 3](https://github.com/younginnovations/iatipublisher/pull/1310)
- [Bump docker/setup-buildx-action from 2 to 3](https://github.com/younginnovations/iatipublisher/pull/1309)
- [Bump docker/login-action from 2.2.0 to 3.0.0](https://github.com/younginnovations/iatipublisher/pull/1307)
- [Bump actions/checkout from 3 to 4](https://github.com/younginnovations/iatipublisher/pull/1301)

**Comment by PG-Momik** [comment]
Closing this since all depandabot and snyk packages have been merged.
