### ISSUE TITLE
Send user's information along with message when user asks for supports using Zendesk

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1361]
To send the user's information the following needs to be done in the Zendesk configuration or setting and provide to developers:

1. Navigate to the "Admin Center."
2. Within the sidebar, locate "Objects and Rules."
    1. Access "Fields."
    2. Create custom fields, each has a unique "Field ID" and "Display Name."
    3. Developers require both the "Field ID" and "Display Name" to transfer information to Zendesk.
3. The extra details from IATI are then passed in the ticket information on Zendesk.

Following custom fields can be Full name of user, username, email address of user, Organisation Name, URL of page when user sends the message to support.

**Comment by dan-odsc** [comment]
Further discussion required our end. Will confirm whether we want to go ahead with this asap.

**Comment by emmajclegg** [comment]
I'm closing this issue as we are not likely to work on it any time soon. It may be a nice to have to investigate further in future, but does not have guaranteed benefit to take it forward at this point.
