### ISSUE TITLE
Updating or preserving activity data elements, as per the IATI Standard, when a publisher's organisation identifier changes

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1364]
If a publisher needs to change their _organisation-identifier_ in IATI Publisher post-registration, we would expect the following behaviour:

### **STEP 1 - user updates their organisation identifier**
- The user can edit their _organisation-identifier_ from the [Organisation Data](https://iatipublisher-staging.yipl.com.np/organisation) screen.
- The user can change their "Organisation Registration Agency" and "Registration Number". The change will be accepted (i.e. IATI Publisher lets them save it) if the new _organisation-identifier_ is the same as on their Registry publisher account.
- The [Organisation Data](https://iatipublisher-staging.yipl.com.np/organisation) screen will display the new _organisation-identifier_, and _reporting-org reference_ will have been updated to match.

### **STEP 2 - IATI Publisher updates activity data**

CASE A: For activities that were already published:
- _iati-identifier_ does not change
- _reporting-org reference_ changes to the new _organisation-identifier_
- _[other-identifier](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/other-identifier/#:~:text=Definition,has%20changed%20it's%20organisation%20identifier.)_ is added. This will have _type_ = B1 (Previous Reporting Organisation Identifier) and _ref_ = the old organisation-identifier
- The option to "Republish" the activity is visible to the user

CASE B: For activities that were unpublished:
- _iati-identifier_ changes to include the new _organisation-identifier_
- _reporting-org reference_ changes to the new _organisation-identifier_
- _other-identifier_ is added (as above)

CASE C: For newly created activities:
- _iati-identifier_ uses the new _organisation-identifier_
- _reporting-org reference_ uses the new _organisation-identifier_
- _other-identifier_ is added (as above)

### **STEP 3 - User republishes their activity file**
Activities that were previously published should be updated as per STEP 2, CASE A (there appears to be activity duplication happening when I tested this in staging today)

-------------------------
(Prawesh's comment)
- [x] When user clicks 'Save', Show a confirmation message 'This will change the reporting-org's reference in organisation file and all the activities. Are you sure you want to save the change?' 'Yes' and 'No' in option
- [x] When user clicks 'Yes' and if the organisation-identifier has changed, change the reporting-org's reference in organisation file and all the activities. 
- [x] Once the organisation-identifier is changed, show a message to the user: 'Please check your published activities, you will have to republish them. And in new activities please add old organisation-identifier in other-identifier's reference field.'
- [x] When user clicks 'Yes', if there is no change in organisation-identifier don't make any changes as mentioned above. 
- [x] This should not change the activity identifier of a published activity. 
- [x] The activity identifier of new activity or activity in draft stage but not published should have new organisation identifier in it's ID

**Comment by praweshsth** [comment]
CC: @robredpath 

Please review the requirement of this user story and suggest or edit if any changes are required

**Comment by robredpath** [comment]
@emmajclegg in https://github.com/younginnovations/iatipublisher/issues/1343#issuecomment-1921825411 I asked @praweshsth to separate out the "make sure activity IDs don't ever change" work from the "dealing with the case where an org changes its org-ID" case. I suspect that this latter case is relatively rare, so I think we can probably deprioritise this at the moment. 

For the benefit of any future development, I think that it would be helpful for us to outline here the steps that would be useful for IATI Publisher to carry out when this circumstance occurs: the workflow described above seems to push some of the work back on to the user, whereas I think we can probably describe some automatic updates that would make more sense. But, that's the limit of my knowledge of the practicalities of IATI publishing!

**Comment by emmajclegg** [comment]
@robredpath @praweshsth - I've edited the issue description above to explain the expected workflow (@IsabelBirds - a sense-check is welcome, particularly of the use of _other-identifier._)

I agree org IDs changing is uncommon, but it will come up so I think it would be good to estimate the work involved as a start. It may be that we then de-prioritise this against other issues that I'm planning to create in the coming days.

@praweshsth - i've left your original checklist in the description but suggest we remove it or relocate the detail if my explanation is clear. I agree with Rob that we want to avoid pushing too much manual work onto the user so happy to discuss how best to do that

**Comment by IsabelBirds** [comment]
@robredpath The reason this work started is because of the need to change an org-id, which has been blocking a migration since November - so very much a priority for me, and not as rare as you'd expect.

@emmajclegg Your workflow is correct and very clear, thanks!

**Comment by sarinasindurakar** [comment]
**Issues**

- [ ] 1. The publishing is not working. While the UI indicates failure, the API status indicates completion.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/5dd9961d-7344-49b2-b895-f9ea8513bc68)

- [ ] 2.  The popup modal looks distorted.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/630b095e-1280-439c-9594-b71ecfe89582)

**Comment by sarinasindurakar** [comment]
@emmajclegg This has been deployed to staging.

**Comment by emmajclegg** [comment]
Thanks @sarinasindurakar - I'll have a look on Monday

**Comment by emmajclegg** [comment]
@sarinasindurakar - I've done some testing and this looks to be working well. Some feedback/questions below:

1) Up until now, when the user tried to [edit organisation-identifier](https://iatipublisher-staging.yipl.com.np/organisation/organisation_identifier) from the Organisation Data page, an error message was returned if the identifier entered did not match what was on the IATI Registry for that publisher:
![image](https://github.com/younginnovations/iatipublisher/assets/137316374/61aca8ca-c423-43de-ab99-78f888ece855)

Can IATI Publisher still perform this check against the Registry to avoid users changing identifiers in error? I managed to enter and save an identifier which didn't match my Registry account.

The error message could highlight the Registration Agency and Registration Number boxes and say _''Please make sure your registration agency and number match the organisation identifier in your IATI Registry account''_

2) `other-identifier,` when added to existing activities, shows as ''not completed'' on the Activity Data screen. However, the two mandatory fields are populated so I'm unsure why?

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/52a56cd7-788a-40a9-a2ef-8e73421d4562)

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/fa7a7087-b958-4be5-b485-266f621307dc)

3) Can we make sure ''organisation identifier'' is spelt consistently - e.g. in the warning message below. IATI spells it with an 's'.

<img width="300" alt="image" src="https://github.com/younginnovations/iatipublisher/assets/137316374/092f25a0-0aec-4af9-9715-732144d755c2">

**Comment by PG-Momik** [comment]
1. > Can IATI Publisher still perform this check against the Registry to avoid users changing identifiers in error? I managed to enter and save an identifier which didn't match my Registry account.

Validation against registry had been disabled temporarily for testing purposes. Previous error message "Please enter correct identifier as present in IATI Registry" will now be shown when trying to save with incorrect `organisation-identifier`

2. > other-identifier, when added to existing activities, shows as ''not completed'' on the Activity Data screen. However, the two mandatory fields are populated so I'm unsure why?

This was a mistake on my part, upon updating other-identifier, complete status needed to be update, however i didnt handle this case.

3. > Can we make sure ''organisation identifier'' is spelt consistently - e.g. in the warning message below. IATI spells it with an 's'.

Done.

---

All changes have been deployed to staging.

**Comment by emmajclegg** [comment]
Great, thanks @PG-Momik - all looks to be working well. Can I suggest minor edits to the error message for clarity:

Current: "Please enter correct identifier as present in IATI Registry"
New: ''Please enter the correct identifier to match your IATI Registry account''

And - last point - can capital letters be removed from organisation-identifier, iati-identifier and reporting-org in the warning below (it looks odd for data elements)



![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/7dd10e63-b87d-46ab-922d-28016cb021a7)

**Comment by PG-Momik** [comment]
![Image](https://github.com/younginnovations/iatipublisher/assets/57512059/3685d4c3-a5a8-433e-9661-a6b550ef37da)


![Image](https://github.com/younginnovations/iatipublisher/assets/57512059/5e2c40a3-ad6d-44ce-889f-1dda5f3b697d)

---


Changes have been deployed to staging.

**Comment by emmajclegg** [comment]
Looks good from your screenshots @PG-Momik (I can't see the changes in staging though to be aware - the "organisation-identifier has changed" warning isn't coming up at all)

**Comment by PG-Momik** [comment]
My bad. I deployed #1298 to staging but forgot to merge and deploy this as well.
