### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1367]
The publisher has given the go ahead for migration from AidStream to IATI Publisher - info can be found in the Zendesk ticket:
https://iati.zendesk.com/agent/tickets/43402

**Comment by emmajclegg** [comment]
Once the migrated publisher has confirmed that they can log into IATI Publisher ok (they were having some problems), I'll update and close this GitHub issue.

**Comment by emmajclegg** [comment]
The publisher has confirmed that they can log in to Publisher now so I will close this migration as completed.
