### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by Man0zZ** [younginnovations/iatipublisher#138]
- [ ] success/error messages

**Comment by man-git007** [comment]
@Man0zZ What is the status of this issue and what branch is related with this issue?

**Comment by Man0zZ** [comment]
@man-git007 This issue is yet to be fixed. It is related to **77-auth-translation** branch

**Comment by Man0zZ** [comment]
@man-git007 There is animation left . It is related to 138-error-messages branch

**Comment by man-git007** [comment]
@Man0zZ How much time will it take to finish this issue?
@sriza @SauravSilwal10 Is this feature required or can we halt for now?

**Comment by Man0zZ** [comment]
@man-git007  don't know, have to see it.
