### ISSUE TITLE
Update migration script to fix activity's transaction completeness

### ISSUE THREAD

**Issue by A4family** [younginnovations/iatipublisher#1382]
### Issue Overview

During the organization migration process, an issue has arisen regarding the "completeness" of an element, even when all the data were correctly filled out. Generally, an observer is in place to ensure the completion status of an activity element when created or updated. However, in the case of migration, this observer fails to be triggered, particularly with transaction elements. Consequently, even if all the data were completed in a transaction, the "complete" status was not visible.

**Comment by emmajclegg** [comment]
Can we list the specific IATI data elements affected by this (it doesn't sound like just transactions), and whether it's the same fix required for all?

It sounds like the data migrated from AidStream is correct, and this is just a problem with the "completeness" labelling in Publisher? If this has highlighted any issues with publishers' migrated data, let me know as we will need to communicate with them from IATI Support before making any retrospective changes.

**Comment by A4family** [comment]
@emmajclegg 

Regarding the migration script, only the "transactions" element was directly affected, as its observer was not triggered. However, due to the relationship between the "recipient region" and "recipient country" elements with transactions, the complete status of these elements was also impacted by the bug. Therefore, while the fix primarily addresses the issue with the "transactions" element, it indirectly resolves the related issues with the other elements as well.

Yes, the data migrated from AidStream is correct, and the labeling of "completeness" in Publisher is also accurate. The only issue occurred within the script not being able to trigger the observer.

**Comment by emmajclegg** [comment]
Ok, thanks @A4family - that makes sense. Can you confirm if the script to fix the data completeness of previous publishers that were migrated from AidStream has already been run? (I understood that it had from @Sanilblank's comment in Zendesk #[43402](https://iati.zendesk.com/agent/tickets/43402))

These are example activities from previously migrated publishers where `recipient-country` and/or `transactions` are currently showing as "not completed" for unclear reason:
[https://publisher.iatistandard.org/activity/3237](https://publisher.iatistandard.org/activity/3237)
[https://publisher.iatistandard.org/activity/4538](https://publisher.iatistandard.org/activity/4538)

**Comment by A4family** [comment]
@emmajclegg 
I have created a new issue related to this here #1387
