### ISSUE TITLE
Add ability for IATI Admin users to block spam email addresses

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1385]
There has been an increase in spam IATI Publisher accounts being created - IATI Admins want to be able to delete and then block these users from creating an account again in future.

When we go to delete a user from IATI Publisher, can we add an optional functionality to also block the email address?

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/83216fcc-883d-4591-ba4c-71cbb74b66b4)

(We are blocking these spam users across other IATI tools, including the Registry and IATI Connect)

**Comment by PG-Momik** [comment]
@emmajclegg  we can work on this. 

We could add a simple checkbox on this modal to flag a email as spam.
![image](https://github.com/younginnovations/iatipublisher/assets/57512059/1878233e-775e-48c7-8401-cce4866fea8f)

The flagged emails can then be stored in separate `spam_emails` table. We could then prevent new registration from said emails if it exits on `spam_emails` table. 

I'll update this issue with a breakdown of possible tasks.

**Comment by emmajclegg** [comment]
Based on the solution you've proposed for #1384 @PG-Momik , I no longer think we need the ability to block user email addresses from the [User](https://publisher.iatistandard.org/users) page as well. If we can block the email address associated with an organisation when we delete the organisation, that should be sufficient.

**Comment by emmajclegg** [comment]
Closing as worked on in https://github.com/younginnovations/iatipublisher/issues/1384 and no further action needed
