### ISSUE TITLE
Fix the completeness issue of activity element while running migration script.

### ISSUE THREAD

**Issue by A4family** [younginnovations/iatipublisher#1387]
>[!NOTE]
> @emmajclegg 
As you have mentioned before in #1382 , there were two activities from different organizations where the "Recipient Country," "Recipient Region," and "Transactions" weren't marked as completed for unclear reasons. 

First, we carefully checked the migration script to make sure there were no problems when migrating the organization and its activities. We also tried creating and filling in activity data manually in the recipient region and country, and everything seemed to be working fine.

After spending some time looking through the code, we discovered there was a mistake in the completeness check that wouldn't have been noticeable through manual checking. This issue only became noticeable when we compared the data received from manual process with the data received from the migration script which was different.

We've fixed this problem now and written another script to ensure that all existing activities for migrated organizations are complete.

Before, when we checked the migration code, we discovered that only the "Transaction" element wasn't triggering its observer properly, which caused it to remain incomplete. Additionally, some migrated organizations had incomplete statuses for their "Recipient Country" and "Recipient Religion" too due to a problem in the completeness code. This code worked fine in the user interface (UI) but didn't function correctly when running the migration script.

To address this issue, we've created a separate script to mark all previously migrated organization activities as complete if necessary.

**Comment by emmajclegg** [comment]
Thanks for the update @A4family. The _recipient-country_ and _recipient-region_ completeness checks now look ok for the example migrated publishers I was looking at.

Transactions are still showing as "not completed" for activity https://publisher.iatistandard.org/activity/3237 - can you explain why this is? I'm not sure if it's related to the current fix or something different.

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/1c9d6fd4-2535-4deb-a88c-31b2cc859dff)

**Comment by A4family** [comment]
@emmajclegg 

It seems that during the migration script process, this organization might have been overlooked. However, we've re-run the script and everything now seems to be in order.

**Comment by emmajclegg** [comment]
@A4family - i've just noticed this activity with the same problem ("not completed" transactions): https://publisher.iatistandard.org/activity/4788

Do we have a list of the publishers that have been migrated from AidStream to Publisher to properly test this? (cc'ing @praweshsth, as not something to share via GitHub)

**Comment by A4family** [comment]
@emmajclegg 

We've executed both scripts sequentially (previously, we did so randomly) for all four batches of organizations that were migrated into IATI. Everything appears to be functioning as expected.

**Comment by emmajclegg** [comment]
Thanks @A4family - I've done spot-checks of previously migrated publishers and haven't noticed any further issues. Happy to close this issue.
