### ISSUE TITLE
Clearer labelling and/or auto-population of reporting-org/@narrative

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1406]
We're seeing many users mistakenly complete the `reporting-org/@narrative` field in Organisation Data with an organisation description, when it should be their organisation name. The long text strings that they're entering are causing problems for other IATI tools, so we want to make it clearer to users what this field is and, ideally, populate it for them.

In cases where the organisation has signed up as a primary reporter (almost all cases), `reporting-org/@narrative` should equal `iati-organisation/name`

For example, in my test account below, I've registered with publisher name "Emma's test publisher v.2" and as a primary reporter (`reporting-org/@secondary-reporter` = false)

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/f73e0d0f-4f60-4d41-b969-e0b22af22340)

My `iati-organisation/name` has been auto-populated, whereas the `reporting-org/@narrative` is left blank.

To make things clearer to users:
1) can we replace the word "narrative" by "name" in the reporting-org user interface? (highlighted in the two screenshots below)
2) what options are there for auto-populating this field with the publisher's organisation name? (in cases when `reporting-org/@secondary-reporter` = false). If missing default language is the problem, we can consider collecting this at point of registration.

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/99a10cfc-cc1d-4eef-8a85-cb058103f0ed)

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/d425c443-bc00-4785-9638-e39d326ecc2d)

**Comment by praweshsth** [comment]
# Approach
- When there is new sign up, the narrative will be populated with the name of the organisation. 
- The narrative, though, will be editable by the user, which will not update the existing name of the organisation element.
- For existing organisation, deploy the script to change the narrative to the name of the organisation and republish organisation and published activitiy file

# Issue/ concern/ question
- For existing organisations, if there are multiple narrative in multiple languages, what should we do?
- For existing organisations, the organisation file and the activity file needs to republish. Would that be okay? 

@emmajclegg

**Comment by emmajclegg** [comment]
@praweshsth - the approach above sounds good for new sign ups; that's what I was focusing on.

I don't think we need to retrospectively apply it to existing organisations' data. In Support, we've already contacted a few publishers to ask them to correct their `reporting-org/@narrative` so we can continue doing that for those that need to change it.

**Comment by praweshsth** [comment]
Added estimation.

**Comment by sarinasindurakar** [comment]
@PG-Momik 

- [ ] Issue 1: Change the placeholder text as " Type name".
<img width="1512" alt="Screenshot 2024-04-16 at 16 30 29" src="https://github.com/younginnovations/iatipublisher/assets/65848732/77fa3cd8-d2ae-4c95-9d3a-0ec78450edb4">

- [ ] Issue 2: Change the "Add additional narrative" to "Add additional name ".
<img width="1020" alt="Screenshot 2024-04-16 at 17 31 20" src="https://github.com/younginnovations/iatipublisher/assets/65848732/d7811ac1-c142-45cf-bd0e-3ed94118e220">

- [ ]  Issue 3. The placeholder not shown in organisation level languages.

- [ ]  Issue  4:   The language is not preselected in organisation information.

**Comment by PG-Momik** [comment]
This has been deployed to staging.

**Comment by emmajclegg** [comment]
Looks great!
