### ISSUE TITLE
Limit document-link category codelists for organisation vs. activity data

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1409]
When users are selecting a `document-link` category code ([codelist available here](https://iatistandard.org/en/iati-standard/203/codelists/documentcategory/)), it would be useful if Publisher restricts choice to what's allowed for the IATI organisation vs. activity file.
	
On the Activity Data page, only codes beginning with "A" are relevant:
<img width="736" alt="image" src="https://github.com/younginnovations/iatipublisher/assets/137316374/0853d6c8-bf5f-446d-9937-6c8890f92cda">

On the Organisation Data page, only codes beginning with "B" are relevant:
<img width="855" alt="image" src="https://github.com/younginnovations/iatipublisher/assets/137316374/25f11ea5-1f27-4963-9a19-a81f8321bbfa">

Can we restrict the drop-down menus accordingly to prevent users selecting the wrong codes?

**Comment by praweshsth** [comment]
# Issue/ concern / Question
As per the IATI Standard the [code category](https://iatistandard.org/en/iati-standard/203/codelists/documentcategory-category/#documentcategory-category):

| Code | Name               | Description                                             |
| ---- | ------------------ | ------------------------------------------------------- |
| A    | Activity Level     | The document is relevant to a specific activity         |
| B    | Organisation Level | The document is relevant to the organisation as a whole |

Does this mean that Document with code starting from 'B' will not be added in activity level? If the document with code 'B' might be added in activity level, then we should not seperate it. 

@emmajclegg

**Comment by emmajclegg** [comment]
@praweshsth - correct, documents with "B" codes should only be added to the Organisation file. And documents with "A" codes only to the Activity file. So they can be separated

**Comment by PG-Momik** [comment]
@emmajclegg, We can separate the category code for document-link as requested. 

One concern that we were not able to initially identify is how the existing data is to be handled. 
Looking at some of the data, I've noticed that some organizations have used category code  of group A on Organization level. Likewise,  category code of B have also been used in Activity level. Please let us know you want us to handle this.

**Comment by emmajclegg** [comment]
@PG-Momik - my team (IATI Support) will need to contact the existing organisations in this case to ask them to correct their data, as we shouldn't change anything on their behalf. If you have a list of organisations that this applies to, email it to me and I can action this.

Does the existing data need correcting before changes can be made to the IATI Publisher drop-down menus?

**Comment by PG-Momik** [comment]
@emmajclegg 

> Does the existing data need correcting before changes can be made to the IATI Publisher drop-down menus?

I see no immediate issues that will be caused by  changing the list in dropdown menu. Minor bugs that will occur for users data that have already used "wrong" code in the `document-link >> category >> code` field are:
1. Value not showing up on the detail page (UI level issue):
    a. 'Missing' doesn't show up because the code value is actually filled.
    b. Category name doesn't show up because it doesn't exist. (I temporarily removed it)
![ss_000897654](https://github.com/younginnovations/iatipublisher/assets/57512059/d8ce5eca-bd69-4877-8c8f-712bfd2e2713)

2. Values not showing up on form (UI and data level issue)
   a. Value doesnt show up if worng code used previously.
   ![image](https://github.com/younginnovations/iatipublisher/assets/57512059/59c9dca9-0e02-43f3-85d5-32b24e04034f)

   b. Will clear the use of "wrong" code from database when "Save and Exit" is clicked.
      -  Example: If a user had previously entered code 'B01' in activity. It would have been written to DB. With this change in action, if user opens the document-link form, and presses save and exit , the  value 'B01' previously set in DB will now be changed to " " (empty string).

**Comment by emmajclegg** [comment]
Hi @PG-Momik - ok, I don't see any major problems with the interface points you've described. The main thing is we don't want to be changing existing users' data in IATI Publisher without them doing anything.

It's not the end of the world if existing users have used "incorrect" codes against documents up until now (so we likely won't contact them to retrospectively correct), but we would still like the drop down menus separated out - as described in this issue - for ease of data entry going forward.

Any other questions, let me know - otherwise I'm happy for this task to be estimated in terms of number of hours work required.

**Comment by praweshsth** [comment]
Estimation added.

**Comment by sarinasindurakar** [comment]
@PG-Momik

**Comment by PG-Momik** [comment]
@emmajclegg 
This has been deployed to staging,
