### ISSUE TITLE
Display all users on Users page (including the active user)

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1411]
Currently, a user cannot see themselves on the [Users page](https://iatipublisher-staging.yipl.com.np/users) for their organisation, so it is common to have 0 users visible:

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/3972731d-8b38-4e99-8b3d-45bf47ce6c92)

It looks like the Users page lists other user accounts that have been associated with the organisation, but excludes the user that is currently logged in. To see their own username and role, the active user has to go to their Profile instead:

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/f6262c4a-064f-4722-892c-70e4abdddd8c)

To give both active users and IATI admins an easier way to see - at a glance - all user accounts associated with an organisation, can we include the current user on the Users page list?

**Comment by praweshsth** [comment]
# Approach
The user will be able to see themselves in the list of users but will not be able to take any actions like edit and delete from the list. To edit it, they should go to their profile instead. 

@emmajclegg

**Comment by emmajclegg** [comment]
That makes sense @praweshsth - the important thing is being able to see them included in the user list.

**Comment by praweshsth** [comment]
Estimation added

**Comment by PG-Momik** [comment]
@emmajclegg 
This has been deployed to staging
