### ISSUE TITLE
Is it necessary to filter the country budget item code based on the vocabulary?

### ISSUE THREAD

**Issue by sarinasindurakar** [younginnovations/iatipublisher#1418]
**For element: Country-budget-item**
All the budget codes appears in the dropdown option irrespective of the vocabulary selection. 

[Untitled_ Apr 03,2024 2_11 PM.webm](https://github.com/younginnovations/iatipublisher/assets/65848732/ba821f18-c7cc-419d-83dc-8c989ba5befe)

@emmajclegg  
Should the codes be filtered according to the budget vocabulary?

**For example:**
If we select, country-budget-items vocabulary = 2, should the codes for vocabulary 2(example 2.1.1 , 2.1.2) appear, or all the codes present for the country-budget-item element?

**Comment by emmajclegg** [comment]
@sarinasindurakar - I'll get feedback from the team on this tomorrow and update this issue. It's not a commonly used area of the Standard so we're checking how it should work.

**Comment by emmajclegg** [comment]
@sarinasindurakar - after checking within ODS, we believe this _country-budget-item_ element in the activity file is now redundant (i.e. no longer in use!). However the IATI Standard documentation is not particularly clear so it's something we want to more formally remove this year.

For now, there's no action needed on the drop-down menu filtering (your original question on this issue). I'll keep this issue open for now as it's likely we'll want to remove this element from IATI Publisher at some point this year.

**Comment by emmajclegg** [comment]
Closing this issue as no further action needed
