### ISSUE TITLE
Updates to text on registration page

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1436]
Can me make the following minor text updates to the new registration Step 1 page? (taken from our snagging board)

1. Change message to: "Start your IATI publishing journey by creating accounts in both IATI Publisher and the IATI Registry"
2. Change in-box text to: "Type your publisher ID here" (there is risk of confusion with a later field by saying organisation ID). 
3. Change message to: "This information will be used to register your organisation" (for simplicity)
4. Remove "for" in this prompt text (not needed)
5. Spell "Data Licence" with a "c" not "s" (i.e. IATI uses British spelling!)
6. Change to: "Organisation Description"
7. Remove the word "for" (same as point 4 above)
8. Change "IATI Organisational Identifier" to "IATI Organisation Identifier" 

The page also looks like it's missing the "mandatory fields" label to explain the red asterisks.

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/81028ee6-b404-4468-8ae2-30e9e16f7555)

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/1e5d1879-bec0-4c11-9f6b-d4d3fd3627db)

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/e77226f7-dbcc-45ac-aac5-1a82cb0a2078)

**Comment by PG-Momik** [comment]
@emmajclegg 
This has been deployed to staging.

**Comment by emmajclegg** [comment]
thanks @PG-Momik - can we make sure changes are reflected on the other registration page? (i.e. "My organisation has registered with IATI" route)

I suggest "Start your IATI publishing journey by creating an account in IATI Publisher" for the top message (1) 



![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/8429932e-7b93-4d12-a0b0-f79f1e7d0c65)

**Comment by PG-Momik** [comment]
This has been deployed to staging.

**Comment by emmajclegg** [comment]
@PG-Momik - looks good apart from the message now under the main heading (for the "My organisation has registered with IATI" registration route).

The publisher will already have an account on the IATI Registry if they're on this page, so I suggested this wording: 
_**"Start your IATI publishing journey by creating an account in IATI Publisher"**_ 

![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/ac512c13-56e4-4dcb-b38c-853f6097c388)

Thanks

**Comment by PG-Momik** [comment]
This has been deployed to staging.
