### ISSUE TITLE
Review workflow for bulk import via .xls file

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1439]
We often receive queries about how to use the IATI Publisher .xls bulk import feature - the most common are:

- Users don't know if using the bulk import functionality **overwrites** or **adds** to existing activity data in IATI Publisher
- Users can't find where to upload transactions
- We (in IATI Support) don't see evidence that the results templates are used and are confused by the need for 3 separate spreadsheet templates

Can we review the workflow here to guide users better, perhaps learning from what AidStream has done?

We can split the following into separate, smaller issues once discussed and agreed:
1) It is not clear from the activity overview screen that results and transactions can be bulk uploaded (these are the most likely activity elements to require a bulk upload). When clicking on these fields, can users be asked whether they want to enter these manually (one by one) or in bulk? If in bulk, they can be directed to the relevant [import xls page](https://iatipublisher-staging.yipl.com.np/import/xls).

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/b5e62dc1-416d-49f4-a5bc-a0129a247861)

2) Rather than "Please select one to proceed", how about we guide users by saying "What would you like to import?" - giving them the options of a) Basic Activity Data, b) Transactions or c) Results
![image](https://github.com/younginnovations/iatipublisher/assets/137316374/6adb0607-340b-4f6c-9a6b-ffb060e0ee1a)

3) Next, users could be asked whether they want to "overwrite" or "add" to existing data? If the import is going to overwrite their existing data (which is what currently happens I believe), they should be prompted to download their activity data first so that they can add to it and it's not lost.

4) Review the existing spreadsheet templates - it will be common for users to want to upload just transactions for an existing activity. For results, users ideally want to upload in one go rather than using 3 templates. How feasible is it to adapt the spreadsheet templates so that there are three to choose from? (see point 2 above): 
a) Basic Activity Data 
b) Transactions 
c) Results

---

# Tasks: 
- [ ]  #1524

**Comment by praweshsth** [comment]
@emmajclegg All your suggestions looks better for users making it easy for them to add the data. However, regarding point no. 3, that can be very complex to implement. Hence, we can implement a flow:

1. if the user wants to update, the system will provide the xls file with existing data and they make changes in it and upload it
2. if the user wants to replace, the system will provide empty xls file and they add data and upload it. 

To implement this, we need to work on the design first. 

CC: @Sanilblank @PG-Momik @sarinasindurakar

**Comment by emmajclegg** [comment]
>if the user wants to update, the system will provide the xls file with existing data and they make changes in it and upload it
if the user wants to replace, the system will provide empty xls file and they add data and upload it.

@praweshsth - that sounds sensible to me. The main thing is that it's not clear to users what's happening currently (i.e. whether they're overwriting vs. adding to existing data)

Should I split this issue into 4 smaller ones, according to my points above, or would you prefer to think about it as a whole workflow?

**Comment by praweshsth** [comment]
@emmajclegg before breaking it down, since the flow is going to be changed, we need to work on the flow design based on this and then we can estimate for it. It's better to do in a single go rather than break it down in parts.

**Comment by emmajclegg** [comment]
Ok @praweshsth - that makes sense. Feel free to estimate the work needed on design as a first step.

**Comment by emmajclegg** [comment]
@praweshsth - I'm moving this "to do" to work on when there's capacity - it's lower priority than the other issues currently on the project board.

**Comment by praweshsth** [comment]
@emmajclegg 

@shreyaydi will start the design work

@PG-Momik will look into the changes as per no. 4 question.

**Comment by BibhaT** [comment]
I've created a new workflow, please have a look: [Mind Map.pdf](https://github.com/user-attachments/files/16636992/Mind.Map.pdf)

I've also made an explanatory video for the same for ease: https://youtu.be/fbrz8th02so

**Comment by emmajclegg** [comment]
Thanks @BibhaT - I will have a look at this and comment on Monday

**Comment by emmajclegg** [comment]
Hi @BibhaT - this new workflow looks logical to me. It makes the difference between adding new vs. editing existing data much clearer, particularly helping the user to download their existing activity data when needed.

For the download step - for info - I had already started thinking about how we simplify exporting data as a future improvement here: [#1526](https://github.com/younginnovations/iatipublisher/issues/1526) (there are a lot of steps currently)

I'm happy to progress with this design, and happy to help with instruction text for the interface if you need. The main thing I think is important to make clear to users is when an import is about to overwrite existing data in IATI Publisher, which can be factored into the in-tool instructions at the "change data and upload" steps in the workflow.

**Comment by praweshsth** [comment]
this will be referred in designing and development issues that will be created later.
