### ISSUE TITLE
Review titles of steps in registration process to make them more intuitive

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1443]
For the "I am new to IATI" registration route, can we rename the steps to make it clearer what data each section is collecting?

This is to make the process more intuitive to users (particularly whether each section is about the user's organisation or them as an individual), and correct some typos in the step 3 text. 

**Current steps:**
![image](https://github.com/younginnovations/iatipublisher/assets/137316374/41eb4d77-3801-4311-ad93-bfdfa9f528dc)

**Suggested titles for steps:**

1. Organisation Information: "This information will be used to register your organisation as an IATI publisher"
2. Contact Information: "This is your organisation's contact information"
3. Publishing Information: "This is about how your organisation will publish data"
4. Administrator Information: "This will create an admin account for you as an individual"
5. Email Verification

**Question**: what is the "default language" collected in step 3 being used for at the moment? Could "default currency" be collected here as well, then these two default values auto-populated in IATI Publisher's Settings? (they are the most important two, and this would save the user needing to populate them later)

**Comment by PG-Momik** [comment]
> what is the "default language" collected in step 3 being used for at the moment ? 

The default language field was added on registration pages because of the changes made on issue #1406 , where
1. The keyword was changed from 'narrative' to 'name' on element: reporting_org, 
2. Reporting org narrative is auto populated. 

Since narrative cannot be filled without language, default language is collected on registration page and associated to reporting org's narrative upon organisation creation.

> Could "default currency" be collected here as well, then these two default values auto-populated in IATI Publisher's Settings? (they are the most important two, and this would save the user needing to populate them later)

Sure this could be done.

**Comment by emmajclegg** [comment]
Thanks @PG-Momik. To keep things simple for now, let's leave "default currency" to be populated in Settings (i.e. not add it to the registration flow).

As "default language" is now collected in the registration flow, however, it makes sense for this same value to be applied on the Settings page, so that the user does not need to complete it twice.

I'll move this issue to "to do" - any questions on the step labelling part, let me know.

**Comment by emmajclegg** [comment]
Thanks all - no comments to add.
