### ISSUE TITLE
Migration (AidStream to IATI Publisher)

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1448]
A publisher has asked for their activity data to be transferred from AidStream to IATI Publisher, with their AidStream account subsequently closed.

Details of the publisher can be found here: https://iati.zendesk.com/agent/tickets/44131

**Comment by praweshsth** [comment]
Migration completed

**Comment by emmajclegg** [comment]
Thanks @praweshsth . I'll close this issue.
