### ISSUE TITLE
Remove link to IATI Registry in Publishing Checklist

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1449]
On the IATI Publisher [Publishing Checklist](https://publisher.iatistandard.org/publishing-checklist) page, the link highlighted in the screenshot below takes users to the IATI Registry when we don't want them to register there.

This is confusing as the line before is correct in saying that new users no longer need to visit the IATI Registry in order to register.

Can we replace the highlighted link with one to IATI Publisher's "I am new to IATI" [registration page](https://publisher.iatistandard.org/iati/register) instead?

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/97642b42-85d5-4ccf-8b32-e14c2025816f)

**Comment by sarinasindurakar** [comment]
@emmajclegg This has been deployed to staging.

**Comment by emmajclegg** [comment]
thanks @sarinasindurakar

**Comment by Sanilblank** [comment]
This issue has been solved along with the issue

[Issue link](https://github.com/younginnovations/iatipublisher/issues/1450)
