### ISSUE TITLE
Add link to privacy policy

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1450]
We've noticed that IATI Publisher doesn't include a link to IATI's privacy policy (https://iatistandard.org/en/privacy-policy/) when this should be available to users.

Can we please add this as a new link in the tool's footer:

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/4db72011-6685-4089-a6d6-4591da993d01)

Also, does IATI Publisher use cookies to track users? If so, we should make sure it's clear what information is being collected here.

**Comment by sarinasindurakar** [comment]
@emmajclegg  This has been deployed to staging.

**Comment by emmajclegg** [comment]
Thanks @sarinasindurakar - can we have some information about what cookies IATI Publisher uses? So that we can compare against https://iatistandard.org/en/privacy-policy/cookie-policy/ to see if this needs more information added.

**Comment by PG-Momik** [comment]
@emmajclegg We only use basic cookies:
- Session Cookies: These are used for managing user sessions, allowing users to remain logged in.
- CSRF Token Cookies: These are utilized for security purposes, protecting against Cross-Site Request Forgery (CSRF) attacks to ensure that all actions performed on the site are authorized.

Besides the mentioned cookies we also collect standard browsing data (IP Address and Browser Information) for security and analytical purposes.

---

cc: @praweshsth @Sanilblank @sarinasindurakar
