### ISSUE TITLE
Investigate possible transactions bug for a publisher

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1460]
Issue details here (it only looks to affect a single publisher): https://iati.zendesk.com/agent/tickets/44456

**Comment by PG-Momik** [comment]
@emmajclegg we've looked into the issue. In some of the activities of the mentioned organisation, elements: sector, recipient region and recipient country data is malformed. Since these elements are also linked to transaction, the organisation is facing problem when saving transactions. 

For now the immediate solution would be to delete sector, recipient region, recipient country and transactions, and adding them again.

We would like to know how the organisation was able to create transaction with such data for us to look into it further.

**Comment by emmajclegg** [comment]
Thanks for looking into this @PG-Momik - can you share a list of the affected activities with me, either by email or via @praweshsth in the [Zendesk ticket](https://iati.zendesk.com/agent/tickets/44456)?

Also, when you say sector, recipient country/region are incorrect, what do you mean exactly? That the publisher has managed to enter non-valid values in those fields, or save them partially incomplete?

**Comment by emmajclegg** [comment]
Ok, thanks @PG-Momik and @praweshsth.

I will clarify with the publisher what level they want to publish sector, country and region information at (activity vs. transaction) and get more information on whether they entered their existing data manually or via a file import.

> For now the immediate solution would be to delete sector, recipient region, recipient country and transactions, and adding them again.

Do you need any further information from the publisher or time to look at their data before I work with them to do this?  ˄ ˄

Go ahead and raise any bugs found so far as new issues.

**Comment by PG-Momik** [comment]
> Do you need any further information from the publisher or time to look at their data before I work with them to do this?

We'd like to know/confirm if they too imported activities via xml. If they did import via xml or any other medium, we'd like to take a look at the file as well if possible.

Issue: [Import xml and form level bugs](https://github.com/younginnovations/iatipublisher/issues/1462) has been created to work on the bugs raised.

**Comment by emmajclegg** [comment]
To update - the publisher has not got back to me with more information yet on how they imported their activity data to IATI Publisher (or confirmed whether they want to include sector & recipient country/region at the activity or transaction level going forward).

I will leave this issue open for the time being and update when they've got back to me, and when I've worked with them to delete and re-add the problematic data.

**Comment by sarinasindurakar** [comment]
Hi @emmajclegg ,
The Initial issue while importing csv file listed in (https://github.com/younginnovations/iatipublisher/issues/1462) has been resolved and deployed to staging .

We have tested the CSV file and found out that it contains invalid data. The  activity elements : participating organization type, CRS channel, organization role, recipient country, activity date, and status all appear to have incorrect data.
![Image](https://github.com/younginnovations/iatipublisher/assets/65848732/39ef37dc-dc0d-45c0-8ece-f35a79f82cbb)

**Comment by PG-Momik** [comment]
@emmajclegg Closing this issue. The changes required for this issue were worked on #1462 . Issue #1462 has been deployed to production. Please let us know if any issues persist. 

Thank you.
