### ISSUE TITLE
While importing activity via XML, user should not be able to import activity if sector, RR, RC are filled in both activity level and transaction level. Fix the bug while importing that language is selected for empty narrative. Fix the bug that is preventing to show the error msg in frozen fields

### ISSUE THREAD

**Issue by PG-Momik** [younginnovations/iatipublisher#1462]
# Bugs:
- [x] Sector frozen in both activity and transaction level.
- [x] Language selected even tho there is no narrative
- [x] RR and RC allows for empty space as value.
- [x] Validation message not recognizable as the text color is frozen.

**Comment by sarinasindurakar** [comment]
@PG-Momik 

- [ ] 1. The error message is not displayed at the transaction level when the user adds the recipient region, country, and sector at both the transaction and activity levels.

- [ ] 2.When the user adds spaces in the recipient region, country, and sector at both the activity and transaction levels, an error message is shown. The spaces should be treated as empty values, and the user should be able to import the CSV and XLS files.

**Comment by sarinasindurakar** [comment]
@emmajclegg  This has been deployed in staging .
