### ISSUE TITLE
Make it clearer that new users of existing IATI Publisher organisations cannot register via "Join Now"

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1464]
A few users have been confused by the "Join Now" page, thinking they can use it to add themselves to an existing organisation's account in IATI Publisher. Instead, only an existing admin user from the organisation (or a member of IATI Support) can do this.

Can we take the opportunity to update the page text as follows, to make the options clearer:

1) "My organisation is new to IATI"
2) "Use this option if your organisation has already registered on the [IATI Registry](https://www.iatiregistry.org/), but is new to using IATI Publisher"
3) "If you are a new user of an organisation already using IATI Publisher, an admin user from your organisation can create an account for you. If you need help, or are not sure which option to select, please [Contact Support](mailto:support@iatistandard.org)."
4) "IATI Publisher"
5) "Welcome to IATI Publisher. This lets you publish IATI data on your organisation's development and humanitarian activities. Use this page to create a new account for your organisation."

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/6abf17ca-4f34-44f0-888e-33a7518b9127)

**Comment by PG-Momik** [comment]
@emmajclegg This has been deployed to staging.

**Comment by emmajclegg** [comment]
Thanks @PG-Momik.

A few minor points - in the text highlighted red below, can "organisation" be spelt consistently, and "IATI Registry" hyperlinked the same way as it is in the text box underneath? :

![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/05eb907e-614a-414b-a0b9-8aafc68b39c1)

Also, I see that the left-hand text applies to the Sign In page too now. The sentence highlighted green below is not relevant on this page - can this be removed please? If awkward, I think it's fine to remove that sentence from both pages (Sign In & Join Now)

![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/ed820f52-675e-4892-8ccf-45942679a25a)

Lastly "Join Now" and "Sign In" are titles so, for tidiness, we don't need the full stop ( . ) after them.

**Comment by PG-Momik** [comment]
Thank @emmajclegg . I've made the changes for the feedback above and deployed them.
