### ISSUE TITLE
Check user password minimum length and correct text

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1467]
In Step 4 of the "My organisation is new to IATI" registration route, a password of minimum length 6 characters is asked for: 

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/7be65515-94eb-44ff-b802-3a2a17b8e3af)

A user has noticed (and we have replicated on the IATI Publisher staging site) that a 6 character password is not accepted by the site. The same step in the "My organisation has already registered with IATI" registration route asks for an 8 character password:

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/a6b06c63-6e6e-4bc5-b209-b7489a308a2f)

1) Can the sub-text underneath both pages' **_Password_** boxes be updated with the right minimum character length.
2) Can the sub-text underneath the **_Confirm Password_** box in the first screenshot above be corrected to: "This should match the password on the left"

**Comment by PG-Momik** [comment]
@emmajclegg  This has been deployed to staging. Let me know if there any issue.
