### ISSUE TITLE
#148 Bug: Login>>User '=-98654321' is unable to sign in even if it has been successfully registered

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#147]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
- User is being registered as =-98654321

### Steps ###
- Enter Username as "=-98654321"
- Enter password as "test1234" >> User sees frontend validation stating "These credentials do not match our records."
- Click on reset and send mail to "yiplqa1+pub1@gmail.com"
- Fill required field and RESET PASSWORD

### Actual result ###
- User could  be logged in through it but not with login page

### Expected result ###
- While registering the user, in the username field, the character limitation along with special character limitation for the field should be applied

https://user-images.githubusercontent.com/25945530/170636475-c5ede798-ecde-404b-9e91-ef85b7898a6c.mp4

**Comment by sriza** [comment]
@AbhishekSka 
The validation rules for the username have been updated. Please check and let me know if further changes are required.

cc @man-git007  @praweshsth

**Comment by SauravSilwal10** [comment]
@sriza 
This fix still has bugs. Please go through it again.



https://user-images.githubusercontent.com/78422663/172329672-fd21dd4b-d120-4f92-9895-056d80104743.mp4

cc @man-git007  @praweshsth

**Comment by man-git007** [comment]
@sriza Have we fixed this issue?

cc @SauravSilwal10

**Comment by SauravSilwal10** [comment]
Issue Fixed 
cc @man-git007 @sriza
