### ISSUE TITLE
Add activity totals to Activity Data screen

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1475]
Can activities on the Activity Data screen be numbered, and a total of how many are published vs. draft added? 

(similar to AidStream):

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/78cd733a-fab4-4162-9197-f2250e2d6045)

This will:
- allow end users to see at a glance how many activities they have in draft vs. published state
- ~make it easier to refer to activities on the Activity Data screen without having to always use their title~
- allow IATI Support to spot discrepancies between the number of published activities in IATI Publisher and on the IATI Registry

Related support ticket: https://iati.zendesk.com/agent/tickets/44548

**Comment by PG-Momik** [comment]
@emmajclegg I dont quite understand what this means

> make it easier to refer to activities on the Activity Data screen without having to always use their title

Do you mean that it'll be easy for users to report/contact support by referring to an activity by the SN number rather than the title?

**Comment by emmajclegg** [comment]
@PG-Momik - I think you can disregard that use case on reflection.

The important thing here is that users should be able to see how many activities they have in total on the Activity Data screen. I don't believe they can currently and this makes it hard for them to keep track when they have 10+ activities.

Numbering the activities in the interface then seems intuitive from a visual perspective, but is not essential on reflection (I realise the activity order can change when filters are applied)

**Comment by sarinasindurakar** [comment]
- [ ]  If no activities are available then filters are distorted.


![Image](https://github.com/user-attachments/assets/969e3cb5-bb9b-4c0b-ac33-f3e95a62fb90)
