### ISSUE TITLE
Review default value for humanitarian flag

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1476]
The IATI activity `humanitarian` flag is an optional element according to the [IATI schema](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/), whereas IATI Publisher looks to populate it automatically as "Yes" (TRUE) unless the user overrides this:

![image](https://github.com/user-attachments/assets/f77dc474-986d-4803-8ef7-5dfc641a6e2c)

To check, is there a reason why this logic was agreed for IATI Publisher? 

We are worried that this is labelling activities unnecessarily as humanitarian in cases where users just haven't populated their default values.

**Comment by praweshsth** [comment]
@emmajclegg 

We referred to the planning documents and previous emails regarding it and couldn't find the reason for it. Is this causing any issue to the users currently? If it is, what issue they are facing?

**Comment by emmajclegg** [comment]
@praweshsth - this is less about user experience and more about the accuracy of the data that IATI Publisher produces.

If the humanitarian flag is populated, the user should have made an intentional choice whether it is "Yes" or "No" (there is no reason why "Yes" should be assumed as default). The flag is optional so it is fine for it to be unpopulated in the activity XML file.

Also - at the moment, it looks like there is no way to override the default humanitarian flag for individual activities? (This element does not appear in the Activity Data page IATI field list. [humanitarian-scope](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/humanitarian-scope/) is a different element) :



![Image](https://github.com/user-attachments/assets/4d791efa-f107-471a-865c-58742d825fc7)

**Comment by praweshsth** [comment]
@emmajclegg 

There is a way to override it for each activity. 

<img width="435" alt="Screenshot 2024-07-18 at 09 51 19" src="https://github.com/user-attachments/assets/42badbb6-73b5-49da-8e6c-dcb671c40ba2">

Each activity has the link to edit the default values for it. 

If it is not that important then we can remove the 'Yes is selected if empty'

**Comment by emmajclegg** [comment]
Ok @praweshsth - yes, can we please remove the "If not selected, it will be set to 'Yes' in all the activities" message (and behaviour) for the Humanitarian field in Default Settings.

If the user does not populate it, the field should remain blank.

**Comment by sarinasindurakar** [comment]
@PG-Momik 
 

- [ ] 1. In the downloaded XML file, the humanitarian field is shown as '1' even though the data is not populated.



![Image](https://github.com/user-attachments/assets/2ce1fc2e-89f0-4097-9bc0-2b4ade475ea3)

**Comment by emmajclegg** [comment]
> Should we also remove the auto-population of "yes" for "humanitarian" in the "Override this activity's default values" section?

Hi @sarinasindurakar - yes, the humanitarian field shouldn't be auto-populated anywhere.

If the user has populated it in Default Values under Settings, I would expect the "Override this activity's default values" section to reflect whatever value they have entered. Otherwise I would expect the field to be blank in this section.

**Comment by emmajclegg** [comment]
Thanks for the work on this. Everything looks as expected in the IATI Publisher interface, though I have a question on the activity file XML code:

When the user selects humanitarian = "No" for an activity, then `humanitarian = "0"` should appear in the XML file. I don't think IATI Publisher is including this at the moment?

This is a screenshot of the activity file from my test organisation "My org's name" in IATI Publisher. The first activity has humanitarian set to "No" and the second has it set to "Yes", but only the second activity contains the attribute:



![Image](https://github.com/user-attachments/assets/2544d822-e612-4a8b-bcc1-8f584da77ba5)

(To note - if the user doesn't populate "humanitarian" at all, then it is correct for the attribute to not appear in the activity XML)

**Comment by PG-Momik** [comment]
@emmajclegg The mechanism to remove humanitarian when 0 was implemented long before. We assumed it was intended behaviour. I've made necessary changes to persist humanitarian even when 0. 

This has been deployed to staging .

**Comment by emmajclegg** [comment]
Brilliant - thanks @PG-Momik. That's working as I would expect now
