### ISSUE TITLE
Assess AidStream publisher base to inform migration plan

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1479]
Work to plan migration of users and publishers from AidStream to IATI Publisher.

**Scope**: AidStream organisation accounts that have been successfully linked to an IATI Registry publisher account. 
(this should eliminate test accounts, inactive accounts and duplicates for the same organisation)

**Considerations**: 
- Pro AidStream publishers cannot be migrated until the premium features they use have been built into IATI Publisher. 
- We want to prioritise migration of publishers that fit IATI Publisher's target audience (< 100 activities or equivalent)
- We want to be aware of any organisations with activity data files that are too large to migrate successfully

### Questions to help assess the publisher base:
1) How many AidStream publishers are there? (broken down by free vs. pro account) 
2) How many AidStream publishers have more than 100 activities? (i.e. may not suitable to migrate to IATI Publisher as stands due to volume of data)
3) How many "inactive" AidStream publishers are there? (e.g. no one from that organisation has logged in in the last 2 years)
4) What order should organisations be migrated in?

**Comment by BibhaT** [comment]
This is what I have come up with, do let me know if anything else can be included
https://docs.google.com/document/d/1AjpdmEyhNgYzxLe4zPa9UNFvbG3Y809-eoHr-sxvjXM/edit

**Comment by emmajclegg** [comment]
Thanks @BibhaT - that's useful to feed into planning. I've added a few comments to the doc with clarifying questions. 

Using this, I've started an initial plan here on the steps and communications surrounding migrating accounts from AidStream: [Account migration plan: AidStream to IATI Publisher](https://docs.google.com/spreadsheets/d/17GsCBOXDgmYS56QGFAqAn7gbXjkXUEHFwuuIxW0yPnM/edit?gid=442310768#gid=442310768)

I'm sharing now as I want to give your team sight of my thinking so far, and it would be useful to get any early feedback. We can talk more about it on our Tuesday call perhaps. 

This plan fits into wider AidStream migration tasks on the project backlog, so something I fully expect to be working on beyond August. Us in ODS will lead on communications, and the migration steps themselves will be a joint YI-ODS effort!

The takeaways are:
- I'm suggesting notifying the IATI community soon (by early September) on our plan to integrate the tools, which should be followed by direct messaging to AidStream users.
- I've provisionally put November as the time to start account migrations, with various comms and preparation in the run up to that.
- we haven't committed to migrating all AidStream accounts by the end of 2024, only stopping new sign ups to AidStream, so there is some flexibility into next year if we need to continue migrating organisations.
- I've grouped organisations into batches on the "Account migration sheet" and suggested an initial order, but this is very open to change based on what you think is best. The PRO AidStream users are the ones where I am least sure of specific dependencies on paid features.

Comments directly on the doc or here are welcome, and happy to discuss more next week. 
cc' @praweshsth

**Comment by emmajclegg** [comment]
Hi @BibhaT - following our discussion earlier today, I have created a new issue about exporting a list of AidStream accounts with information that will help split them into groups for migration: #1533 

If there's spare capacity to work on this in August, by all means make a start (without going over the max number of days for the month @praweshsth). Otherwise, this can become part of September work.

Either way, check that the task description makes sense and if there's any information you think helpful to add to the export.

**Comment by BibhaT** [comment]
Further communication will be carried out in issue #1533 and on the [Comms plan](https://docs.google.com/spreadsheets/d/17GsCBOXDgmYS56QGFAqAn7gbXjkXUEHFwuuIxW0yPnM/edit?gid=442310768#gid=442310768) created by Emma.
