### ISSUE TITLE
#148 Bug: After successful login user is get back to login page by clicking Back button from browser

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#149]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://stage.iatipublisher.yipl.com.np/
- Username: User_A
- Password: test1234

### Steps ###
- Login with above mentioned User name and password
- When in Activities Page>> Hit back from browser or https://stage.iatipublisher.yipl.com.np/login

### Actual result ###
- User is being redirected to the Login page once again  

### Expected result ###
- User should remain over the activities page once being logged into the system
- Route handling for different pages to be made

https://user-images.githubusercontent.com/78422663/172559409-40bd7cfc-233a-40f2-a9d1-4fd4027c5616.mp4

**Comment by SauravSilwal10** [comment]
@sriza 
This issue has not been fixed. Please review again.


cc @man-git007  @praweshsth

**Comment by man-git007** [comment]
@sriza Has this issue been solved? If yes @SauravSilwal10 Please close this issue

cc @AbhishekSka

**Comment by SauravSilwal10** [comment]
@sriza This issue has not been fixed . Please have a look.

cc @man-git007  @AbhishekSka

**Comment by man-git007** [comment]
@SauravSilwal10 lets put this issue in a backlog

**Comment by SauravSilwal10** [comment]
@man-git007  okay
