### ISSUE TITLE
Email addresses for sign in are case sensitive

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1491]
If a user capitalises their email address different to the way they wrote it when registering, they are unable to sign in and see the error message below:

![image](https://github.com/user-attachments/assets/c3c472ca-019a-403e-82fa-917d74c1cee2)

This makes us think that email addresses are case sensitive in IATI Publisher, which is causing log in issues.

Can this case sensitivity be removed unless there is a reason for it?

**Comment by PG-Momik** [comment]
Hi @emmajclegg,

We can proceed with removing case sensitivity for login. However, please note that some accounts in production have multiple entries with the same email address but different cases. All the affected users are users that have been migrated from Aidstream. I've emailed you a list of these users. Let us know how you'd like to handle this situation.

**Comment by emmajclegg** [comment]
@PG-Momik - thanks for emailing the list of affected users. I've deleted the duplicate entries (prioritising keeping a validated email over a non-validated one), and we'll support these users to log in in future if they have any problems.

Go ahead with removing the email case sensitivity.

**Comment by sarinasindurakar** [comment]
@PG-Momik 

- [ ] 1. The verification email is not being sent in creation of new user .

- [ ] 2.  The search functionality is not working in user listing page

**Comment by PG-Momik** [comment]
@emmajclegg This has been deployed to staging. Do let me know if any issues arise.

**Comment by emmajclegg** [comment]
Great - this looks to be working as expected on staging
