### ISSUE TITLE
Remove requirement for "actual" and "target" value against a result period

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1492]
According to the IATI Standard, a result's [period](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/period/) must have either an "[actual](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/period/actual/)" or "[target](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/period/target/)" value. It may have both but this is not essential.

We believe IATI Publisher (via [this GitHub script](https://github.com/younginnovations/iatipublisher/blob/main/app/Http/Requests/Activity/Period/PeriodRequest.php)) expects both "actual" and "target" values to be populated for quantitative indicators. Can this logic be changed to require only one?

---
This will help in cases such as:
- If the `period-end` date is in the future, an "actual" value won't typically be available
- If the period is used as a baseline (i.e. the first period for the result), a "target" value won't typically be available

At the moment, the rule is over-restrictive for users entering data.

**Comment by emmajclegg** [comment]
If this is a small job (e.g. an hour), feel free to move straight to "to do" without formal estimation.

**Comment by PG-Momik** [comment]
@emmajclegg This has been deployed to staging.

**Comment by emmajclegg** [comment]
Thanks @PG-Momik .

To make the link between the two fields a bit clearer to users, can we use this wording for the error messages?

"_Target value is required if actual value is not provided_", or "_Actual value is required if target value is not provided_"

![Image](https://github.com/user-attachments/assets/f8075986-c27c-4b8e-af13-459538d754ab)

![Image](https://github.com/user-attachments/assets/110a613c-372a-4c27-bfec-418d1ef07f9e)

**Comment by PG-Momik** [comment]
@emmajclegg  The changes have been deployed to staging.
