### ISSUE TITLE
Remove requirement for a "revised" activity budget to have an equivalent "original" budget

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1493]
It is not strictly necessary for an activity [`budget`](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/budget/) with `@type` "revised" to have an equivalent budget of type "original" entered for the same period, according to the IATI Standard.

It looks like IATI Publisher expects both budget types in this [BudgetRequest script](https://github.com/younginnovations/iatipublisher/blob/main/app/Http/Requests/Activity/Budget/BudgetRequest.php) (see line _"Budget with type revised must have period start and end same to that of one of the budgets having same type original for budgets elements at position"_)

Can this requirement be removed so that users are not being given an error message unnecessarily?

**Comment by emmajclegg** [comment]
If this is a small job (e.g. an hour), feel free to move straight to "to do" without formal estimation.

**Comment by PG-Momik** [comment]
@emmajclegg  This has been deployed to staging.

**Comment by emmajclegg** [comment]
Great - thanks @PG-Momik. This looks to be working as expected.
