### ISSUE TITLE
Unable to register new organisation on IATI Publisher staging site

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1499]
I am currently unable to register a new organisation on the IATI Publisher staging site. (We have no evidence that this is affecting the live site)

Going to "Join Now" on the homepage, then following the "My organisation is new to IATI" route, I have tried to enter details on a new organisation (see example video attached).

Each time, on trying to save Step 1, I see the error message below:

![image](https://github.com/user-attachments/assets/54a3733a-2ba1-40f8-a370-3c247a512e9d)

Another user of the staging site has reported having the same problem. This is the first time I'm seeing this error message on this screen. 

https://github.com/user-attachments/assets/7213cdcd-2bba-4ff4-b717-df89d69d3445

**Comment by PG-Momik** [comment]
@emmajclegg  this has been fixed and deployed to staging.

**Comment by emmajclegg** [comment]
Thank you!
