### ISSUE TITLE
#148 Bug: Multiple clicks over the Login to be disabled

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#150]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://stage.iatipublisher.yipl.com.np/
- Username: User_A
- Password: test1234

### Steps ###
- Login with above mentioned User name and password
- Multiple click on Login button

### Actual result ###
- User with get 419 session expired status code eventually 

### Expected result ###
- Click disable for the login button once user click for the Login button is to be implemented
- Request with similar payload is to be prohibited

https://user-images.githubusercontent.com/25945530/170646855-36714d98-e289-4a87-88fa-5e8e1b046d8a.mp4

**Comment by sriza** [comment]
@AbhishekSka 
This issue has been fixed with the placement of loader and is now deployed to the staging site. Please have a look.

cc @man-git007 @praweshsth

**Comment by AbhishekSka** [comment]
@sriza This issue seems to have been recurred. Can you please take a look at it?

cc @man-git007 @praweshsth

**Comment by man-git007** [comment]
@sriza Has this issue been solved? if not @jenishshrestha  Can you look into this? @SauravSilwal10 If fixed lets close this issue

cc @AbhishekSka

**Comment by titungdup** [comment]
@man-git007 Issue resolved.
