### ISSUE TITLE
Review mandatory field display in interface for document-link

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1501]
We often get support queries from users about data validation errors related to documents, usually because they are confused which elements are mandatory to enter in the IATI Publisher interface.

Can we ensure mandatory fields are clear on data entry pages? (I've focused this issue on documents, but this will likely have applications elsewhere in IATI Publisher)

**IATI Standard _document-link_ rules**
[`document-link`](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/document-link/) is an optional IATI data element found in various places across the IATI Standard.

If a document-link is added,
- the attributes @/url and @/format are mandatory to populate.
- the following sub-elements are mandatory: [title](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/document-link/title/), [category](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/document-link/category/)
- the following sub-elements are optional: [description](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/document-link/description/), [language](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/document-link/language/), [document-date](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/document-link/document-date/)

Users find the data entry screens in IATI Publisher confusing, as the mandatory red asterisk labels are at attribute (rather than sub-element) level and it is not clear what needs completing - e.g. "description" in the screenshot below for a [result](https://iatipublisher-staging.yipl.com.np/activity/1127/result/349/edit) is optional but looks mandatory:

![image](https://github.com/user-attachments/assets/f6526b63-7acd-4ae4-a91e-c8cf89af474f)

Conversely, some sub-elements don't look mandatory when they are - e.g. "category" in the screenshot below for a [period](https://iatipublisher-staging.yipl.com.np/indicator/768/period/2350/edit).

![image](https://github.com/user-attachments/assets/a5eed2a1-0a4a-457f-bf65-344700e58c1f)
 
Is there a way to make these screens clearer to users - e.g. by moving the mandatory sub-elements to the top of the page, or collapsing (hiding) optional ones ?

**Comment by PG-Momik** [comment]
@emmajclegg

The changes have been deployed to staging. Here's what has been updated:

1. The Category field has been moved up.
2. Description, Language, and Document Date fields are now collapsible.

These updates apply to the document-link at the activity, result, indicator, and period levels.

Additionally, I've made the necessary adjustments in the form builder module, which is responsible for creating all the forms. This will allow for **most** of the other sub-elements to be made collapsible if needed in the future.

Have a look at it and let us know if any changes need to be made.

**Comment by emmajclegg** [comment]
Thanks @PG-Momik - this looks a lot clearer for filling in the fields. 

Two minor comments, but otherwise happy with the interface:

- I've noticed the placeholder "Help" text underneath the boxes, which doesn't look like it should be there.

I think it's worth replacing the first one with some instruction to the user that they're either entering a url or uploading a document - e.g. "Enter a public link to your document or upload it below."

![image](https://github.com/user-attachments/assets/071745b7-7a42-4e0c-bbbc-4b2a9ac50792)

- The "code" attribute of the document-link element against a results period ([example](https://iatipublisher-staging.yipl.com.np/indicator/771/period/2353/edit)) seems to be missing the mandatory red asterisk that is present elsewhere for this element:
![image](https://github.com/user-attachments/assets/ea0a39c1-ee57-40fd-94c4-8527f837392c)


Also - is there a reason why users don't have the option to upload a document in this case?

**Comment by PG-Momik** [comment]
> Also - is there a reason why users don't have the option to upload a document in this case?

In the earlier phase of development, document upload didn't exist and was only added because of [this issue which doesn't specify other levels](https://github.com/younginnovations/iatipublisher/issues/13). This might be why document upload is not present in other levels.

> The "code" attribute of the document-link element against a results period ([example](https://iatipublisher-staging.yipl.com.np/indicator/771/period/2353/edit)) seems to be missing the mandatory red asterisk that is present elsewhere for this element:

I've added the red asterisk to category code in all level. I've also removed the 'Help' text with the actual help text only for url field in activity level. 
The changes have been deployed to staging.

**Comment by PG-Momik** [comment]
> Sorry, I originally missed that clicking on the...

No problem

**Comment by emmajclegg** [comment]
@PG-Momik - for info, this fix hasn't appeared in IATI Publisher production yet (not sure if that's intentional)

**Comment by emmajclegg** [comment]
@praweshsth @PG-Momik  - I'm reopening this issue to check as it doesn't look right in IATI Publisher production at the moment.

Data fields that were hidden on the staging site for document-link appear on production, and clicking "Hide" in the screenshot below generates duplicate "You can expand..." text:
![image](https://github.com/user-attachments/assets/5df7cff3-2c46-42b3-b40f-f778dab44248)

(I've checked this for a few different organisations on the live site and it looked like this for all of them)

**Comment by emmajclegg** [comment]
To be fixed as soon as possible as this is generating a lot of user support queries now.

**Comment by PG-Momik** [comment]
@emmajclegg Sorry about the delayed response. I was on leave. I've deployed the fix to production. It seems a small change did not make it through when merging the initial changes to main, which caused this bug to appear.

**Comment by emmajclegg** [comment]
Thank you @PG-Momik. Hope you enjoyed your leave
