### ISSUE TITLE
When user tried to create an account, the user is blocked saying 'user already exist'

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1507]
The user email couldn't be found in the system. 

Need to find why this issue has occurred.

Zendesk ticket: https://iati.zendesk.com/agent/tickets/44705

**Comment by PG-Momik** [comment]
@emmajclegg I've looked into this. 

(Error message)
![image](https://github.com/user-attachments/assets/76d8d135-9a0a-46f6-b24b-3cbb060631ba)

(No email in the system)
![image](https://github.com/user-attachments/assets/d2c5f1a6-19bf-4f8d-8bd3-7b062561bbba)

The "**Email already exists**" error message mentioned in the ticket is not generated by the Publisher's system. The validation message is being generated from the registry system. When creating a new admin user in Publisher via **My Organisation is new to IATI**, the system attempts to create a user in the registry as well.

> ... accounts associated with it have been deleted from the IATI Registry.
> zendesk ticket

Could it be that the registry implements a soft delete mechanism. This would explain why the validation message is generated even though user is deleted from registry.

---

cc: @praweshsth

**Comment by emmajclegg** [comment]
Thanks for looking into this @PG-Momik , @praweshsth - yes, we suspect the IATI Registry soft deletes user accounts which is causing this. I've requested a hard delete for the affected accounts from our Registry supplier.

One question for YI - when are user accounts in IATI Publisher checked against the IATI Registry before creation? Is my understanding below correct? :

User checked against IATI Registry and blocked if account already exists:
-  administrator sign up in "My organisation is new to IATI" registration route 

User not checked against IATI Registry:
- administrator sign up in "My organisation has already registered with IATI" registration route
- any user added post-registration via the "Users" page in IATI Publisher

**Comment by PG-Momik** [comment]
@emmajclegg Yes, your understanding of the email checks against IATI Registry for user creation is correct.

For now, we've decided to update the error messages to specify if the email already exists is in Publisher or IATI Registry




![Image](https://github.com/user-attachments/assets/034fbc15-fb6e-4851-b0b4-7d79c3ad2ba7)




![Image](https://github.com/user-attachments/assets/6c7a69f0-2017-4865-a924-c539c6142ff6)

This has been deployed to staging. Let us know if any changes need to be made.

---

cc: @praweshsth

**Comment by emmajclegg** [comment]
Thanks @PG-Momik - that looks useful for future. Happy for it to be deployed
