### ISSUE TITLE
Unable to update publisher ID

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1509]
Affects one organisation - details here: https://iati.zendesk.com/agent/tickets/44782

**Comment by PG-Momik** [comment]
@emmajclegg I've fixed this and deployed it to staging. It seems the system was throwing a error when trying to save the change made to publisher-id for an unpublished/new organisation.

Do let me know if the issue persists.

**Comment by emmajclegg** [comment]
Ok thanks @PG-Momik - happy for this to be deployed to live.
