### ISSUE TITLE
#148 Bug: User's login password could be viewed through xhr request

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#151]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://stage.iatipublisher.yipl.com.np/
- Username: User_A
- Password: test1234

### Steps ###
- Login with above mentioned User name and password
- click on Login button
- Open dev tools and check for the request

### Actual result ###
- The entered password is visible of xhr request

### Expected result ###
- Password encryption over the payload is to be made

![image](https://user-images.githubusercontent.com/25945530/170648165-9c6c221b-1e07-46b6-8606-dfb19248fb93.png)

**Comment by man-git007** [comment]
@sriza Does the issue still persist? If yes please fix this today.

cc @Sanilblank @SauravSilwal10 @AbhishekSka

**Comment by SauravSilwal10** [comment]
Issue Fixed 
 cc @man-git007 @sriza @AbhishekSka
