### ISSUE TITLE
Sign up fixes

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#152]
- [x] #156
- [x] #158
- [x] #159
- [x] #160
- [x] #163
- [x] #164
- [x] #165
- [x] #168
- [ ]  #177

**Comment by man-git007** [comment]
@AbhishekSka @SauravSilwal10 Can we close this issue?

**Comment by SauravSilwal10** [comment]
#177 is remaining which comes under a backlog issue.

cc @man-git007 @AbhishekSka
