### ISSUE TITLE
#148 Bug: The username and password input fields should have a character limitation.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#153]
Context

- Desktop
- Chrome 100.0.4896.127

Precondition
- https://stage.iatipublisher.yipl.com.np/login

Steps
- Enter a Username: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt.
- Enter a Password: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt.
- Click the Sign in Button

Actual result
-  These credentials do not match our records.

Expected result
- The username must not be greater than 255 characters.
- The password must not be greater than 255 characters.

https://user-images.githubusercontent.com/78422663/170670724-38059ddd-7c7c-4fb7-b5bd-fe8fb90ab2be.mp4

**Comment by man-git007** [comment]
@sriza @Sanilblank Can you both look into this?

cc @SauravSilwal10 @AbhishekSka
