### ISSUE TITLE
#148 Bug :Time counter isn't operating correctly.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#154]
### Context

- Desktop
- Chrome 100.0.4896.127

### Precondition

- https://stage.iatipublisher.yipl.com.np/login

### Step

- Enter a Username: Test1
- Enter a Password: Testing123
- Click the Sign in Button

### Actual result

- The timer stops working.

### Expected result
- The timer should accurately indicate the remaining time.

https://user-images.githubusercontent.com/78422663/170673014-9631947e-bdd6-4045-8a19-516cc0166eff.mp4

**Comment by man-git007** [comment]
@AbhishekSka @SauravSilwal10 Can we close this issue?

**Comment by SauravSilwal10** [comment]
@man-git007 This issue hasn't been fixed.

cc @sriza

**Comment by man-git007** [comment]
@SauravSilwal10 Lets halt this issue for now and maintain it as a backlog tasks

cc @AbhishekSka

**Comment by SauravSilwal10** [comment]
Please refer to the Issue #489 

cc @titungdup @sriza
