### ISSUE TITLE
Simplify data overview screens and remove references to "missing" unpopulated fields

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1550]
_User story: As someone entering data in IATI Publisher, I want data overview screens to show me clearly a) what information I have entered, and b) if there are any mandatory fields missing_

**User issues:**

- From support queries, we know that displaying the word "missing" on the overview screens makes some users think that they **have** to go back and populate these fields, which is not true if they are optional
- The extra text clutters the interface - a blank space would equally communicate that the field is unpopulated and make it clearer for users to see the information that they have populated so far.

![Image](https://github.com/user-attachments/assets/ab87937c-f5e1-4c66-80ac-c802ad92b5cb)

**Suggested action:**
Can we review the overview screens for [transaction](https://iatipublisher-staging.yipl.com.np/activity/1240/transaction/16619), [result](https://iatipublisher-staging.yipl.com.np/activity/1240/result/479) and [indicator](https://iatipublisher-staging.yipl.com.np/result/479/indicator/896) initially.

1.  to focus on information that the user has populated, rather than showing them all possible data fields (most of which will be unpopulated). At minimum, they shouldn't see all the unpopulated fields for document-link in the screenshot above, when this is a nested element that hasn't been used
2. to remove the word "missing" when a data field is unpopulated, unless this can be applied only to mandatory fields

This is related to, and should complement, the review of data entry forms [#1553](https://github.com/younginnovations/iatipublisher/issues/1553)

**Comment by asminashrestha** [comment]
[Sub-elements missing case](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=8596%3A139561&node-id=16272-23728&node-type=frame&viewport=-5343%2C-1251%2C0.3&t=wfeEOeLHHRpYlfrZ-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=8643%3A140060&show-proto-sidebar=1)
[Baseline missing case](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=8596%3A139561&node-id=16272-24250&node-type=frame&viewport=-5343%2C-1251%2C0.3&t=wfeEOeLHHRpYlfrZ-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=8643%3A140060&show-proto-sidebar=1)
[Document Link missing case](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=8596%3A139561&node-id=8643-140438&node-type=frame&viewport=-5343%2C-1251%2C0.3&t=wfeEOeLHHRpYlfrZ-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=8643%3A140060&show-proto-sidebar=1)

**Comment by emmajclegg** [comment]
@asminashrestha - to update on the user accessibility point:

For context, ODS will likely do full accessibility reviews of all IATI tools (including IATI Publisher) at some point, though probably not this year. Among other things, this will be to make sure the tools are accessible for people with visual impairments who use a screen reader. The translated French/Spanish interface work is another example.

In this case of data overview screens, the use of light grey text is not judged accessible from a visual readability point of view. The alternatives that have been suggested to me to separate out populated from unpopulated fields are:
a) Replace the light grey "N/A" with empty space (i.e. no text), or
b) List unpopulated fields, rather than trying to display a value for them - i.e something along the lines of the section highlighted green below:

![Image](https://github.com/user-attachments/assets/50d36fec-cd4e-42c1-95e7-3e3814600c76)

I'll take your steer on which of these approaches is easier to implement, but it's worth making the changes now rather than having to redo work in future. 

Any questions, let me know (tomorrow - Friday - is my last day before a week's leave)

**Comment by BibhaT** [comment]
> Similar to how data entry form changes will need to be applied across IATI Publisher in one go, will the changes in this issue affect all overview screens (e.g. ones on the Activity Data page shown below)?

This is all FrontEnd work and the structure is different from that on the BackEnd. These changes will have to be done one element at a time and won't affect another element's/activity detail view.

**Comment by asminashrestha** [comment]
Hi @emmajclegg We reviewed the options you suggested and reconsidered the color for the "N/A" label. We feel that the best option is to use a darker color for "N/A" to ensure there are no accessibility issues. Please take a look and let us know your thoughts. [View Link](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=8596%3A139561&node-id=16272-23728&node-type=frame&viewport=-12002%2C-3161%2C0.67&t=QCVKW21LFbcNcpds-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=8643%3A140060)
Also, regarding the "Language: English" label, we had a short discussion over it,  We feel that further detailed discussion is needed before making a decision. We suggest that we treat this as a separate issue for now. Is that okay?

**Comment by Sanam-07** [comment]
Issue 1 : The transaction type is displayed as missing in the transaction section. Need to fix it @Yash-ftW .
![Image](https://github.com/user-attachments/assets/5dc7f38d-2348-4559-b711-6cf62313d75a)

**Comment by Yash-ftW** [comment]
@emmajclegg , This has been deployed to staging.

**Comment by emmajclegg** [comment]
Thanks @Yash-ftW - can I confirm how widely these changes have been applied? (i.e. which interface pages have changed)

I see changes on the [Indicator Detail](https://iatipublisher-staging.yipl.com.np/result/512/indicator/928) and [Period Detail](https://iatipublisher-staging.yipl.com.np/indicator/928/period/2528) pages for example, but mentioned that I'm no longer seeing changes to the location element in staging in this issue (#1559), so want to check

**Comment by Yash-ftW** [comment]
Hi @emmajclegg,  The changes are for Indicator, Period and Transaction element.

>but mentioned that I'm no longer seeing changes to the location element overview in this issue (https://github.com/younginnovations/iatipublisher/issues/1559)

The location changes are on other issue. Both changes have been deployed to staging now.

**Comment by emmajclegg** [comment]
Ok @Yash-ftW - for consistency, can the Period Detail screen be checked as there still seems to be full `document-link` information showing even if the user has not populated anything for this sub-element:

![image](https://github.com/user-attachments/assets/e13fd89f-2b74-421f-bdd4-d3f62742b645)

This nested element detail no longer appears on the Result and Indicator Detail screens (which is good, as it detracts from the more important information on these overview screens).

For remaining "missing" labels against unpopulated fields - let's wait and replace these (with "N/A" or otherwise) once the automated text extraction and reintegration process is in place (task #1477). This will be quicker than continuing to manually update text in different parts of the interface

**Comment by Yash-ftW** [comment]
Thankyou @emmajclegg, I've changed for the Period interface as well, and has been deployed to staging. Please review it and let me know if any changes are to be done.

**Comment by emmajclegg** [comment]
Ok thank you @Yash-ftW - i've had a look and are happy for the changes to be implemented

**Comment by Yash-ftW** [comment]
Hi @emmajclegg, The change has been made and deployed to staging. Please review it and let me know if any more changes are to be done.

**Comment by emmajclegg** [comment]
I've reviewed and happy for this to be implemented
