### ISSUE TITLE
Review design of data entry forms to make mandatory vs. optional fields clearer

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1553]
# Task
- [x] #1572
- [x] #1599 

# Context:
Follows discussion about the result element in #1542 

_**User story**: As a user, I want data entry forms to be simple and intuitive, with mandatory elements clearly marked, so that it is easy for me to input my data._

There are currently collapsed optional fields for the element `document-link`, although we don't think this format will work to copy across the rest of IATI Publisher.

**Key user issues:**
1) Mandatory asterisks are used at the level of data fields within sub-elements, with no mandatory vs. optional information for the sub-element itself:

![image](https://github.com/user-attachments/assets/fd2421e6-6b6d-43b5-bf97-d6ff314e8048)

2) There are an overwhelming number of data entry boxes in many forms (especially transaction, result, indicator and period)

**Can we improve the design of data entry forms further by:**
- removing unnecessary green lines and borders to reduce clutter in the interface (see example screenshot below)
- clearly label optional data elements as "optional", or collapse areas of the Standard that are very rarely used (ODS can advise what to do for each element, and the example below shows how "optional" can be added to text labels)
- in the case of nested elements (e.g. adding a `document-link` within `result`), the user shouldn't see all of the nested `document-link` data fields in the result data entry form, unless they have chosen to expand this element - e.g. with a "Add a document" option. This will vastly simplify the forms by reducing the number of data entry boxes the user is first presented with.

This is a (very rough) example of how much cleaner the form could look without unnecessary borders:

![image](https://github.com/user-attachments/assets/0d9b3984-78e4-460c-9f99-3ee8b7b54661)

If we use the `result` element as an example,
- `type`, `title` and `indicator` are mandatory
- `document-link` can be collapsed, with the user given the option to "add a document"
- `reference`, `description` and `aggregation-status` can be kept on screen and labelled as "optional"
- both `type` and `aggregation-status` could be better presented as multiple choice buttons (as in AidStream simplified UI)

It would help us to think beyond rigidly presenting the technical IATI Standard to people, and more about what users expect to see from a data entry form, in language that makes sense to them.

Once we agree on a design, we can create separate GitHub issues for implementing across data forms in IATI Publisher, in an order that makes sense.

**Comment by emmajclegg** [comment]
@praweshsth - if there's free capacity for front end design work this month, this issue has been separated out from #1542 and is high value to work on (we get a fair number of support queries related to problems interpreting the data entry forms)

Any questions, let me know - happy to discuss

**Comment by emmajclegg** [comment]
For info - I've added a second screenshot to the description above (under "key user issues") to emphasise the two levels of mandatory vs. optional fields that we're dealing with, and that are causing user confusion. Only one (the nested level) is currently clear in the data entry forms.

Any questions, please let me know.

**Comment by BibhaT** [comment]
@emmajclegg Asmina will share the design with you, Momik will come up with the time estimation on Monday. 

@PG-Momik @asminashrestha

**Comment by asminashrestha** [comment]
Hi @emmajclegg We have come up with the first draft for the form redesign. [View link](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=16112%3A37956&node-id=16112-37957&node-type=frame&viewport=801%2C707%2C0.2&t=XneCsJ6lWgqfCMUR-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=16112%3A37957&show-proto-sidebar=1) We’ve simplified the form by removing lines that previously cluttered the layout and minimizing the nesting of elements. To enhance the user experience, we’ve made the fields collapsible, ensuring the form looks clean and organized. This way, users can focus on entering only the necessary information, expanding fields only when needed. Also, we have added a sticky sidebar so that user can use it to open and move to the need fields as necessary.

**Comment by emmajclegg** [comment]
Thanks all.

@asminashrestha - the design's looking better. I'm not sure how the mandatory asterisks ( * ) are working in this design but making mandatory vs. optional fields intuitive is the main thing i'm trying to address (because users are publishing data with errors due to missing mandatory data at either element or sub-element level)

In this result example, @/type and the Title sub-element are the only things that are mandatory, so can we make sure this is clear - e.g. by adding an "optional" label on the collapsed fields highlighted:

![image](https://github.com/user-attachments/assets/628b7c77-89a2-49f4-bcd4-9bd2dadfb91a)

I'm not sure how much the sidebar will be needed for navigation given the new collapsed format - I'll ask my team for quick thoughts on Monday. Either way, the sidebar should probably use the plain English section headers to match (rather than the technical iati sub-element names)

**Comment by emmajclegg** [comment]
Hi @PG-Momik 

> All forms in IATI Publisher are rendered via the form builder, which uses a common mechanism across all forms. This means any design changes we implement for activity results (as shown in the example) will affect all other activity elements and sub-elements as well. 

This makes sense. The important thing will be to make sure that the form design we agree on works well for both simple IATI elements and the more complicated data entry forms like activity `transaction` and `result`

> With this in mind, my rough estimation is that implementing the changes will take approximately 50-60 hours, plus an additional 2-4 days for QA, depending on the scope of changes once the designs are finalized.

Can you provide more detail here on the steps required for implementation? This time estimate is higher than one of our developers would expect.

In particular - how has your core component library been set up to reuse common elements across data entry forms in IATI Publisher? A number of issues on the project board now involve reuse of IATI schema rules too - mainly, interpretation of what data is mandatory vs. optional. I would hope this schema logic is maintained in one place in IATI Publisher and reused, rather than being hard-coded in multiple places within data entry forms and processing?

If helpful, I can ask advice from one of the ODS developers on how we best implement changes.

----

@asminashrestha - if helpful for feedback, my team agree that the new form sidebar design might confuse more than help, and does not seem necessary for navigation in forms that will be shorter in length (due to the collapsed sub-elements):

![image](https://github.com/user-attachments/assets/15886502-883b-4052-889e-85954462b6b5)

If removing this sidebar completely, or keeping the sub-element menu that's currently in IATI Publisher (below), saves time on development work then please can we take that approach.

![image](https://github.com/user-attachments/assets/ffc73a5b-4b4a-426f-ada1-4f7b54b0e08a)

**Comment by PG-Momik** [comment]
@emmajclegg  I've created an issue for the tasks for this issue based on the design.  [Implement changes in formbuilder](https://github.com/younginnovations/iatipublisher/issues/1572). I've estimated a higher for this issue because of my previous experiences with form builder.  Form builder is the most complex module in IATI publisher. The initial team that worked with the form builder are no longer here.  The inner working of formbuilder is quite frankly "tribal knowledge". Overtime we've made small changes on form builder (freeze fields/elememts, collapseable), these small changes have always taken longer than what we'd expected. 

> In particular - how has your core component library been set up to reuse common elements across data entry forms in IATI Publisher

I dont completely understand what you mean by this. Basically forms can be broken down into:

1. How form is defined:

- We maintain json echemas that basically define what and how a form SHOULD look like (basically control how form is rendered). [elementJsonSchema.json](https://github.com/younginnovations/iatipublisher/blob/main/app/IATI/Data/elementJsonSchema.json)  contains the definition of all activity element form and children form, [organisationJsonSchema.json](https://github.com/younginnovations/iatipublisher/blob/main/app/IATI/Data/elementJsonSchema.json) for organization level form. 

2. How form is rendered: (Form builder) 

- Files inside [Builder](https://github.com/younginnovations/iatipublisher/tree/main/app/IATI/Elements/Builder) and [Form](https://github.com/younginnovations/iatipublisher/tree/main/app/IATI/Elements/Forms ) will basically render the forms based on the definitions in json schema. 
 
3. Form Validation:

- Forms are validated against interpretations of IATI standard on request level. i.e request file. Example if you fill Activity title with 2 narrative with same language, it will throw a validation error.  This logic is handled in [TitleRequest.php](https://github.com/younginnovations/iatipublisher/blob/main/app/Http/Requests/Activity/Title/TitleRequest.php)
 
4. Behind the scene logic (completeness, mandatory v optional):
- Calculations like core complete calculation, element completion status, deprecation code usage are usually done once the form is saved. The logic for this is handled by service files in  https://github.com/younginnovations/iatipublisher/tree/main/app/IATI/Services. 

- These service file either user json schema or have common functions within them to do necessary calculation. Example to calculate if activity sector is complete or not. [ElementCompleteService.php](https://github.com/younginnovations/iatipublisher/blob/main/app/IATI/Services/ElementCompleteService.php) reads the JSON file for rules needed to check what what attributes and subelements are mandatory. It then fetches activity sector data from database and checks if the elements and attributes (needed for completion, defined in JSON file) is complete or not. The logic to check if complete or not is found in service files and not in JSON files.

This is a very simple breakdown of how forms are rendered and handled.

cc: @Sanilblank

**Comment by emmajclegg** [comment]
Thanks @PG-Momik for the detail here and on the call earlier today. It's useful for us to have a basic understanding of how these functionalities work in IATI Publisher.

I had another look at the [form design you presented in Figma](https://www.figma.com/design/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?node-id=16112-37956&node-type=canvas&t=xCAfKtfqi3rQSJPP-0) (cc' @asminashrestha):

- One question - will the open vs. collapsed field approach (as shown in the Initial State view) also be applied to nested elements? For example, in the `result` form, if the user expands the optional "Document Link" sub-element, will they see "Title" and "Category" open in the interface, then "Description"/"Language"/"Document Date" as collapsed?

The above would be ideal to guide users to the mandatory sub-elements first. A clear "optional" label on the collapsed sub-elements will further make this foolproof to users if easy to add.

I've seen the implementation steps [here](https://github.com/younginnovations/iatipublisher/issues/1572) and have no further questions for now.

**Comment by asminashrestha** [comment]
@emmajclegg We won’t be applying the collapsible approach to nested elements. Hiding too much information within collapsible sections could indeed lead to confusion. You're right about distinguishing between mandatory and optional elements, but I believe the use of an asterisk (*) is sufficient to indicate required fields. Nesting optional elements could make the form more complex and add unnecessary confusion.

**Comment by BibhaT** [comment]
Hi @emmajclegg , depending on whether or not your concern has been addressed by the above comment, should we move ahead with the development?

**Comment by emmajclegg** [comment]
> We won’t be applying the collapsible approach to nested elements. Hiding too much information within collapsible sections could indeed lead to confusion. You're right about distinguishing between mandatory and optional elements, but we believe the use of an asterisk (*) is sufficient to indicate required fields. 

Having spoken to my support colleagues, we still don't think this is clear enough unfortunately. `document-link` is the nested element we've needed to support users with the most (in terms of making sure they fill in mandatory fields), so there is evidence behind asking for the following:

1) We would still like optional sub-elements, even within nested elements, to be collapsed when the user first views the element. 

Looking at the example of Category and Description from Document Link below, the mandatory asterisk next to Category is a good start, but it still looks like the Description `narrative` and `language` fields need completing when they don't:

![image](https://github.com/user-attachments/assets/033c06f8-7bcf-490b-8cd0-7fb6b3ffab7a)

2) We would like the word "optional" clearly marked on the sub-elements it applies to.

As soon as the user starts expanding optional elements, similar to above, we can see that it becomes less clear what is optional. A label like below would retain that clarity even with the form fully expanded: 

![image](https://github.com/user-attachments/assets/276f1675-0dd3-4728-9f71-5b2bdf73d9e5)

Any questions, let me know.

With these changes applied, I'm happy to move ahead with the development.

**Comment by emmajclegg** [comment]
For further user context @asminashrestha @BibhaT  - the critical errors in this publisher's data (https://validator.iatistandard.org/report/fowdk-activities) are representative of what us in support have to troubleshoot daily. 

It is far too common to see critical errors in `document-link` and `result`, as in this case, which is why this data entry form work is so important. We want to guide, rather than just show, users what is mandatory to improve the data currently being published.

**Comment by asminashrestha** [comment]
Hi @emmajclegg We've made the requested changes. Please take a look and let us know if you have any feedback. [Updated Form](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=16112%3A37956&node-id=16283-30740&node-type=frame&viewport=991%2C282%2C0.1&t=KNNPdXM3uGurJxET-1&scaling=min-zoom&content-scaling=fixed)

**Comment by BibhaT** [comment]
Thanks @emmajclegg we'll start the development from today.

**Comment by Sanam-07** [comment]
Issue 1 : We can give the equal width to all the container containing the text like the figma design.
Actual Design : 
![image](https://github.com/user-attachments/assets/3c014163-da53-434b-af9b-92e614372472)
Figma Design : 
![image](https://github.com/user-attachments/assets/aae9ffd4-7ef0-4879-9666-b709f08d750f)

**Comment by Sanam-07** [comment]
Issue 5 : When the user encounters an error in the location form while saving, then the error message should be displayed without collapsing the error section.
[Video.webm](https://github.com/user-attachments/assets/cea66e86-f894-4b89-a585-26745a92033e)
![image](https://github.com/user-attachments/assets/ce5f71b4-6708-4833-a98e-e5bae70d3ae4)

**Comment by PG-Momik** [comment]
@emmajclegg This has been deployed to staging. Forms in both activity level and organisation level have been update.

Major Changes:
1. Simplify nested forms + consistent borders
2. Implement collapse functionality to every elements (Previously only in document link)
3. Added required / optional  label on form's element header.
4. Changed positioning and text of delete parent  button
5. Added Highlight on delete parent button hover
6. Breadcrumbs on edit form.

Please have a look and let me know if any changes are required.

**Comment by emmajclegg** [comment]
Thanks @PG-Momik - this is looking good. I've gone through element-by-element with things to check below.

**1. Check mandatory vs. optional labelling**

ACTIVITY DATA:
- `conditions` sub-element "[condition](https://github.com/IATI/IATI-Schemas/blob/version-2.03/iati-activities-schema.xsd#L1967)" is showing as mandatory when it's optional
- `planned-disbursement` sub-element "[period-end](https://github.com/IATI/IATI-Schemas/blob/version-2.03/iati-activities-schema.xsd#L2085)" is showing as mandatory when it's optional
- `budget` sub-element "[value](https://github.com/IATI/IATI-Schemas/blob/version-2.03/iati-activities-schema.xsd#L2036)" is showing as optional when it's mandatory

ORGANISATION DATA:
- `recipient-region-budget` attribute "[status](https://github.com/IATI/IATI-Schemas/blob/version-2.03/iati-organisations-schema.xsd#L507)" is showing as mandatory when it's optional

**2. Remove yellow "core" rings against sub-elements** 
(these are confusing at the sub-element level as mandatory fields are already marked with a red asterisk).

The following elements are affected:
ACTIVITY DATA: `budget`, `planned-disbursement`, `transaction`
ORGANISATION DATA: `total-budget`, `recipient-organisation-budget`, `recipient-region-budget`,` recipient-country-budget`

Example for `budget`:
![Image](https://github.com/user-attachments/assets/561ae690-c64f-43fb-b3aa-278fad5f78a7)

**3. No space between element names and the "(Optional)" label in cases where there's no help text:**
![Image](https://github.com/user-attachments/assets/d7c1279f-f766-40fa-889a-375e76c561a3)

After completing this issue, it'll be much easier for us to review remaining data completeness alerts across the tool - I've created a new issue for this ([#1597](https://github.com/younginnovations/iatipublisher/issues/1597)), likely for November work.

Any questions, let me know.

**Comment by emmajclegg** [comment]
Thanks @PG-Momik. The element below still needs checking but the other changes look good:

> ORGANISATION DATA: `recipient-region-budget` attribute "[status](https://github.com/IATI/IATI-Schemas/blob/version-2.03/iati-organisations-schema.xsd#L507)" is showing as mandatory when it's optional

When we implement these new data entry forms, is there anything to be aware of in terms of impact on existing users' data in the interface? As far as I can see, the main thing would be that data they've entered in optional sub-elements will now appear hidden to them (within the new collapsed sub-element format).

Also, for awareness - I was showing the data entry forms to support colleagues today and we discussed the positioning of help text being inaccessible (i.e. the yellow box in the screenshot below). I have already created an issue on the backlog (#1531) about reviewing it, likely over the next two months, but wanted to mention here in case there's overlap with this form builder work.

![image](https://github.com/user-attachments/assets/8e601315-435f-4b6a-b194-d8184518df9a)

**Comment by PG-Momik** [comment]
@emmajclegg No there wont be any data level changes for existing data. As you mentioned, even if users have filled optional sub elements, they will be rendered in collapsed state.

**Comment by emmajclegg** [comment]
I'm happy for these data entry form changes to be implemented

**Comment by PG-Momik** [comment]
Changes have been deployed to production.

**Comment by emmajclegg** [comment]
Reopening this issue because of a potential bug related to `document-link`:

CASE 1 (correct behaviour): For `document-link` as an activity element ([example](https://iatipublisher-staging.yipl.com.np/activity/1183/document_link)), the mandatory vs. optional fields of the data entry form are correct:
![image](https://github.com/user-attachments/assets/c5e8869a-a124-4482-a891-2005564af4f1)

CASE 2 (incorrect): For `document-link` as a sub-element within a `result` ([example](https://iatipublisher-staging.yipl.com.np/activity/1183/result/517/edit)), "category" is marked optional when it should be mandatory:
![image](https://github.com/user-attachments/assets/4307fa89-82ae-4b99-9b85-025b08cfd885)

CASE 3 (incorrect): For `document-link` as a sub-element within an `indicator` ([example](https://iatipublisher-staging.yipl.com.np/result/517/indicator/932/edit)) or `period` ([example](https://iatipublisher-staging.yipl.com.np/indicator/932/period/2532/edit)), both "title" and "category" are marked optional when they should be mandatory:
![image](https://github.com/user-attachments/assets/bb2980f9-efe9-4e73-84ae-df5acbb8c684)

The mandatory vs. optional logic is always the same for this element wherever it appears - can the data entry forms in Cases 2&3 be fixed to match Case 1.

Any questions let me know.

**Comment by PG-Momik** [comment]
@emmajclegg This has been fixed and deployed to all environments.

**Comment by emmajclegg** [comment]
Great - thank you @PG-Momik
