### ISSUE TITLE
Transaction List - Allow bulk deletion of transactions

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1556]
**User story:** "As a user, I want to be able to delete a group of transactions at once, rather than one by one, to save time"

**Suggested solution:**
The user can select and delete multiple (e.g. 10) transactions at once

**Considerations:**
If an activity has transactions, it is highly likely to have more than one. It is intuitive in the Transaction List to be able to select and delete a group of transactions at once (e.g. if the user has imported duplicates in error)

![image](https://github.com/user-attachments/assets/600c8576-eee5-41ff-8a38-7c0185ff98cc)

**Comment by Sanam-07** [comment]
- [ ] Issue 1 : When the user select all the transaction from 2 pages then the count should be 20 but its showing 19 actually.
[Transaction Video.webm](https://github.com/user-attachments/assets/a03e3aad-18d6-4fce-af5e-b447cf1411d9)
![image](https://github.com/user-attachments/assets/a2d9cdff-c11d-4219-9002-218f28f3293d)

- [ ] Issue 2 : When the user delete large amount of transaction at a time then then the blank page appears in the UI indicating that transaction not found.
![image](https://github.com/user-attachments/assets/94d8b62e-3182-463d-a455-c151469f66a3)
[Bulk Transaction Video.webm](https://github.com/user-attachments/assets/8e841395-0c96-4ca3-ad7e-2c373407779c)

**Comment by Yash-ftW** [comment]
@emmajclegg, This has been deployed to staging.

Additional Change to be expected:
- When deleting transactions the filter and pagination are reset to the default (i.e Page 1 and Filtered by all).

**Comment by emmajclegg** [comment]
(moving back to "review ODS" as I commented about a potential issue in #1607)
