### ISSUE TITLE
Unpopulated point sub-element causing error in activity location XML code

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1558]
This relates to this support ticket: https://iati.zendesk.com/agent/tickets/45131

All sub-elements are optional for the activity `location` element. A publisher has reported, and I have replicated on staging, that a critical error is being caused by an unpopulated sub-element appearing in the XML code for the activity `location` element.

**My test activity's location data:** https://iatipublisher-staging.yipl.com.np/activity/1240/location 
(I've only populated the `name` sub-element, which is ok according to the IATI Standard)

**Issue**: the XML code generated contains an unpopulated `point` sub-element:
![image](https://github.com/user-attachments/assets/abf91b91-e342-441a-bba7-2a5ffc9bf866)

, which causes a critical data validation error:
![image](https://github.com/user-attachments/assets/5116a2f6-ed05-465c-b6e8-4a3805bbb3cb)

The `point` sub-element should not appear in the XML code in this scenario. Can this please be fixed

**Comment by PG-Momik** [comment]
@emmajclegg  This has been deployed to staging. 

During xml generation, an if condition in the code was loosely checking for empty string. only When in fact it should have been checking for any empty values (null, false, empty string, etc). This has been changed and deployed to staging. Now, the rogue `point` sub element will not show up when downloading xml or publishing.

**Comment by emmajclegg** [comment]
Thank you @PG-Momik - this looks ok in staging so go ahead and push to production.

Does this only affect this location `point` element, or could the same fix be required elsewhere in the xml generation code?

**Comment by PG-Momik** [comment]
@emmajclegg I've only made the change for loaction->point.  We'll need to check if similar issue exist in other element->subelements and then fix it accordingly. For now I'll have this deployed to prod and we can look for similar bugs in the future.  I've noted down this bug and visit it some time later.

**Comment by emmajclegg** [comment]
Thank you @PG-Momik . I've created a placeholder issue here (https://github.com/younginnovations/iatipublisher/issues/1566) for the wider sub-element checks
