### ISSUE TITLE
Review activity location element data completeness alert

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1559]
This is similar to work done on the activity result element (#1542) and would also be improved by completion of #1553 and #1550 

_**User story:** "As a user, if I see a "not completed" warning for the activity `location` element in the interface, I want this to be accurate against the IATI Standard and for it to be obvious which data fields I am missing"_

![image](https://github.com/user-attachments/assets/5c9ad9d3-587d-4966-bdd2-5177fdec2248)

According to the IATI Standard, the activity [`location`](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/location/) element is optional. If a user chooses to complete it,
- the attribute `@/ref `is optional 
- all sub-elements (`location-reach, location-id`, etc.) are optional
- therefore, data completeness should only be checked for sub-elements that the user has started populating
- within sub-elements, there will be mandatory fields (e.g. `pos` for the sub-element `point`)

Can we review the current data completeness check on the `location` element to make sure it aligns with the logic above.

**Comment by Yash-ftW** [comment]
Hi @emmajclegg,

For this user story we are planning to do this for location, there are two conditions:

1. When user '**saves and exits**' an empty location (i.e. without filling any of the fields inside) the following would be shown:

![Image](https://github.com/user-attachments/assets/9244917b-0fcd-4510-bf2a-24799b4eade2)

2. When user '**saves and exits**'  with any of the field filled the following would be shown:

![Image](https://github.com/user-attachments/assets/88e8a4c2-65c2-4a7d-9c82-07121ff00f02)

Please let us know if this is okay.

CC: @BibhaT

**Comment by emmajclegg** [comment]
@Yash-ftW - thanks for sharing. Is there a reason that the sub-element "location reach" is highlighted at the top in both of these cases? All sub-elements for `location` are optional, so I don't see an obvious reason why this one is more important than the others. 

Given that, I would think it's clearer to just display N/A in the first case?
![image](https://github.com/user-attachments/assets/77d317a4-21b0-44b8-9b81-44a3fd2f6668)

Then list all sub-elements as you've done for case 2, ideally with Location Reach in the same format as the other sub-elements, but the important thing being that we don't make fields look mandatory to complete when they're not.

**Comment by Yash-ftW** [comment]
Hi @emmajclegg, 
For the location reach it is not a new change, it was the same since it was created. 
>Then list all sub-elements as you've done for case 2, ideally with Location Reach...

We will go with this approach.

**Comment by Yash-ftW** [comment]
@emmajclegg, This has been deployed to staging. Please review it and let us know if any changes need to be made.

**Comment by emmajclegg** [comment]
Thanks @Yash-ftW - the interface looks fine. I think the data completeness check is overly strict though - what does the user have to populate to have the `location` element labelled "completed"?

![Image](https://github.com/user-attachments/assets/1c680ec4-a397-488d-b58d-1ab5a4464ec4)

All of the sub-elements are optional so "not completed" should only show if a sub-element has been started but only partially completed - e.g. [location-id](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/location/location-id/)  @/code has been populated but not @/vocabularly

I don't want us making this overly complicated, but it is confusing to the user as stands.

**Comment by Yash-ftW** [comment]
Hi @emmajclegg, 
>I think the data completeness check is overly strict though - what does the user have to populate to have the location element labelled "completed"?

For this we didn't change anything, it was how it was earlier. We just changed the front end design on how to display the data.

>All of the sub-elements are optional so "not completed" should only show if a sub-element has been started but only partially completed - e.g. [location-id](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/location/location-id/) @/code has been populated but not @/vocabularly

To do this we need to make changes in the back end and also change all other optional fields(for consistency across elements).Hence if we are to do it, we could do it as another issue and address it there which might take a while. Please let us know.

CC: @BibhaT

**Comment by emmajclegg** [comment]
@Yash-ftW - I spoke to @BibhaT today about this.

The changes you've made to the front end design look like they are addressing issue (#1550) more than reviewing how the data completeness label is working (which is what this issue #1559 was originally about). I am happy for you to implement the interface changes on that basis, however the data completeness logic (across the tool) still requires reviewing and I will create a new issue to capture this.

For example - in this `location` case, apparently the user has to populate all sub-elements for the element to be marked "completed", which is unlikely to ever happen as all of these sub-elements are optional.

Bibha made a good point this morning that the IATI Publisher data entry forms themselves could have additional validation logic applied to stop the user saving when they have only partially entered information (i.e. to apply the logic I mention in the comment below). This will lessen the need for data completeness checks at the element level.

> All of the sub-elements are optional so "not completed" should only show if a sub-element has been started but only partially completed - e.g. [location-id](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/location/location-id/) @/code has been populated but not @/vocabularly

Note - I can no longer see the interface changes for the `location` element on the staging site - is that because of the fix applied after today's log-in issue?

![Image](https://github.com/user-attachments/assets/c4d30a64-8c16-47a4-bc75-879119479893)

**Comment by Yash-ftW** [comment]
Hi @emmajclegg,
Do you want us to implement validation for location in this current issue or should we do it together with other elements (i.e across the tool)?

>Note - I can no longer see the interface changes for the location element on the staging site - is that because of the fix applied after today's log-in issue?

This was because the two issues were in two separate branches and thus the interface on staging for the location element wasn't showing as #1550 was deployed. As for now, both of it was merged and deployed to staging.

CC: @BibhaT

**Comment by emmajclegg** [comment]
@Yash-ftW @BibhaT - please don't do further data validation work for this `location` element, unless one of the following temporary fixes is quick (i.e. less than a few hours work):

a) relax the `location` element data completion check, so that completion of any sub-element by the user marks it as "completed"
OR
b) remove the "completed" vs. "not completed" labels so that neither shows for this element

More thought needs to be given to data validation and completeness across IATI Publisher as a whole, so that we're being consistent and applying checks in the most sensible place. The different aspects to this are:
- Clearer data entry forms (#1553), which we are close to implementing I hope
- Deciding what additional checks to run at the point that a user saves their data (i.e. clicks "Save and Exit" from a data entry form). This seems the most logical place to prevent a user partially completing information for an IATI sub-element, for example. I will create a new GitHub issue to capture this
- Reviewing the logic behind element-level data completeness alerts - to ensure these are actually useful to users and in line with the IATI Standard

**Comment by BibhaT** [comment]
@emmajclegg thanks for the feedback! 
 
> a) relax the `location` element data completion check, so that completion of any sub-element by the user marks it as "completed" OR b) remove the "completed" vs. "not completed" labels so that neither shows for this element

 Both of them take equal time so I think it would be best to mark it as "completed" if any sub-element is filled in as it maintains consistency across the elements. 

@Yash-ftW @PG-Momik

**Comment by Yash-ftW** [comment]
Hi @emmajclegg, 

>a) relax the location element data completion check, so that completion of any sub-element by the user marks it as "completed"

This has been implemented and deployed to staging.

**Comment by emmajclegg** [comment]
Ok perfect - thanks both. I've reviewed in the interface and all looks good.

Can we make sure the completeness label is updated for existing users' `location` data in IATI Publisher? i.e. you ran a script for this when we worked on `result` in #1542
