### ISSUE TITLE
#152 Bug: User is allowed to register over the logged in session 

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#156]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://stage.iatipublisher.yipl.com.np/register
- Username: User_A
- Password: test1234

### Steps ###
- Create two instances of  https://stage.iatipublisher.yipl.com.np/ in browser
- Open
- In first https://stage.iatipublisher.yipl.com.np/register
- Second https://stage.iatipublisher.yipl.com.np/login

- In first instance>> enter valid publisher id and other details
- Fill in valid entries and move to Step 2
 

- In Second instance>> enter Valid name and Login
- Login with above mentioned User name and password
- Click on Login button

- Now Go to for first instance>>Click Next from Step 2
- Open dev tools and check for the request

### Actual result ###
- Screen keeps loading over the request

### Expected result ###
- Session for the same instance is to be handled

https://drive.google.com/file/d/1BvCP_JrLIC5PxgQ0azc7DQMIUzQPwWrv/view?usp=sharing

**Comment by sriza** [comment]
@AbhishekSka 
The fixes to this issue is deployed to the staging site. Could you please test the changes and let me know if the issue persists?

cc @man-git007 @praweshsth

**Comment by SauravSilwal10** [comment]
@sriza 
This fix still has bugs.
Actual Output: The registration page continues to refresh indefinitely.
Excepted Output: The registration page should redirect to the activity page, and the session for the same instance should be handled.

https://user-images.githubusercontent.com/78422663/172322651-48467ab0-c0e2-43ad-a726-6e1294cead11.mp4
cc @man-git007  @praweshsth

**Comment by man-git007** [comment]
@sriza Have we fixed this issue?

cc @SauravSilwal10

**Comment by SauravSilwal10** [comment]
Issue Fixed 

cc @man-git007 @sriza
