### ISSUE TITLE
Staging IATI Regsitry is down again

### ISSUE THREAD

**Issue by PG-Momik** [younginnovations/iatipublisher#1564]
@emma, [Staging IATI registry](https://staging.iatiregistry.org/) is down again. Is there someone we could contact directly via email incase this happens again?

**Comment by emmajclegg** [comment]
Thanks for flagging @PG-Momik and sorry that this is causing problems again. The Registry staging site is working as of now, and we are escalating the cause of the outages.

if it happens again, I recommend raising a GitHub issue here: https://github.com/IATI/ckanext-iati/issues, and tagging me and @cormachallinanderilinx in the first instance

**Comment by PG-Momik** [comment]
@emmajclegg . No problem and thank you as well.

**Comment by PG-Momik** [comment]
@emmajclegg New Organisation registration API is not working in IATI Registry Staging.

**Comment by emmajclegg** [comment]
@PG-Momik - i've raised a Registry staging issue here: https://github.com/IATI/ckanext-iati/issues/465. Can you add the name of the specific API call (and any other relevant information for troubleshooting) in a comment on that issue please.

Thank you

**Comment by PG-Momik** [comment]
Closing this since the timeout issue has been fixed.
