### ISSUE TITLE
Check XML generation code for unpopulated sub-elements

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1566]
This follows #1558 , which fixed an unpopulated `location >> point` sub-element that was creating data validation issues.

> We'll need to check if similar issue exist in other element->subelements and then fix it accordingly. For now I'll have this deployed to prod and we can look for similar bugs in the future. I've noted down this bug and visit it some time later.

This issue is to check for this problem elsewhere in the activity XML generation code, and applying fixes as necessary.

**Comment by Sanam-07** [comment]
Issue 1 : The user gets redirected to the period list when they fill the string value instead of integer value in value field.
https://github.com/user-attachments/assets/44961636-3adc-48a3-844b-d16e395e49a1
![Image](https://github.com/user-attachments/assets/81cff683-599a-456e-aa83-447487c1fbfd)

**Comment by PG-Momik** [comment]
@emmajclegg  This has been deployed to staging. We didnt find any other elements with malformed as in location (#1558).

Testing process:
1. (Manually) Fill different combinations of empty fields and non empty fields -> save and exit -> downloading xml -> confirm if malformed. Repeat for all activity elements, especially:(contact_info, conditions, country_budget_items, document_link, indicator, location, other_identifier, period, planned_disbursement, result, transactions)
