### ISSUE TITLE
#148 Bug: After deleting the cookies, the sign-up page becomes unresponsive.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#157]
Context
- Desktop
- Chrome 100.0.4896.127

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Saurab
- Password: test1234

Steps
- Click the inspect
- open the application
- Click the cookies
- Delete the XSRF-TOKEN

Actual result
- The sign-up page becomes unresponsive

Expected result
- Sign up page should be reactive

https://user-images.githubusercontent.com/78422663/170679232-e4ef3a6d-d065-4ec9-bd3d-41dad6f7a2b5.mp4

**Comment by man-git007** [comment]
@AbhishekSka @SauravSilwal10 What is the status of this issue? If fixed lets close this issue

cc @sriza

**Comment by SauravSilwal10** [comment]
@sriza This issue has not been fixed yet. Please have a look.

cc @man-git007  @AbhishekSka

**Comment by man-git007** [comment]
@SauravSilwal10 Lets halt this issue for now and maintain it in a backlog.

cc @sriza @AbhishekSka @jenishshrestha @Man0zZ

**Comment by SauravSilwal10** [comment]
please refer to the issue #489 

cc @sriza
