### ISSUE TITLE
Minor text corrections to Activity Data screen alerts

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1574]
Ahead of translation work, can we update the text of the three activity alerts pictured below as follows:

1) **Email not verified:** Please check for the verification email sent to you when you registered (click here to resend the verification email). Contact support@iatistandard.org for further assistance.

2) **Complete your setup:** We recommend that you [complete default values](https://iatipublisher-staging.yipl.com.np/setting) (language, currency and recommended defaults for activity data) to enable full functionality of IATI Publisher.

3) **IATI Registry account is inactive:** Your account is pending approval by the IATI team - someone should be in touch within two working days.

![image](https://github.com/user-attachments/assets/4a430750-f9ae-4102-b2f4-fe641d37caba)

This is for clarity and to be consistent with other messaging we've updated in the tool.

**Comment by Yash-ftW** [comment]
Hi @robredpath, Could you verify the changes on staging https://iatipublisher-staging.yipl.com.np/ and move this user story to 'ODS Passed' if everything is ok.
