### ISSUE TITLE
#152 Bug: Register>>Step 2>>Password and Confirm Password Validation should  be done .

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#158]
Context

- Desktop
- Chrome  100.0.4896.127 

Precondition
- https://stage.iatipublisher.yipl.com.np/register
- tester
-  NP-CRO-145
-  test111145

Steps

- https://stage.iatipublisher.yipl.com.np/register
- Fill required necessary field and move to Step 2
- Enter Password:Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. 

- Enter a confirm Password:Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. 

Actual result
- Redirect to the email verification page.
Expected result
- The password and confirm password must not be greater than 255 characters.

https://user-images.githubusercontent.com/78422663/170919692-2c4a36bf-7bba-48a0-a1be-5c43f4a1b0e9.mp4

**Comment by sriza** [comment]
@SauravSilwal10 
The validation rules for password and password confirmation have been updated. Please have a look at it and let me know if further changes are required.

cc @man-git007 @praweshsth

**Comment by man-git007** [comment]
@sriza @SauravSilwal10 What is the status of this ticket?

**Comment by SauravSilwal10** [comment]
Issue fixed 
cc @man-git007  @sriza
