### ISSUE TITLE
Review recipient-country and recipient-region "percentage" labelling

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1595]
For the [`recipient-country`](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/recipient-country/) element, the IATI Standard says _"When a single recipient country in a vocabulary is declared, the percentage must either be omitted, or set to 100"_. A similar logic applies to element [`recipient-region`](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/recipient-region/)

Currently, if a user populates a single `code` for either `recipient-country` or `recipient-region` in IATI Publisher and leaves `percentage` unpopulated, the respective element is marked "not completed":

![image](https://github.com/user-attachments/assets/a488012a-de94-4ae2-a8f8-72ab92e47e88)
![image](https://github.com/user-attachments/assets/40291e85-7c75-4c68-8009-c7fecf46d07d)

It is not clear to the user what they need to populate in the data entry form to fix this.

----

**Solution 1:** we label the "percentage" field as required (*) for `recipient-country `and `recipient-region`, to ensure the user completes it.
**Solution 2:** we change the data completeness logic to show the elements as "completed" in the situation highlighted above.

I assume solution 1 would be easiest to implement, so would vote for this to avoid overcomplicating the data completeness logic?

NOTE: `sector` is an element with similar logic, so we would want to ensure consistency.

**Comment by PG-Momik** [comment]
@emmajclegg Thank you for the proposed solutions. As you mentioned, Solution 1 seems the easiest to implement, as it doesn’t require altering the logic for calculating completeness or modifying the existing form validation. It simply involves adding a required * for RR or RC percentage, as well as for Sector RR and RC.


cc: @Sanam-07 @BibhaT

**Comment by PG-Momik** [comment]
@emmajclegg  This has been deployed to staging. Required * has been added to percentage field in RR, RC and sector.

**Comment by emmajclegg** [comment]
Great - thank you
