### ISSUE TITLE
#152 Bug: Register>>Step 2>> Validation over the email field stays once it gets validated

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#160]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://staging.iatiregistry.org/
- yiplqa1@gmail.com
- test1234
[Publisher Name 6](https://staging.iatiregistry.org/publisher/pub_6)

### Steps ###
- https://stage.iatipublisher.yipl.com.np/register
- Fill required necessary field and move to Step 2
- Fill all required field and in email field enter email id which has already been registered say "yiplqa1+pub1@gmail.com"
- Click Next
- Field get validated
- enter fresh email id to the field

### Actual result ###
- Field still gets validated even email is unused

### Expected result ###
- Validation should be removed upon entering unused mail id and moved to next step

https://drive.google.com/file/d/1X7HqE65U-NmFF9WkjKuyxXAcE88_stQH/view?usp=sharing

**Comment by man-git007** [comment]
@AbhishekSka Is this issue resloved? If yes lets close this issue.

cc @sriza

**Comment by man-git007** [comment]
@SauravSilwal10 Can you re-confirm the issue?

**Comment by SauravSilwal10** [comment]
Issue Fixed 
cc @man-git007
