### ISSUE TITLE
Troubleshoot duplicate activities with the same identifier

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1604]
This issue was reported by an end user in this support ticket: https://iati.zendesk.com/agent/tickets/45658

After using the XML import, they have ended up with the same activity appearing twice in the interface. This should not be possible when the activity identifiers are the same.

**Comment by PG-Momik** [comment]
Hi @emmajclegg,

Quick update on the issue. We've been able to reproduce the duplication problem, though not under the exact conditions mentioned in the ticket.

>    "... hitting the import button twice, because nothing appeared to have happened the first time...."
>    Zendesk ticket

We haven't been able to replicate the scenario of clicking the import button twice in any of our environments (local, dev, staging, prod), as the 'importing...' screen appears immediately after the first click. Initially, we suspected that multiple import jobs might be triggered simultaneously, causing the duplication of activities. This suspicion aligns with the user's description—essentially, performing two import jobs at the same time in different browser tabs.

Currently, the system doesn't prevent multiple parallel import jobs, so we are working on a solution to block multiple import jobs from running for the same organization at the same time.


cc: @BibhaT

**Comment by Sanam-07** [comment]
- [ ]  Issue 1 : The user is able to create the two different activity from the same xml file within the same organization with same user by using two different browser.
[Untitled_ Nov 18,2024 5_20 PM.webm](https://github.com/user-attachments/assets/05c22a73-8b05-441a-af69-344b7a1aab0d)
![image](https://github.com/user-attachments/assets/881c8a84-bd79-43c1-9b25-8690c4684e2e)

**Comment by PG-Momik** [comment]
@emmajclegg  This has been deployed to staging. 
- Users cannot press the import button more than once. (This was causing the initial issue)
- Organizations cannot have multiple import jobs running at the same time.

**Comment by emmajclegg** [comment]
Thanks @PG-Momik - all looks to be working as expected.
