### ISSUE TITLE
Get Started guidance not displaying properly

### ISSUE THREAD

**Issue by PG-Momik** [younginnovations/iatipublisher#1613]
Source: https://iati.zendesk.com/agent/tickets/45732

**Comment by Sanam-07** [comment]
Issue 1 : An error message occurs when the user try to publish the organization data.
![image](https://github.com/user-attachments/assets/b4f5952e-17ef-4ef7-95d1-a72f6f290691)

**Comment by PG-Momik** [comment]
@emmajclegg This has been deployed to stage.

**Comment by emmajclegg** [comment]
Thanks @PG-Momik - I can't test this easily but the "Get Started" guidance looks as expected in my staging test account. Go ahead and deploy, then I'll doublecheck the affected publishers after.
