### ISSUE TITLE
#148 Bug:While logged into a system, a user can reset his or her password.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#162]
Context

- Desktop
- Chrome 100.0.4896.127

Precondition

- https://stage.iatipublisher.yipl.com.np/
- Username: Hari
- Password: 123456789

Steps

- Create two instances of https://stage.iatipublisher.yipl.com.np/ in the browser
- Open
- first https://stage.iatipublisher.yipl.com.np/login
- Second https://stage.iatipublisher.yipl.com.np/login
- In the first instance>>Enter a valid username and password>>Click the Sign in Button
- In the Second instance>Enter a valid email >>Click send password reset link button >>Enter a password and confirm the password.

Actual result
- Password resets successfully.

Expected result
- Upon Changed password current session should expire 

https://user-images.githubusercontent.com/78422663/170690554-1121c80d-5329-409e-b92c-3d7c24a8b723.mp4

**Comment by man-git007** [comment]
@AbhishekSka What is the status of this issue?

**Comment by SauravSilwal10** [comment]
Issue Fixed 
cc @man-git007  @AbhishekSka
