### ISSUE TITLE
Improvements to Results List usability

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1620]
Similar to work on the Transaction List in #1607 , can we make it easier for users to find results in the Result List:

![image](https://github.com/user-attachments/assets/192bbde5-55a5-45a0-ad99-d4ba75071f6e)

**User issues**
- It is not easy to read the result titles as only the start of the title displays on screen
- It is not possible to search for a result by keyword in the title, or sort columns (ascending vs. descending), to help find a specific result

**Suggested improvements**: (we can consider changes to the Transaction List for consistency)
- Increase the character limit of the title showing on screen, so that more of the text is visible
- Allow users to sort columns, especially to order by title
- (if easy to do) Add a filter on Result Type, similar to the filter currently on the activity list for activity draft vs. published status

**Other considerations:**
- Is Result Number a useful thing to show the user? More space for the title, or a "result last updated" date may be more useful here
- Users may want to search for a result by typing in a keyword (that searches the result titles)

**Comment by BibhaT** [comment]
Hi Emma,

> Similar to work on the Transaction List in [#1607](https://github.com/younginnovations/iatipublisher/issues/1607) , can we make it easier for users to find results in the Result List:

> **User issues**
> 
> * It is not easy to read the result titles as only the start of the title displays on screen
Yes, that's definitely not a good experience. We can increase the number of characters to show in the Result list. 

> * It is not possible to search for a result by keyword in the title, or sort columns (ascending vs. descending), to help find a specific result
I think search option would be much more easier to the users compared to sorting the columns. It takes equal time for the development of both the features, so I propose we go with the search option. Let me know your thoughts. 


> * (if easy to do) Add a filter on Result Type, similar to the filter currently on the activity list for activity draft vs. published status
Keeping consistency with the Transaction 
Considering consistency with the Transaction element, it would make sense to add this functionality. It would also make it much easier for the publisher to narrow down what they are looking for. 


> * Is Result Number a useful thing to show the user? More space for the title, or a "result last updated" date may be more useful here
I wouldn't say it is useful for the user, but, it is something that needs to be shown for easy access. They might need to refer to the number when making changes to existing data. It would be helpful for them to cross check the numbers. 
I am not sure how useful "result last updated" would be here, what purpose would the user need it for? It also won't be consistent with Transaction element. Let me know your thoughts. 

_Note: Momik has suggested developing result bulk deletion as well while we're working on this. _ 

We have estimated 3-4 days for all the above mentioned features.

**Comment by BibhaT** [comment]
Thanks @emmajclegg

**Comment by Sanam-07** [comment]
- [ ] Issue 1 : When the user search specific result and move to next page then all the results appears.
[Video.webm](https://github.com/user-attachments/assets/7ce86ddc-6236-4360-8e5f-ea26ded227e3)
![image](https://github.com/user-attachments/assets/f43baf7e-7005-4ea6-bf40-5481498742ad)

**Comment by PG-Momik** [comment]
@emmajclegg  This has been deployed to staging.

**Comment by emmajclegg** [comment]
Thanks @PG-Momik - I've tested the result search, filters and deletion - all look to be working fine.

Can we show more of the result title on screen? This is the only thing from the original issue above remaining,

Currently there's a lot of blank space available in the table, yet the title is cut off at a small number of characters:
![Image](https://github.com/user-attachments/assets/82a70d04-563c-4b0c-b33c-e40683bf4e35)

**Comment by Yash-ftW** [comment]
@emmajclegg, This has been deployed to staging.

**Comment by emmajclegg** [comment]
Thanks @Yash-ftW - the table still doesn't look as neat as I think we could make it (in terms of length of result title showing on screen and amount of blank space the "Result Number" column has.

![Image](https://github.com/user-attachments/assets/af5142f4-a5a9-4448-b924-d57637def188)

The format of activity titles in the activity list is much clearer for example: 
![Image](https://github.com/user-attachments/assets/fc307e60-d4a8-4b4e-9d3b-5e0d25ca1cce)

Is it straightforward to wrap text for result titles (i.e. display them on multiple lines)? I appreciate we don't want masses of text on screen, but this would make reading titles much more accessible.

**Comment by PG-Momik** [comment]
@emmajclegg  This has been deployed to staging. 

We have decided to include two lines of information with 70 characters' limit per line (which is the standard practice).

(1920x1080)
![Image](https://github.com/user-attachments/assets/ff52e461-65d7-4ba7-b0cd-db80c6442952)

(1440x1080)
![Image](https://github.com/user-attachments/assets/1978e1f0-2bf3-446e-ae24-5661fd9ed522)


cc: @BibhaT @shreyaydi
