### ISSUE TITLE
#152 Bug: 500 while registering the user 

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#163]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://stage.iatipublisher.yipl.com.np/register

### Steps ###
- Registration>> Enter vaild information for Step 1
- Enter valid information for Step 2
- Hit next

### Actual result ###
- User face 500 upon submission of api

### Expected result ###
- User should observe verification email sent and page moved to Step 3 email verification 

![image](https://user-images.githubusercontent.com/25945530/170918496-af567e11-9bd3-430d-9ed3-873dd5fdfa12.png)

**Comment by man-git007** [comment]
@sriza Could you please look into this?

**Comment by sriza** [comment]
@AbhishekSka 
The fixes to this issue is deployed to the staging branch. Please let me know if the issue persists.

cc @man-git007 @praweshsth

**Comment by man-git007** [comment]
@SauravSilwal10 @AbhishekSka Does the issue still persist?

**Comment by SauravSilwal10** [comment]
Issue Fixed 
cc @man-git007 @AbhishekSka
