### ISSUE TITLE
#152 Bug: Register>>Step 2>>when you enter invalid email address administrator information page becomes unresponsive.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#164]

**Comment by SauravSilwal10** [comment]
Context

- Desktop
- Chrome 100.0.4896.127

Precondition

https://stage.iatipublisher.yipl.com.np/register

- tester
- NP-CRO-145
- test111145

Steps

https://stage.iatipublisher.yipl.com.np/register 
Enter an email:3@3
Click the next step  button


Actual result
-administrator Information page becomes unresponsive

Expected result
- The email format is invalid.

https://user-images.githubusercontent.com/78422663/170921381-1ca2eb7d-7bd9-469b-afa1-cc449adec556.mp4

**Comment by sriza** [comment]
@SauravSilwal10 
This issue has been fixed and deployed to the staging site. Please have a look and let me know if the issue persists.

cc @man-git007 @praweshsth

**Comment by man-git007** [comment]
@SauravSilwal10 @AbhishekSka Does the issue still persist? If not let's close the issue

cc @sriza

**Comment by SauravSilwal10** [comment]
Issue fixed 

cc @man-git007 @sriza @AbhishekSka
