### ISSUE TITLE
#152 Bug :Register>>Step 3>>User's sign up  password  and confirm password could be viewed through xhr request

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#165]
Context

- Desktop
- Chrome 100.0.4896.127

Precondition

- https://stage.iatipublisher.yipl.com.np/
- tester
- NP-CRO-145
- test111145
- Steps

- https://stage.iatipublisher.yipl.com.np/register
- Fill required necessary field and move to Step 3

Actual result

- The entered password is visible on xhr request

Expected result

- Password encryption over the payload is to be made
![Screenshot from 2022-05-25 14-48-27](https://user-images.githubusercontent.com/78422663/170925760-33257554-0784-41b7-995d-48d05265e1ea.png)

**Comment by sriza** [comment]
@SauravSilwal10 
The password fields are now encrypted and deployed to the staging site. Please have a look.

cc @man-git007 @praweshsth

**Comment by SauravSilwal10** [comment]
@sriza 
This fix still has bugs.
Actual Output: After registration, a new user is unable to log into the system.
Excepted Output: A new user should log in to the system successfully.
https://user-images.githubusercontent.com/78422663/172328944-178065f3-cad0-4029-952d-53cf56d7d934.mp4
 cc @man-git007  @praweshsth

**Comment by praweshsth** [comment]
I used the following credentials:

username: Test data
password: 12345678 

as per the video, it logs in.

**Comment by man-git007** [comment]
@SauravSilwal10 Does the issue still persist? If yes @sriza Let's fix this today. 
Also, this issue is also mentioned in #151 

cc @praweshsth @sriza @Sanilblank

**Comment by sriza** [comment]
@SauravSilwal10 @man-git007 This issue has already been fixed.

**Comment by SauravSilwal10** [comment]
Issue Fixed 

cc @man-git007
