### ISSUE TITLE
#148 Bug: Password recovery >> Hamburger button  is not working properly.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#166]
Context

- Desktop
- Chrome 100.0.4896.127

Precondition

- https://stage.iatipublisher.yipl.com.np/login
- Click the reset button

Steps

- https://stage.iatipublisher.yipl.com.np/password/email
- Fill in the required necessary field and move Password Recovery

Actual Result

- The Ham burger is not working properly.

Excepted Result

- Ham Burger should work properly.

https://user-images.githubusercontent.com/78422663/170929490-24dec01d-b8ee-4f82-bdaf-9fe06769836b.mp4

**Comment by man-git007** [comment]
@Man0zZ Could you please look into this?

**Comment by Man0zZ** [comment]
@AbhishekSka i have fixed this bug and merged it into staging please check it out.

cc @man-git007 
cc @praweshsth

**Comment by man-git007** [comment]
@SauravSilwal10 Please verify the fix and close the issue if done

cc @Man0zZ @AbhishekSka

**Comment by SauravSilwal10** [comment]
Issue fixed 

cc @man-git007 @Man0zZ @AbhishekSka
