### ISSUE TITLE
#152 Bug: Register>>Step 3>>Email verification is not mandatory .

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#167]

**Comment by SauravSilwal10** [comment]
Context

- Desktop
- Chrome 100.0.4896.127

Precondition

- https://stage.iatipublisher.yipl.com.np/register

- Publisher Name: tester
- Publisher ID: test111145
- IATI Organisational Identifier :NP-CRO-145
- UserName Test1 
- Full name: Tester
- Email: test_1@gmail.com
- password:12345678
- Confirm Password:12345678

Steps

- Click the next step button and move to step 3
- Hit the URL https://stage.iatipublisher.yipl.com.np/login
- Enter username:Test1 
- Enter password:12345678
- Click the sign in button

Actual result

- Login is successful.

Excepted Output

- Email verification should be mandatory.

**Comment by man-git007** [comment]
@sriza We do have email verification right?

cc @praweshsth

**Comment by sriza** [comment]
@SauravSilwal10 
We do have email verification, but the user can login to the system while still having unverified email. 
The unverified user will be notified about the lack of verification through the error message:
![image](https://user-images.githubusercontent.com/24825118/170976285-0763a7e3-07c4-4b78-b4be-21bf93c5d680.png)

The error message feature is a work in progress and is not deployed to the staging yet.

cc @man-git007 @praweshsth

**Comment by praweshsth** [comment]
Yes, even though the email is not verified, the user can log in, add activity and organisation. However, the user can't publish activity or organisation until the email is verified along with other settings and default values and mandatory elements.

**Comment by AbhishekSka** [comment]
@praweshsth dai Is " the user can't publish activity or organisation until the email is verified" already implemented or on our upcoming sprints??

**Comment by praweshsth** [comment]
@publishing activity and organisation has not been done yet. When it is developed these things will be taken into consideration.

**Comment by AbhishekSka** [comment]
since it's a feature to be done rather than bug, closing the ticket for now.
