### ISSUE TITLE
#152 Bug: UI isssue over mozilla

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#168]
### Context

- Desktop
- Mozilla 100.0.2

### Precondition
- Resolution 1366x768
- Viewport: 1312x627

_Issue 1_

- [x]  Overflow content in Login page

![Screenshot(1)](https://user-images.githubusercontent.com/25945530/170924535-c729539b-be22-432e-bc42-7a0f93035b74.png)

_Issue 2_

- [x]  All of the fonts are on San serif
![Screenshot(2)](https://user-images.githubusercontent.com/25945530/170925461-5ba12fc0-61f1-4140-a66d-b08ee0ea9f7d.png)

_Issue 3_

- [x]  Spacing difference 
![Screenshot(3)](https://user-images.githubusercontent.com/25945530/170925925-06da6ed1-7df5-46c0-9057-bad1e9510efb.png)

_Issue 4_
- [x] Register>>Multilined placeholder of dropdown field's placeholder 
![Screenshot(4)](https://user-images.githubusercontent.com/25945530/170927137-6fab7694-a601-4080-96a2-2a5a63e5553b.png)

_Issue 5_
- [x] Register>> Button text  multi lined 
![image](https://user-images.githubusercontent.com/25945530/170927287-978c5e5e-f78b-4e9b-b90a-6ecb6f4aef9c.png)

**Comment by Man0zZ** [comment]
@AbhishekSka  can you check issue no. 1 and 5 again..I tested in multiple browsers in same resolution it works fine.

**Comment by man-git007** [comment]
@AbhishekSka @SauravSilwal10 What is the status of this issue?

cc @Man0zZ

**Comment by titungdup** [comment]
@man-git007 All issues are resolved. Closing this issue.
