### ISSUE TITLE
#54 Bug: Settings Design differences over figma

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#169]
**Context**
- Desktop
- Chrome 100.0.4896.127

**Precondition**
- https://stage.iatipublisher.yipl.com.np/
- Username: User_A
- Password: test1234

| **Steps**      | **Actual result** | **Expected result**    |
| :---        |    :----:   |          ---: |
|Issue 1: Default values>>Title "Registration form" missing    | ![image](https://user-images.githubusercontent.com/25945530/170945393-7f15fd46-6499-4405-93ea-f5e342408a7c.png) | ![image](https://user-images.githubusercontent.com/25945530/170953953-295937ca-67a2-4258-811a-bed2c309306c.png) |
|Issue 2: Publishing setting>>Missing field detail notes from design   |![image](https://user-images.githubusercontent.com/25945530/170947074-af68eb83-ddd1-4c18-b2b8-383fabdd1775.png) | ![image](https://user-images.githubusercontent.com/25945530/170947268-2c83f072-9867-4ed2-815a-40e0f712d4d1.png)|
| Issue 3: setting>>Missing Breadcrum |![image](https://user-images.githubusercontent.com/25945530/170947675-973f386c-3390-47a1-99a9-e5669c690130.png)  | Need to discuss ![image](https://user-images.githubusercontent.com/25945530/170947769-dc6a9d22-b591-4440-99cf-e474bd6f3dd1.png) |
| Issue 4:Publisher setting>>Publisher| field Publisher Id looks as if it could be edited![image](https://user-images.githubusercontent.com/25945530/170949163-fad71ff5-1dd3-41de-83ad-34675bbcbe9f.png)| Text value should be discolored if the field is to be notified as disabled   |

**Comment by man-git007** [comment]
@praweshsth Could you please verfiy?

**Comment by praweshsth** [comment]
- No. 1 looks fine to me. It doesn't have to be same as the design. And for both no. 1 and no.2, please refer to this document for the content - https://docs.google.com/spreadsheets/d/1AYj0Nn6StKUu2S23BIYa8o7OadWr_uJkFtuvWOtU5WU/edit#gid=0
- For next 2, Please go ahead with the feedback
@AbhishekSka @man-git007

**Comment by man-git007** [comment]
@SauravSilwal10 @praweshsth @nirvanalama What is the status of this issue?

**Comment by nirvanalama** [comment]
@man-git007 Is this a Design issue or frontend/dev issue?

**Comment by praweshsth** [comment]
@jenishshrestha Please look into these issue
