### ISSUE TITLE
#54 Bug: Invalid message appears during the verification of token

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#172]
Context
- Desktop
- Chrome 100.0.4896.127

Precondition
- The user should be logged into the system.
- https://stage.iatipublisher.yipl.com.np/activities

Steps

- Click the setting button
- Enter an invalid API token or Leave a blank field for the API token.
- Click the verify button.
- Click the Save publishing button.

Actual output

- API Token verified Successfully.
- Publisher setting stored successfully.

Excepted Output

- An error message should be displayed.

https://user-images.githubusercontent.com/78422663/170962941-14c407ec-29e2-46bd-b952-f97e81216869.mp4

**Comment by man-git007** [comment]
@sriza @SauravSilwal10 Do we still have this issue? If not let's close this issue
