### ISSUE TITLE
Result Design Flow

### ISSUE THREAD

**Issue by nirvanalama** [younginnovations/iatipublisher#173]

**Comment by nirvanalama** [comment]
**Here is the result flow:**
@praweshsth @andreaszenasidi @amy-silcock @k8hughes 

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=5020%3A61830&node-id=6446%3A113725&viewport=385%2C1355%2C0.02&scaling=min-zoom&starting-point-node-id=6446%3A113725&show-proto-sidebar=1

**Activity detail page with different states**
https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=5020%3A61830&node-id=6446%3A113602&viewport=385%2C1355%2C0.02&scaling=min-zoom&starting-point-node-id=6446%3A113602&show-proto-sidebar=1

**Comment by praweshsth** [comment]
@Rohini-IATI so do you think we need to sit down to discuss it on Monday?

**Comment by Rohini-IATI** [comment]
I think that @andreaszenasidi and @titiolukole may have inputs. Also it would be good to speak as I have questions about the display of the elements content and future copy-writing tasks for this project.

**Comment by praweshsth** [comment]
Sure, let's meet on Monday as planned.

**Comment by andreaszenasidi** [comment]
@praweshsth the design looks very good! It's easy to navigate in my opinion.

**Comment by praweshsth** [comment]
> @praweshsth the design looks very good! It's easy to navigate in my opinion.

Thank you.
