### ISSUE TITLE
#54 Bug: Settings>>Publishing settings>> Upon adding correct api token then directly Saving the settings sends payload for "token_verification":"false"

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#175]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
- Should have API token over IATI registry 

### Steps ###
- Settings>> Publishing settings>> enter API token
- Without verify directly hit "Save Publishing Settings" button 
- Check for payload in the xhr in network

### Actual result ###
- "token_verification: false" is being sent to the request even if the token is successfully verified

### Expected result ###
- Upon change in the Token field it is first to be verified then Saved
- Save Publishing Settings could be disabled unless user verifies it(suggestion)

https://drive.google.com/file/d/1m48F3Eao0n4rcWOhUzfjJMYJtKzqdntV/view

**Comment by man-git007** [comment]
@sriza What is the status of this issue?

**Comment by man-git007** [comment]
@SauravSilwal10 Can you look into this issue?

**Comment by Sanilblank** [comment]
I have just tried this and it seems to be working fine. Will close the issue now.
