### ISSUE TITLE
#152 Bug :User can register into the IATI publisher with the publishers that are unapproved from the iati registry

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#177]
Context
- Desktop
- Chrome 102.0.5005.61

Steps
Create two instances of https://stage.iatipublisher.yipl.com.np/ in the browser
Open
- First https://staging.iatiregistry.org/publisher/new
- Second https://stage.iatipublisher.yipl.com.np/register
- In the first instance>> enter valid publisher information and click publisher information
- Then redirect to the publisher information page where publisher information details are displayed.
- In the Second instance>> enter above mentioned Publisher Information>> move to the step 2
- Enter valid administrator information>>move to the step 3 
- Login with above mentioned User name and password
- Click on the Login button

Actual Result 
- Registration and Login are Successful.

Excepted Result 
- The user cannot be registered into the system.

https://user-images.githubusercontent.com/78422663/171563518-1b99239d-2c12-47c6-8033-b03745ecf979.mp4

**Comment by man-git007** [comment]
@sriza What is the status of this issue?

cc @SauravSilwal10

**Comment by SauravSilwal10** [comment]
Please refer to this link  #489 
cc @sriza
