### ISSUE TITLE
#148 Bug: UI issues

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#180]
**Context**
- Desktop
- Chrome 100.0.4896.127

**Precondition**
- https://stage.iatipublisher.yipl.com.np/login
- Click the Reset Button.

| **Steps**      | **Actual result** | **Expected result**    |
| :---        |    :----:   |          ---: |
|Issue 1: Password Recovery/password/email>> Margin is missing between password recovery and enter an email|![Screenshot from 2022-06-03 15-23-48](https://user-images.githubusercontent.com/78422663/171832512-276bb5e2-21d6-43af-89ca-f54a919a4425.png) |![Screenshot from 2022-06-03 15-25-03](https://user-images.githubusercontent.com/78422663/171832605-c7bac5aa-e36e-4ce8-8a35-24b98c84c64a.png) |
|Issue 2: Password Recovery/password/confirm>> Margin is missing between password recovery and email has been sent   |![Screenshot from 2022-06-03 15-30-15](https://user-images.githubusercontent.com/78422663/171832853-2d763e93-42ef-4a2f-84a6-0ddcacd202da.png)| ![Screenshot from 2022-06-03 15-31-15](https://user-images.githubusercontent.com/78422663/171833086-caaa0f60-16e8-42e2-914d-71484ff3d953.png)|
| Issue 3: Password Recovery/password/reset> Margin is missing between reset password and please enter your new password|![Screenshot from 2022-06-03 15-34-31](https://user-images.githubusercontent.com/78422663/171833135-07f2361f-c55f-4154-b080-a72faa54338a.png) | ![Screenshot from 2022-06-03 15-35-30](https://user-images.githubusercontent.com/78422663/171833167-881bb4d3-99b8-43ff-bd94-58760c5eb4f9.png)|
| Issue 4:Footer>>Different Font color is used  @ copy right.| ![Screenshot from 2022-06-03 15-49-38](https://user-images.githubusercontent.com/78422663/171833980-32e45cdb-2d37-4622-97b3-4eea484c12ac.png)| Font color: #A6B5BA |
| Issue 5:Sign In>> Margin is missing between sign In and Welcome back! Please enter your details |![Screenshot from 2022-06-03 17-30-42](https://user-images.githubusercontent.com/78422663/171847522-2090126a-c1f3-4c08-b6f3-a6b1e5aa05b4.png) | ![Screenshot from 2022-06-03 17-32-55](https://user-images.githubusercontent.com/78422663/171847778-348d702e-81bc-4a01-a96f-4fa43c134af3.png)|

**Comment by Man0zZ** [comment]
@SauravSilwal10  @AbhishekSka This issue has been resolved. Please check it out.

cc @man-git007
cc @praweshsth

**Comment by SauravSilwal10** [comment]
@Man0zZ None of these bugs have been addressed. Please go through it again.

cc @man-git007 
cc @praweshsth
