### ISSUE TITLE
Using IATI Validator instead of buildling logics to check the data within the publisher? 

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#184]
Is it possible and feasible to use IATI validator API to validate the activity and organisation files within the IATI Publisher without developing any logic to validate the data? 

@k8hughes @andreaszenasidi @titiolukole @anjesh @man-git007

**Comment by k8hughes** [comment]
@akmiller01 and I spoke about this today - the validator API only goes as granular as activity level, it doesn't go down to elements but the logic for elements are all in the ruleset json in our github:
https://github.com/IATI/IATI-Rulesets/blob/version-2.03/rulesets/standard.json 
And then in theory, all of the field types are contained in the schema files: https://github.com/IATI/IATI-Schemas/blob/version-2.03/iati-activities-schema.xsd and https://github.com/IATI/IATI-Schemas/blob/version-2.03/iati-common.xsd and https://github.com/IATI/IATI-Schemas/blob/version-2.03/iati-organisations-schema.xsd

As much as possible it would be good that the publishing tool is taking its standard logic from here as these files remain the source of truth.  Is this what is currently happening?

**Comment by man-git007** [comment]
@k8hughes Thank you for the clarification on element validator API. We can use the ruleset from [https://github.com/IATI/IATI-Rulesets/blob/version-2.03/rulesets/standard.json](https://github.com/IATI/IATI-Rulesets/blob/version-2.03/rulesets/standard.json) for validating each element.

cc @praweshsth @sriza @Sanilblank
