### ISSUE TITLE
Results edit/add form

### ISSUE THREAD

**Issue by jenishshrestha** [younginnovations/iatipublisher#190]
- [x] Add and edit form of results activity element
- [x] Solve font issue (Arial font)
- [ ] Clean code app.ts file inside resources > assests > js

**Comment by man-git007** [comment]
@jenishshrestha What is the status of this issue?

**Comment by jenishshrestha** [comment]
> @jenishshrestha What is the status of this issue?

Could not get the third issue to work. Vue stops working if remove codes from app.ts.

**Comment by man-git007** [comment]
@titungdup lets look into this today

**Comment by man-git007** [comment]
@SauravSilwal10 Move this issue to backlog

**Comment by SauravSilwal10** [comment]
Please refer to this issue 

cc @jenishshrestha
