### ISSUE TITLE
#57 Bug: Any user is allowed to access all of the activities created by any user

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#193]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://stage.iatipublisher.yipl.com.np/
- Username: User_A
- Password: test1234

- Username: $username=%00;
- Password: test1234

### Steps ###
- Go to 
- https://stage.iatipublisher.yipl.com.np/activities/1
- https://stage.iatipublisher.yipl.com.np/activities/2
- https://stage.iatipublisher.yipl.com.np/activities/3
- https://stage.iatipublisher.yipl.com.np/activities/11
- https://stage.iatipublisher.yipl.com.np/activities/37

### Actual result ###
- User allowed to access to all of the activities which is not its own

### Expected result ###
- Activities which is only of its own is to be allowed to be accessible

https://user-images.githubusercontent.com/25945530/173503872-292198fa-e280-4bb3-9f26-b600933ebefa.mp4

**Comment by man-git007** [comment]
@SauravSilwal10 This issue seems to be fixed. Please check once.

cc @sriza

**Comment by SauravSilwal10** [comment]
Issue Fixed 
cc @man-git007 @sriza
