### ISSUE TITLE
#57 Bug: Activity details with large Activity title overflows over breadcrum

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#197]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://stage.iatipublisher.yipl.com.np/
- Username: $username=%00;
- Password: test1234

### Steps ###
- Create activity and set title of the Activity with 500 words
- Go back to activity detail Page 

### Actual result ###
- We could see full title present over the breadcrum and title of the activity
- Due to this upon edit of any element the Add more button is inaccessible

### Expected result ###
- Truncation of the title and breadcrum should occur after certain characters 

![image](https://user-images.githubusercontent.com/25945530/173764117-ea24d7ab-a24c-434b-a9c3-cbdc4ec31fbc.png)
![image](https://user-images.githubusercontent.com/25945530/173764176-93b80e77-7fd9-448a-93b0-35ab951dd2fd.png)

**Comment by man-git007** [comment]
@jenishshrestha @titungdup @SauravSilwal10 Does this issue still persist?

**Comment by SauravSilwal10** [comment]
Issue Fixed.
@man-git007 @jenishshrestha @titungdup
