### ISSUE TITLE
#57 Bug: Cancel button working as submission for the forms

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#198]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://stage.iatipublisher.yipl.com.np/
- Username: $username=%00;
- Password: test1234

### Steps ###
- Create/Edit activity for any element
- Make changes to the contents 
- hit Cancel 

### Actual result ###
- It gets saved instead of discarding changes

### Expected result ###
- Clicking cancel should discard changes

![image](https://user-images.githubusercontent.com/25945530/173765464-b84ba30a-f9b5-4a4e-864c-73ba2e9ba5b9.png)

**Comment by SauravSilwal10** [comment]
@sriza This has not been fixed. Please review again.


https://user-images.githubusercontent.com/78422663/178961264-5b510af6-3a30-4dfd-b7b5-ad2bea365a5f.mp4

cc @man-git007 @praweshsth

**Comment by man-git007** [comment]
@sriza Have we worked on this issue?

**Comment by sriza** [comment]
@man-git007 
We have already worked on this issue.

cc @SauravSilwal10 @AbhishekSka

**Comment by SauravSilwal10** [comment]
Issue fixed.

Cc @man-git007 @AbhishekSka @sriza
