### ISSUE TITLE
#57 Bug: 'iati-identifier'/'other identifier'>> Rule>>Element must not contain any of the symbols /, &, |  ?

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#200]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://stage.iatipublisher.yipl.com.np/
- Username: $username=%00;
- Password: test1234

### Steps ###
- From Activity listing>>Add activity/Other identifier
- Fill up required fields and over iati-identifier enter characters  /, &, | ?
- save

### Actual result ###
- These characters are accepted
![image](https://user-images.githubusercontent.com/25945530/173770586-eb885f55-ef07-44a8-aef0-221b84deb7ab.png)

### Expected result ###
- Field should be validated upon entering these characters

![image](https://user-images.githubusercontent.com/25945530/173770506-ccb63e2d-36e8-40c6-93db-5b7d9f5edffa.png)

**Comment by SauravSilwal10** [comment]
@sriza I think this issue has not been fixed yet. Please review again.


https://user-images.githubusercontent.com/78422663/176835406-376fba08-8f4e-4ced-ae53-922d6bf0cc88.mp4


cc @man-git007 @praweshsth

**Comment by man-git007** [comment]
@SauravSilwal10 Does the issue still persist?

cc @AbhishekSka

**Comment by SauravSilwal10** [comment]
Issue Fixed 
 cc @man-git007  @sriza @AbhishekSka
