### ISSUE TITLE
#57 Bug: Mutliple activity with same iati-identifier could be created upon larger payload

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#204]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://stage.iatipublisher.yipl.com.np/
- Username: $username=%00;
- Password: test1234

### Steps ###
- From Activity listing>>Add activity
- Fill up Narratives with 500 words
- Identifiers
- Click submission button multiple times

### Actual result ###
- Same activity could be created  multiple times

### Expected result ###
- backend validation over the iati with same Iati identifier and click block over the submission button  

https://drive.google.com/file/d/1JyEmdcxQNNilOc27v_psdET3Q2hkVlpQ/view

**Comment by man-git007** [comment]
@AbhishekSka @SauravSilwal10 If this issue has been resoled, let's close this issue

**Comment by SauravSilwal10** [comment]
Issue Fixed 
 CC @man-git007 @AbhishekSka
