### ISSUE TITLE
#57 Bug: After pressing the edit button, the actual title becomes a dummy title.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#205]
Context

- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Hari
- Password: 12345678

Steps
- Create an activity.
- Go to activity detail Page
- Click the collaboration-type >> select the drop-down >> click the save publishing setting button.
- Go back to the activity detail Page>> click the edit button of collaboration-type.

Actual result
- A dummy title is displayed on the screen.

Expected result
- The actual title should be displayed on the screen.

https://user-images.githubusercontent.com/78422663/173996851-f9dee875-3397-4522-af15-1bf074cc5d50.mp4

**Comment by man-git007** [comment]
@SauravSilwal10 Seems to be fixed. Please check once

cc @AbhishekSka

**Comment by SauravSilwal10** [comment]
Issue Fixed 

cc @man-git007 @AbhishekSka
