### ISSUE TITLE
#57 Bug: Description>> Rules mentioned over the iati standard missing

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#206]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
- Username: $username=%00;
- Password: test1234

### Steps ###
- Activity >> Description
- Add Narratives and Lang fields
- save the pages

### Actual result ###
-  Validation for @type field

### Expected result ###
- As per IATI Standard Rules:" The type of description being provided. This is not required if only one general description of the activity is reported."

**Comment by SauravSilwal10** [comment]
@Man0zZ and @sriza Since we are prioritizing the bug for now. So we are closing this issue for now. Once the priority bugs have been resolved, we will reopen this issue.

cc @AbhishekSka  @man-git007 @praweshsth
