### ISSUE TITLE
#57 Bug: Finance type>> Drop down option are missing in Default Finance type.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#207]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
https://stage.iatipublisher.yipl.com.np/
- Username: Hari
- Password: 12345678

| **Steps**      | **Actual result** | **Expected result**    |
| :---        |    :----:   |          ---: |
|Issue: acitvity>>Default Finance type| Drop-down options are missing in the default finance type![Screenshot from 2022-06-16 11-46-41](https://user-images.githubusercontent.com/78422663/174002224-3622c161-8ba9-482b-91fa-625475bdcc63.png)| All Drop down options should be mentioned  As per IATI Standard.https://iatistandard.org/en/iati-standard/203/codelists/financetype/ |

**Comment by SauravSilwal10** [comment]
@praweshsth  and @man-git007 dai What should be done with the IATI Standard's (withdrawn) choices? Should they be included in drop-down options or not?
![Screenshot from 2022-06-16 11-55-09](https://user-images.githubusercontent.com/78422663/174003280-f44cd9d0-0831-4cc3-a479-92ceafe1a53c.png)

**Comment by praweshsth** [comment]
Don't include 'Withdrawn' options.

**Comment by SauravSilwal10** [comment]
@sriza The drop-down option contains items that have been withdrawn from the IATI standard. Thus, kindly review once again.

![Screenshot from 2022-07-01 14-09-08](https://user-images.githubusercontent.com/78422663/176855776-c3c73b07-d4d7-4c6b-9004-1af60ceafee3.png)

![Screenshot from 2022-07-01 14-08-31](https://user-images.githubusercontent.com/78422663/176855790-23228374-2cf9-477b-b2f4-269cd5c43fdc.png)

cc @praweshsth  @man-git007

**Comment by man-git007** [comment]
@sriza What is the status for this issue?

**Comment by sriza** [comment]
@man-git007 This issue has already been fixed and can be closed.

cc @SauravSilwal10

**Comment by SauravSilwal10** [comment]
Issue Fixed 

cc @man-git007 @sriza
