### ISSUE TITLE
#57 Bug: Other activities always redirect  to the activities 1 page after clicking an edit button.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#209]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Hari
- Password: 12345678

Steps

- Create an activity.
- Go to activity detail Page
- Click the edit button.

Actual result
- Redirect to the activities 1 page

Expected result
- Should redirect to the actual activities page.

https://user-images.githubusercontent.com/78422663/174019762-97e3967b-fb4f-44bf-a19f-ed3f0f9d2c4a.mp4

**Comment by man-git007** [comment]
@AbhishekSka @SauravSilwal10 Can we close this issue?
