### ISSUE TITLE
#57 Bug: Issue over dropdowns

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#210]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://stage.iatipublisher.yipl.com.np/
- Username: $username=%00;
- Password: test1234

### Steps ###
_Issue 1_
-  Upon the selection of  dropdowns on the attribute elements such as
 - @xml:lang 
 - @type
 - @code

_Issue 2_
- click on the dropdown 
- Try to type for the item to be selected 

### Actual result ###
_Issue 1_
- Selected elements are not highlighted

_Issue 2_
- the cursor over the search text is unavailable

### Expected result ###
_Issue 1_
- Selected elements are to be highlighted to notify user about the selection 

_Issue 2_
- Upon activating the dropdown cursor is to be made available for the quick search

**Comment by man-git007** [comment]
@SauravSilwal10 Does the issue still persist? If yes @Man0zZ @jenishshrestha @titungdup Can you look into this?

cc @sriza

**Comment by SauravSilwal10** [comment]
Issue fixed 
@man-git007
