### ISSUE TITLE
#57 Bug: Upon clicking on any of the tooltip icon on the field, element page is getting saved

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#211]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://stage.iatipublisher.yipl.com.np/
- Username: $username=%00;
- Password: test1234

- For already created activity

### Steps ###
- Edit or goto 
- https://stage.iatipublisher.yipl.com.np/activities/58/description
- Make changes  
- then click on ![image](https://user-images.githubusercontent.com/25945530/174049796-0f665d46-40fc-4020-85d8-cb7b3966f85c.png)

### Actual result ###
- Page gets saved and redirected to details page

### Expected result ###
- Only tool tip is to be displayed

https://user-images.githubusercontent.com/25945530/174050683-f5393ad6-e2c4-4972-b64a-d45f5e822185.mp4

**Comment by man-git007** [comment]
@AbhishekSka Does the issue still persist? if not let's close this issue

**Comment by man-git007** [comment]
@AbhishekSka @SauravSilwal10 Can we close this issue?

**Comment by titungdup** [comment]
@man-git007 Issue resolved.
