### ISSUE TITLE
#57 Bug: Recipient country >> Recipient region IATI standard rule hasn't been followed.

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#212]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://stage.iatipublisher.yipl.com.np/
- Username: $username=%00;
- Password: test1234

### Steps ###
- Create/Edit activity 
- Fill up required fields 
- On the percentage field enter say 80 or save without entering any data.
- Save

### Actual result ###
- Page gets saved.

### Expected result ###
- We must follow the IATI standard regulation.
- Please click the link in the text below for the rule.
https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/recipient-country/
https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/recipient-region/

**Comment by SauravSilwal10** [comment]
@Man0zZ  and @sriza Since we are prioritizing the bug for now. So we are closing this issue for now. Once the priority bugs have been resolved, we will reopen this issue.

cc @AbhishekSka  @man-git007  @praweshsth

**Comment by man-git007** [comment]
@SauravSilwal10 If the issue still persist then lets keep this in a backlog

cc @sriza @praweshsth

**Comment by SauravSilwal10** [comment]
okay 
@man-git007

**Comment by SauravSilwal10** [comment]
please refer to this issue #489

**Comment by man-git007** [comment]
@praweshsth Need to discuss about this rule.
