### ISSUE TITLE
#57 Bug: Recipient country>> On activity detail, card looks empty with minimum data fill up

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#213]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://stage.iatipublisher.yipl.com.np/
- Username: $username=%00;
- Password: test1234

### Steps ###
- Recipient country>>Only fill up code field
- Save the element
- Check over "recipient_country" card on the details 

### Actual result ###
- The content is displayed as 
![image](https://user-images.githubusercontent.com/25945530/174058597-4daf597f-f261-4199-bb64-bb45465e5f60.png)

### Expected result ###
-  NTD

**Comment by man-git007** [comment]
@AbhishekSka @SauravSilwal10 Does the issue still persist?

cc @Man0zZ

**Comment by SauravSilwal10** [comment]
Issue fixed 
cc @AbhishekSka @man-git007 @Man0zZ
