### ISSUE TITLE
#57 Bug:  UI Issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#214]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Hari
- Password: 12345678
- For already created activity

| **Steps**      | **Actual result** | **Expected result**    |
| :---        |    :----:   |          ---: |
|Issue 1: Activity Detail Page >>Icon doesnot match with the design **(DONE)** |![Screenshot from 2022-06-17 11-14-14](https://user-images.githubusercontent.com/78422663/174231516-a25eba35-dbb6-47b2-8913-9cb32337832c.png)|![Screenshot from 2022-06-17 11-14-02](https://user-images.githubusercontent.com/78422663/174231709-8f46df9d-c7e9-41c8-899a-44ce2616ff7a.png)|
| Issue 2:  Activity Detail Page (DONE)>>Difference between design and implementation **(DONE)**|![Screenshot from 2022-06-17 11-21-08](https://user-images.githubusercontent.com/78422663/174232190-69347140-89ef-4263-a274-abb4bbddcc7d.png) |![Screenshot from 2022-06-17 11-20-26](https://user-images.githubusercontent.com/78422663/174232122-7b55db9e-1c2c-4ad2-97c0-593074836e05.png)|
| Issue 3:  Activity Detail Page >>Difference between design and implementation **(DONE)** |![Screenshot from 2022-06-20 10-19-15](https://user-images.githubusercontent.com/78422663/174525982-1dd2dcba-45fe-4b89-a879-8f2e6e4c5db3.png)|![Screenshot from 2022-06-20 10-15-19](https://user-images.githubusercontent.com/78422663/174526030-1f2afedc-5ad1-4f66-8142-018b98ca0f54.png)|
| Issue 4:  Activity Detail Page >> Tag NO margin between line and vocabulary **(DONE)** |![Screenshot from 2022-06-20 11-53-09](https://user-images.githubusercontent.com/78422663/174535902-5b9c9795-2520-4379-a571-01e4ce409297.png)|There should be proper margin between them.|
| Issue 5:  Activity Detail Page >> Tag Pageoverflow after selecting a drop down options.|https://user-images.githubusercontent.com/78422663/174536694-0e3c2627-72b7-49f9-9cf8-d8594c50c83b.mp4|There should not be an overflow on the page.|
| Issue 6:  Activity Detail Page >> Humanitarian scope Side content disappear for long time after a refresh.**(DONE)**|https://user-images.githubusercontent.com/78422663/174741385-dfc63c0c-e547-4676-ad48-c390c386249a.mp4|This process should be optimized.|
| Issue 7:  Activity Detail Page >>activity-identifier/Other Identifier |![image](https://user-images.githubusercontent.com/25945530/175016431-b3291d78-7725-4799-9077-790f7ccc3cb2.png)![image](https://user-images.githubusercontent.com/25945530/175016886-0a115165-43c3-4de6-adab-993fac96de55.png) |Fields could be made to the same row 
| Issue 8:  Activity title page(**DONE**) |what is activity tooltip display wrong information![Screenshot from 2022-06-23 11-05-15](https://user-images.githubusercontent.com/78422663/175221037-a2b1f67d-570e-4178-b20c-826acb341f9d.png)| https://docs.google.com/document/d/16G0tjT1iprHO2jIp3cn9cyFC1HGnt8FUl5zWXaoWldo/edit#
| Issue 9:  Activity Detail Page **(DONE)** | default-finance-type does not match with the design.![Screenshot from 2022-06-24 12-47-23](https://user-images.githubusercontent.com/78422663/175481180-fa39c3a7-af44-4f9a-b47d-466f5d61db1f.png) |![Screenshot from 2022-06-24 12-44-41](https://user-images.githubusercontent.com/78422663/175481003-21a712e3-b29d-4bbb-bd5d-83fe429dea1b.png)|
| Issue 10:  Activity Detail Page **(DONE)** | Padding between narrative and  @xml lang![Screenshot from 2022-06-24 15-52-57](https://user-images.githubusercontent.com/78422663/175514021-8c82250f-00b7-49be-aefc-a07f4e99d645.png)   |  Padding between narrative and @ xml lang should be same |
| Issue 11:  Activity Detail Page >>Description |Bold line in Description![Screenshot from 2022-06-27 11-28-25](https://user-images.githubusercontent.com/78422663/175868113-a2cbee59-ad3a-45a7-a8f5-2f76ee3a9280.png)|Description element must correspond to its design.|
| Issue 12:  Activity Detail Page >>Title **(DONE)** |Uneven spacing in title ![Screenshot from 2022-06-28 11-49-05](https://user-images.githubusercontent.com/78422663/176105023-68190755-0c9f-4169-9d22-2a8b88e780c9.png)|![Screenshot from 2022-06-28 11-52-06](https://user-images.githubusercontent.com/78422663/176105439-60afcd17-3c31-42b4-8b3e-c808ef3579d1.png)|
| Issue 13:  Activity Detail Page >>recipient-region **(DONE)**| Vocabulary and percentage is not aligned properly.![Screenshot from 2022-06-28 14-11-47](https://user-images.githubusercontent.com/78422663/176132862-af903bac-c7ae-4d52-9257-3d9278d06372.png)|"vocabulary" and "%" should be in the same line.|
| Issue 14:  Activity Detail Page >>other-identifier| shape of the border line ![image](https://user-images.githubusercontent.com/25945530/176359411-40bace76-f895-4763-bea1-751b44a89c4d.png)|![image](https://user-images.githubusercontent.com/25945530/176359885-d546cd1e-f173-4de2-aedc-8eb8821bdbde.png)|
| Issue 15:  Activity Detail Page >>Activity date **(DONE)** |  Title of element and tooltip has not aligned in the same line![Screenshot from 2022-06-29 11-28-42](https://user-images.githubusercontent.com/78422663/176360505-21e7ec0c-426f-41c9-b3dc-3cf51bacc61f.png)| ![Screenshot from 2022-06-29 11-29-45](https://user-images.githubusercontent.com/78422663/176360982-abfaa9f4-898c-41f1-8135-224a090debef.png)|
| Issue 16:  Activity Detail Page >>Legacy system>> Related activity **(DONE)**|   Element are not bold ![Screenshot from 2022-06-30 11-08-32](https://user-images.githubusercontent.com/78422663/176599094-a840808b-4158-4bea-acab-11512cb9fef7.png)| Shoud be bold.
| Issue 17:  Activity Detail Page >>Other-identifier **(DONE)**| attributes are aligned properly![Screenshot from 2022-06-30 11-17-14](https://user-images.githubusercontent.com/78422663/176600238-bb6480cd-d334-4c37-a5f3-5d6b8f60fe4d.png)| Should be aligned properly.
| Issue 18:  Activity Detail Page >>Other-identifier **(DONE)**|Difference between design and implementation![Screenshot from 2022-07-07 13-51-44](https://user-images.githubusercontent.com/78422663/177723992-240f617c-35cd-4782-b6b0-01bf5263b709.png)|![Screenshot from 2022-07-07 13-49-22](https://user-images.githubusercontent.com/78422663/177723582-ef31637b-2cf2-43b6-b186-9eb1bc90bc15.png)
| Issue 19:  Activity Detail Page >>Sidebar _ working as -|https://user-images.githubusercontent.com/78422663/177725181-bd09384f-b4c0-439f-8cb7-64552c510742.mp4|Sidebar search functionality should work properly.
| Issue 20:  Activity Detail Page >>Capital spend **(DONE)**| Unsuitabe card arrangement![Screenshot from 2022-07-07 14-39-10](https://user-images.githubusercontent.com/78422663/177733684-84bc8841-f7b3-4e6d-a74b-16a4bb82ba53.png)|Suitable card arrangment can be done.
| Issue 21:  Activity Detail Page >> tooltip guidance link is not working|https://user-images.githubusercontent.com/78422663/178419429-1fc90d8e-271f-4ff5-baa6-f83ce35d860d.mp4|tooltip guidance link should work properly.
| Issue 22:  Activity Detail Page >> other-identifier override in activity detail page **(DONE)**|![Screenshot from 2022-07-14 10-45-18](https://user-images.githubusercontent.com/78422663/178909254-fe89d417-a4a6-4f3d-9f21-44b9235e511c.png)|should not override
| Issue 23:  Activity Detail Page >> Title Unwanted delete button appears on title edit form|![Screenshot from 2022-07-15 10-12-41](https://user-images.githubusercontent.com/78422663/179150730-24b51a25-9dc0-477b-b5fe-23f8e72dfd1d.png)|Unwanted delete button should be removed.
| Issue 24:  Activity Detail Page >> Conditions Design Break down **(DONE)**|![Screenshot from 2022-07-22 11-47-20](https://user-images.githubusercontent.com/78422663/180373670-2f46e1bf-a675-415d-b9da-363b4d227804.png)|Implementation should match the design.
| Issue 25:  Activity Detail Page >> Other-identifier tooltip is missing|https://user-images.githubusercontent.com/78422663/180704678-65ff29f2-3c0f-4c7e-a7e1-54723e1d3a0f.mp4|Tool tip should be present.
| Issue 26:  Activity Detail Page detail core element is missing form sidebar | https://user-images.githubusercontent.com/78422663/180998822-8c93b9d2-0b1f-4139-8948-e1cc94238563.mp4|Core element should be present .

**Comment by SauravSilwal10** [comment]
@praweshsth @nirvanalama  Could you please verify?

**Comment by nirvanalama** [comment]
@shreyaydi

**Comment by shreyaydi** [comment]
Issue 7 - "other Identifier" element yet to be fixed
![image](https://user-images.githubusercontent.com/47111065/175904050-904b9f37-1969-4978-82c2-ee7fa81b92e2.png)

Issue 8 - Yet to be fixed
Issue 9 - Yet to be fixed

**Comment by Man0zZ** [comment]
@SauravSilwal10 @AbhishekSka i have resolved issue no. 8, 9, 10.

cc @man-git007
cc @praweshsth

**Comment by shreyaydi** [comment]
@Man0zZ Also for issue 2, the langauge should be written in their full form, for example, "english" and not "en"

**Comment by AbhishekSka** [comment]
@Man0zZ 
- Issue 10 padding between the field and Label has been removed which should be there.
Expected
![image](https://user-images.githubusercontent.com/25945530/176357268-387665fd-fe9c-447f-9df0-db96ca955bdc.png)
Actual
![image](https://user-images.githubusercontent.com/25945530/176357333-733fbda4-280e-40e6-a878-d6587ebf3474.png)


@nirvanalama @shreyaydi 
- Issue 9>> since there are labels with longer names such as "default-finance-type","country-budget-items" and "humanitarian-scope". These are hard to be contained in single line, thus has multi lined. However this causes inconsistency with design with the containers . Should we leave as it is or would be finding alternative solution for it?
![image](https://user-images.githubusercontent.com/25945530/176358070-47cdddaa-f954-4560-aa86-df6fde74fecd.png)

**Comment by SauravSilwal10** [comment]
@manoz and @sriza  There are still a lot more problems to be resolved. Please go through it one again.

cc @man-git007  and @praweshsth

**Comment by man-git007** [comment]
@Man0zZ  Does the issue still persist? If yes lets work on it. If not @SauravSilwal10 Please close the issue.

cc @sriza

**Comment by man-git007** [comment]
@SauravSilwal10 Can we close this issue?

**Comment by SauravSilwal10** [comment]
Issue Fixed 
@man-git007
