### ISSUE TITLE
#57 Bug: Activity>>Description Back button redirect to Activity Title page.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#217]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Hari
- Password: 12345678
- For already created activity

Steps 
- Activity detail page>>Description page
- Click the back button

Actual Result
- Redirect to the Activity Title page.

Excepted Result
- Should Redirect to Activity Detail Page.

https://user-images.githubusercontent.com/78422663/174250072-f466b96d-b518-4fcf-b3df-64e3b837cfaf.mp4

**Comment by man-git007** [comment]
@SauravSilwal10 can we close this issue?
