### ISSUE TITLE
#57 Bug: Activity>>Condition Language attribute displayed without language

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#219]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Hari
- Password: 12345678
- For already created activity

Steps
- Activity detail page>>Condition
- Enter attached

Actual Result
- Language attribute gets displayed.

Excepted Result
- Language attribute should not display.

https://user-images.githubusercontent.com/78422663/174525127-edab6a2b-f5fb-4016-8996-cfac86c46cee.mp4

**Comment by man-git007** [comment]
@sriza Can we look into this?

**Comment by SauravSilwal10** [comment]
Issue fixed 

cc @man-git007 @sriza

**Comment by man-git007** [comment]
@SauravSilwal10 Can we close this issue?
