### ISSUE TITLE
#57 Bug: Activity Title Page Next Button and Previous  Button are enabled if user has only one page.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#220]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Hari
- Password: 12345678
- For already created activity

Steps
-Click the Next and Previous Button.

Actual Result
- Next and Previous Button is enabled.

Excepted Result
- Next and Previous Buttons should be disabled. 

https://user-images.githubusercontent.com/78422663/174274341-d2856590-1bf3-44b6-ad90-736a14a500e0.mp4

**Comment by SauravSilwal10** [comment]
@sriza Here's a new problem. An unwanted message is flickering at the side of the prev button. Please check it.

![Screenshot from 2022-07-01 15-07-49](https://user-images.githubusercontent.com/78422663/176866559-3f251c4e-a6fa-46cd-b271-cb8700a20781.png)

cc @praweshsth @man-git007

**Comment by man-git007** [comment]
@SauravSilwal10 Does the issue still persist? If not lets close this issue

**Comment by SauravSilwal10** [comment]
Issue Fixed
 cc @man-git007
