### ISSUE TITLE
#57 Bug: Activity>>Default-Flow-Type Drop down options that were removed from the IATI standard have been reintroduced.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#223]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Hari
- Password: 12345678
- For already created activity

Steps
- Activity detail page>>Default flow type
- View the drop down option.

Actual Output
- 10 ODA
- 20 OOF
- 21 Non-export credit OOF
- 22 Officially supported export credits
- 30 Private Development Finance
- 35 Private Market
- 36 Private Foreign Direct Investment
- 37 Other Private flows at market terms
- 40 Non flow
- 50 Other flows

Excepted Output
- 10 ODA
- 21 Non-export credit OOF
- 22 Officially supported export credits
- 30 Private Development Finance
- 36 Private Foreign Direct Investment
- 37 Other Private flows at market terms
- 40 Non flow
- 50 Other flows

**Comment by SauravSilwal10** [comment]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Hari
- Password: 12345678
- For already created activity

Steps 
- Activity detail page>>Default flow type
- View the drop down option.

Actual Output
- 10	ODA	
- 20 	OOF	
- 21	Non-export credit OOF	
- 22	Officially supported export credits	 
- 30	Private Development Finance	
- 35    Private Market
- 36	Private Foreign Direct Investment	
- 37	Other Private flows at market terms	
- 40	Non flow
- 50	Other flows

Excepted Output
- 10	ODA	
- 21	Non-export credit OOF	
- 22	Officially supported export credits	 
- 30	Private Development Finance	
- 36	Private Foreign Direct Investment	
- 37	Other Private flows at market terms	
- 40	Non flow
- 50	Other flows

**Comment by man-git007** [comment]
@SauravSilwal10 @AbhishekSka Does the issue still persist?

**Comment by SauravSilwal10** [comment]
Issue fixed

cc @man-git007 @AbhishekSka
