### ISSUE TITLE
Understand and discussion on validation and publishing workflows

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#232]
This was our understanding of the publishing workflow including validation:

A. When user tries to publish an activity, the tool first checks:

1. If core elements are added and completed
2. If non-core elements are added and completed

Then the tool shows the error if they haven't added mandatory elements and also shows for better data quality to add core elements. The user can only go back and add mandatory elements and then again proceed to publish. 

B. User has completed mandatory elements and proceeds to publish, the tool will validate the activity file using validator and displays the error sent back from the validator. And user can not publish until those errors are taken care of. 

However, from today's conversation, we understand that even though the user has not added and completed mandatory elements or has added but not completed non-mandatory elements and there are errors provided by validator, user can still publish the activity. If it is so,

1. Do we need to inform user that they haven't added or completed mandatory elements? 
2. Do we need to show the user mandatory elements using the mandatory symbol? 

Please add your feedback on it and anything if I have missed in it.

@k8hughes @titiolukole @Rohini-IATI @man-git007 @nirvanalama

**Comment by praweshsth** [comment]
@k8hughes @titiolukole @Rohini-IATI we had discussion on this and we will be designing the flow as per the following validation and publishing flow:
![publish and validation workflow](https://user-images.githubusercontent.com/2421695/176375600-8732cb51-d32b-4cc2-9ee4-706282eef469.png)

@man-git007 @nirvanalama @anjesh

**Comment by k8hughes** [comment]
Users should be allowed to publish invalid data, but heavily encouraged and incentivised to publish valid data. 

Our suggested is that the options are simple and binary –
eg As a user, I can click to publish at any time, the tool will run a pre publishing validation report and tell me either.

My data is invalid, go back and fix it would be the main highlighted option most visible to the user, with smaller text that says “publish anyway” or something similar, with hover over info that states that my data may not appear in certain IATI tools if it is invlaid.

My data is valid, publish now

Adding any other rules to control publishing would create a second level of validation that will confuse users.
