### ISSUE TITLE
Fix listed issues 

### ISSUE THREAD

**Issue by jenishshrestha** [younginnovations/iatipublisher#233]
- [x] text area and input field do not align.
- [x] “Delete button” should according to the design
- [x]  Remove delete in the first (default) narrative box
- [x]  Show pop-up “Are you sure you want to delete this?”
- [x]  Can’t add more after 2 boxes on the form - Seems its working correctly.
- [x]  In elements panel use (-) hyphen not (underscore)
- [x]  Add icon in activity detail title (Form title new design with dynamic icon, dynamic title, dynamic status)
- [x] Element name should be same in the element panel, detail page card and form.

#235

===================================================================================
### Issue ###

- [x] #249

**Comment by man-git007** [comment]
@jenishshrestha @SauravSilwal10 What is the status of this issue?

**Comment by SauravSilwal10** [comment]
Issue Fixed 
cc @man-git007 @jenishshrestha
