### ISSUE TITLE
#148 Bug:The same reset password URL can be used repeatedly by the user to reset their password.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#234]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Pub_6

Steps
1. Click the reset button>> enter a valid email>> a reset password URL appears in Gmail
2. Open Gmail and click the URL and reset the password.
3. Repeat step 2 numerous times.

Actual result
- Password gets reset and redirect to the activity page.

Expected result
- "This password reset token is invalid." should be displayed as an error message.

https://user-images.githubusercontent.com/78422663/174949406-a029ce1d-8580-4527-99f3-1335bb60862c.mp4

**Comment by man-git007** [comment]
@sriza Have we fixed the issue? If not let's fix this today.

cc @SauravSilwal10

**Comment by SauravSilwal10** [comment]
Issue fixed 
Cc @man-git007 @sriza
