### ISSUE TITLE
#57 Bug:On the fields with percentage, user could enter unlimited numbers of 0

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#237]
### Context ###
- Desktop
- Chrome 102.0.5005.61 

### Preconditon ###
https://stage.iatipublisher.yipl.com.np/
- Username: publisher 3
- Password: test1234

### Steps ###
- Activity>>
 - recipient_region
 - sector
 - country_budget_items
 - recipient_country
 - recipient_region
 - capital_spend
- Enter the longest possible ' 0 ' 

### Actual result ###
- Activity detail page viiew is overflowed with 0

### Expected result ###
-  Upon entering the number of 0, it should be truncated to single 0 

![image](https://user-images.githubusercontent.com/25945530/175011796-0399076e-41f6-4614-8540-1ebea5489b7a.png)

**Comment by sriza** [comment]
@SauravSilwal10 
Further validation considering the cases of decimal digits has been made. Please have a look.

cc @man-git007 @praweshsth

**Comment by SauravSilwal10** [comment]
@sriza As soon as the user types 0.000000, the issue persists. Can't we seek a different approach?


https://user-images.githubusercontent.com/78422663/176870624-445b6cd9-c60b-4e73-8d59-e78d2cf26be6.mp4

cc @praweshsth @man-git007

**Comment by SauravSilwal10** [comment]
@sriza The problem is still there.Please review again.

![Image](https://user-images.githubusercontent.com/78422663/180367353-813c58c6-387b-4361-b72c-fd14d105da44.png)

cc @man-git007 @praweshsth

**Comment by man-git007** [comment]
@sriza and @Sanilblank  Can we look into this?

cc @SauravSilwal10

**Comment by sriza** [comment]
Closed on halt. Will open if will be working on this issue.
