### ISSUE TITLE
Design sign up flow

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#24]
Design sign up flow (include notifications design as well)

- [ ] Organisation is not registered in IATI Registry
- [x] Organisation is registered in IATI Registry

For reference, check https://github.com/younginnovations/iatipublisher/issues/8

**Comment by praweshsth** [comment]
@andreaszenasidi Ok.

**Comment by andreaszenasidi** [comment]
@praweshsth this is approved.

**Comment by praweshsth** [comment]
thank you @andreaszenasidi
