### ISSUE TITLE
#57 Bug: Other Identifier>> Issues over the attributes ,fields and save button

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#240]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: publisher3
- Password: test1234

| **Steps**      | **Actual result** | **Expected result**    |
| :---        |    :----:   |          ---: |
| Issue 1: check for Delete button over "References" Attribute   |     Delete button over "References" Attribute is missing even after multiple Owner org addition ![image](https://user-images.githubusercontent.com/25945530/175019141-f619fce0-5b62-493c-9b12-0fb79bf82b69.png)   |  Delete button should be visible iff user has added more than Owner org    |
| Issue 2: Label of References           |    ![image](https://user-images.githubusercontent.com/25945530/175019496-88616a53-2d44-4c63-b5eb-3af7aba01813.png)     |     Label for the References should be "@ref"             |
| Issue 3: Other idetifier>>Fill up @type from dropdown>>Save           | ![image](https://user-images.githubusercontent.com/25945530/175021919-092b8535-6e0d-43a5-9c21-1f78adfae4e9.png)
![image](https://user-images.githubusercontent.com/25945530/175021965-77404e85-473c-40ce-b547-2298e9a5deb4.png)   |     Saved data over field on @type is to be displayed             |
| Issue 4: Other idetifier>>Fill up @type from dropdown>>Save|  An wrong message is displayed  https://user-images.githubusercontent.com/78422663/175516457-86a790a2-18cd-4784-93b4-0a3abe36ae88.mp4|  A proper message should be displayed             |

**Comment by SauravSilwal10** [comment]
@sriza Issue 4 has not been fixed yet. Please review again.

https://user-images.githubusercontent.com/78422663/176876805-ac0ea29e-7015-4125-baba-2d432608e804.mp4

cc @man-git007 @praweshsth

**Comment by SauravSilwal10** [comment]
@sriza As mentioned the message that appears after pressing the save button has not yet been addressed. So please review again.


cc @man-git007 @praweshsth

**Comment by SauravSilwal10** [comment]
@sriza as the arrangement of the label field has not been fixed. So please review again.

**Comment by man-git007** [comment]
@sriza Have we fixed this issue? If this is related to UI @jenishshrestha @Man0zZ Can you guys look into this?

cc @SauravSilwal10

**Comment by titungdup** [comment]
@man-git007 All issues resolved. Closing it.
