### ISSUE TITLE
57-activity-page-bug-fix

### ISSUE THREAD

**Issue by Man0zZ** [younginnovations/iatipublisher#244]
- [x] #197 
- [x] #199 
- [x] #216 
- [x] #217 
- [x] #225 
- [x] #228 
- [x] #241

**Comment by Man0zZ** [comment]
@SauravSilwal10 @AbhishekSka This issues has been resolved. Please check it out.

cc @man-git007
cc @praweshsth

**Comment by AbhishekSka** [comment]
Issues fixed @Man0zZ 

cc @man-git007
cc @praweshsth

**Comment by man-git007** [comment]
Closed manually.
