### ISSUE TITLE
tag>>Uneven delete button.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#253]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password:12345678
- for created activity

steps
- Activity >> tag 
- Add more tag 

Actual Result
- An unnecessary Delete button appears.

Expected Result
- Delete should appear as per requirements 

https://user-images.githubusercontent.com/78422663/175518938-9dcfaf03-1bfb-4b83-b53b-4df62fe35581.mp4

**Comment by man-git007** [comment]
@SauravSilwal10 @jenishshrestha What is the status of this issue?

**Comment by titungdup** [comment]
@man-git007 Issue resolved.
