### ISSUE TITLE
#57 Bug:The message "The selected code does not exist" appears whenever the user selects a drop-down option from default-finance-type.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#254]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password:12345678
- for created activity

steps
- Activity >>default-finance-type
- select drop down 625 
- click save button

Actual Result  
- This error " The selected code does not exist" displays on the screen.

expected Result
- should redirect to the activity detail page.

https://user-images.githubusercontent.com/78422663/175524734-73656c70-f5e6-45e0-8dd2-99d706303254.mp4

**Comment by SauravSilwal10** [comment]
@sriza The drop-down option contains items that have been withdrawn from the IATI standard. Thus, kindly review once again.

![Screenshot from 2022-07-01 14-09-08](https://user-images.githubusercontent.com/78422663/176856778-46a00153-a2bd-4a73-b6c7-183eca59f463.png)

![Screenshot from 2022-07-01 14-08-31](https://user-images.githubusercontent.com/78422663/176856806-2693f9c9-06cf-4636-a58a-b13c87906bef.png)

cc @praweshsth @man-git007

**Comment by sriza** [comment]
@SauravSilwal10 
The dropdown list is now updated with removal of withdrawn codes. Please test it again.
