### ISSUE TITLE
#57 Bug:Activity-Date>> An unwanted information is displaying in activity detail page.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#266]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password:12345678
- for created activity

steps
- Activity >>activity-date 
- select type >> select ISO-date >> enter narrative >> select lang
- click save button

Actual Result
- Unwanted information .i,e description is displayed on the activity detail page.

Expected Result
- Unwanted information shouldn't display.

https://user-images.githubusercontent.com/78422663/176173533-3bed62c9-98e4-4dfd-bef8-ccaa011fcba9.mp4

**Comment by Man0zZ** [comment]
@SauravSilwal10 @AbhishekSka This issue have been resolved. plz check it out.

cc @man-git007
cc @praweshsth

**Comment by man-git007** [comment]
@SauravSilwal10 Please check the fix

**Comment by SauravSilwal10** [comment]
Issue fixed 

cc @man-git007
