### ISSUE TITLE
#57 Bug:Default-tied-status>> Activity-Status>> Recipient-region>> Collaboration-type>> default-flow-type attributes detail are missing from the activity detail page.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#275]
Context

- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password:12345678
- for created activity

steps
- Activity >>default-tied-status
- select code from drop-down options 
- click save button

Actual Result
- Element details in activity details are displayed as Key and vale format. However here only values are being displayed and keyword are not

Expected Result
- Element details in activity details are displayed as Key and vale format.

https://user-images.githubusercontent.com/78422663/176597272-5faf36c1-dc25-4d8a-a921-c1eedfd7c420.mp4

**Comment by SauravSilwal10** [comment]
@Man0zZ This issue hasn't been fixed yet. Please review again.


https://user-images.githubusercontent.com/78422663/177720859-8b44cede-9763-44ae-bd79-bae037e6db8e.mp4

cc @man-git007  @praweshsth

**Comment by Man0zZ** [comment]
@SauravSilwal10 @AbhishekSka We have disscussed this issue and we don't have to show attribute for half card because there is only one detail. Instead it will show for eg. "Vocabulary Not Available" if you don't fill up the field.

cc @man-git007
cc @praweshsth
