### ISSUE TITLE
Eslint fix

### ISSUE THREAD

**Issue by jenishshrestha** [younginnovations/iatipublisher#276]
Clone of #261
### ESLint Issues ###
- [x] #268 
- [x] #269 
- [x] #270

**Comment by SauravSilwal10** [comment]
@jenishshrestha  @sriza  Listed issues have not been fixed. Please go through it again.


https://user-images.githubusercontent.com/78422663/177276610-e9b6ec14-43ca-41b0-97b8-ed52420ae3ac.mp4


https://user-images.githubusercontent.com/78422663/177276690-72a07939-158e-42bb-9920-3f81cd878748.mp4

![Screenshot from 2022-07-05 13-29-19](https://user-images.githubusercontent.com/78422663/177276746-5fe0a8ae-8a93-4c35-bc34-121b90859cc0.png)
