### ISSUE TITLE
#57 Bug:Activity>> Budget Issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#288]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Hari
- Password: 12345678
- for created activity

**Issue 1: Budget Icon is missing on the edit page.**

Steps 
- Activity >> Budget 
- Click the edit button 

Actual Result 
- A budget icon is missing 

Excepted Result 
- The budget icon should be present in the edit form.
![Screenshot from 2022-07-05 10-31-51](https://user-images.githubusercontent.com/78422663/177251574-ecead65e-165b-4b07-8610-3f2b9e0e10da.png)

**Issue 2: Budget elements is in capital letter.**

Steps 
- Activity >> Budget 
- Click the edit button 

Actual Result 
- The budget title is in capital letters.

Excepted Result 
- The budget title should be in small letters.

![Screenshot from 2022-07-05 10-31-51](https://user-images.githubusercontent.com/78422663/177251944-7d8a74e7-121f-48f5-8bb4-ab73fd5bd16a.png)

**Issue 3: Delete button is missing from the edit form.**

Steps 
- Activity >> Budget 
- Click the edit button 

Actual Result 
- Delete button is missing from the edit form.

Excepted Result 
-  Delete button should be present.

https://user-images.githubusercontent.com/78422663/177253017-68c0b150-70e5-4b69-bc82-6eeb6b1cc74b.mp4

**Issue 4:An unwanted attribute is displayed in the Budget edit form**

Steps 
- Activity >> Budget 
- Click the edit button 

Actual Result 
![Screenshot from 2022-07-05 11-10-52](https://user-images.githubusercontent.com/78422663/177255644-6b5cc38d-36db-420c-bd69-d428cfe849d3.png)

Expected  Result 
![Screenshot from 2022-07-05 11-41-16](https://user-images.githubusercontent.com/78422663/177259223-b0955fe8-2ae4-4eb8-8f9f-3dbf5320fa3a.png)
- Amount attribute is not available in IATI standard document.
- please refer to this document as well(https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/budget/value/)

**Issue 5(Rule): User can save the form without entering the period end**

Steps 
- Activity >> Budget 
-Enter only period start and period end >> click the save button

Actual Result 
- Form gets saved.

Excepted Result 
- It violates the  IATI rules, proper validation should be in form.

https://user-images.githubusercontent.com/78422663/177260652-707aef50-dfaf-4638-9254-44fa250ae552.mp4

**Issue 6: No amount validation**

Actual Result 
![Screenshot from 2022-07-11 11-57-38](https://user-images.githubusercontent.com/78422663/178199980-7fc2eb6d-07d3-4628-8c0d-bdb9f70cd54b.png)

Excepted Result 
- A proper validation for the amount should be in the form

**Comment by sriza** [comment]
@SauravSilwal10 
Issue 4: Unwanted item displayed on budget form
- The amount field is the content of the budget-value tag
![image](https://user-images.githubusercontent.com/24825118/177948104-f50361ce-f2a5-4625-b08d-5e1d871cd901.png)

Issue 5:User can save without entering period end
- Required with and required validation and currently not included in the validation of forms.

cc @praweshsth @man-git007

**Comment by man-git007** [comment]
@SauravSilwal10 What is the status of this issue?

cc @sriza @praweshsth @Man0zZ @jenishshrestha

**Comment by SauravSilwal10** [comment]
Issue Fixed 

cc @sriza @praweshsth @Man0zZ @jenishshrestha @titungdup
