### ISSUE TITLE
#57 Bug:While loading any element form , form loads first then sidebar.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#290]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password: 12345678
- for created activity

steps 
- activity >> load any  element form

Actual Result 
- Form loads first then a sidebar

Excepted Result 
- Both forms and sidebar should load simultaneously

https://user-images.githubusercontent.com/78422663/177262498-bd1c5892-1616-4e82-a305-1deca764087f.mp4

**Comment by man-git007** [comment]
@SauravSilwal10 This seems to have been fixed. Can you verify this?

**Comment by SauravSilwal10** [comment]
Issue Fixed
cc @man-git007
