### ISSUE TITLE
#57 Bug:Activity>> Planned disbursement issue

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#292]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password: 12345678
- for created activity

**Issue 1 : Design Break down** 

Actual Result 
![Screenshot from 2022-07-06 17-29-51](https://user-images.githubusercontent.com/78422663/177543043-6c5d2ef5-2387-45ea-8068-efedc60201ae.png)

Excepted Result 
- Design should not break down

**Issue 2 : Delete Button is missing** 
 
Actual Result 
https://user-images.githubusercontent.com/78422663/177543513-94eb8325-aea1-4648-b4f0-e6deea902a9f.mp4

Excepted Result 
- Delete should be present in the Edit form.

 **Issue 3: Presence of capital as spend sub-element which is not in IATI standard** 

Steps 
- Activity >> Planned disbursement 

Actual Result 
![Screenshot from 2022-07-06 17-37-57](https://user-images.githubusercontent.com/78422663/177544114-6ef51e2c-70ad-479e-9046-51cfb9b002d6.png)
- Sub Element capital spend appears in the form.

**Issue 4(Rule): User can save the form without entering the period end and period start**
Steps
- Activity >>  planned disbursement
- Enter only  period start or period end 

Actual Result 
- The form gets saved.

Expected Result 
- A proper validation should be in form.

https://user-images.githubusercontent.com/78422663/177691969-576125d1-1bf3-4574-95ca-f38c30fa4246.mp4

**Issue 5: Uneven spacing between attributes on activity detail page**
Steps
- Activity >>  planned disbursement
- Add more planned disbursement 

Actual Result 
- Uneven spacing appears on the activity detail page.

Expected Result 
- There should be equal space between attributes.

https://user-images.githubusercontent.com/78422663/177697771-8375c406-0491-472a-bdae-1e06dccfabc7.mp4

**Issue 6: The tooltip is missing in the edit form.**

Actual Result 
![Screenshot from 2022-07-07 11-21-01](https://user-images.githubusercontent.com/78422663/177699296-46f90b18-97a3-4c5d-ab5a-d5ee1fd43114.png)

Excepted Result 
- The tooltip should be present in the edit form.

**Issue 7: The tooltip doesn't provide appropriate information**

Actual Result 
https://user-images.githubusercontent.com/78422663/177700500-117641ad-7612-4790-9a82-693410228ee2.mp4

Expected Result 
- A tooltip should provide appropriate information.

**Comment by SauravSilwal10** [comment]
@sriza The IATI standard is not followed by Planned Disbursement, which fails to present the necessary data in activity detail page. Please go through it one again.



https://user-images.githubusercontent.com/78422663/180203504-e69b5adc-ef64-4ef1-ab16-5827f08ef632.mp4

cc @man-git007 @praweshsth

**Comment by man-git007** [comment]
@SauravSilwal10 This issue seems to be fixed. Can you re-verify?

cc @Man0zZ @sriza

**Comment by SauravSilwal10** [comment]
Issue Fixed 

cc @man-git007 @sriza
