### ISSUE TITLE
Publish/ Validate flow

### ISSUE THREAD

**Issue by nirvanalama** [younginnovations/iatipublisher#300]
### **1. Success Flow without error:**

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=8144%3A118565&node-id=8174%3A136090&viewport=-152%2C-247%2C0.04&scaling=min-zoom&starting-point-node-id=8174%3A136090

- This flow is simple and straight forward that shows the results while publishing the activity with no validation errors.

- Start the flow by clicking on the **"Publish"** button.

- The system will inform that user that the data will be validated before publishing. Followed by a message that the activity has been successfully published.

- Press "R" on your keyboard to restart the flow.

### **2. Error Flow:**

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=8144%3A118565&node-id=8174%3A129576&viewport=-152%2C-247%2C0.04&scaling=min-zoom&starting-point-node-id=8174%3A129576&show-proto-sidebar=1

- Start the flow by clicking on the **"Publish"** button.

- There are two levels of validation first being the "Core elements not complete "and the second the errors found on IATI validator

- As suggested by the IATI team on the last meeting, we have highlighted "FIX ERRORS" and "FIX ISSUES" to encourage the users to correct the errors before publishing whereas "PUBLISH ANYWAY" is the secondary and less prominent button.

- The activity will be published with errors (shown on the top right)

- Click on the "show" button at the top right (next to the "7 errors found")  to expand the list of errors. 

- Click on the "hide" button  to collapse the list of errors. 

- Press "R" on your keyboard to restart the flow.

### **3. Error listing on edit page:**

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=8144%3A118565&node-id=8144%3A119133&viewport=-152%2C-247%2C0.04&scaling=min-zoom&starting-point-node-id=8144%3A119133

- This flow shows the listing of errors on the Activity edit page/form.

- Click on the "show" button at the top right (next to the "7 errors found")  to expand the list of errors.

**Comment by praweshsth** [comment]
@k8hughes @Rohini-IATI @titiolukole Is it possible to discuss it tomorrow?

**Comment by k8hughes** [comment]
1. Success floe without error - I think we need to tell the user they have no errors or it is confusing, when I watched the flow I thought validation had been forgotten because I was not informed of the validation result.  Can we add a step here?

2. This seems like a good solution.
3.  This also seems really good.

**Comment by praweshsth** [comment]
Thank you @k8hughes for you feedback. Also, from our meeting today, you had mentioned to inform user that the data is valid for publication if there are no critical errors and even though there are alerts and warnings. We will work on this and your feedback and also wait for the feedback from @Rohini-IATI

**Comment by nirvanalama** [comment]
@k8hughes @Rohini-IATI @praweshsth I've updated these according to the feedbacks

### 1. Success Flow without error
https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=8144%3A118565&node-id=8174%3A136090&viewport=-152%2C-247%2C0.04&scaling=min-zoom&starting-point-node-id=8174%3A136090

### 2. Error Flow
https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=8144%3A118565&node-id=8174%3A129576&viewport=-152%2C-247%2C0.04&scaling=min-zoom&starting-point-node-id=8174%3A129576&show-proto-sidebar=1

Here is a snapshot of what the pop-up would look like with no critical errors:

![Image](https://user-images.githubusercontent.com/57661914/178718944-570be5e4-e1bb-4d94-b433-2f6c11ba603c.png)

**Comment by k8hughes** [comment]
On the error flow we have various different possible cases:
1. Case shown here - core elements not filled - a user still needs to be able to check on the validator and not publish the data.  Current example only allowed me to use the validator if I was going to publish.
2. Case where core elements are filled but validation report has critial errors - we need to warn the user that their data won't appear on tools, but they can still publish anyway.
3. Case where core elements are filled, validation report shows no critial errors but some errors and warnings - let them know their activity is schema valid and will appear on tools if they publish it, but they can still improve the useability of the data.  Changes can be made after publication.

Cases 2 and 3 have the same user flow but just different copy in the alerts that come in the text boxes.

When we have all these cases covered can we pull out the copy into the copy docs Rohini is working on so we can work it out carefully?  Also this way we have it in the right format for translation.

**Comment by nirvanalama** [comment]
@k8hughes  @Rohini-IATI Thank you for your feedbacks. Here are the flows for the above mentioned cases:

### **2. Case where core elements are filled but validation report has critial errors** 

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=8144%3A118565&node-id=8543%3A133805&viewport=-152%2C-247%2C0.04&scaling=min-zoom&starting-point-node-id=8543%3A133805

### **3. Case where core elements are filled, validation report shows no critial errors but some errors and warnings**

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=8144%3A118565&node-id=8543%3A139238&viewport=-152%2C-247%2C0.04&scaling=min-zoom&starting-point-node-id=8543%3A139238


@praweshsth will have a discussion with you about the first case. Sure, we will add the content in the 'copy' document

**Comment by k8hughes** [comment]
for cases 2 and 3 shown here - there is no need for the 'Core elements complete' message - please remove this step.  This was just information for your team to highlight thou core elements are filled there can still be very different types of validation reports

**Comment by nirvanalama** [comment]
I. Case where core elements are filled AND NO ERRORS

II. Case where core elements are filled but validation report has critial errors

**Comment by k8hughes** [comment]
Designs are agreed, these are great!

**Comment by praweshsth** [comment]
Thank you @k8hughes
