### ISSUE TITLE
#57 Bug:Activity>>Result Issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#304]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password: 12345678
- for created activity

- [ ]  **Issue 1:Arranagement of label field**

Actual Result 
![Screenshot from 2022-07-08 13-20-24](https://user-images.githubusercontent.com/78422663/177941666-d4532866-9295-4268-b701-fa3aa938f2d4.png)

Expected Result 
- Should be in the same line.

- [ ]  **Issue 2: Language in Activity Detail page is shown as English even though user selects any other language in description whilst creating result**

Actual Result 
![Screenshot from 2022-08-02 10-12-54](https://user-images.githubusercontent.com/78422663/182291789-fae324d4-c75a-4486-887a-663b7ea17d53.png)
![Screenshot from 2022-08-02 10-14-35](https://user-images.githubusercontent.com/78422663/182291947-b7c7baf2-e686-4f43-a78b-7ef7a7f27ca5.png)

Expected Result
Inappropriate information should be displayed.

- [x]  **Issue 3: Data Duplication in Document link**

Actual Result 
https://user-images.githubusercontent.com/78422663/182293559-11770869-6208-47bc-9280-dd8e7144b38b.mp4

Excepted Result 
-Data duplication should be avoided.

- [x]  **Issue 4:When you enter a long text design gets breakdown** 

Actual Result 
![Screenshot from 2022-08-02 10-32-22](https://user-images.githubusercontent.com/78422663/182293926-7b22afb5-42b3-49f3-a4aa-b810ddde32c9.png)

Excepted Result
- Changes in text length should be reflected in the design.

- [x]  **Issue 5: Document-link URL is not working properly**

Actual Result 
https://user-images.githubusercontent.com/78422663/182295057-682e7dcc-675c-40e4-bd1e-2a601e4f7cc5.mp4

Excepted Result 
- Should work properly.

**Issue 6: Document-link URL open on the same page**

Actual Result 

https://user-images.githubusercontent.com/78422663/182295308-572ec247-93d0-4009-9586-06975572331d.mp4

Excepted Result 
- Form should open in the next tab

**Comment by AbhishekSka** [comment]
- [ ]  **Issue 1:Arranagement of label field** >>TBD
- [ ]  **Issue 2: Inappropriate information displayed on Activity Detail page**>>TBD

@sriza @jenishshrestha

**Comment by man-git007** [comment]
@AbhishekSka @SauravSilwal10 What is the status of this issue?

cc @Man0zZ @sriza @jenishshrestha

**Comment by SauravSilwal10** [comment]
Issue Fixed 

cc @man-git007
