### ISSUE TITLE
#57 Bug:Activity>>Transactions Issue

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#306]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password: 12345678
- for created activity

**Issue 1:Overflow issue** 

Actual Result
![Screenshot from 2022-07-26 13-18-55](https://user-images.githubusercontent.com/78422663/180949829-e4202f4c-d111-4a59-a869-406606c014cb.png)
Expected Result
- Page shouldn't overflow.

**Issue 2: Delete button is not working properly**
Actual Result 

https://user-images.githubusercontent.com/78422663/180955255-e17c5c78-c3d7-4347-8b7d-f76f3fab1207.mp4

Expected Result 
-Delete button should work properly

**Issue 3: Breadcrumb is missing** 

Actual Result 

![Screenshot from 2022-07-26 13-31-55](https://user-images.githubusercontent.com/78422663/180952376-699c0c6c-c5de-4d12-a4d3-74d69c28053b.png)

Excepted Result
- Breadcrumb should be dynamic

**Issue 4: Disbursement channel  drop down options is missing** 

Actual Result 

![Screenshot from 2022-07-26 13-51-51](https://user-images.githubusercontent.com/78422663/180956422-3cc45eec-1d20-4e26-8a8d-1bb75560fdea.png)

Expected Result 

- Drop down should be present .Please refer to IATI documentation(https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/transaction/disbursement-channel/)

**Issue 5: incorrect way to display value** 

Actual Result  
![Screenshot from 2022-07-26 13-36-54](https://user-images.githubusercontent.com/78422663/180953661-5829f934-77f8-4988-a0ae-1706407892ae.png)

Excepted Result 
![Screenshot from 2022-07-26 13-39-57](https://user-images.githubusercontent.com/78422663/180953868-06295b28-c32b-4ec4-be5f-04fa76111d55.png)

**Issue 6: Edit button is missing from each element in transactions detail page** 

Actual Result 

https://user-images.githubusercontent.com/78422663/180957455-d015949a-5ea0-4ce6-9502-74cdcc8247cf.mp4

Expected Result 
- Edit button should be present.

**Issue 7: Delete button is missing** 

Actual Result 

![Screenshot from 2022-07-12 15-36-00](https://user-images.githubusercontent.com/78422663/178463453-dac2ced1-0836-4460-a8ec-a61412d30258.png)

Excepted Result 
- Delete button should be present 

**Issue 8 : No pagination number options for transaction list**

Actual Result 
![Screenshot from 2022-07-26 13-59-32](https://user-images.githubusercontent.com/78422663/180957871-4cff074c-64cc-42b1-8a28-e6a4c4e0fd55.png)

Excepted Result 
![Screenshot from 2022-07-26 13-58-51](https://user-images.githubusercontent.com/78422663/180958147-3c0aaea8-defb-4ce5-9bb4-18335804b3a3.png)

**Issue 9: Transaction detail page >> your activities redirect to the activity listing page**

Actual Result 

https://user-images.githubusercontent.com/78422663/180965049-036a35d6-4dbc-4c51-8987-0dabab6975e7.mp4

Excepted Result 
- Should redirect to the transaction listing page

**Issue 10 : FINANCIAL appears defaultly on activity detail page**

Actual page 
![Screenshot from 2022-07-26 14-38-04](https://user-images.githubusercontent.com/78422663/180966571-10c855da-6d3b-43f0-ad55-ee0aacfafce9.png)

Excepted Result
Title shouldn't appears defaultly on the activity detail page

**Comment by Sanilblank** [comment]
The above mentioned issue have been fixed in commit 262aab09757a7bb33de1bcf98333d9b29c4a58d9

**Comment by sriza** [comment]
@SauravSilwal10 
**Issue 2: Delete button is not working properly**
The delete functionality of transaction, indicator, period, result and activity is yet to be worked on.
**Issue 6: Edit button is missing form each element in transactions detail page**
The individual element of transaction cannot be edited. Transaction can be edited as a whole only.
**Issue 8: No pagination number options for transaction list**
Pagination for transaction listing page will be done in 331 branch.

**Comment by man-git007** [comment]
@Sanilblank @sriza What is the status of this issue? Have all these issues been fixed?

**Comment by SauravSilwal10** [comment]
Issue Fixed 
 cc @man-git007  @sriza @Sanilblank
