### ISSUE TITLE
#57 Bug:Activity>>Indicator Issue

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#316]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password: 12345678
- for created activity

- [x] **Issue 1: Indicator page overflow** 

Actual Result 
![Screenshot from 2022-08-02 14-43-56](https://user-images.githubusercontent.com/78422663/182335741-09ff9891-fed4-4bb5-b2b9-bf95389e38f5.png)
Expected Result 
- Indicator page should overflow.

- [x] **Issue 2: No validation for Value**

Actual Result
![Screenshot from 2022-08-02 14-47-29](https://user-images.githubusercontent.com/78422663/182336682-1a2d34ea-30ef-4572-a286-27f98b536dde.png)

Expected Result
- A proper validation should be in the form

- [x] **Issue 3: Ascending result not displaying on Indicator Detail page**

Actual Result

https://user-images.githubusercontent.com/78422663/182345348-99c3a50c-0fb6-47e4-b21b-200c60528983.mp4

Excepted Result
- Ascending results should display on the Indicator Detail page.

- [x] **Issue 4: unnecessary element displaying on the indicator detail page.**

Actual Result
![Screenshot from 2022-08-02 15-48-16](https://user-images.githubusercontent.com/78422663/182349060-68c51095-d45c-4a62-b1ea-1e905ff7082b.png)

Excepted Result
- This element should be removed

- [ ] **Issue 5: an inappropriate way to display data** 

Actual Result
![Screenshot from 2022-08-02 16-00-25](https://user-images.githubusercontent.com/78422663/182351566-8ae87a72-a243-4c8e-90e1-2594ad9f85c8.png)

Expected Result
- Dimension : code ---- value ----

- [x] **Issue 6: Conflict between design and implementation**

Actual Result
![Screenshot from 2022-08-02 16-10-31](https://user-images.githubusercontent.com/78422663/182353037-9c116c18-2b3b-4650-bbcc-2b9ad352047e.png)

Excepted Result
![Screenshot from 2022-08-02 16-08-33](https://user-images.githubusercontent.com/78422663/182353098-5fff9be4-82dc-413d-a917-aa92a113a392.png)

- [x] **Issue 7: IATI standard hasn't been followed.**

 Actual Result
https://user-images.githubusercontent.com/78422663/182354753-59fadf96-ebd7-4064-bbca-cea81528b384.mp4

Expected Result
- Please refer to this document(https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/reference/)

- [x] **Issue 8:Document-link URL open on the same page**

Actual Result
https://user-images.githubusercontent.com/78422663/182355885-eb9c858a-d91e-4202-984a-97f165b4af2e.mp4

Expected Result
- Url should redirect to the next tab

- [x] **Issue 9:Conflict between Design and implementation**

Actual Result

https://user-images.githubusercontent.com/78422663/182357858-228cc021-e57c-4f5e-8503-19a1a3258a17.mp4

Expected Result
![Screenshot from 2022-08-02 16-33-09](https://user-images.githubusercontent.com/78422663/182357111-cde3f86c-a276-457d-a936-cc6dc2f919f2.png)

**Comment by AbhishekSka** [comment]
- [ ] **Issue 3: Ascending result not displaying on Indicator Detail page**>>Similar case for the indicator field "Measure". If the field is left blank field is unavailable in view.
- [ ] **Issue 7: IATI standard hasn't been followed.**>> TBD

**Comment by AbhishekSka** [comment]
@SauravSilwal10  "Issue 5: an inappropriate way to display data" to be addressed later. Do make separate issue copy for it

**Comment by man-git007** [comment]
@AbhishekSka @SauravSilwal10 What is the status of this issue?

**Comment by SauravSilwal10** [comment]
@sriza Please have a look over this issue. Then we could decide to end this issue.

- [ ] **Issue 1**
Actual Result
![Screenshot from 2022-09-13 12-01-11](https://user-images.githubusercontent.com/78422663/189824386-a1b8edae-3684-481f-b747-d896fdfbdc3c.png)
Expected Result
![Screenshot from 2022-09-13 12-01-44](https://user-images.githubusercontent.com/78422663/189824464-e0aaac89-5f65-46db-85af-c166e696686e.png)

- [ ] **Issue 2**
Actual Result
![Screenshot from 2022-09-13 12-03-39](https://user-images.githubusercontent.com/78422663/189824712-2b371ef1-fe80-48a8-ab4b-38de57f78b84.png)
Expected Result
Dimension --- , value ----
 cc @man-git007

**Comment by man-git007** [comment]
@titungdup Can you look into this?
