### ISSUE TITLE
#57 Bug:Activity>>Period Issue

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#317]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password: 12345678
- for created activity

- [x] **Issue 1(Rule): The start date of the indicator period must be before the end date of the indicator period rule has not been followed** 

Steps 
- Period start >> enter iso date before the period end date 

Actual Page 
- Page gets saved 

Expected Result
- A proper form validation should be in form.

https://user-images.githubusercontent.com/78422663/178717809-998d8d22-5ec8-4eb9-a2d7-02c9ec9f3eec.mp4

- [x] **Issue 2: In the period listing page add a button leading to the indicator edit form**

- Click the add button 

 Actual Result 
- redirect to the indicator edit form

Expected Result
- should redirect to the period form.

https://user-images.githubusercontent.com/78422663/182369449-a53d64a0-1fb3-4439-be02-bf86329eef49.mp4

- [x] **Issue 3: Period listing page is not working properly** 

Actual Result 
https://user-images.githubusercontent.com/78422663/182367442-7e6fadd0-5197-4da3-b120-4455a10bd6d5.mp4

Expected Result 
- Period listing page should  work properly

- [ ] **Issue 4: The @value should be omitted for qualitative measures rule has not been followed**

Steps 
- select the qualitative measure >> enter a value in the period 

Actual Result 
- Page gets saved and data gets displayed.

Expected Result 
- value should be omitted for qualitative measures 

- [x] **Issue 5: multiple breadcrumbs displayed on the period listing page**

Actual Result 
![Screenshot from 2022-08-02 17-42-43](https://user-images.githubusercontent.com/78422663/182369234-4f5f1994-f156-492d-8274-2627128e450b.png)

Expected Result
- Only one breadcrumb should be displayed

- [x] **Issue 6: No edit button for the period on the activity detail page**

Actual Result
![Screenshot from 2022-08-02 17-49-58](https://user-images.githubusercontent.com/78422663/182370471-37e61ec9-11df-4cbe-bde5-b169ba298e85.png)
Expected Result 
- Edit button should be available on the activity detail page for user convenience.

**Comment by AbhishekSka** [comment]
- [ ] **Issue 1(Rule): The start date of the indicator period must be before the end date of the indicator period rule has not been followed** 
- When user enters same date
![Image](https://user-images.githubusercontent.com/25945530/182801173-26f3b865-f0f1-4393-93af-7e43098b716f.png)

- [ ] **Issue 4: The @value should be omitted for qualitative measures rule has not been followed**
- Validation has been  implemented for it above rule but there is more to it:
     -  The @value must be included for non-qualitative measures.
     -  The @value should be a valid number for all non-qualitative measures.
     - This value must be of type xsd:string.

@sriza @jenishshrestha @Sanilblank

**Comment by AbhishekSka** [comment]
Issu4 moved to #374

**Comment by man-git007** [comment]
@AbhishekSka Can we close this issue?

**Comment by SauravSilwal10** [comment]
Issue Fixed

@man-git007 @AbhishekSka
