### ISSUE TITLE
#57 Bug:Activity>>Clicking on side bar redirect to the edit form after form has been already filled once.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#320]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password: 12345678
- for created activity

Steps 
- Activity >> capital spend 
- fill the form>> save it 
- click capital spend to side bar

Actual Result 
- redirect to the edit form

Excepted Result 
-  should redirect to the capital spend on the activity detail page

https://user-images.githubusercontent.com/78422663/178958345-97288f93-e592-4c6c-9a81-87be572c4fb0.mp4

**Comment by SauravSilwal10** [comment]
@jenishshrestha  This issue hasn't been fixed yet. So please review again.



https://user-images.githubusercontent.com/78422663/180201697-fb34f647-2876-44c7-afee-95e7c8c2fbd0.mp4


cc @man-git007 @praweshsth

**Comment by man-git007** [comment]
@SauravSilwal10 @sriza @jenishshrestha  What is the status of this issue? If completed let's close this issue.

**Comment by SauravSilwal10** [comment]
Issue Fixed
cc @man-git007  @sriza  @jenishshrestha
