### ISSUE TITLE
#57 Bug:Activity>>Country-budget-items issue

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#321]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password: 12345678
- for created activity

**Issue 1 : Incomplete data display on activity detail page**

Steps 
- Fill all the form >> click save button

Actual Result 
- Incomplete data display on activity detail page.

Excepted Result
- complete data should  display on activity detail page.

https://user-images.githubusercontent.com/78422663/178975154-dff12ac4-bad4-4151-8ef9-459f96b56dec.mp4

**Issue 2 : Withdrawn drop-down options from IATI are present.**

Actual Result
![Screenshot from 2022-07-14 17-24-19](https://user-images.githubusercontent.com/78422663/178974235-5c4c6480-8886-49ab-918a-249f05b739f6.png)

Excepted Result
- Withdrawn should be eliminated from drop-down options
- Please refer to the IATI documentation(https://iatistandard.org/en/iati-standard/203/codelists/budgetidentifiervocabulary/)

**Issue 3: Required drop-down options are missing from the code**

Actual Result
![Screenshot from 2022-07-14 17-32-51](https://user-images.githubusercontent.com/78422663/178975552-ed807d65-6209-42c6-becb-cdc1ca6d080f.png)

Excepted Result
- Required drop-down should be present.
- Please refer to the IATI documentation( https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/country-budget-items/budget-item/)

**Comment by man-git007** [comment]
@SauravSilwal10 @sriza What is the status of this issue? If completed let's close this issue.

**Comment by SauravSilwal10** [comment]
Issue Fixed 
 cc @man-git007  @sriza
