### ISSUE TITLE
#57 Bug:Activity>>legacy-data issue

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#322]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password: 12345678
- for created activity

Issue 1: legacy-data tooltip is not informative

Actual Result

https://user-images.githubusercontent.com/78422663/178977312-85015fdb-6971-4ded-92ca-5e4db1d6fa7f.mp4

Excepted Result
- The tooltip should be informative

**Comment by man-git007** [comment]
@SauravSilwal10 @sriza What is the status of this issue? If completed let's close this issue.

**Comment by SauravSilwal10** [comment]
Issue Fixed

cc @man-git007  @sriza
