### ISSUE TITLE
#57 Bug:Activity>>Document-link>>No chosen button works as a submission button

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#324]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password: 12345678
- for created activity

Steps 
- document-link >> document
- click no file chosen 

Actual Button
- works as choose file button 

Excepted Result
- should work as cancel button.

https://user-images.githubusercontent.com/78422663/179187646-0fe2c546-1e0e-4f46-be19-8f9a24b5aa49.mp4

**Comment by man-git007** [comment]
@SauravSilwal10 @sriza  What is the status of this issue? If completed let's close this issue.

**Comment by SauravSilwal10** [comment]
This Issue has not been solved yet. @sriza 

cc @man-git007
