### ISSUE TITLE
#57 Bug:Activity>>participating-org issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#325]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password: 12345678
- for created activity

**Issue 1 :Display an inappropriate information in activity detail page**

Steps
- document-link >> fill a form
- click save 

Actual Result 
- Display an  inappropriate information in activity detail page

Excepted Result 
- An appropriate data should be displayed.

https://user-images.githubusercontent.com/78422663/179668865-9dde2401-5403-4321-8970-80c5f477fe01.mp4

**Issue 2 : Information is missing in tooltip**

Actual Result

https://user-images.githubusercontent.com/78422663/179669459-2bf2f964-3238-4ec9-8535-a7bf271740a2.mp4

Excepted Result
- An information should be available in tooltip.

**Issue 3 : Unwanted drop down in attribute**

Actual Result 
![Screenshot from 2022-07-19 10-58-19](https://user-images.githubusercontent.com/78422663/179670204-027b4e9f-461e-40b1-8236-f92a72d862d4.png)

Excepted Result
- Drop down should be removed.
- Please refer to this document (https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/participating-org/)

**Comment by SauravSilwal10** [comment]
@sriza  Issue 1 hasn't been fixed yet. Please review again.

![Image](https://user-images.githubusercontent.com/78422663/179971091-30aefc68-5cd6-4f0e-b9c0-ddd1bd78304c.png)

cc @man-git007  @praweshsth

**Comment by man-git007** [comment]
@SauravSilwal10 @sriza What is the status of this issue? If completed let's close this issue.

**Comment by SauravSilwal10** [comment]
Issue Fixed

cc @man-git007 @sriza
