### ISSUE TITLE
#57 Bug:Activity>>Result>>Undefined array key "code"

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#326]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password: 12345678
- for created activity

Steps
- Activity >>Result
- Click the save button

Actual Result
- An unwanted error message is displayed.

Excepted Result
- Form should save 

https://user-images.githubusercontent.com/78422663/179672760-9eae1132-6e8c-4b60-8e81-29f33adfa4a2.mp4

**Comment by man-git007** [comment]
@sriza What is the status of this issue?

cc @SauravSilwal10

**Comment by SauravSilwal10** [comment]
Issue Fixed 
cc @man-git007 @sriza
