### ISSUE TITLE
#57 Bug: Activity>>Transactions >>recipient-country>>recipient-region>>flow-type>>finance-type>>aid-type>>tied-status should be declared for either the activity or for all transactions rule has not been followed.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#338]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition 
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password: 12345678
- For already created activity

**Create two instances**
**Instance 1**
Steps 
- Activity >> flow type,finance-type recipient-country,recipient-region,flow-type,finance-type,aid-type, tied-status
- Select drop-down options and fill necessary form field>> click save and exit

**Instance 2** 
Steps 
- Transactions >>flow type ,finance-type ,recipient-country,recipient-region,flow-type,finance-type,aid-type, tied-status
- Select drop-down options  >> click save and exit

Actual Result 
- Different recipient-country,recipient-region,flow-type,finance-type,aid-type, tied-status is created for the same activity.

Expected Result 
- The edit form of transactions should provide an appropriate validation.
- IATI standard has been violated. Please refer to this documentation(https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/transaction/)

https://user-images.githubusercontent.com/78422663/180932046-f7b44d0e-e509-461d-bd3d-c7690bcaafd4.mp4

**Comment by man-git007** [comment]
@SauravSilwal10 What is the status of this issue?

**Comment by SauravSilwal10** [comment]
@man-git007 and @praweshsth we need to discuss this issue.

cc @sriza  @Sanilblank

**Comment by SauravSilwal10** [comment]
please refer to the issue #489
