### ISSUE TITLE
#57 Bug: Issue with Result details' page

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#362]
**Context**
- Desktop
- Chrome 102.0.5005.61

**Precondition**
- https://stage.iatipublisher.yipl.com.np/
- Username: Publisher 3
- Password: test1234
- for created activity

- [x] **Issue 1: Result detail page >> Value of Aggregation status field stays "False" when entered blank**

**Steps** 
-  Existing result https://stage.iatipublisher.yipl.com.np/activities/2/result/20#indicator
-  On aggregate status field >>Enter blank and save

**Actual result** 
- Value is being saved as "false" in detail page 
- Value is shown True in Result listing page

![Image](https://user-images.githubusercontent.com/25945530/182774844-94a097e8-d9a7-4331-bce1-9c7a82176e59.png)

![Image](https://user-images.githubusercontent.com/25945530/182774622-ea6e7ca0-a2ec-469b-adb6-acdc32abc69d.png)

**Expected Result**
- If value is unavailable it should state as "Not available ".

================================================================================================
- [x] **Issue 2: Result detail page>> Indicator section >> Naming of two buttons is same**

 **Actual Result** 
![image](https://user-images.githubusercontent.com/25945530/182771009-5c907172-96fc-4ef3-9f17-6a9127ba6678.png)

**Expected Result**
![image](https://user-images.githubusercontent.com/25945530/182771222-61808b4a-db0a-498d-a4d9-97c89b5ffb70.png)
===================================================================================================

**Comment by man-git007** [comment]
@AbhishekSka Can we close this issue

cc @sriza @SauravSilwal10

**Comment by SauravSilwal10** [comment]
Issue Fixed 
 cc @man-git007  @sriza @AbhishekSka
