### ISSUE TITLE
Issue when trying to publish to Staging IATI Registry

### ISSUE THREAD

**Issue by Sanilblank** [younginnovations/iatipublisher#365]
When trying to call the API for publishing the XML file to the staging IATI registry, it responds that the type of file mentioned in the URL section is not an XML file.

I have confirmed that the URL is indeed an XML file and I have also tested the same using an actual XML file URL published to IATI registry.

I did not have this problem working on the task the day before. Could you please check if there is some issue with the system?

cc. @k8hughes @titiolukole

**Comment by k8hughes** [comment]
@akmiller01 this might require you supporting.  It sounds like a question we need to pass on to Derleinx

**Comment by akmiller01** [comment]
I think we'll need to pass this straight to Derilinx, @k8hughes . I only have a basic login for the Staging Registry, so I'm unable to even test the staging Registry API. I've sent it to Titi on Slack.

**Comment by cormachallinanderilinx** [comment]
Hi @Sanilblank 

Is this still an issue? 
I was doing to work on staging I broke this functionality while testing.

If this is still an issue I will investigate.

If possible can you send on the file you use (or similar), which will help me to reproduce the issue.

**Comment by Sanilblank** [comment]
@cormachallinanderilinx This issue has been fixed as of now. The API is working as it needs to as of now.

Thank you for the help.

**Comment by man-git007** [comment]
@Sanilblank Can we close this issue?
