### ISSUE TITLE
#57 Bug: Breadcrum for the create pages of Results/Indicator/Period

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#367]
**Context**
- Desktop
- Chrome 102.0.5005.61

**Precondition**
- https://stage.iatipublisher.yipl.com.np/
- Username: Publisher 3
- Password: test1234
- for created activity

- [ ] **Issue 1: Results/Indicator/Period page >> Breadcrum for the ADD/EDIT page**

**Actual result** 
![image](https://user-images.githubusercontent.com/25945530/182807941-6f967401-0372-43a7-9e6f-f4e0b970d4cf.png)

**Expected Result**
![image](https://user-images.githubusercontent.com/25945530/182808281-42ffa977-ad97-4a3b-bd05-312974c0548d.png)

================================================================================================

**Comment by man-git007** [comment]
@jenishshrestha What is the status for this issue?

**Comment by SauravSilwal10** [comment]
Issue fixed 

cc @man-git007 @jenishshrestha
