### ISSUE TITLE
#57 Bug:Transaction/ Result/ Indicator>> The field titles/Elements separated by "_" to be changed to "-"

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#371]
**Context**
- Desktop
- Chrome 102.0.5005.61

**Precondition**
- https://stage.iatipublisher.yipl.com.np/
- Username: Publisher 3
- Password: test1234
- for created activity

### Actual Result ###
- Transaction>>
     - transaction_type
     - transaction_date
     - provider_organization
     - receiver_organization
     - disbursement_channel
     - recipient_country
     - flow_type
     - finance_type
     - aid_type
     - tied_status
- Result >>
     - aggregation_status
     - document_link
- Indicator >>
     - aggregation_status
     - document_link

![image](https://user-images.githubusercontent.com/25945530/183005537-377f16ce-1bf0-4a7a-a9f4-47a245577a1e.png)

### Expected Result ###
![image](https://user-images.githubusercontent.com/25945530/183005599-c09d69d9-2c45-49cd-a351-fa4db59ee26a.png)

**Comment by man-git007** [comment]
@praweshsth We need to discuss this issue.

cc @jenishshrestha @AbhishekSka @sriza @SauravSilwal10

**Comment by man-git007** [comment]
This issue is related to the #507 issue. We will close this issue after #507 is resolved

cc @jenishshrestha @praweshsth @SauravSilwal10

**Comment by man-git007** [comment]
@SauravSilwal10 Can we close this issue?

**Comment by sriza** [comment]
Merged to main branch. Closed manually.
