### ISSUE TITLE
# Bug: Transaction/Result/Indicator/Period/Planned Disbursement>> Form's Element tiles to be maintained on all small cases and separated by "-"  where required

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#372]
**Context**
- Desktop
- Chrome 102.0.5005.61

**Precondition**
- https://stage.iatipublisher.yipl.com.np/
- Username: Publisher 3
- Password: test1234
- for created activity

### Actual result ##
![title](https://user-images.githubusercontent.com/25945530/183007461-d990b6f4-c38b-41aa-bfbc-0086141519c6.gif)

**Comment by man-git007** [comment]
@AbhishekSka @jenishshrestha @sriza What is the status of this issue?

**Comment by SauravSilwal10** [comment]
Please refer to the Issue #489
