### ISSUE TITLE
Bug : Period>> The @value should be omitted for qualitative measures rule has not been followed

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#374]
**Context**
Desktop
Chrome 102.0.5005.61

**Precondition**
https://stage.iatipublisher.yipl.com.np/
Username: Publisher 3
Password: test1234
for created activity

**To Be implemented**
Validation has been implemented for it above rule but there is more to it:

- The @value must be included for non-qualitative measures.
- The @value should be a valid number for all non-qualitative measures.
- This value must be of type xsd:string.

## Actual Result ###
Upon changing the measure value in indicator on to non qualitative user still faces validation

**Comment by man-git007** [comment]
@AbhishekSka @sriza What is the status of this issue? Can we close this issue?

**Comment by SauravSilwal10** [comment]
@sriza This has not been fixed yet.

cc @man-git007  @AbhishekSka
