### ISSUE TITLE
Bug: Issue with the period edit section in activity detail page

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#375]
**Context**
Desktop
Chrome 102.0.5005.61

**Precondition**
https://stage.iatipublisher.yipl.com.np/
Username: Publisher 3
Password: test1234
for created activity

- [ ] **Issue 1:404 on edit of period details from activity detail page**
- Activity detail page>> Go to indicator >>present with period
-  https://stage.iatipublisher.yipl.com.np/activities/2
-  click on edit

**Actual result**
- results to 404 
- redirection Link is  https://stage.iatipublisher.yipl.com.np/activities/2/result/20/indicator/15/period/edit
![period link](https://user-images.githubusercontent.com/25945530/183029551-0886d85e-a3e4-4d5b-9938-d9d47824e64d.gif)

**Expected Result** 
- redirection Link  to be https://stage.iatipublisher.yipl.com.np/activities/2/result/20/indicator/15/period/7/edit
- Ends up on period edit field

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- [ ] **Issue 2:Unaligned "Edit" and "Show full  period result"**

**Actual result**
- ![image](https://user-images.githubusercontent.com/25945530/183031026-ad1294b4-4b37-4bbd-accf-367197643c1b.png)

 
**Expected Result**
- Text of two buttons should be in same line

**Comment by man-git007** [comment]
@jenishshrestha @sriza @AbhishekSka Can we close this issue?

**Comment by SauravSilwal10** [comment]
Issue Fixed
