### ISSUE TITLE
Bug: Indicator detail page>> In case of multiple Baseline, the separation is unavailable causing confusion with start of next baseline content

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#376]
**Context**
Desktop
Chrome 102.0.5005.61

**Precondition**
https://stage.iatipublisher.yipl.com.np/
Username: Publisher 3
Password: test1234
for created activity

**Steps**

- [ ] Issue 1

- For the indicator>> create multiple Baseline and save it
- https://stage.iatipublisher.yipl.com.np/activities/7/result/21/indicator/13

- [ ] Issue 2
- Missing Add period

**Actual result**
Issue 1
- Here the content after the separator of document link and Starting from "Year" looks as if it is Content of Document link
![image](https://user-images.githubusercontent.com/25945530/183036435-87ceba5d-a459-400d-80e2-b6234193ca02.png)

where as content starting from "Year" is of newly added Baseline
![image](https://user-images.githubusercontent.com/25945530/183036645-8fa53c3d-d2e9-479e-8abc-2d45b0d51ffc.png)

Issue 2
![image](https://user-images.githubusercontent.com/25945530/183071021-4563993b-1c3f-4cc9-b0e5-8e6a99f7ae50.png)

  
**Expected result**
- View to be improvise so that user could easily get the separation between two different baseline
-  Issue 2
![image](https://user-images.githubusercontent.com/25945530/183071087-1f72ef7e-ea67-4c95-8b0e-0349c633ba11.png)

**Comment by man-git007** [comment]
@AbhishekSka @jenishshrestha Can we close this issue?

**Comment by SauravSilwal10** [comment]
Issue fixed
