### ISSUE TITLE
Fixing Bugs

### ISSUE THREAD

**Issue by jenishshrestha** [younginnovations/iatipublisher#377]
- [x] #368
- [x] #371
- [x] #375
- [x] #376
- [x] Result, indicator and period route changes
- [x] Result complete status font color in activity detail
- [x] Remove complete/incomplete status from edit form
- [x] Activity edit page lagging (loader or other solution)
- [x] 'Add period' in indicator detail page

**Comment by man-git007** [comment]
@jenishshrestha @titungdup @SauravSilwal10 
I think, we can close this issue.

**Comment by jenishshrestha** [comment]
> @jenishshrestha @titungdup @SauravSilwal10 I think, we can close this issue.

PR #378 needs to be merged for some of the issues to be fixed.

**Comment by man-git007** [comment]
@SauravSilwal10 Move this issue to backlog

**Comment by SauravSilwal10** [comment]
@man-git007 Okay
