### ISSUE TITLE
Bug: iati-identifier complete status and progress bar is not working properly.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#381]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Publisher 3
- Password: test1234

Steps 
- Click add activity button >> enter narrative and activity identifier>> select drop down options from @xml:lang
- Click save button

Actual Result
- Complete status is untouched by changes.
- Progress bar doesn't progress

Excepted Result
- It is necessary to update incomplete status to completed status.
- Progress bar should progress.

https://user-images.githubusercontent.com/78422663/183369268-e21e3227-7f88-445a-832b-84c185e3c457.mp4

**Comment by man-git007** [comment]
@SauravSilwal10 Seems working

**Comment by man-git007** [comment]
@SauravSilwal10 Does the issue still persist?

**Comment by man-git007** [comment]
@SauravSilwal10 If all is OK let's close this issue. Also @jenishshrestha Could you please verify from your side as well?

cc @jenishshrestha

**Comment by man-git007** [comment]
@SauravSilwal10 Can we close this issue?

**Comment by SauravSilwal10** [comment]
Issue F
