### ISSUE TITLE
#57 Bug: Policy-marker issue

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#384]
Context
Desktop
Chrome 102.0.5005.61
Precondition
https://stage.iatipublisher.yipl.com.np/
Username: Publisher 3
Password: test1234
for created activity

 **Issue 1 : Unwanted field in edit form**

Actual Result
![Screenshot from 2022-08-08 16-53-48](https://user-images.githubusercontent.com/78422663/183404795-ae26a3a6-ed44-47c6-9bc8-68d558ba8366.png)

Excepted Result
- Unnecessary field should be removed.Please refer to IATI documentation(https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/policy-marker/)

**Issue 2 : If the vocabulary is 99 (reporting organisation), the URI where this internal vocabulary is defined rule hasn't been followed**

Actual Result

https://user-images.githubusercontent.com/78422663/183410484-c940803c-0d05-45e3-8a96-253c9925984d.mp4

Excepted Result
- If the vocabulary is 99 (reporting organisation), the URI where this internal vocabulary is defined rule should be  followed.Please refer to IATI documentation(https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/policy-marker/)

**Comment by man-git007** [comment]
@sriza Could you please look into this.

**Comment by man-git007** [comment]
@sriza any progress to this issue?

**Comment by sriza** [comment]
@SauravSilwal10 
The fixes to this issue is deployed to staging site. Please have a look.

**Comment by SauravSilwal10** [comment]
@sriza policy marker information doesn't display on the Activity detail page. Please review again.


https://user-images.githubusercontent.com/78422663/185064210-8908cda7-2dbc-4036-befd-c7209ec19620.mp4

**Comment by man-git007** [comment]
@SauravSilwal10 If this issue has been fixed. Let's close this issue

cc @sriza
