### ISSUE TITLE
Bug: Status issues with the elements 

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#386]
**Context**
Desktop
Chrome 102.0.5005.61

**Precondition**
https://stage.iatipublisher.yipl.com.np/
Username: Publisher 3
Password: test1234
for created activity

- [ ] **Issue 1**
**Steps**

Recipient region/Tag 
- After adding mandatory fields @vocabulary and @code
- Click on add more and save 
![recipeint](https://user-images.githubusercontent.com/25945530/183565188-608b671b-2cca-435b-8acc-dbb27bd55e57.gif)

**Actual result**
- Status could be seen as completed even after the addition another Recipient region section
 

**Expected result**
- The status should be not-complete if mandatory fields are not filled
-------------------------------------------------------------------------------------------------------------
- [ ] ** Issue 2 **  
**Steps**

Recipient region/Tag
- After adding mandatory fields @vocabulary and @code
- Click on add more Recipient region/Tag
- Enter only code on newly added section 
- save 
![tag](https://user-images.githubusercontent.com/25945530/183571055-e14c9c42-fdf2-4b80-a8be-e742f7b0df34.gif)

**Actual result**
- Status could be seen as completed even after the addition another Recipient region section in detail page

**Expected result**
- The status should be not-complete if mandatory fields are not filled
-------------------------------------------------------------------------------------------------------------- 

- [ ]   ** Issue 3 **
**Steps**

Humanitarian scope
- For first section add all required fields
- Click on add more humanitarian-scope 
- Select type and Vocabulary as 99 - Reporting Organisation
- Without entering code >>hit save 
![humanitarian](https://user-images.githubusercontent.com/25945530/183567459-9a92e0cf-48c2-4bc5-a4f4-8f8e670d2d77.gif)

**Actual result**
- Status could be seen as completed even after the addition another Recipient region section in detail page

**Expected result**
- The status should be not-complete if mandatory fields are not filled

---------------------------------------------------------------------------------------------------------------

- [ ] **Issue 4 **
**Steps**

Any element(Related activity/ legacy data)
- For Mandatory field with input field
- Enter 0 in all of them 
- save 
![0](https://user-images.githubusercontent.com/25945530/183569878-78cd09c4-f3fd-4ea6-acec-4ef5e0ccfc12.gif)

**Actual result**
- Upon entering 0 to the field, the status of the element becomes not-completed

**Expected result**
- NTD
---------------------------------------------------------------------------------------------------------------
- [ ]  **Issue 5 -Contact info>> Requires filling whole form to get complete status**
**Steps**

Any element(Contact info)
- Only enter Mandatory field  
- save 
![contactInfo](https://user-images.githubusercontent.com/25945530/183570807-d9e22633-f6ed-4768-9560-e28a9b7955b5.gif)

**Actual result**
- All the field are to be filled to make element status completed 

**Expected result**
- The entering of mandatory field should make element status completed
---------------------------------------------------------------------------------------------------------------
- [ ] **Issue 6 - planned disbursement>> have to enter whole (Value section which is not mandatory ) to make element complete**

**Steps**

Any element(Planned disbursement)
- Only enter Mandatory field  
 - @type
 - Period start>>@iso-date  &   Period end>>@iso-date 
 - @value-date
- save 
![planned disbursment](https://user-images.githubusercontent.com/25945530/183572992-392ac62f-2efa-4f13-aae7-9eef70fca607.gif)

**Actual result**
- Whole Value section is required to filled inorder to make element complete

**Expected result**
- As per doc above mentioned field are only mandatory. Thus to make element complete, those are to be only filled

**Comment by man-git007** [comment]
@AbhishekSka 
**Issue 1**
Code is only mandatory if @vocabulary is selected

**Issue 2**
Same as Issue 1

**Issue 3 & 4**
Doing. Will notify once finished

**Issue 5**
mandatory fields are narrative of `Organization`, `Department`, `Person name`, `Job title` and `mailing address`. Refer this [link](https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=650896675&range=A39)

**Issue 6**
mandatory are `period_start @iso-date`, `period_end @iso-date`, `amount`, `currency` and `value_date`. Refer this [link](https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=650896675&range=A159)

cc @SauravSilwal10

**Comment by man-git007** [comment]
@AbhishekSka Issue 3 has been fixed

For now lets ignore Issue4

**Comment by man-git007** [comment]
@AbhishekSka Can we close this issue now?

**Comment by man-git007** [comment]
@AbhishekSka Lets close this issue.

cc @praweshsth @SauravSilwal10

**Comment by man-git007** [comment]
Closing this issue manually.
