### ISSUE TITLE
Bug: country-budget-items>> narrative attribute is mandatory. 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#387]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Publisher 3
- Password: test1234

steps 
- fill all country-budget-items attribute except  narrative

Actual Result 
- incomplete status doesn't changes into the complete status

Excepted Result
- incomplete status should change into the complete status.Please refer to the IATI standard documentation (https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/country-budget-items/budget-item/description/narrative/) 
- narrative attribute should not be mandatory

https://user-images.githubusercontent.com/78422663/183571162-7d8dd1b3-dc6a-441a-aa02-a8c153efb34a.mp4

**Comment by man-git007** [comment]
@SauravSilwal10 Please refer to this [link](https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=650896675&range=A116) for the mandatory list.

**Comment by SauravSilwal10** [comment]
Misunderstanding between two documents.So, Issue closed
