### ISSUE TITLE
Bug: Status issues with document-link 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#388]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Publisher 3
- Password: test1234
- for created activity

**Issue 1: Language attribute is not mandatory**

Actual Result
![Screenshot from 2022-08-09 11-40-50](https://user-images.githubusercontent.com/78422663/183575161-86208841-7937-47aa-9844-ecc0633af702.png)

Excepted Result
- Language attributes should be mandatory. Please refer IATI documentation
- https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/document-link/language/

**Comment by man-git007** [comment]
@SauravSilwal10 
Please refer to this [link](https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=650896675&range=A239)

cc @AbhishekSka

**Comment by SauravSilwal10** [comment]
@man-git007 Language (@code) attribute should be mandatory according to the [link](https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=650896675&range=A239).
![Screenshot from 2022-08-10 15-22-18](https://user-images.githubusercontent.com/78422663/183869745-d9ce53df-f645-4379-b0cc-8e35220813b5.png)
![Screenshot from 2022-08-10 15-23-24](https://user-images.githubusercontent.com/78422663/183869772-45576f66-7272-4406-8c7c-aa0bd6dba907.png).

cc @AbhishekSka @praweshsth

**Comment by man-git007** [comment]
@SauravSilwal10 Has been deployed to the staging server. Please check

**Comment by man-git007** [comment]
@SauravSilwal10 Does the issue still persists?

**Comment by man-git007** [comment]
@SauravSilwal10 If this issue has been sloved? then lets close this issue
