### ISSUE TITLE
Bug: Unwanted behavior in side bar  

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#389]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Publisher 3
- Password: test1234
- for created activity

steps 
- search the element in sidebar 

Actual Result

https://user-images.githubusercontent.com/78422663/183589394-e0770267-220b-4d92-b0d1-e6364f8bf24e.mp4

![sidemenu](https://user-images.githubusercontent.com/25945530/183823685-6190d3c3-bd87-405e-9bcd-542196290232.gif)

Excepted Result
- This Unwanted behavior should be removed.

**Comment by jenishshrestha** [comment]
This issue has been fixed in branch 377-fixings-bugs
