### ISSUE TITLE
Bug : status issue with location

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#390]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Publisher 3
- Password: test1234
- for created activity

**Issue 1 : Location reach (@code ) , administrative(@vocabulary and @code ) and exactness(@code) are not mandatory.**

Actual Result 
![Screenshot from 2022-08-09 13-36-53](https://user-images.githubusercontent.com/78422663/183595696-56eb8b8e-79cf-490d-9371-e3b5aa8afe21.png)

Excepted Result
- Location reach (@code ) , administrative(@vocabulary and @code ) and exactness(@code) should be  mandatory.Please refer to IATI documentation
https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/location/location-reach/
https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/location/administrative/
https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/location/exactness/

**Comment by man-git007** [comment]
@SauravSilwal10 Could please retest this using this [link](https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=650896675&range=A73)?

**Comment by SauravSilwal10** [comment]
@man-git007 Location reach (@code ) , administrative(@vocabulary and @code ) and exactness(@code)  are mandatory in this [link](https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=650896675&range=A73).Would you kindly review it again?

cc @AbhishekSka  @praweshsth

**Comment by man-git007** [comment]
@SauravSilwal10 Changes have been deployed to the staging server. Please check once.

**Comment by man-git007** [comment]
@SauravSilwal10 Can this issue be closed? Please refer to this [link](https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=1664498206&range=A1) if any confusion
