### ISSUE TITLE
Bug: Issues over the transaction result indicator and period status 

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#391]
**Context**
Desktop
Chrome 102.0.5005.61

**Precondition**
https://stage.iatipublisher.yipl.com.np/
Username: Publisher 3
Password: test1234
for created activity

- [ ] **Issue 1** : Without completing the required field, the status of the transaction result indication and the period are always displayed as completed.
**Steps**
- https://stage.iatipublisher.yipl.com.np/activities/4/transactions

**Actual result**
![image](https://user-images.githubusercontent.com/25945530/183612920-0e825c61-1c91-477b-a23a-e5264962d761.png)
![Screenshot from 2022-08-09 17-11-50](https://user-images.githubusercontent.com/78422663/183825935-951afb11-ca65-46f6-8804-30c1cb207eee.png)
![Screenshot from 2022-08-09 17-13-04](https://user-images.githubusercontent.com/78422663/183825955-74f853d4-e3ea-422d-9d4b-5065cabf3059.png)

**Expected result**
- Statuses are to be shown as per the transaction result indicator and period  field's mandatory entries

**Comment by man-git007** [comment]
@AbhishekSka We only check the overall complete status of the result. Thus, we will remove the status column from result, transaction and period list page

cc @praweshsth @SauravSilwal10

**Comment by man-git007** [comment]
@AbhishekSka Has removed the status column from the list table.

**Comment by man-git007** [comment]
@AbhishekSka Can we close this issue?

**Comment by man-git007** [comment]
@AbhishekSka Lets close this issue with a comment

**Comment by man-git007** [comment]
Closed manually
