### ISSUE TITLE
Bug : status issue with period 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#392]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Publisher 3
- Password: test1234
- for created activity

Steps
- Do not fill the mandatory  field i.e.
- Period-start @iso-date
- period-end @iso-date
- Document-link @url @format 
- click save button

Actual Result
- Completed status is marked at result in activity detail page.

Excepted Result
- incomplete status should be marked at result in activity detail page.

https://user-images.githubusercontent.com/78422663/183638736-16810209-b12e-4016-b0bf-1d61c2a1316e.mp4

**Comment by man-git007** [comment]
@SauravSilwal10 Seems OK

**Comment by SauravSilwal10** [comment]
@man-git007 The issue is still present. Would you kindly review it again?


https://user-images.githubusercontent.com/78422663/183886039-929e00d6-8ae4-46b0-8553-8886f3679099.mp4

cc @AbhishekSka  @praweshsth

**Comment by man-git007** [comment]
@SauravSilwal10 Changes have been deployed to the staging server. Please check once
