### ISSUE TITLE
Bug :  Transaction status is marked as not-completed even after filling required fields as per iati standard

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#393]
**Context**
Desktop
Chrome 102.0.5005.61

**Precondition**
https://stage.iatipublisher.yipl.com.np/
Username: Publisher 3
Password: test1234
for created activity

**Steps**
- Fill up mandatory fields
 - Transaction type:@code 
 - Transaction date: @iso-date
 - Value: @amount  | @value-date
 - Disbursement channel : @code
 - Sector : @code
 - Recipient country: @code
 - Recipient region : @code
 - Flow type : @code
 - Finance type : @code
 - Aid type : @code

**Actual result**
- Result over the activity details is Transaction status is not completed
https://stage.iatipublisher.yipl.com.np/activities/5/transactions/3

**Expected result**
- After filling up the required fields of transaction form it should be shown as completed

**Comment by man-git007** [comment]
@AbhishekSka Could please use this [link](https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=650896675&range=A182) for reference?

**Comment by man-git007** [comment]
@AbhishekSka Does the issue still persist?

**Comment by man-git007** [comment]
@AbhishekSka @SauravSilwal10 Does the issue still persist? if not let's close this issue

**Comment by man-git007** [comment]
@AbhishekSka @SauravSilwal10 What is the status?

**Comment by SauravSilwal10** [comment]
@man-git007 There is still one logical problem, and @Sriza is addressing them. When it's finished, I'll close this ticket.

**Comment by man-git007** [comment]
@SauravSilwal10 Can we close this issue?

**Comment by SauravSilwal10** [comment]
issue fixed
