### ISSUE TITLE
Bug: Core element progress chart ends up at 94% even after filling up all the core elements

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#394]
**Context**
Desktop
Chrome 102.0.5005.61

**Precondition**
https://stage.iatipublisher.yipl.com.np/
Username: Publisher 3
Password: test1234
for created activity

- [ ] **Issue 1** :  Core element progress chart ends up at 94% even after filling up all the core elements

**Steps**
- https://stage.iatipublisher.yipl.com.np/activities/21
- Fill up all the core elements with complete status
- Check for the resultant progress chart

**Actual result**
- result ends up at 94% 

**Expected result**
- chart should show the completion with 100%

![100](https://user-images.githubusercontent.com/25945530/183821899-44bff2f8-42d8-46a8-bd6c-cc5a12bd89cc.gif)

**Comment by man-git007** [comment]
@AbhishekSka This might be due to the `reporting-org` element in Organization. Please ignore for now.
