### ISSUE TITLE
Bug : status issue with result and indicator issue

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#395]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Publisher 3
- Password: test1234
- for created activity

**Issue 1 : Document-link (language @code ) is not mandatory in result and indicator**  

Actual Result 

https://user-images.githubusercontent.com/78422663/183823958-95244b2b-f29a-41ca-8a47-69b8d76d796f.mp4

Excepted Result
- Document-link (language @code ) should be mandatory.Please refer to IATI documentatio(https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/document-link/language/).

**Issue 2 : Indicator**

- After adding mandatory fields 
- Click on add more document link 
- don't fill mandatory attributes
- save

Actual result
- Status could be seen as completed 

Excepted Result
- The status should be not-complete if mandatory fields are not filled

https://user-images.githubusercontent.com/78422663/183824540-d528b70c-1284-4ca1-bd6d-0d41172f35c1.mp4

**Comment by man-git007** [comment]
@SauravSilwal10 Please refer to this [link](https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=650896675&range=A288)

**Comment by man-git007** [comment]
@SauravSilwal10 Deployed to the staging server. Also regarding issue 1, @code attribute is not mandatory according to this [link](https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=650896675&range=A288)

**Comment by SauravSilwal10** [comment]
The IATI standard makes document-link (language **@code**) mandatory. But in this [link](https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=650896675&range=A288) the **@code** attribute is not mandatory. @praweshsth Could you verify it? (https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=650896675&range=A288)

cc @man-git007

**Comment by man-git007** [comment]
@praweshsth Should we make the updates?

**Comment by man-git007** [comment]
@SauravSilwal10 Please refer to this [link](https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=1664498206&range=A1). If all OK let's close this issue
