### ISSUE TITLE
Bug: Issue with the percent fields 

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#396]
**Context**
Desktop
Chrome 102.0.5005.61

**Precondition**
https://stage.iatipublisher.yipl.com.np/
Username: Publisher 3
Password: test1234
for created activity

- [ ] **Issue 1** : Unavailable validation if the field consists of percent  > 100 over multiple fields

**Steps**
- Elements >> recipient-country | policy-marker | recipient-region | sector | country-budget-items
- Enter @percentage to 100
- Add more of element section and fill 100 over the percent field
- save 
https://stage.iatipublisher.yipl.com.np/activities/26/

**Actual result**
- Percent with accumulative score of greater than 100 could  be saved 
 
![PERCENT](https://user-images.githubusercontent.com/25945530/183838820-cd8de9ab-fb25-49ec-b059-2316046a7bf3.gif)

**Expected result**
- Content must be a decimal number between 0 and 100 inclusive, with no percentage sign. Percentages for all reported countries and regions within a vocabulary MUST add up to 100.
- validation over the field are to be displayed

[For more information](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/recipient-country/)"
-------------------------------------------------------------------------------------------------------------
- [ ] **Issue 2** : country-budget-items>> blank save @percentage gives NaN in activity detail view
-
**Steps**
- country-budget-items>> Blank save @percentage
https://stage.iatipublisher.yipl.com.np/activities/26/

**Actual result**
-  blank save @percentage gives NaN in activity detail view

![image](https://user-images.githubusercontent.com/25945530/183839086-0f8ffaf7-4285-4b8b-bef0-5e3c59265842.png)

**Expected result**
- If unavailable @percentage values then nothing is to be displayed

**Comment by man-git007** [comment]
@SauravSilwal10 What is the status for this issue?

**Comment by SauravSilwal10** [comment]
The proper validation of the percentage is remaining.@sriza is working on it. 

cc @man-git007
