### ISSUE TITLE
Bug : status issue with default-aid-type, sector,policy-marker

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#397]
Context
- Desktop
- Chrome 102.0.5005.61

Precondition
- https://stage.iatipublisher.yipl.com.np/
- Username: Publisher 3
- Password: test1234
- for created activity

**Issue 1 : Element status mark as completed without entering the mandatory attributes**

Steps
- just click save button  in edit form of default-aid-type, sector,policy-marker,tag

Actual Result
- Element status is mark as completed 

Excepted Result
- without filling up the required fields of  default-aid-type, sector,policy-marker form it should be shown as incomplete.

https://user-images.githubusercontent.com/78422663/183843422-ebd4723a-f90c-4cda-ad20-721e500e0e15.mp4

**Issue 2 : Without displaying the code attribute in activity detail page  , complete status mark as completed.**

steps
- just fill code attribute and click save button  in edit form of default-aid-type, sector,policy-marker,tag

Actual Result
- complete status mark as completed, Without displaying the code attribute in activity detail page

Expected Result
- Code should be disabled until a vocabulary is chosen by the user.

https://user-images.githubusercontent.com/78422663/190313903-5705ee40-ed91-4c84-9c93-b1add6b037b5.mp4

**Comment by SauravSilwal10** [comment]
@man-git007 The issue is still present. Would you kindly review it again?

cc @praweshsth

**Comment by man-git007** [comment]
@SauravSilwal10 
The attributes are required only when `@vocabulary` is selected. If not selected it is not required. Now it does create problems from the user's perspective. What should we do @praweshsth? Can we ignore it for now?

**Comment by man-git007** [comment]
@SauravSilwal10 Please refer this [link](https://docs.google.com/spreadsheets/d/1hxeH0JAUl8Ln8zYiQaqkhL1phsLNc_C6kDt_lnI99RQ/edit#gid=1664498206&range=A1). If all OK lets close this issue

**Comment by man-git007** [comment]
@SauravSilwal10 Lets look into this today.

**Comment by SauravSilwal10** [comment]
@@praweshsth We need to discuss this issue.

cc @man-git007

**Comment by SauravSilwal10** [comment]
Please refer to this issue #489.
