### ISSUE TITLE
Bug: Organization Data>>Organization identifier form issues 

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#402]
**Context**
Desktop
Chrome 102.0.5005.61

**Precondition**
https://stage.iatipublisher.yipl.com.np/
Username: Publisher 3
Password: test1234
for created activity

- [x] **Issue 1** : organisation-registration-agency is not saved
**Steps**
- https://stage.iatipublisher.yipl.com.np/organisation/organisation_identifier
- Change field of organisation-registration-agency to anything new
- Save 
- edit the element again

**Actual result**
-  The value save isnt displayed over the field

 ![organization reg](https://user-images.githubusercontent.com/25945530/184102007-2919c402-bd93-4295-afc0-d417e7cbe28d.gif)

**Expected result**
- Selected field is to be displayed over the organisation-registration-agency field
-------------------------------------------------------------------------------------------------------------
- [ ] ** Issue 2 **  : Changed organization identifier not reflected on the existing activity 

**Steps**
- Create the new activity 
- Organization data> change the fields on the elements
- Check for it on the activity

**Actual result**
- Organization identifier field changes are not reflected over the activity
![activity organization](https://user-images.githubusercontent.com/25945530/184103751-1a897579-aa41-4d2f-be37-c0e4c10a9905.gif)

**Expected result**
- Upon changing the organization identifier details user should also see the changed over the iATI identifier field in activity 

-------------------------------------------------------------------------------------------------------------- 

- [ ]   ** Issue 3 ** : organisation-registration-agency not displayed as per country

**Steps**
- Select Country in the organization identifier
- select organisation-registration-agency

**Actual result**
- User could select the organisation-registration-agency that are not of its own country 

![country dependency](https://user-images.githubusercontent.com/25945530/184104084-c2ec156c-14e0-4803-a0d2-c5ed092b02e5.gif)

**Expected result**
-  The hierarchy of country and organisation-registration-agency should be similar as that in registration page
- NTD
 
--------------------------------------------------------------------------------------------------------------

**Comment by SauravSilwal10** [comment]
@sriza The organisation-identifier must not contain any of the symbols /, &, | or ?. Please review again 


![Image](https://user-images.githubusercontent.com/78422663/185339524-15ddb1cd-7525-4b5a-ab8a-ec72fa0e19a0.png)
