### ISSUE TITLE
Bulk Publish Flow

### ISSUE THREAD

**Issue by nirvanalama** [younginnovations/iatipublisher#407]
### **Bulk** Publish Flow

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=9481%3A163952&node-id=9481%3A183768&viewport=-2444%2C-461%2C0.06&scaling=min-zoom&starting-point-node-id=9481%3A183768

@k8hughes @titiolukole @Rohini-IATI @praweshsth 

Posted above is the link to the **Bulk Publish Flow.** Please interact with the flow and let us know if you have any feedbacks.

**Comment by k8hughes** [comment]
when I click on this nothing changes, it seems like it is only a one page design.  Can you let me know how to click though?

**Comment by praweshsth** [comment]
@k8hughes  Click the check boxes to move ahead. You will see button, 'Publish Selected'. Click it.

**Comment by k8hughes** [comment]
![Screenshot 2022-08-22 at 16 02 20](https://user-images.githubusercontent.com/36768381/185953977-775a7d26-b2b1-4528-ade2-9f3c46c572a7.png)
So this message I don't understand as it says both that core elements are complete and are not complete...

**Comment by k8hughes** [comment]
when I got to the end of the flow and I had done the bulk publish, I then wanted to view my validation error for each activity , but I wasn't clear how to do this, can we discuss tomorrow on the call?

**Comment by praweshsth** [comment]
> ![Screenshot 2022-08-22 at 16 02 20](https://user-images.githubusercontent.com/36768381/185953977-775a7d26-b2b1-4528-ade2-9f3c46c572a7.png) So this message I don't understand as it says both that core elements are complete and are not complete...

This is just to show that which activities' core elements are completed and which activities' core elements are not. Here, we used the same names of the activities in both cases and hence the confusion. @k8hughes

**Comment by praweshsth** [comment]
> when I got to the end of the flow and I had done the bulk publish, I then wanted to view my validation error for each activity , but I wasn't clear how to do this, can we discuss tomorrow on the call?

Just before publshing the activities at the end, the user can see the errors, warnings and critical errors in each activity by expanding and similar to single activity publishing, all the errors, warnings and critical errors are listed within the activities' detail pages 

![Uploading Screen Shot 2022-08-23 at 10.34.13.png…]()

**Comment by nirvanalama** [comment]
Here is the updated Bulk Publish Flow:

@k8hughes @titiolukole @praweshsth @Rohini-IATI 

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=9481%3A163952&node-id=9481%3A183768&viewport=-2444%2C-461%2C0.06&scaling=min-zoom&starting-point-node-id=9481%3A183768

**Comment by nirvanalama** [comment]
@Sanilblank
