### ISSUE TITLE
Bulk Publishing

### ISSUE THREAD

**Issue by Sanilblank** [younginnovations/iatipublisher#418]
Implement bulk publishing features for publishing multiple activities by the user

TASKS

- [x] Check selected activities core elements completed
- [x] Selection of activities and individual validation on IATI
- [x] Save validation response in database
- [x] Show categorized and summarized list of activities and errors
- [x] Initialize jobs with status for performing bulk publishing
- [x] Show modal at the bottom right of the screen to show the progress of bulk publishing
- [x] After success or failure update jobs

**Comment by Sanilblank** [comment]
For this to work, horizon and redis need to be setup.
Install redis on your system and then run composer update.

QUEUE_DRIVER=redis
QUEUE_CONNECTION=redis
REDIS_CLIENT=predis

Set these in .env file.
Also, if validator API key and such required for publishing activities have not been set in .env file then need to set them.

**Comment by man-git007** [comment]
@SauravSilwal10 Could you please verify this in the staging server?
