### ISSUE TITLE
Setting Page UI

### ISSUE THREAD

**Issue by nirvanalama** [younginnovations/iatipublisher#42]
Related issues: #26 
Design Link: https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=3332%3A41372&node-id=3332%3A41384&viewport=350%2C48%2C0.2&scaling=min-zoom&starting-point-node-id=3332%3A41384

**Comment by nirvanalama** [comment]
@AudreyIATI @Rohini-IATI @k8hughes 

Here is the design of the settings page. Please look into it and provide feedbacks.

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=3332%3A41372&node-id=3332%3A41384&viewport=350%2C48%2C0.2&scaling=min-zoom&starting-point-node-id=3332%3A41384

**Comment by andreaszenasidi** [comment]
@nirvanalama looks good!

**Comment by k8hughes** [comment]
Yes this looks good 👍

**Comment by andreaszenasidi** [comment]
@nirvanalama this is approved. Only thing is that Publisher ID needs to be made mandatory.

**Comment by praweshsth** [comment]
@andreaszenasidi thank you.
