### ISSUE TITLE
Bug :Activity Detail>>User can unpublished same activity  multiple times

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#422]
Context

Desktop
Chrome 102.0.5005.61
Precondition

- https://stage.iatipublisher.yipl.com.np/

- Username: Publisher 3

- Password: test1234

- for created activity
step
- Click the unpublished button

Actual Result
- Users can unpublished same activity multiple times

Expected Result
- An error message should display regarding the unpublished activity data 

https://user-images.githubusercontent.com/78422663/186346093-c2f84a15-5227-45a0-bfd8-2aa31cc5d6e4.mp4

**Comment by man-git007** [comment]
@Sanilblank What is the status of this issue?

**Comment by Sanilblank** [comment]
@man-git007 This issue has been fixed
