### ISSUE TITLE
Bug :Sorting algorithm is not working properly.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#439]
Context
- Desktop
- Chrome 102.0.5005.61

Preconditions
- https://stage.iatipublisher.yipl.com.np/
- Username: publisher
- Password:12345678

Actual Result
![Screenshot from 2022-08-29 13-52-38](https://user-images.githubusercontent.com/78422663/187156253-f316c78a-faf5-4c99-a915-948364869d80.png)

Expected Result
- Sorting should be updated as per time.

**Comment by man-git007** [comment]
@SauravSilwal10 Fixed. Please check
