### ISSUE TITLE
Devops: Maintenance and Support

### ISSUE THREAD

**Issue by pravin-yipl** [younginnovations/iatipublisher#446]
- [x] Pass env variable on docker build
- [x] Multistage docker build including node run time
- [x] Add env variable in production - k8s

**Comment by pravin-yipl** [comment]
- [ ] Pass env as a file
- [ ] add supervisor conf and install supervisor in dockerfile
- [ ] add redis server and config on k8s cluster

**Comment by man-git007** [comment]
@pravin-yipl What is the status of this issue?If this has been done and merged in `main` branch then lets close this issue

**Comment by pravin-yipl** [comment]
Yes. It's done
