### ISSUE TITLE
Bug :setting>>default issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#447]
Context
- Desktop
- Chrome 103.0.5060.114

Preconditions
- stage.iatipublisher.yipl.com.np
- Username: Ram
- Password: 12345678
- set default language and currency 

- [x] **Issue 1 :Language is not automatically set when a new activity is added.**
Actual Result
https://user-images.githubusercontent.com/78422663/187616866-0d2dea0c-cce0-4c4e-85f3-112456bf3f52.mp4

Excepted Result
- There shouldn't be any language check when creating an activity if the default language is specified in the settings.

- [x] **Issue 2 : default currency  and default language are not dynamic** 
Actual Result
https://user-images.githubusercontent.com/78422663/187621666-76acadcf-674a-49ad-bab7-ccf72ef39b87.mp4

Excepted Result
- should be dynamic

- [x] **Issue 3 :Duplication of currency and language**
Actual Result
![Screenshot from 2022-08-31 13-16-38](https://user-images.githubusercontent.com/78422663/187619591-96a7594f-8acf-423a-a604-719f593b7eba.png)
Excepted Result

- A proper validation should be done in edit form.

- [x]  **Issue 4 :when user changes default currency  and default language in setting but  changes doesn't appear in activity detail page**
Actual Result
https://user-images.githubusercontent.com/78422663/187621492-5a9532b4-158b-4c53-b41d-d13ef47cf962.mp4
Excepted Result
- Changes should appear in activity detail page.

**Comment by man-git007** [comment]
@sriza @Sanilblank What is the status of this issue?

**Comment by man-git007** [comment]
@Sanilblank What is the status of this issue?

cc @SauravSilwal10 @sriza

**Comment by Sanilblank** [comment]
This issue has been resolved
