### ISSUE TITLE
Proxy Design flow

### ISSUE THREAD

**Issue by nirvanalama** [younginnovations/iatipublisher#449]
### Proxy Design Prototype

@praweshsth @titiolukole @k8hughes @DaveEade49 

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=9984%3A170652&node-id=9987%3A170928&viewport=564%2C246%2C0.18&scaling=scale-down&starting-point-node-id=9987%3A170928

Let us know if you have any feedbacks.

**Comment by nirvanalama** [comment]
@Sanilblank

**Comment by man-git007** [comment]
@titungdup Could you please go through the design and implement the UI part of it?
