### ISSUE TITLE
Bug : UI issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#458]
- [x] **Issue 1 : Core element icon is  missing from collaboration-type.**
Actual Result
![Screenshot from 2022-09-01 15-54-07](https://user-images.githubusercontent.com/78422663/187890814-fa958370-ff99-48d2-a1c5-2990ea8677c1.png)
Expected Result
- Core element icon should be present 
- [ ] **Issue 2: Hyphen should be used instead of underscore**
Actual Result
![Screenshot from 2022-09-01 16-19-45](https://user-images.githubusercontent.com/78422663/187894438-0f4871da-fa88-4772-816a-694613714b15.png)
- [x] **Issue 3 : UI breakdown**
![Screenshot from 2022-08-31 17-13-31](https://user-images.githubusercontent.com/78422663/187668650-4d921ee3-7ab8-4f60-93b0-b506d315a1c6.png)

- [x] **Issue 4 : Spacing is needed** 
![Screenshot from 2022-08-31 17-14-26](https://user-images.githubusercontent.com/78422663/187668804-b0485912-ebd9-4074-bdfa-a9b50277e8cb.png)

- [x] **Issue 5: #420 issue 3**

- [x] **Issue 6: Unwanted space in participating-org and location** 

Actual Result
![Screenshot from 2022-09-02 10-23-57](https://user-images.githubusercontent.com/78422663/188061289-ce07369c-089d-4a4a-97a1-94a26bf140db.png)

Excepted Result
- Spacing should be reduced 

- [x] **Issue 7: Unaligned show period list button** 

Actual Result
![Screenshot from 2022-09-02 10-32-49](https://user-images.githubusercontent.com/78422663/188061155-1549179e-bb34-4e08-9d35-83c9c90271ee.png)
Expected Result
- show period list button should be aligned

- [x] **Issue 8: In indicator Inconsistent UI for the same attribute**

Actual Result
![Screenshot from 2022-09-05 16-53-23](https://user-images.githubusercontent.com/78422663/188436813-293b1985-48cc-4ba4-8c8c-bb414a0b99b5.png)

Expected Result
- Should be inconsistent.

- [x] **Issue 9: Bold letter in Result**
Actual Result
![Screenshot from 2022-09-05 17-05-51](https://user-images.githubusercontent.com/78422663/188437805-403e3520-a5f0-44b0-9bfe-4956689b7a1f.png)
Expected Result
-Should not be bold

- [x] **Issue 10: inconsistent font-size**
Actual Result
![Screenshot from 2022-09-05 17-19-44](https://user-images.githubusercontent.com/78422663/188439775-a7dc0631-ca0d-439d-b075-5a8890154e98.png)
![Screenshot from 2022-09-05 17-19-10](https://user-images.githubusercontent.com/78422663/188439799-d2581103-685c-4b66-acd2-b0dca6ad5f8d.png)
Expected Result
- Should be consistent

- [x] **Issue 11 :inconsistent way to display data in activity detail page**
Actual Result
![Screenshot from 2022-09-05 17-24-58](https://user-images.githubusercontent.com/78422663/188440817-0df6685d-ba23-4b61-b262-184bfd58b32e.png)
![Screenshot from 2022-09-05 17-25-16](https://user-images.githubusercontent.com/78422663/188440849-1d1dac10-92ec-4739-91a1-b2e48f94e558.png)
![Screenshot from 2022-09-05 17-25-50](https://user-images.githubusercontent.com/78422663/188440879-4c23ff3a-61e9-478e-881e-1b3b077f1ea2.png)
![Screenshot from 2022-09-05 17-19-44](https://user-images.githubusercontent.com/78422663/188440958-05992196-4f86-42bc-9eea-41d60381525c.png)
Expected Result
- Should be consistent

- [x] **Issue 12 : Inappropriate way to display breadcrumb in activity detail page**
Actual Result
![Screenshot from 2022-09-15 10-09-58](https://user-images.githubusercontent.com/78422663/190314559-2a424297-c5e3-42c7-80a9-a16b69d03f20.png)
Excepted Result
![Screenshot from 2022-09-15 10-10-36](https://user-images.githubusercontent.com/78422663/190314585-7c6d0989-6b34-4c14-ae13-0e23c5dbfe6e.png)

**Comment by man-git007** [comment]
@SauravSilwal10 Regarding Issue 2: Should the hyphen be in all attributes like a date as well?

**Comment by SauravSilwal10** [comment]
@man-git007 Yes, if it's feasible.

**Comment by man-git007** [comment]
@SauravSilwal10 @jenishshrestha 
Issue 1 has been done and will be deployed later

**Comment by man-git007** [comment]
@SauravSilwal10 Deployed to the staging server. Lets check this on Monday

**Comment by man-git007** [comment]
@titungdup What is the status of this issue?

**Comment by man-git007** [comment]
@titungdup Can we test this today in the stage server?
@SauravSilwal10 Move this issue to backlog

**Comment by titungdup** [comment]
@man-git007 All issues are fixed except for Issue 2 which needs discussion.

**Comment by man-git007** [comment]
@SauravSilwal10 Let's move issue 2 to backlog and test all the other issues. If ok we will close this issue and the issue2 will be moved to the backlog

cc @praweshsth @titungdup

**Comment by man-git007** [comment]
@SauravSilwal10 Let's move issue 2 to backlog and test all the other issues. If ok we will close this issue and the issue2 will be moved to the backlog

cc @praweshsth @titungdup

**Comment by SauravSilwal10** [comment]
For issue 2 please refer to issue #489
