### ISSUE TITLE
Activity detail page UI

### ISSUE THREAD

**Issue by nirvanalama** [younginnovations/iatipublisher#46]
Related issues: #12 
Design Link: https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=34%3A327&node-id=1426%3A16559&viewport=350%2C48%2C0.46&scaling=min-zoom&starting-point-node-id=1862%3A40201&show-proto-sidebar=1

**Comment by nirvanalama** [comment]
@Rohini-IATI @AudreyIATI @k8hughes 

Here is the activity detail page design after the feedbacks we received.

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=34%3A327&node-id=1426%3A16559&viewport=350%2C48%2C0.46&scaling=min-zoom&starting-point-node-id=1862%3A40201&show-proto-sidebar=1

**Comment by andreaszenasidi** [comment]
@nirvanalama looks good to me, only one suggestion to order the below list to have the core elements first, followed by the rest of the elements:
![image](https://user-images.githubusercontent.com/74558657/161992042-0a2d2e50-4159-4eb4-8e74-eed97dceb337.png)

Lets see what others think.

**Comment by praweshsth** [comment]
@andreaszenasidi I think we will be discussing this (regarding the core or recommended+mandatory elements) today.

**Comment by nirvanalama** [comment]
Hello. We made changes according to the feedback we discussed at the last meeting.

https://www.figma.com/file/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?node-id=1426%3A16559

**Comment by k8hughes** [comment]
I have left some comments in figma - I think we are nearly there!
