### ISSUE TITLE
Bug: Activity Issue

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#462]
- [x] **Issue 1: Indicator listing page  display wrong information**
Actual Result
https://user-images.githubusercontent.com/78422663/188055878-76d00d46-27af-4aa9-a20e-f2094ae2917d.mp4
Expected Result
- Accurate information should be displayed
- [x] **Issue 2: element status of other-identifier is not working**
Actual Result

https://user-images.githubusercontent.com/78422663/188067225-8f10dcc1-653d-401a-909c-5eee5d9f20c1.mp4

Excepted Result
- Should work properly.

**Comment by man-git007** [comment]
@SauravSilwal10 Worked on it and after delete module tested. Will deploy this update.

**Comment by man-git007** [comment]
@SauravSilwal10 Deployed to the staging server. Lets check this on Monday
