### ISSUE TITLE
Activity List - Header after login (UI/UX implementation) and other components

### ISSUE THREAD

**Issue by jenishshrestha** [younginnovations/iatipublisher#47]
- [x] Header frontend development.
- [x] Pagination component.
- [x] Code refactor of Vue components after typescript and vue 3 implementation.
- [x] When one or more activity is/are selected, show 'Publish Selected' and 'Delete Selected' buttons
- [x] Sticky Toast Message UI - "5 activities ready to publish Publish all"
- [x] Code refactor of all components using composition api of vue 3

Parent issue: #37

**Comment by man-git007** [comment]
Manually closed
