### ISSUE TITLE
Bug : Drop Down Issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#470]
Context
- Desktop
- Chrome 103.0.5060.114

Preconditions
- stage.iatipublisher.yipl.com.np
- Username: Ram
- password: 12345678

Steps
- Select the drop-down options

Actual Result
- remove the icon is missing from the drop-down options

Expected Result
- remove the icon should be in the drop-down options

https://user-images.githubusercontent.com/78422663/188442470-e3bb2ba7-67a8-4a45-bf68-27d76ebcc1b7.mp4

**Comment by man-git007** [comment]
@SauravSilwal10 Move this issue to backlog.
@jenishshrestha Can we fix this issue today?

**Comment by man-git007** [comment]
@jenishshrestha Did you get time to look into this? If not lets assign to @titungdup

**Comment by man-git007** [comment]
@titungdup We have merged this to the `main` branch, right? If we have merged it lets close this issue.

**Comment by titungdup** [comment]
@man-git007 okay.
