### ISSUE TITLE
Bug : Delete module>> Period delete button is not working.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#477]
Context
- Desktop
- Chrome 103.0.5060.114

Preconditions
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password:12345678
- for created activity
 
Steps
- Period listing page  >> click the delete button

Actual Result
-  delete button is not working.

Expected Result
- Should work properly.

https://user-images.githubusercontent.com/78422663/189320119-81138545-f62f-4c5a-a78f-010db50eadfc.mp4

**Comment by man-git007** [comment]
@SauravSilwal10 Done and deployed to the staging server. Please verify.
