### ISSUE TITLE
Activity List UI

### ISSUE THREAD

**Issue by nirvanalama** [younginnovations/iatipublisher#48]
Related issues: #37  
Design Link: https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?node-id=1426%3A16260&scaling=min-zoom&page-id=34%3A327&starting-point-node-id=1426%3A16260

**Comment by nirvanalama** [comment]
@AudreyIATI @k8hughes @Rohini-IATI @amy-silcock 

Activity list UI design. Please review and provide feedbacks. Thank you. 

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?node-id=1426%3A16260&scaling=min-zoom&page-id=34%3A327&starting-point-node-id=1426%3A16260

**Comment by praweshsth** [comment]
@andreaszenasidi the unpublish will be in the detail page of the activity.

**Comment by andreaszenasidi** [comment]
@praweshsth this is approved.

**Comment by praweshsth** [comment]
Thank you @andreaszenasidi
