### ISSUE TITLE
Assistive text below the text fields

### ISSUE THREAD

**Issue by nirvanalama** [younginnovations/iatipublisher#486]
Here are two design option for the Additional Information below the text fields 

### Sticky Option

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=8596%3A139561&node-id=10397%3A172722&viewport=-336%2C1183%2C0.13&scaling=min-zoom&starting-point-node-id=10397%3A172722&show-proto-sidebar=1

https://user-images.githubusercontent.com/57661914/189868921-b1cbd33a-6d49-4575-9ab4-6a97cae97383.mov

### Hover Option

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=8596%3A139561&node-id=10403%3A182574&viewport=-336%2C1183%2C0.13&scaling=min-zoom&starting-point-node-id=10403%3A182574&show-proto-sidebar=1

https://user-images.githubusercontent.com/57661914/189868955-b6b94820-8f8f-4255-b337-a9d665f879e7.mov

@Rohini-IATI @DaveEade49 @k8hughes @praweshsth

**Comment by praweshsth** [comment]
@nirvanalama 

1. The first iteration, where the information is sticky in the side. 
2. Change 'Assistive text' to 'Help'
3. Show 'IATI Standard Reference' at the top of all the hover over text

**Comment by nirvanalama** [comment]
@praweshsth @Rohini-IATI @DaveEade49 @k8hughes 


https://user-images.githubusercontent.com/57661914/190316983-55312ea9-ad84-430b-92e3-025382331c5d.mov

**Comment by nirvanalama** [comment]
@Rohini-IATI @k8hughes @praweshsth @DaveEade49 

There was little space on the right side so we had to move the Help text to the left.

https://user-images.githubusercontent.com/57661914/190370406-d1d9c2dd-7881-4179-932c-7731095724f7.mov

**Comment by k8hughes** [comment]
As I didn't join the discussion on this one I don't feel able to comment @Rohini-IATI are you happy?

**Comment by DaveEade49** [comment]
Moving the help box to the left makes sense due to space - so that is fine with me.

Have we also checked how it renders on a tablet?

Dave

**Comment by Rohini-IATI** [comment]
Yes this is great, please implement
