### ISSUE TITLE
Bug : Arrangement of label fields 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#487]
- [x] **Issue 1: Iati- Identifier**
Actual Result
![Screenshot from 2022-09-14 13-04-30](https://user-images.githubusercontent.com/78422663/190087473-5e9d6cea-10db-4c83-a137-bd3e0067a9aa.png)

Expected Result
- Should be aligned in the same line

- [x] **Issue 2: Transactions** 
Actual Result
![Screenshot from 2022-09-14 13-09-04](https://user-images.githubusercontent.com/78422663/190088439-28af7802-97c2-4215-9838-3e1ebbce5ae6.png)

Expected Result
![Screenshot from 2022-09-14 13-09-47](https://user-images.githubusercontent.com/78422663/190088585-c51c6404-b7a2-44b9-a389-bb91c379bdc5.png)

- [x] **Issue 3 : Result**
Actual Result
![Screenshot from 2022-09-14 13-10-47](https://user-images.githubusercontent.com/78422663/190088747-0cff62cd-808f-4c43-a402-8eb76d59645e.png)

Expected Result
- Should be aligned in the same line

- [x] **Issue 4 : Indicator** 
Actual Result
![Screenshot from 2022-09-14 13-13-46](https://user-images.githubusercontent.com/78422663/190089428-05440a24-9d6b-4dac-a13e-a63bbf3c31a4.png)

Expected Result
![Screenshot from 2022-09-14 13-12-35](https://user-images.githubusercontent.com/78422663/190089489-15cfe16f-2b5a-4816-bbf2-d367da6c1303.png)

- [x] **Issue 5 :organisation data >>organisation-identifier** 

Actual Result
![Screenshot from 2022-09-15 10-40-21](https://user-images.githubusercontent.com/78422663/190318000-743060f1-ab6a-427e-9f61-579b7f8611da.png)
Expected Result
- Should be aligned in the same line

**Comment by jenishshrestha** [comment]
Fixed this issue in branch [code-and-bug-fixes](https://github.com/younginnovations/iatipublisher/compare/code-and-bug-fixes)

**Comment by man-git007** [comment]
> Fixed this issue in branch [code-and-bug-fixes](https://github.com/younginnovations/iatipublisher/compare/code-and-bug-fixes)

Seems OK
