### ISSUE TITLE
Bug : Linked Data URI is present in Settings

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#488]
Context 
- Chrome 104.0.5112.101 
- Desktop 

Preconditions 
- https://stage.iatipublisher.yipl.com.np
- Username: Ram
- Password:12345678

Steps
- Go to setting

Actual Result
![Screenshot from 2022-09-14 13-56-03](https://user-images.githubusercontent.com/78422663/190098565-dbc9aaf9-06a4-4829-a9c6-fe50f1153e55.png)

Expected Result
- Linked Data URI should be removed from Settings

**Comment by Sanilblank** [comment]
This issue has been worked on by Shreeja

**Comment by SauravSilwal10** [comment]
Issue Fixed
