### ISSUE TITLE
Backlog 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#489]
- [ ] **Issue 1**: #154 
- [ ] **Issue 2**: #157 
- [ ] **Issue 3**: #372
- [x] **Issue 4**: #397 
- [ ] **Issue 5:When inserting the special character like #,_,% without matching the IATI-identifier and Title name, the result is displayed.**
Actual Result

https://user-images.githubusercontent.com/78422663/190144009-37a2013b-704e-4731-9227-05b367bc8eb0.mp4

Excepted Result
- Result shouldn't  be displayed until IATI-identifier and Title name is matched.

- [ ] **Issue 6:** #177 
- [ ] **Issue 7**: #149 
- [ ] **Issue 8: proxy issue** 

- steps 

1. create two instances 

**instance 1**
1. log in as a normal user 
2. try to publish the activity 

**instance 2**
1. log in as the proxy 
2. delete the same activity that the user wants to publish

Actual Result
- the user's system freezes when they attempt to publish their activities

Expected Result
- An error message might be helpful to users

https://user-images.githubusercontent.com/78422663/195293424-51137642-ddbb-4da3-aa9d-d57387ad0677.mp4

- [ ] **Issue 9 : Email verification page issue** 

steps

**instance 1**
- open https://iatipublisher-dev.yipl.com.np/ in one tab
- login as normal user
- click send verification email  continuously  

**instance 2** 
- open gmail in next tab
- email is send to the particular gmail

Actual Result
- activity detail page doesn't get  refresh automatically 
- no error message for previous email

Excepted Result
- automatically refresh page might be help to the user
- hash value should be checked and session expired error message should be displayed  
- only lastest email should work 

 

https://user-images.githubusercontent.com/78422663/196095968-88117eeb-8489-4477-9b17-c327035ad079.mp4

- [ ] #618 issue 2

**Comment by man-git007** [comment]
@sriza @jenishshrestha Lets look into issue 7,8,9,10
