### ISSUE TITLE
Bug : Core element is missing from sidebar of activity detail page

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#490]
Context
- Chrome 104.0.5112.101
- Desktop

Preconditions
- https://stage.iatipublisher.yipl.com.np/
- Username: Ram
- Password:12345678
- for created activity

Steps
- click the core element 

Actual Result

https://user-images.githubusercontent.com/78422663/190315426-b3dff54f-d059-4def-b211-0ce3369240df.mp4

Excepted Result
-  core element  should be present

**Comment by man-git007** [comment]
@titungdup Can you please look into this.

**Comment by jenishshrestha** [comment]
This is has been fixed in branch [code-and-bug-fixes](https://github.com/younginnovations/iatipublisher/compare/code-and-bug-fixes).
