### ISSUE TITLE
Feedback on bulk publish

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#510]
- [x] 1. When multiple activity files are selected, remove ‘Delete Selected’ button
- [x] 2. When an activity is just created and validated using IATI Validator so in the error message in the activity detail page:
       - there is a critical error ‘ Element 'iati-activity', attribute 'humanitarian': 'yes' is not a valid value of the atomic type 'xs:boolean’.’ The humanitarian value in the XML not in the form, should be boolean instead of Yes or No.
       - There is another critical error ‘Element 'iati-activity': Missing child element(s). Expected is ( description ).’ Why is this shown here?
       - There is a warning ‘The activity identifier should begin with your IATI organisation identifier (either the current IATI Organisation identifier for the reporting organisation or a previous version included in other-identifier element) followed by a unique string for the activity separated by a hyphen’. Probably the activity identifier doesn’t begin with the organisation identifier in the XML file
- [x] 3. After validation via IATI validator, the user can see the summary of the errors by expanding using ‘Show more’ link in the list of errros. There is a link that takes users to detail page of that particular activity. The link should open the detail page in a new tab of browser rather than opening the activity detail page in same tab. 
- [x] 4. When publishing of activities is completed, the list page doesn't refresh and show which activities are published hence once the publishing is complete, the page should be refreshed and show the activities are published.
- [x] 5. If the user tries to publish already published activity, which has no changes, the first notice the user sees is that already published activity will not be processed for publishing. But the user can see that activity in the list of core element completion and after validation from IATI validator. Don’t show the unchanged published activity in the process of publishing from the start. 
- [x] 6. In the list of core elements completed or not and errors after validation, the activity title have the link to the detail page of the activity. Should that be there?

**Comment by man-git007** [comment]
@titungdup Can you look into Issue 1,3
@Sanilblank Can you look into Issues 2,4,5,6

cc @praweshsth @AbiChitrakar @SauravSilwal10

**Comment by jenishshrestha** [comment]
Completed and pushed in branch 418-bulk-publishing.

**Comment by man-git007** [comment]
@SauravSilwal10 Please verify this.

**Comment by praweshsth** [comment]
@Sanilblank for issue no. 4, let's put a notification that the user can refresh the activity listing page or go to listing page to see the changes after all the activities have been published.

**Comment by Sanilblank** [comment]
> @Sanilblank for issue no. 4, let's put a notification that the user can refresh the activity listing page or go to listing page to see the changes after all the activities have been published.
> 
> We might need @nirvanalama help here.

@jenishshrestha

**Comment by man-git007** [comment]
@Sanilblank Can we close this issue?

cc @praweshsth @SauravSilwal10

**Comment by man-git007** [comment]
@Sanilblank Lets close this issue.

cc @praweshsth @SauravSilwal10
