### ISSUE TITLE
Bug : User experience is poor while publishing activities and bulk publications

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#526]
Context
- Chrome : 104.0.5112.101
- Desktop

Preconditions
- https://stage.iatipublisher.yipl.com.np/
- Username:Ram
- Password:12345678

Actual  Result

https://user-images.githubusercontent.com/78422663/191926828-a49957d7-c65d-459e-b4d3-2bf9bcbfeb4d.mp4

https://user-images.githubusercontent.com/78422663/191926856-b6041fb7-005c-4c57-96a2-957ac015c8f2.mp4

Expected Result
- The background button should not be enabled while publishing the activity.
- For the user to have a good publishing experience, the activity background should be covered by a white screen.

**Comment by jenishshrestha** [comment]
Solved in branch 533-override-activity-default-values.

**Comment by man-git007** [comment]
@jenishshrestha Please look into this issue today.

cc @SauravSilwal10

**Comment by man-git007** [comment]
@SauravSilwal10 What is the status of this issue? If hasn't been done @titungdup Can you look into this?

cc @jenishshrestha @titungdup

**Comment by titungdup** [comment]
@man-git007 This issue is fixed and deployed. Closing it.
