### ISSUE TITLE
Checking Hover and Help section in different labels .

### ISSUE THREAD

**Issue by AbiChitrakar** [younginnovations/iatipublisher#544]
Context
- Version 105.0.5195.125 (Official Build) (64-bit)
- Desktop

Preconditions
- https://stage.iatipublisher.yipl.com.np/
- Username:abuie
- Password:aaaaaaaa

Actual  Result
- [ ] **Reporting Organization** Page is leading to 404 Not Found. So can not check the sub-element and attributes present in it. 

- [x]  Under **activity-status**, we can not  hover to view texts and Help is also missing.
![image](https://user-images.githubusercontent.com/72198302/192679483-dd0de695-8469-43f4-a982-bd67451101b1.png)

- [x] Under **Activity scope**,there is no hover text.

- [x]  Under **Recipient region**, Recipient region--> **code** ,the Help is missing 
![image](https://user-images.githubusercontent.com/72198302/192680587-b685a230-dca3-49b8-8e7e-b7597d819761.png)

- [x] Under **Recipient region** Element , the **vocabulary URL** attribute is missing .
![image](https://user-images.githubusercontent.com/72198302/192681011-7b684ff2-154a-4a10-a67e-0eb8cd679e5c.png)

- [x] Under **Recipient region** Element ,under **percentage** attribute the hover text is missing .
![Screenshot from 2022-09-28 09-14-17](https://user-images.githubusercontent.com/72198302/192681435-ac4c65b6-adca-41d1-be18-53373ee5eef4.png)

- [x] Under **location** element, under the  **Pos** sub-sub element the hover text is missing. (also the Latitude and Longitude field is also missing in the shared document)
![image](https://user-images.githubusercontent.com/72198302/192682419-b2cd8418-02e0-485c-a69b-fbe67ba5132d.png)

- [x] Under **sector**  element ,the  whole **vocabulary url** attribute is missing.
![image](https://user-images.githubusercontent.com/72198302/192683732-65ecd5ed-803c-481d-8f8b-38f4acea504d.png)

- [x] Under **tag**  element ,the  whole **vocabulary url** attribute is missing.
![image](https://user-images.githubusercontent.com/72198302/192690798-17f44b3f-fb4d-429e-8a1e-c1a21e3b3257.png)

- [x] Under **country-budget-items** ,the ? Hover to view texts is missing. 
![image](https://user-images.githubusercontent.com/72198302/192691284-babcdd96-0232-4933-bdd5-fec6a8e04a2e.png)

- [x] Under **country-budget-items** ,under the **Budget item** sub-element the  ? Hover to view texts is missing. 
(but rather **Help** is present in the development whose description is not there in documents)
![image](https://user-images.githubusercontent.com/72198302/192692087-57d3ce14-b063-4b60-a248-9a26457e46d5.png)

- [x] Under **country-budget-items** ,under the **vocabulary** attribute the **Help** field is missing.
![Screenshot from 2022-09-28 10-44-13](https://user-images.githubusercontent.com/72198302/192691564-955556a8-818a-4da2-a080-6c1b4555389b.png)
- [x] Under **humanitarian-scope**  element ,the  whole **vocabulary url** attribute is missing.
![image](https://user-images.githubusercontent.com/72198302/192692993-87d39541-80fd-4f5c-beb3-184dd0579cce.png)

- [x] Under **policy-marker**  element ,the  whole **vocabulary url** attribute is missing.
![image](https://user-images.githubusercontent.com/72198302/192703126-b10134e9-5e0d-4114-8492-43523b212592.png)

- [x] Under **collaboration-type**  element, the ? Hover and  Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192703782-94ac2146-cbfd-4142-8f8a-1c6196a993f7.png)

- [x] Under **default-flow-type**  element, the ? Hover and  Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192704300-bbfcff00-9430-47ef-b7d8-da96d1c864f8.png)

- [x] Under **default-finance-type**  element, the ? Hover and  Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192704623-221352a3-2d8d-4985-ae8f-82ca204d02bf.png)

- [x] Under **default-aid-type**  element, the ? Hover and  Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192704887-acd552a9-a94b-4d28-9729-cb1f4ebd9aec.png)

- [x] Under **default-tied-status**  element, the ? Hover and  Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192705248-f448787a-3a47-48c4-8c51-8e4242618376.png)

- [x] Under **budget**  element,  under the **Period start**  Sub-element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192706303-b7ff6c9a-3b0c-4c43-9c20-18b45c81f33d.png)

- [x] Under **budget**  element,  under the **Period end**  Sub-element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192707184-ce1d265e-f830-4dfd-a0cc-87e5497b1e7c.png)

- [x] Under **budget**  element,  under the **Budget value**  Sub-element, the ? to  Hover  is missing.
![image](https://user-images.githubusercontent.com/72198302/192707711-ba9674ee-3eaa-440d-b297-a26400701d12.png)

- [x] There is **amount** attribute in the development but not the description of it in shared docuement.
![image](https://user-images.githubusercontent.com/72198302/192708000-715f0437-8d7d-4f44-9926-9cde2a9d1d99.png)
  
- [x] The element **planned-disbursement**  has two different ?  to hover  and showing different description of it .
![image](https://user-images.githubusercontent.com/72198302/192708918-3ffda924-038a-4a9b-a527-e92ad0ddc37b.png)

Hovering over first ? is showing title description.
![image](https://user-images.githubusercontent.com/72198302/192709260-ae667ed5-bdb0-46f6-9ab3-27caa25931ff.png)
 
- [x] Under **planned-disbursement**  element, under the **Value** Sub-element the ? to Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192710484-21336c8a-199f-4540-a9ec-4a7a621ab995.png)

- [x] Under **planned-disbursement**  element,  the **capital spend** sub-element and **percentage** attributes are missing (lookig at the document, i.e looking last two rows from https://docs.google.com/document/d/1tMDFR2lHUwkO2l-hSXGB24spBZA-pWgAqyZXco-PSQY/edit)

- [x] Under **document-link**  element, the ? Hover is missing.
![Screenshot from 2022-09-28 14-31-25](https://user-images.githubusercontent.com/72198302/192735148-15bb4322-37e5-4318-9a82-404888348264.png)

- [x] Under **document-link**  element, under the **url** attribute, the ? Hover is missing.
![Screenshot from 2022-09-28 14-34-41](https://user-images.githubusercontent.com/72198302/192735195-77f88e57-ec7d-4a48-95b6-70294c2de67c.png)

- [x] Under **document-link**  element, under the **format** attribute, hovering over the ? is just showing format.
![image](https://user-images.githubusercontent.com/72198302/192735800-26724ae0-2fba-4b21-bd7f-2a4f41ef5a77.png)

- [x] No description of document attribute in the provided documents ,where the document attribute lies under the document-link element 

- [x] Under **document-link**  element, under the **Title** sub-element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192737310-4085168b-9029-46ba-97c3-04a84f89a341.png)

- [x] Under **document-link**  element, under the **Description** sub-element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192737717-5f76ac1f-edfe-4626-99fd-36fd629d784b.png)

- [x] Under **document-link**  element, under the **Category** sub-element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192738006-f8154b17-93a3-4bf4-acb5-b8e82ed67d76.png)

- [x] Under **document-link**  element, under the **Category** sub-element,  under the **code** attribute ,hovering over the ? is just showing code.
![image](https://user-images.githubusercontent.com/72198302/192738789-94e3918a-d2bd-45da-9bc5-b666d81c1bb4.png)

- [x] Under **document-link**  element, under the **Language** sub-element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192739016-905cf9de-e926-4a4f-8655-d67dbba8e25f.png)

- [x] Under **document-link**  element, under the **Document date** sub-element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192739525-94b469ba-504b-42a4-b224-3ab2761bba89.png)

- [x] Under **related-activity**  element, the ? Hover and  Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192740357-7aa57119-b9e1-4708-a164-b2e2ddf8f348.png)

- [x] Under **legacy-data**  element, the ? Hover and  Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192740779-46751d8b-ebe5-4e24-bbef-4c981aa7404a.png)

- [x] Under **conditions**  element, the ? Hover and  Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192741174-684627dd-553d-4503-9d20-464b74465cba.png)

- [x] Under **conditions**  element, under the **Condition** sub-element, hovering over the ? is showing just the description as  Condition( and **Help** in **Condition** sub-elements is not required as per the provided document https://docs.google.com/document/d/1SvcpMHH7b0lBzxJTjAnhkbo26wF_avEAd6YjcZVAhZM/edit) .
![Screenshot from 2022-09-28 15-07-23](https://user-images.githubusercontent.com/72198302/192742693-79c6ed5a-3e15-4e9b-8ff2-08347c55297f.png)

- [x] Under **result**  element, the ? Hover and  Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192743505-f7199538-8775-4e64-808a-8f332def7e04.png)

- [x] Under **result**  element, under the **Title**  Sub-element the ? Hover is missing but Help is present which should not be present as per the provided document.
![image](https://user-images.githubusercontent.com/72198302/192744426-20aae1af-700e-4126-ab24-084d4918fd79.png)

- [x] Under **result**  element, under the **Description**  Sub-element the  Help is present which should not be present as per the provided document.
![image](https://user-images.githubusercontent.com/72198302/192751941-3b9b7a09-9cae-4c33-ae95-8297b2296bcd.png)

- [ ] Under **indicator**  sub-element, the ? Hover and  Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192933803-b9eac144-1293-47fe-a7b1-fe0f7b28dfd5.png)

- [ ] Under **indicator**  sub-element, under **Title**  sub-sub-element, the ? Hover is missing but Help is present which is not required. as per the docs.
![image](https://user-images.githubusercontent.com/72198302/192934019-912e0cae-52cd-4191-bf05-dd5150c51016.png)

- [ ] Under **indicator**  sub-element, under **Description**  sub-sub-element, the Help is present which is not required. as per the docs.
![image](https://user-images.githubusercontent.com/72198302/192934221-42040448-5e37-45a3-8c20-f3658c5d3e22.png)

- [ ] Under **indicator**  sub-element, under **Title**  sub-sub-sub-element, the ? Hover is missing but Help is present which is not required. as per the docs.
![image](https://user-images.githubusercontent.com/72198302/192935027-f15898ee-f869-40e0-a36f-f033229e8417.png)

- [ ] Under **indicator**  sub-element, under **Category**  sub-sub-sub-element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192935427-deafaaf5-4c60-4dd6-a1e9-2bd912edd8ad.png)

- [ ] Under **indicator**  sub-element, under **Baseline**  sub-sub-element, the Help is not showing complete description as per the docs.
![image](https://user-images.githubusercontent.com/72198302/192936170-93955066-3fb7-4b9f-9e52-eaedb507bfd2.png)

- [ ] Under **indicator**  sub-element, under **Document link**  sub-sub-sub-element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192938018-24c13ef9-cee8-4d8d-9e30-7a0e80c0d5bb.png)

- [ ] Under **indicator**  sub-element, under **Category**  sub-sub-sub-sub-element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192938780-60f91146-68ba-444d-a7c3-3ec2b2032548.png)

- [ ] Under **indicator**  sub-element, under **Language**  sub-sub-sub-sub-element, the Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192939384-f3beea6a-781b-4768-919a-09cbf0233cb2.png)

- [ ] Under **indicator**  sub-element, under **Title**  sub-sub-sub- lement, the **language** attribute is missing Help.
![image](https://user-images.githubusercontent.com/72198302/192940769-01773fe6-c5f6-47a5-8a06-1e76a85959be.png)

- [ ] Under **period**  sub-element, the ? Hover and  Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192941429-53d7f3ed-ece2-4893-95cf-d6cc35ae3ee3.png)

- [ ] Under **period**  sub-element, under the **Period start** sub-sub-sub element ,the ? Hover is missing but Help is present which is not as per the docs.
![image](https://user-images.githubusercontent.com/72198302/192941502-d1aee2cb-a87d-40d3-923d-879a8aeea168.png)

- [ ] Under **period**  sub-element, under the **Period end** sub-sub-sub element ,the ? Hover is missing but Help is present which is not as per the docs.
![image](https://user-images.githubusercontent.com/72198302/192944076-534197a8-e2bd-4ab2-a0e5-8eb317d4c0b9.png)

- [ ] Under **period**  sub-element, under the **Title** Sub-sub-sub-sub-sub element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192944808-c7199b84-44d3-4bfd-ac7a-49d21feeff14.png)

- [ ] Under **period**  sub-element, under the **Category** Sub-sub-sub-sub-sub element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192945349-ae68973d-ac53-48bb-bacf-efc7697ed7e5.png)

- [ ] Under **transaction** element, the ? Hover and Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192968267-dc04284f-0627-4782-966c-06790891723d.png)

- [ ] Under **transaction** element, under **Transaction type** sub-element, the ? Hover  is missing.
![image](https://user-images.githubusercontent.com/72198302/192968684-57308fe4-91e5-4bd6-a47e-acf66fa88388.png)

- [ ] Under **transaction** element, under **Transaction date** sub-element, the ? Hover  is missing but Help is present which  should not be present as per the docs .
![image](https://user-images.githubusercontent.com/72198302/192968967-52877c9c-0ae6-48c8-a97d-6204c6c1bd22.png)

- [ ] Under **transaction** element, under **Value** sub-element, the ? Hover  is missing but Help is present which  should not be present as per the docs .
![image](https://user-images.githubusercontent.com/72198302/192969224-001b0b31-a9e5-4868-bbd5-2f185017f5d5.png)

**Comment by Sanilblank** [comment]
@AbiChitrakar Regarding the issues 

1. Under country-budget-items ,under the vocabulary attribute the Help field is missing.
This field does not have help section in the docs

2. Regaring the vocabulary-uri fields the field appears only when user selects 99 or 98 from vocabulary dropdown
3. The amount field is required for us to create the XML data tho it is not actually considered an attribute or sub element
4. The recipient-org redirection issue was being looked at by @man-git007 if I am not mistaken
5. Capital spend is a separate element with its attribute percentage. It does not fall under planned disbursement
