### ISSUE TITLE
Bug : 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#549]
Context 
- Desktop
- Chrome : 104.0.5112.101

Preconditions
- iatipublisher-dev.yipl.com.np
- Username: admin1234
- Password: 12345678 

- [x] **Issue 1 : iati-identifier cancel button is not working** 

Actual Result

https://user-images.githubusercontent.com/78422663/192754923-a2f3d3db-ecff-451c-b37d-842af00a3e4b.mp4

Excepted Result
- Should work properly

- [x] **Issue 2 : No Url validation for document -link in  indicator**  
Actual Result
![Screenshot from 2022-09-28 16-07-38](https://user-images.githubusercontent.com/78422663/192755617-cb43d6ec-bf61-4b72-ac74-6bff31aff949.png)

Excepted Result
- should be validation for Url 

- [x] **Issue 3 : Email field is missing from contact-info in activity-detail page**

Actual Result
![Screenshot from 2022-09-28 16-10-45](https://user-images.githubusercontent.com/78422663/192756062-d920d1a8-2aed-4c2e-8ee2-e25353fa0a73.png)

Excepted Result
- Email field  should present in activity-detail page.

- [x] Issue 4 : **Verification email successfully sent Toast message doesn't disappear from activity listing page**
Actual Result

https://user-images.githubusercontent.com/78422663/192773660-dec6536c-33bb-4fdf-993d-ab4c95060cc1.mp4

Excepted Result
- Toast message  should be removed after certain time .

**Comment by man-git007** [comment]
@sriza Can we finish this issue by today?

**Comment by sriza** [comment]
@man-git007 The bugs listed on this issue are fixed but require testing

**Comment by SauravSilwal10** [comment]
Issue fixed 
cc @sriza  @man-git007
