### ISSUE TITLE
Add/edit acitivity UI

### ISSUE THREAD

**Issue by nirvanalama** [younginnovations/iatipublisher#55]
Related issues: #27 
Design Link: https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=34%3A327&node-id=1493%3A14279&viewport=350%2C48%2C0.46&scaling=min-zoom&starting-point-node-id=1493%3A14279&show-proto-sidebar=1

**Comment by nirvanalama** [comment]
@AudreyIATI @Rohini-IATI @k8hughes 

The link to the Add/edit activity detail page:

https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=34%3A327&node-id=1493%3A14279&viewport=350%2C48%2C0.46&scaling=min-zoom&starting-point-node-id=1493%3A14279&show-proto-sidebar=1

**Comment by andreaszenasidi** [comment]
@nirvanalama not sure if we should be looking at the labels as well in this github issue, but if we do, then the labels should be user friendly, not just a copy of the IATI XML schema element names 
![image](https://user-images.githubusercontent.com/74558657/161990293-85f2aa06-c532-4802-a408-f1b6349a7ca9.png)

Suggestion to order the below list to have the core elements first, followed by the rest of the elements:
![image](https://user-images.githubusercontent.com/74558657/161992042-0a2d2e50-4159-4eb4-8e74-eed97dceb337.png)

**Comment by praweshsth** [comment]
@andreaszenasidi It was discussed before and we had suggested for the same but it was finalized after several discussions to use the exact term from the iati standard. @k8hughes @Rohini-IATI

**Comment by andreaszenasidi** [comment]
@praweshsth my bad, I missed that conversation. I will remove my comment!

**Comment by andreaszenasidi** [comment]
@praweshsth this is aproved

**Comment by praweshsth** [comment]
Thank you @andreaszenasidi
