### ISSUE TITLE
Issue Regrading import activity

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#554]
Context
- Desktop 
- Chrome

Preconditions
- https://iatipublisher-dev.yipl.com.np/
- Username:admin123
- Password: password

- [x] **Issue 1 : No validation for XML file** 
Steps 
- Upload unrelated XML file

Actual Result
https://user-images.githubusercontent.com/78422663/192940199-2771688e-3950-4ad8-86e5-55274f2ff811.mp4

Expected Result
- The XML file should be properly validated.

- [x] **Issue 2: When a title is missing in the CSV file, an error message is not displayed.**

Actual Result

https://user-images.githubusercontent.com/78422663/192951629-bc6673d6-448d-4ccc-9f61-8b22a3f85377.mp4

Expected Result
- Error should be displayed.

- [x]  **Issue 3: Loader is missing on import activity**

Actual Result

https://user-images.githubusercontent.com/78422663/192952041-e71ee0b8-7b60-4036-a8ad-7d823e98985f.mp4

Expected Result
- Loader should be present 

- [x] **Issue  4: The cursor is missing in the show error message** 

Actual Result

https://user-images.githubusercontent.com/78422663/192952319-73075b6a-4e7b-40da-a619-30e5f4024d8c.mp4

Expected Result
- Cursor should be present

- [x] **Issue 5: When none of the activities is selected, the user can import the activity.**
Actual Result

https://user-images.githubusercontent.com/78422663/192953694-d757d976-f031-49aa-acd4-2ec5d5f00809.mp4

Expected Result
- When none of the activities is selected, the import button should be disabled.

- [ ] **Issue 6: No chosen button work as choose button**
Actual Result

https://user-images.githubusercontent.com/78422663/192954070-6cc42f08-b8f9-4c39-8b56-13196d3fa121.mp4

Expected Result
- Shouldn't  work as a chosen button

- [x] **Issue 7:Result period indicator value is not displaying on the activity detail page**
Actual Result
![Screenshot from 2022-09-29 12-11-19](https://user-images.githubusercontent.com/78422663/192955613-329f6ff0-60f0-46a9-8ec6-7cacb1097573.png)
![Screenshot from 2022-09-29 12-13-13](https://user-images.githubusercontent.com/78422663/192955645-7b43983f-4943-4449-b5a1-f92eff2596ed.png)

Expected Result
- All data should be present

- [x] **Issue 8: When the user tries to import the CSV file which zeroes error message, import is unsuccessful** 
Actual Result

https://user-images.githubusercontent.com/78422663/192961230-1e356e64-e34c-404d-928d-ce8589cdf45c.mp4

Expected Result
- File should be imported if the user has made some changes

- [ ] **Issue 9: Sector(XML and CSV) and Recipient region  code(CSV) is not displaying on activity detail page**
Actual Result
![Screenshot from 2022-09-29 13-06-06](https://user-images.githubusercontent.com/78422663/192967412-d4cd6de4-7eb0-4554-95d9-99b10812763c.png)
![Screenshot from 2022-09-29 13-11-54](https://user-images.githubusercontent.com/78422663/192967494-bda0cda7-e69e-45ca-9e5d-2bbaa1ec1934.png)
Expected Result
- Should be displayed on the activity detail page.

- [x] **Issue 10: Complete status is not working after activity import**
Actual Result

https://user-images.githubusercontent.com/78422663/192968931-7b8d0e4c-d4f9-4eb3-9b60-234cd0393df4.mp4

Expected Result
- Should work properly

- [ ] Issue 11: Other-identifier , tag ,collaboration-type,default-flow-type,default-finance-type,default-aid-type,default-tied-status,country-budget-items,humanitarian-scope,capital-spend,conditions,legacy-data,document-link,location,planned-disbursement,result is missing from CSV file. 
- [ ] **Issue 12: Legacy data name is missing from activity detail page(XML)**
Actual Result
![Screenshot from 2022-09-29 13-36-40](https://user-images.githubusercontent.com/78422663/192973011-ff7b4ef0-a020-4b8e-a533-2b15616591f6.png)
![Screenshot from 2022-09-29 13-36-20](https://user-images.githubusercontent.com/78422663/192973052-4b0ddc9d-0d6f-4c36-b1f8-4299d2d35972.png)

Excepted Result
- Should be displayed on the activity detail page.

- [ ] **Issue 13: It is not possible to upload an activity file that has been downloaded from our system and published by our system.**
Steps
1. Fill out the activity form and publish it 
2. download that particular file 
3. now upload that file through activity import

Actual Result

https://user-images.githubusercontent.com/78422663/192977668-4fe7b0bf-7cbd-417b-bad4-0d30e7804eed.mp4

Expected Result

- Should be uploaded successfully

- [ ] Issue 14: While publishing an importing activity, the loader for validation shows ‘uploading CSV'. It should be ‘‘uploading CSV/XML’
- [ ] Issue 15: The for uploading XML especially in the result, document links section, multiple language data are not taken, only first data are taken. Need to look through this thoroughly.

**Comment by man-git007** [comment]
@Sanilblank Lets look into this issue today.
