### ISSUE TITLE
500 error while importing the activity

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#562]
Context
- Chrome:104.0.5112.101 
- Desktop 

Preconditions
- https://iatipublisher-dev.yipl.com.np/
- Username:admin123
- Password:password

Actual Result
https://user-images.githubusercontent.com/78422663/192994025-a2afc633-56a6-4164-befe-38923ea1b8b1.mp4

Execpted Result
- Activity should be import smoothly

**Comment by man-git007** [comment]
@Sanilblank What is the status of this issue?

cc @SauravSilwal10

**Comment by Sanilblank** [comment]
This issue has been resolved @man-git007
