### ISSUE TITLE
Checking Hover and Help section in different labels  (remaining of previosuly closed) .

### ISSUE THREAD

**Issue by AbiChitrakar** [younginnovations/iatipublisher#565]
Context
- Version 105.0.5195.125 (Official Build) (64-bit)
- Desktop

Preconditions
- https://iatipublisher-dev.yipl.com.np/
- Username:admin
- Password: password

Actual Results

- [x] Under **indicator**  sub-element, the ? Hover and  Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192933803-b9eac144-1293-47fe-a7b1-fe0f7b28dfd5.png)

- [x] Under **indicator**  sub-element, under **Title**  sub-sub-element, the ? Hover is missing but Help is present which is not required. as per the docs.
![image](https://user-images.githubusercontent.com/72198302/192934019-912e0cae-52cd-4191-bf05-dd5150c51016.png)

- [x] Under **indicator**  sub-element, under **Description**  sub-sub-element, the Help is present which is not required. as per the docs.
![image](https://user-images.githubusercontent.com/72198302/192934221-42040448-5e37-45a3-8c20-f3658c5d3e22.png)

- [x] Under **indicator**  sub-element, under **Title**  sub-sub-sub-element, the ? Hover is missing but Help is present which is not required. as per the docs.
![image](https://user-images.githubusercontent.com/72198302/192935027-f15898ee-f869-40e0-a36f-f033229e8417.png)

- [x] Under **indicator**  sub-element, under **Category**  sub-sub-sub-element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192935427-deafaaf5-4c60-4dd6-a1e9-2bd912edd8ad.png)

- [x] Under **indicator**  sub-element, under **Baseline**  sub-sub-element, the Help is not showing complete description as per the docs.
![image](https://user-images.githubusercontent.com/72198302/192936170-93955066-3fb7-4b9f-9e52-eaedb507bfd2.png)

- [x] Under **indicator**  sub-element, under **Document link**  sub-sub-sub-element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192938018-24c13ef9-cee8-4d8d-9e30-7a0e80c0d5bb.png)

- [x] Under **indicator**  sub-element, under **Category**  sub-sub-sub-sub-element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192938780-60f91146-68ba-444d-a7c3-3ec2b2032548.png)

- [ ] Under **indicator**  sub-element, under **Language**  sub-sub-sub-sub-element, the Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192939384-f3beea6a-781b-4768-919a-09cbf0233cb2.png)

- [x] Under **indicator**  sub-element, under **Title**  sub-sub-sub- lement, the **language** attribute is missing Help.
![image](https://user-images.githubusercontent.com/72198302/192940769-01773fe6-c5f6-47a5-8a06-1e76a85959be.png)

- [x] Under **period**  sub-element, the ? Hover and  Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192941429-53d7f3ed-ece2-4893-95cf-d6cc35ae3ee3.png)

- [x] Under **period**  sub-element, under the **Period start** sub-sub-sub element ,the ? Hover is missing but Help is present which is not as per the docs.
![image](https://user-images.githubusercontent.com/72198302/192941502-d1aee2cb-a87d-40d3-923d-879a8aeea168.png)

- [x] Under **period**  sub-element, under the **Period end** sub-sub-sub element ,the ? Hover is missing but Help is present which is not as per the docs.
![image](https://user-images.githubusercontent.com/72198302/192944076-534197a8-e2bd-4ab2-a0e5-8eb317d4c0b9.png)

- [x] Under **period**  sub-element, under the **Title** Sub-sub-sub-sub-sub element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192944808-c7199b84-44d3-4bfd-ac7a-49d21feeff14.png)

- [x] Under **period**  sub-element, under the **Category** Sub-sub-sub-sub-sub element, the ? Hover is missing.
![image](https://user-images.githubusercontent.com/72198302/192945349-ae68973d-ac53-48bb-bacf-efc7697ed7e5.png)

- [x] Under **transaction** element, the ? Hover and Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192968267-dc04284f-0627-4782-966c-06790891723d.png)

- [x] Under **transaction** element, under **Transaction type** sub-element, the ? Hover  is missing.
![image](https://user-images.githubusercontent.com/72198302/192968684-57308fe4-91e5-4bd6-a47e-acf66fa88388.png)

- [x] Under **transaction** element, under **Transaction date** sub-element, the ? Hover  is missing but Help is present which  should not be present as per the docs .
![image](https://user-images.githubusercontent.com/72198302/192968967-52877c9c-0ae6-48c8-a97d-6204c6c1bd22.png)

- [x] Under **transaction** element, under **Value** sub-element, the ? Hover  is missing but Help is present which  should not be present as per the docs .
![image](https://user-images.githubusercontent.com/72198302/192969224-001b0b31-a9e5-4868-bbd5-2f185017f5d5.png)

- [x] Under **transaction** element, under **Value** sub-element, under **value date** attribute the Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192970089-fbce3102-7be1-4fb9-abe8-a31a1d509e63.png)

- [x] Under **transaction** element, under **Description** sub-element , Help is present which is not required as per the docs.
![image](https://user-images.githubusercontent.com/72198302/192970562-a6cdb245-78a2-4943-877f-158ccfc9f6dd.png)

- [x] Under **transaction** element, under **Provider organization** sub-element ,under **type** attribute  Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192971274-2de6498b-fba8-4342-80fc-523c32a5faa8.png)

- [x] Under **transaction** element, under **Sector** sub-element ,under **code** attribute , the Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192972223-bcc2151d-a2be-41d2-b767-86b178c6aba9.png)

- [x] Under **transaction** element, under **Recipient region** sub-element ,under **code** attribute , the Help is missing.
![image](https://user-images.githubusercontent.com/72198302/192972953-2308c584-7be7-46f6-add0-e36be40c0346.png)

- [x] Under **total-budget**element,under **Period start** sub-element the  ? to Hover  is missing, 
![image](https://user-images.githubusercontent.com/72198302/192976687-8ce295dc-9493-4b31-afdb-e8e5c8d5f224.png)

- [x] Under **total-budget**element,under **Period end** sub-element the  ? to Hover  is missing, 
![image](https://user-images.githubusercontent.com/72198302/192977063-81281f59-2250-41f0-a8dc-4091a0de2a8d.png)

- [x] Under **total-budget**element,under **Value ** sub-element the  ? to Hover  is missing, 
![image](https://user-images.githubusercontent.com/72198302/192977647-e07c7aa8-c121-4342-898f-f583a64164bb.png)

- [ ] Under **document_link** element ,under the **Category** sub-element , the Help is not required as per the document.
![image](https://user-images.githubusercontent.com/72198302/193014116-f22dcb38-8a59-46ff-a8e8-d3203f2b0c5d.png)

- [ ] Under **document_link** element ,under the **Language** sub-element , the Help is not required as per the document.
![image](https://user-images.githubusercontent.com/72198302/193014341-b94d7a18-617f-43a1-b25b-c1d1eb5f9a70.png)

**Comment by man-git007** [comment]
@sriza This issue has been deployed to the production server. Please update the issue and close it. If any other issues remain let's create a new issue for that.

cc @AbiChitrakar
