### ISSUE TITLE
While adding activity manually ,there is still  @xml: lang in the very beginning.

### ISSUE THREAD

**Issue by AbiChitrakar** [younginnovations/iatipublisher#568]
### Context ###
- Desktop
- Version 105.0.5195.125 (Official Build) (64-bit)

### Pre-condition ###
- The site is up and running.
- Valid user can login using their valid credentials.

### Steps ###
- Login using valid credentials. 
- Click on + ADD ACTIVITY and click add activity manually.
- Notice the **@xml: lang** attribute and the **Select @xml: lang** in the placeholder .

### Actual result ###
[Screencast from 30-9-22 11:23:57 पूर्वाह्न +0545.webm](https://user-images.githubusercontent.com/72198302/193199854-15f554df-3325-486f-a804-2d2b362b90d6.webm)
- There is **@xml: lang**  attribute and **Select @xml: lang** in the placeholder too.

### Expected result ###
- Should have been **language** attribute and **Select language** in the placehokder.

**Comment by man-git007** [comment]
@Sanilblank @sriza What is the status of this issue?

**Comment by Sanilblank** [comment]
This issue has been resolved @man-git007
