### ISSUE TITLE
Activity module and activity title form

### ISSUE THREAD

**Issue by Sanilblank** [younginnovations/iatipublisher#57]
Start working on the activity module and activity title form.

TASKS

- [x] Kris laravel form builder setup
- [x] Activity migration model service repo setup
- [x] Activity title form using laravel form builder
- [x] Title form validation and store in database

Issues
==================================================================================

- [x] #193
- [x] #197
- [x] #198
- [x] #199
- [x] #200
- [x] #201 
- [x] #204
- [x] #206
- [x] #207 
- [x] #209 
- [x] #210
- [x] #211
- [x] #212 
- [x] #213
- [x] #214 
- [x] #215
- [x] #216 
- [x] #217 
- [x] #218 
- [x] #219 
- [x] #220 
- [x] #223 
- [x] #224 
- [x] #225 
- [x] #226 
- [x] #227 
- [x] #228 
- [x] #230 
- [x] #231 
- [x] #236
- [ ] #237
- [x] #238 
- [x] #239
- [x] #240
- [x] #241
- [x] #242 
- [x] #245 
- [x] #252 
- [x] #253 
- [x] #254 
- [x] #264 
- [x] #266 
- [x] #275 
- [x] #277 
- [x] #279 
- [x] #281 
- [x] #288 
- [x] #290 
- [x] #292 
- [x] #298 
- [x] #299 
- [x] #303 
- [x] #304 
- [x] #306 
- [x] #316 
- [x] #320 `
- [x] #321 
- [x] #322 
- [x] #324 
- [x] #325 
- [x] #338

**Comment by sriza** [comment]
@AbhishekSka @SauravSilwal10 
The tasks related to this issue are deployed to the staging site. Please have a look and let us know if any issues are present.

cc @man-git007 @praweshsth

**Comment by man-git007** [comment]
@SauravSilwal10 @AbhishekSka Can we close this issue?
