### ISSUE TITLE
Bug : More UI Issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#590]
- [x] **Issue 1: Complete status is not working properly whenever the user uses the default value.**
Actual Result

https://user-images.githubusercontent.com/78422663/194820636-51318483-0c84-44c3-a886-7b916acadf6b.mp4

Expected Result
- complete status should work properly.

- [x] **Issue 2 : planned-disbursement (Receiver Activity ID ) value is not displaying activity detail page**
Actual Result

https://user-images.githubusercontent.com/78422663/194820194-a8532d78-6d8a-4ecc-beaa-3a06aae01ea5.mp4

Expected Result
- value should display

- [x] **Issue 3: Result and Transactions Toast Message displays upward rather than the right side** 
Actual Result

https://user-images.githubusercontent.com/78422663/194820223-d6fcd608-106c-4a09-aa2e-1515bb571693.mp4

Expected Result
- should be displayed on the right side 

- [x] **Issue 4: Default value is not working on the result**
Actual Result
![Screenshot from 2022-10-10 13-30-30](https://user-images.githubusercontent.com/78422663/194819329-db0f04b4-8819-4358-95fc-4324b9cd8b46.png)

Expected Result
- Default value should work properly

- [x] **Issue 5: Duplication of category**
Actual Result

- ![Screenshot from 2022-10-10 13-28-47](https://user-images.githubusercontent.com/78422663/194819167-c5d6f093-2d42-46f1-856e-bbcc640aa75a.png)

Expected Result
Duplication is not allowed.

- [x] **Issue 6: Recipient -region font size** 
Actual Result
![Screenshot from 2022-10-10 13-33-32](https://user-images.githubusercontent.com/78422663/194819794-7f5cd987-69f6-4025-9911-c4bad69277cc.png)
Expected Result
![Screenshot from 2022-10-10 13-33-57](https://user-images.githubusercontent.com/78422663/194819826-d0a9f5d3-a75a-4bd8-ab4c-97f7cde51558.png)

- [x] **Issue 7 : A rotating circle appears outside the search bar.**
Actual Result

https://user-images.githubusercontent.com/78422663/194823614-edcf1d7f-9f13-4685-919b-9faac668a38e.mp4
Expected Result
- rotating circle should appear inside the search bar

- [x] **Issue 8: The progress says 100% complete even though one of the core elements (reporting org )has not been completed.**
Actual Result

![Screenshot from 2022-10-10 16-29-36](https://user-images.githubusercontent.com/78422663/194848918-1d212a5b-3256-4d80-b763-7c53473cbac3.png)

Excepted Result 

- After filling in all of the core elements, the progress bar should read 100.

- [x] **Issue 9 : UI breakdown in Location**
Actual Result
![Screenshot from 2022-10-10 16-34-23](https://user-images.githubusercontent.com/78422663/194850082-0e462220-b5e0-458d-adbd-6b533dfd5a66.png)

Excepted Result 
![Screenshot from 2022-10-10 16-39-28](https://user-images.githubusercontent.com/78422663/194850661-363289a6-7544-4a3e-be98-6ca1aab7a3f2.png)

Excepted Result

https://user-images.githubusercontent.com/78422663/194852375-bf9aed31-3a04-4bd4-933f-d5470dc36205.mp4

- [x] **Issue 12: recipient-org-budget narrative is missing in left hand side of org detail page.**

Actual Result
![Screenshot from 2022-10-10 17-33-0Excepted Result5](https://user-images.githubusercontent.com/78422663/194859541-1cc0a79a-d53c-4e63-901d-22d7a4c871c2.png)
Excepted Result
![Screenshot from 2022-10-10 17-34-20](https://user-images.githubusercontent.com/78422663/194859724-f4abbfb2-ed17-43d6-b7e7-0fb2c1b7f972.png)

- [x] **Issue 13 : document-link(Recipient Country) font is bold(organization)** 
Actual Result
![Screenshot from 2022-10-10 17-37-07](https://user-images.githubusercontent.com/78422663/194860486-0c595b8b-6ec4-4478-8380-9125a447381a.png)
Excepted Result 
should not be bold 

- [x] **Issue 14 : Whenever user wants to republish the element, button size increase(organization)**
Actual Result

https://user-images.githubusercontent.com/78422663/194861161-5ccc3c44-7811-4027-82da-f0599702205b.mp4

Excepted Result
-  button size should not increase 

- [x] **Issue 15 : recipient-region-budget(Vocabulary) inappropriate way to  display a value** 
Actual Result
![Screenshot from 2022-10-10 17-48-20](https://user-images.githubusercontent.com/78422663/194862456-966e72f8-0500-4650-9bc3-d7694e16e2e5.png)
Excepted Result
- Vocabulary  Reporting Organisation

- [x] **Issue 16 : Incorrect way to display percentage in country-budget-items**
Actual Result 
![Screenshot from 2022-10-11 10-23-42](https://user-images.githubusercontent.com/78422663/194998696-127c6e6a-fcbc-4f96-a65a-bd36917f6f28.png)
Excepted Result
![Screenshot from 2022-10-11 10-26-54](https://user-images.githubusercontent.com/78422663/194998818-f27664d8-b546-4fbe-9876-e312cbe70802.png)

- [x] **Issue 17 : Policy marker ( Reporting Organisation ) code value is not displaying on activity detail page.**
Actual Value 
https://user-images.githubusercontent.com/78422663/195001148-9033a25d-ea2c-42af-ac2a-1feb20468925.mp4
Excepted Result
value should be displayed

- [x] **Issue 18 : when user add new activity toast message moves to center then to the right  side** 
Actual Result

https://user-images.githubusercontent.com/78422663/195254528-2742f214-7eb3-4780-b23e-f948a5a192ce.mp4
Excepted Result
- toast message should be fixed at right side 

- [ ] **Issue 19: In activity-date, budget date field is named iso date**
Actual Result
![Screenshot from 2022-10-12 11-17-42](https://user-images.githubusercontent.com/78422663/195258634-286538c4-0c6e-4f2f-9e3a-7a8425c28799.png)
Excepted Result
![Screenshot from 2022-10-12 11-22-29](https://user-images.githubusercontent.com/78422663/195258843-18ea4526-9f26-45fe-96e5-94012c460aa9.png)
date field should date instead of iso date

- [x] **Issue 20: The help text was rendered twice**
Actual Result
![Screenshot from 2022-10-12 11-28-19](https://user-images.githubusercontent.com/78422663/195259717-7626042c-1da0-4812-8fc7-e7f5d9a16820.png)
Excepted Result
- The help text should not rendered twice

- [x] **Issue 21 : Whenever there is only unpublished button in activity detail page , delete button is missing**
Actual Result
![Screenshot from 2022-10-12 15-33-26](https://user-images.githubusercontent.com/78422663/195310607-b572ead9-cf9d-458a-8b57-993985fc04a4.png)
Excepted Result
The delete button should be present 

- [x] **Issue 22: unpublish button doesn't have a background color(organisation)**
Actual Result
![Screenshot from 2022-10-12 15-40-12](https://user-images.githubusercontent.com/78422663/195312194-b3836fb6-c0de-45d6-9dee-2c2bb2703506.png)

Excepted Result
The background color should be #1B5366

- [x] **Issue 23 : when user create an activity toast message appears to center then left.**
Actual Result

https://user-images.githubusercontent.com/78422663/195818028-641ad68a-4349-40ef-bae2-d8d9dfb4bc5f.mp4

Excepted Result
- Toast message should be fixed at left

**Comment by man-git007** [comment]
@Man0zZ @sriza Can we finish this issue by today?

**Comment by SauravSilwal10** [comment]
@titungdup  is looking at issues 3 and 14. @man-git007  issues 8,10,11 are yet to solve. Issue 19 is under discussion
cc @praweshsth

**Comment by SauravSilwal10** [comment]
@man-git007 Please have a look at issue 10,11. @man-git007  Issue 8 has not been deployed on the dev server.
![Screenshot from 2022-10-31 10-55-04](https://user-images.githubusercontent.com/78422663/198935780-591a7fec-1eff-46c8-b61d-b163d60309ec.png)

**Comment by SauravSilwal10** [comment]
@man-git007 issues 10, and 11 have not been solved yet . Please review it again.
![Uploading Screenshot from 2022-11-01 12-33-41.png…]()

**Comment by SauravSilwal10** [comment]
Issue fixed
