### ISSUE TITLE
Bug: Transaction and Result Issue

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#591]
Context 
- Chrome 
- Desktop 

Preconditions 
- https://iatipublisher-dev.yipl.com.np/
- Username: admin123
- password:12345678

Steps
- Fill mandatory element of Transaction and Result
- click save
- Delete Transaction and Result

Actual Result
- double tick and element mark as completed in side bar 

Excepted Result
- double tick should be removed from side bar 

https://user-images.githubusercontent.com/78422663/194828482-289999ab-bf03-4b1d-9a49-e547f7562221.mp4

https://user-images.githubusercontent.com/78422663/194828501-7ad920e8-b31a-4b2f-997b-5c2aa62b7424.mp4

**Comment by man-git007** [comment]
@sriza Did you get time to look into this issue?

**Comment by sriza** [comment]
@man-git007 This issue has already been solved but requires testing.

**Comment by SauravSilwal10** [comment]
Issue fixed 
cc @man-git007 @sriza
