### ISSUE TITLE
Refresh Notification after bulk publishing

### ISSUE THREAD

**Issue by jenishshrestha** [younginnovations/iatipublisher#595]
- [ ] Display page refresh notification if bulk publishing is completed

**Comment by man-git007** [comment]
@jenishshrestha What is the status of this issue. If done lets rebase the branch and test in development branch

cc @SauravSilwal10

**Comment by man-git007** [comment]
@jenishshrestha Has this been merged into the main branch?

cc @Sanilblank

**Comment by Sanilblank** [comment]
> @jenishshrestha Has this been merged into the main branch?
> 
> cc @Sanilblank

@man-git007 PR has been created already
Please check and merge
