### ISSUE TITLE
Element Testing feedback from DI

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#598]
- [ ] **Feedback 1 : Sector Error message** 

Actual Result
![Screenshot from 2022-10-11 11-47-42](https://user-images.githubusercontent.com/78422663/195008905-50bf1564-2905-4503-89d9-5f57b37809ec.png)
Excepted Result
- error message should be "should presume 100% percentage for each"

- [x] **Feedback 2 : Contact-info telephone and  website validation**
Actual Result

- Strict validation

Excepted Result
- Should rethink about telephone and  website validation

- [x] **Feedback 3 :Policy Marker** 
Actual Result
https://user-images.githubusercontent.com/78422663/195010127-0841c4b1-cf80-49f9-9f80-305e49dcef6f.mp4
Excepted Result
- When using a reporting organisation policy marker code (vocabulary 99), it must include a narrative

- [x] **Feedback 4 : Other-identifier**
Steps 

1. In Owner org >>Fill @xml;lang without choosing ref and narrative .

Actual Result

1. Page gets saved

Excepted Result

1.Specifiying a language here without a ref or a narrative should probably throw an error. Otherwise if it will make an owner-org element with nothing but xml:lang, that will be invalid
2. A proper valiadtion should be in form.

https://user-images.githubusercontent.com/78422663/195010406-fb9864e7-70fb-43fb-b31f-dcdf20363f11.mp4

- [x] **Issue 5 : Setting>> Humanitarian yes or no is present**

Actual Result
![Screenshot from 2022-10-17 14-57-13](https://user-images.githubusercontent.com/78422663/196138445-7e1a3e08-96ff-46df-b77a-e082aa361831.png)

Excepted Result
- Humanitarian should have boolean value(0 or 1 ) instead of yes and no

**Comment by man-git007** [comment]
@sriza What is the status of this issue?

**Comment by SauravSilwal10** [comment]
@man-git007  Please have a look at this.

**Comment by sriza** [comment]
Merged to main branch and closed manually.
