### ISSUE TITLE
Problems in default-aid type, related activity and legacy data elements as the page are not loading.

### ISSUE THREAD

**Issue by AbiChitrakar** [younginnovations/iatipublisher#602]
### Context ###
- Desktop
- Version 106.0.5249.61 (Official Build) (64-bit)

### Pre-condition ###
- The site is up and running.
- Valid user can login using their valid credentials.

### Steps ###
- Click on default-aid type element.
- Click on related activity element.
- Click on legacy-data element..

### Actual result ###
![image](https://user-images.githubusercontent.com/72198302/195047881-8a3a1291-0d20-406c-837c-527e0c46537c.png)
- There is an error message on clicking default-aid type element. .

![image](https://user-images.githubusercontent.com/72198302/195048041-ae27ea6d-cabd-4c0b-8982-8a79e8c0887e.png)
- There is an error message on clicking related activity element. .

![image](https://user-images.githubusercontent.com/72198302/195048233-5e747b3e-b891-4d86-a072-3a19934d9514.png)
- Instead of form there exista the error on clicking legacy-data element..

### Expected result ###
- All the pages should have worked properly.

**Comment by man-git007** [comment]
@sriza Can you look into this?

cc @AbiChitrakar

**Comment by sriza** [comment]
@man-git007 
This issue has been solved and merged to the main branch.
