### ISSUE TITLE
Remove Indentification part from ORGANIZATION DATA.

### ISSUE THREAD

**Issue by AbiChitrakar** [younginnovations/iatipublisher#604]
### Context ###
- Desktop
- Version 106.0.5249.61 (Official Build) (64-bit)

### Pre-condition ###
- The site is up and running.
- Valid user can login using their valid credentials.

### Steps ###
- Go to **Organization Data** .
- Notice the Identification and IDENTIFICATION.

### Actual result ###
![image](https://user-images.githubusercontent.com/72198302/195051709-01004b57-e351-48a0-bbc6-41b9ea212bcf.png)
- There is Identication sections as shown in above highlighted.

### Expected result ###
- IDENTIFICATION should not be present.

**Comment by man-git007** [comment]
@sriza Can you look into this?

**Comment by sriza** [comment]
@man-git007 This has already been fixed and is now merged to main branch.
