### ISSUE TITLE
Change the word core to all in, "Fill core elements to get 100% score" under ORGANIZATION DATA.

### ISSUE THREAD

**Issue by AbiChitrakar** [younginnovations/iatipublisher#606]
### Context ###
- Desktop
- Version 106.0.5249.61 (Official Build) (64-bit)

### Pre-condition ###
- The site is up and running.
- Valid user can login using their valid credentials.

### Steps ###
- Login and go to **Organisation Data**.
- Under Publishing Progress ,notice the text **Fill core elements to get 100% score** 

### Actual result ###
![image](https://user-images.githubusercontent.com/72198302/195058810-8fe20704-54ac-4cf9-9e9a-4a66d2ed553b.png)
- There is ,**Fill core elements to get 100% score**.

### Expected result ###
- As there are no any core elements present change the word core to all so it becomes, **Fill all elements to get 100% score**.

**Comment by titungdup** [comment]
Issue fixed and merged.
