### ISSUE TITLE
Missing Mandatory  Icon in Filters under Organzation Data.

### ISSUE THREAD

**Issue by AbiChitrakar** [younginnovations/iatipublisher#607]
### Context ###
- Desktop
- Version 106.0.5249.61 (Official Build) (64-bit)

### Pre-condition ###
- The site is up and running.
- Valid user can login using their valid credentials.

### Steps ###
- Go to Organisation Data.
- See the available options in filters.

### Actual result ###
![Screenshot from 2022-10-11 15-38-35](https://user-images.githubusercontent.com/72198302/195073385-c81b7e1d-99fc-4ac9-869a-8a09a6940da2.png)
- There is Mandatory with star symbol below Elements.
- There is not the avaialble option of Mandatory options when applying for the filter.

### Expected result ###
- While applying  filter there must have been mandatory one's icon too.

**Comment by man-git007** [comment]
@sriza Can you look into this?

**Comment by sriza** [comment]
@man-git007 This issue has already been solved and merged to main branch.
