### ISSUE TITLE
#590 UI issue fixes

### ISSUE THREAD

**Issue by Man0zZ** [younginnovations/iatipublisher#608]
#590 Fixes
- [x] Issue 3: Result and Transactions Toast Message displays upward rather than the right side
- [x] Issue 6: Recipient-region font size
- [x] Issue 7: A rotating circle appears outside the search bar
- [x] issue 9: UI breakdown in Location
- [x] Issue 13: document-link(Recipient Country) font is bold(organization)
- [x] Issue 14: Whenever user wants to republish the element, button size increase(organization)

**Comment by man-git007** [comment]
@Man0zZ What is the status of this issue?

**Comment by Man0zZ** [comment]
@man-git007 let's close this after merged

**Comment by man-git007** [comment]
@Man0zZ Has this been merged into the main branch? If yes close this issue
