### ISSUE TITLE
There are two ? hovers in Telephone,in email and in website  subelements under the contact-info element.

### ISSUE THREAD

**Issue by AbiChitrakar** [younginnovations/iatipublisher#611]
### Context ###
- Desktop
- Version 106.0.5249.61 (Official Build) (64-bit)

### Pre-condition ###
- The site is up and running.
- Valid user can login using their valid credentials.

### Steps ###
-  Go to contact-info element.
- Notice there are teo different hovers  in Telephone,in email and in website  subelements.

### Actual result ###
![image](https://user-images.githubusercontent.com/72198302/195261868-f456da7c-ec1a-4326-b176-05aa1f52c6ba.png)

### Expected result ###
- Should have been only one ? Hover present.

**Comment by titungdup** [comment]
@AbiChitrakar Title and element both have their own help text, in this case, they happened to be similar ones so it is valid and they are all according to iati standards.
