### ISSUE TITLE
Bug: Reporting-org and document-link issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#618]
Context 
- Desktop
- Chrome 104.0.5112.101

Preconditions
- https://iatipublisher-dev.yipl.com.np
- Username: admin123
- password: 12345678

- [x] **Issue 1: Being core element reporting org does not contribute to the progress bar of the activity detail  page**

Steps
- Fill in all the mandatory elements of reporting org 

Actual Result
- Doesn't get a double tick on the sidebar 
- the progress bar does not progress

Expected Result
- should get a double tick on the sidebar 
- the progress bar should progress

https://user-images.githubusercontent.com/78422663/195335726-d4dad4b3-56df-48ec-85ed-bd757dd43cbc.mp4

- [ ] **Issue 2: Document link issue(feedback from DI)**

Actual Result
- File upload complains about the @url field, and doesn't choose the appropriate format. Also, formats are not in a user-readable format

Expected Result
- Should be in the code list 
- should be understandable by the user

**Comment by man-git007** [comment]
@SauravSilwal10 I will look into this

**Comment by SauravSilwal10** [comment]
@man-git007 Issue 1 has not been deployed on the dev server.
![Screenshot from 2022-10-31 10-55-04](https://user-images.githubusercontent.com/78422663/198935916-bd9d94c9-4b89-4483-885d-a419c9a53820.png)

**Comment by man-git007** [comment]
@SauravSilwal10 Issue 1 has been fixed and deployed in the development server. Please verify

**Comment by SauravSilwal10** [comment]
Issue 1 is fixed. Issue 2 has been transferred to the backlog issue since it pertains to future improvement.
cc @man-git007 @praweshsth
