### ISSUE TITLE
Other testing feedback from DI

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#624]
- [x] **Feedback 1: Tooltip " What is  activity "**

Actual Result
![Screenshot from 2022-10-13 10-30-07](https://user-images.githubusercontent.com/78422663/195503751-ff87e18b-c2f0-48c4-b633-5eba10fd3020.png)
Expected Result
- Text should read **"What is an activity?"**

- [x] **Feedback 2: Error message in activity date**

Actual Result
![Screenshot from 2022-10-13 10-34-44](https://user-images.githubusercontent.com/78422663/195504333-b3864aba-48d5-47b5-ba28-aa2f93f83790.png)
Expected Result
- Error message should be **"Actual start and end dates may not be in the future."**

- [x] **Feedback 3: Error message in publishing activity**

Actual Result
![Screenshot from 2022-10-13 10-38-17](https://user-images.githubusercontent.com/78422663/195505499-30127cf9-f92e-4776-84ec-a94fa682008e.png)
Expected Result
- An error message should be **"Please add a Registry API key before attempting to automatically publish."**

- [x] **Feedback 4: Clicking on the + doesn't add another element** 

Actual Result
https://user-images.githubusercontent.com/78422663/195506552-6aac9a45-41ac-48a3-bf08-86f5559ec9b2.mp4
Expected Result
- + should be clickable or When the user hovers over +, the cursor/pointer should be removed.

- [x] **Feedback 5: Sector error message** 

Actual Message 
![Screenshot from 2022-10-13 11-04-23](https://user-images.githubusercontent.com/78422663/195508215-fd080698-a64c-48c9-aad6-f7cde12c7bc0.png)
Excepted Result
- An error message should be **"The sum of @percentage within a vocabulary must add up to 100."**

**Comment by man-git007** [comment]
@SauravSilwal10 I will look into this

**Comment by sriza** [comment]
@man-git007 These issues are solved but yet to be tested.

**Comment by SauravSilwal10** [comment]
Issue fixed 

cc @sriza @man-git007
