### ISSUE TITLE
Aws access issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#628]
Context 
- Desktop
- Chrome 106.0.5249.119 

Preconditions
- https://iatipublisher-dev.yipl.com.np/
- username: admin123
- password:12345678

Steps 
1. fill the element and publish the activity 
2. after go to site https://staging.iatiregistry.org/dataset/pub_1254775164636-activities and click download

Actual Result
- An error message "AccessDenied" is displayed 

Excepted Result
- a XML file should display 

https://user-images.githubusercontent.com/78422663/195531480-b4db5c92-dc8b-41d7-abbd-63033f26a325.mp4

**Comment by pravin-yipl** [comment]
Resolved: AWS Bucket permission and access policy made public.
