### ISSUE TITLE
Bug : In org detail default value is not working.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#636]
Context
- Desktop 
- Chrome 

Precondition
- https://iatipublisher-dev.yipl.com.np
- Username : admin1234
- Password : 12345678

Steps
- click  ORGANISATION DATA link 
- fill one element without entering language or currency 

Actual Result
-  default value is not working.

Excepted Result
- default value should work properly

https://user-images.githubusercontent.com/78422663/196092820-2716afc4-b526-45be-8b9a-0b05d7698d21.mp4

**Comment by Sanilblank** [comment]
This issue is fixed. Please confirm and provide feedback. @SauravSilwal10

**Comment by SauravSilwal10** [comment]
Issue fixed 
cc @Sanilblank @man-git007
