### ISSUE TITLE
Under reporting-organisation element, there is reporting-org and also under secondary-reporter drop down there is True/False present.

### ISSUE THREAD

**Issue by AbiChitrakar** [younginnovations/iatipublisher#637]
### Context ###
- Desktop
- Version 106.0.5249.61 (Official Build) (64-bit)

### Pre-condition ###
- The site is up and running.
- Valid user can login using their valid credentials.

### Steps ###
- Go to Organisation Data.
- Go to reporting-organisation element.
- Notice the reporting-org present.
- Under secondary-reporter attribute,notice True and Fase in the dropddown.

### Actual result ###
![Screenshot from 2022-10-17 10-40-54](https://user-images.githubusercontent.com/72198302/196093145-feea7840-4b7a-4cdd-a38e-adf811d9394a.png)
- There is reporting-org present and there is True/ False in the drop down under secondary-reporter.

### Expected result ###
- There should have been reporting-organisation .
- There should have been Yes /No in the drop down.

**Comment by AbiChitrakar** [comment]
- [ ] Under total-budget element ,under value sub-element there is value textbox ,where the placeholder is missing the text.
![image](https://user-images.githubusercontent.com/72198302/196095466-4ae82046-0a7b-492f-a0bf-0ef98a55f8fe.png)

**Comment by AbiChitrakar** [comment]
- [ ] Under **total-budget** element ,under **value** sub-sub-element there is **value** textbox ,where the placeholder is missing the text.
![image](https://user-images.githubusercontent.com/72198302/196096059-eaa78d75-7d0f-47af-b581-dd6f209e5e89.png)

**Comment by titungdup** [comment]
Issue resloved
