### ISSUE TITLE
Should have been organisation but there is just org.

### ISSUE THREAD

**Issue by AbiChitrakar** [younginnovations/iatipublisher#638]
### Context ###
- Desktop
- Version 106.0.5249.61 (Official Build) (64-bit)

### Pre-condition ###
- The site is up and running.
- Valid user can login using their valid credentials.

### Steps ###
- Go to Organisation Data.
- Notice the org present in various elements.

### Actual result ###
![image](https://user-images.githubusercontent.com/72198302/196096625-351988c9-da60-47dc-8c2f-93b775bd06e2.png)
- There is just org in various elements.

### Expected result ###
- Should have been organisation.

**Comment by AbiChitrakar** [comment]
![image](https://user-images.githubusercontent.com/72198302/196097295-795d05ec-107b-4376-9471-c4f5028bbf9f.png)
- [ ] There is just-org present under **recipient-organisation-budget** element .

**Comment by AbiChitrakar** [comment]
- [ ] Under **recipient-organisation-budget** element ,under **Value** sub-element,it is missing the text in the placeholder.
recipient-organisation-budget
![image](https://user-images.githubusercontent.com/72198302/196098050-dcd54e96-a3fc-409c-b712-f0910e25b15c.png)

**Comment by AbiChitrakar** [comment]
- [ ] Under **recipient-organisation-budget** element ,under **Value** sub-sub-element,it is missing the text in the placeholder.
![image](https://user-images.githubusercontent.com/72198302/196098429-3e4f475c-855f-4638-be7e-815371e45ed4.png)

**Comment by AbiChitrakar** [comment]
- [ ] Under **recipient-region-budget** element,under **Value** sub-element,it is missing the text in the placeholder.
![image](https://user-images.githubusercontent.com/72198302/196099191-e4cfd6c7-501e-4a5f-895c-d11f6fde5636.png)

**Comment by AbiChitrakar** [comment]
- [ ] Under **recipient-region-budget** element,under **Value** sub-sub-element,it is missing the text in the placeholder.
![image](https://user-images.githubusercontent.com/72198302/196099745-11ef4f16-3fab-4e42-a9db-a8e551c1a6a3.png)

**Comment by AbiChitrakar** [comment]
- [ ] Under **recipient-country-budget** element,under **Value** sub-element,it is missing the text in the placeholder.
![image](https://user-images.githubusercontent.com/72198302/196100406-6087fdc7-d09a-4764-9f65-486372490cd1.png)

**Comment by AbiChitrakar** [comment]
- [ ] Under **recipient-country-budget** element,under **Value** sub-sub-element,it is missing the text in the placeholder.
![image](https://user-images.githubusercontent.com/72198302/196100575-c792b42a-a116-4b58-ab22-7e99e0728844.png)

**Comment by AbiChitrakar** [comment]
- [ ] Under **total-expenditure** element,under **Value** sub-element,it is missing the text in the placeholder.
![image](https://user-images.githubusercontent.com/72198302/196100777-7d4f7a64-ffe6-4e80-8462-993c703811b8.png)

**Comment by AbiChitrakar** [comment]
- [ ] Under **total-expenditure** element,under **Value** sub-sub-element,it is missing the text in the placeholder.
![image](https://user-images.githubusercontent.com/72198302/196101030-9d7d2919-09c5-42aa-b6ba-2fdf36b67c37.png)

**Comment by titungdup** [comment]
@AbiChitrakar Using "org" for now. The rest of the issues have been fixed.
