### ISSUE TITLE
Issue with bulk publishing 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#639]
Context
- Desktop
- Chrome

Precondition
- https://iatipublisher-dev.yipl.com.np/
- Username: admin1234
- Password: 12345678

Steps 
- try to publish different activities in bulk

Actual Result
- No response from the system

Expected Result
- Activities should be published in bulk.

https://user-images.githubusercontent.com/78422663/196115530-1a44e95b-99c8-4b8e-ba11-43653f221b9e.mp4

**Comment by Sanilblank** [comment]
@SauravSilwal10 This issue seems to not exist anymore. Please confirm and provide feedback.

**Comment by Sanilblank** [comment]
In this case, the response is being sent from the backend as success: false, but it has not been handled in the frontend part. Could @titungdup look into this.

**Comment by SauravSilwal10** [comment]
@titungdup, please look into this issue.
![Screenshot from 2022-10-18 17-18-15](https://user-images.githubusercontent.com/78422663/196418704-67c8c530-86bc-4942-9a02-c51cd8abbcdf.png)

**Comment by titungdup** [comment]
Issue resolved.
