### ISSUE TITLE
Bug:Org detail issue

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#643]
Context
- Desktop
- Chrome

Precondition
- https://iatipublisher-dev.yipl.com.np/
- Username: admin1234
- Password: 12345678

Steps
- Click the ORGANISATION DATA link
- name,reporting-org,total-budget,recipient-org-budget,recipient-region-budget,recipient-country-budget,total-expenditure ,document-link >> click save and exit 

Actual Result
- Server Error unwanted error message is displayed

Excepted Result
- The element should be saved and displayed on the org detail page.

https://user-images.githubusercontent.com/78422663/196128745-da02b50e-e1d0-4c1f-9af8-b0b553ac5354.mp4

**Comment by Sanilblank** [comment]
@SauravSilwal10 This issue has been fixed. Please confirm and provide feedback.

**Comment by SauravSilwal10** [comment]
issue fixed
