### ISSUE TITLE
Remaining Issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#645]
- [x] **Issue 1: No clickable link for a vocabulary-URI in the Result(reference)**

Actual Result
![Screenshot from 2022-10-17 16-33-46](https://user-images.githubusercontent.com/78422663/196169687-b5c4e742-28ad-4372-bde7-4a319ab1b7ec.png)

Expected Result
- There should be a clickable link for  vocabulary-URI

- [x] I**ssue 2: In the org detail, there is no gap between the toast message and the publish button**

Actual Result
https://user-images.githubusercontent.com/78422663/196169994-7d3f7917-dab0-4427-bba1-aed3015a43da.mp4

Expected Result
- there should be a gap between them

- [x] **Issue 3: Period validation message displays at top of the edit form.**

Actual Result
![Screenshot from 2022-10-17 17-29-53](https://user-images.githubusercontent.com/78422663/196168956-53023cc0-0a70-4927-ba3f-b2627148678d.png)

Expected Result
- validation error messages on a particular element will be helpful for the user.

**Comment by titungdup** [comment]
@man-git007 Can you look at Issue no 3?

**Comment by SauravSilwal10** [comment]
@man-git007 Please refer to issue no 3.

**Comment by titungdup** [comment]
Issue no 3. fixed in `import-fixes` branch. @SauravSilwal10 @man-git007

**Comment by man-git007** [comment]
@SauravSilwal10 @titungdup Issue 3 has been fixed and deployed in the development server. Please verify

**Comment by SauravSilwal10** [comment]
@man-git007 issue 3 has not been fixed yet. Please review it again.
![Screenshot from 2022-11-02 10-34-16](https://user-images.githubusercontent.com/78422663/199400901-7c6da306-7c18-4748-bfb6-8ffd462a212b.png)

**Comment by man-git007** [comment]
@SauravSilwal10 Issue 3 has been done. Please check

**Comment by SauravSilwal10** [comment]
@man-git007  An wanted validation has been done.

1. When user doesn't enter a measure in indicator but our system display a validation error.
https://www.loom.com/share/4eb289ae3a84401f8383f99912b45f7e
2. The @value should be omitted for qualitative measures has not been followed.
https://www.loom.com/share/12dd620a3d5e4b9ba06b4f5b01b22d09

**Comment by SauravSilwal10** [comment]
Issue Fixed
