### ISSUE TITLE
csv Template for Upload re-structure

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#686]
As part of the .csv upload a template is made available to download, this template has a number of fields in a structure as column headers.

Various IATI tools already allow for data to be downloaded into .csv files, it would make sense to replicate one of these download is structure, so that publishers can download existing data, amend / update and then upload with a minimum of fuss without going through an exercise of cut & paste or using excel logic to populate the template from existing .csv .xls files.

**Comment by praweshsth** [comment]
The template we have used for CSV upload is similar to that of AidStream with the addition of elements. And the issue is that all the publishing tool might not provide CSV download in a particular standard CSV template. The templates may differ
