### ISSUE TITLE
Feedback from DI 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#687]
- [x] **Feedback 1 : While creating an activity, clicking "reporting-org" and then Save and Exit, takes a user to their Organisation  page, instead of back to the activity being edited.**

Actual Output 

https://user-images.githubusercontent.com/78422663/198955316-741aa9dc-5979-49a9-b808-f50ab33afce5.mp4

Excepted Result

- Should be back to the activity 

- [x] **Feedback 2 : The budget line value date must be within the budget period**
**Activity-(Indicator(baseline,year and value date),planned-disbursement, budget) 
org-(total-expenditure,recipient-country-budget,recipient-region-budget,recipient-org-budget,total-budget)**
Actual Output 
![Screenshot from 2022-10-31 13-05-38](https://user-images.githubusercontent.com/78422663/198953126-44bd327e-0097-46b4-80bf-3519da0a5de5.png)
![Screenshot from 2022-10-31 13-07-21](https://user-images.githubusercontent.com/78422663/198953408-c82c6013-af4d-4f02-9492-7c6f3cbbaf83.png)
Excepted Result
- A proper validation should be in form

- [x] **Feedback 3 : A reference code must only be declared at result OR result indicator level.**

Actual Output 
![Screenshot from 2022-10-31 13-09-30](https://user-images.githubusercontent.com/78422663/198954303-d107b726-8125-449a-a3eb-99d93b342373.png)
Excepted Result
- A proper validation should be in form

**Comment by man-git007** [comment]
@SauravSilwal10 Feedback 2 has been deployed to the development server. Please verify once.

cc @praweshsth

**Comment by SauravSilwal10** [comment]
@man-git007  Issue 2 activity (Indicator(baseline,year and value date),planned-disbursement ) has not been solved.

**Comment by man-git007** [comment]
@SauravSilwal10 Feedback 3 has been done. Please check. Also remaining issue of Feedback 2 has also been completed
