### ISSUE TITLE
Bug : Indicator UI issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#698]
- [x] **Issue 1: Edit Button doesn't align SHOW FULL PERIOD LIST.**

Actual Result
![Screenshot from 2022-11-02 11-30-50](https://user-images.githubusercontent.com/78422663/199408892-913c2203-2b3a-4db2-92db-3ba115679dd7.png)

Expected Result
![Screenshot from 2022-11-02 11-39-20](https://user-images.githubusercontent.com/78422663/199409342-f308df0a-a2f9-4a2f-b60a-7c97347f5fff.png)

- [x] **Issue 2: Comment should align by side instead of downward.**

Actual Result
![Screenshot from 2022-11-02 11-31-24](https://user-images.githubusercontent.com/78422663/199409648-f7702939-5fa6-42c9-b139-a19bd5eed3ea.png)
Expected Result
![Screenshot from 2022-11-02 11-48-21](https://user-images.githubusercontent.com/78422663/199410626-23f7f75a-c51e-49ff-a861-f1d752aa2d95.png)

- [x] **Issue 3: an inappropriate way to display data**

Actual Result
![Screenshot from 2022-11-02 11-57-09](https://user-images.githubusercontent.com/78422663/199411893-0a987823-d7cb-499b-aad9-dab92a70814a.png)
Expected Result
- Dimension: code ----, value ----

**Comment by man-git007** [comment]
@titungdup Close this issue.

cc @SauravSilwal10
