### ISSUE TITLE
Validation issues of budget element

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#704]
Following validations need to maintained for the element 'Budget':

1. The time period should not exceed 1 year i.e. difference between period-end date and period-start date
2. For a time period, there should only be one budget with type 'Original' or 'Revised' 
3. The revised type budget should match with the original type budget with same time period and status (either committed or indicative)
4. The budget value should never be negative
5. If no status is present, the budget is assumed to be indicative.
6. If no type is present, the budget is assumed to be original.

**Comment by man-git007** [comment]
@Sanilblank Can you look into Tasks 2,3,5,6? Task 1,4 has been done in the branch `716-validation-fixes`

**Comment by praweshsth** [comment]
Regarding no. 2, only check if both original or revised have same time range. It should not be same.

**Comment by man-git007** [comment]
Let's discuss the remaining issues if any in the new GitHub ticket. This issue is closed manually as some of the fixes are merged in the `main` branch.

cc @praweshsth @SauravSilwal10 @Sanilblank
