### ISSUE TITLE
Feedback by UNDP (Priority -Medium)

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#705]
**Feedback 1**: Users cannot publish, but they can add draft material. When a user is trying to publish, bulk publish or republish, check if the email is verified and the publishing setting is completed with correct API token. If both are good, then only go ahead with publishing otherwise show user that either email is not verified or api token is incorrect or organisation data is published or all so you need to complete it before publishing> alert message should be pop.
**Feedback 2**: + button in the activity detail page and activity listing page should be replaced with only/one button which includes add activity and import activity.

**Comment by titungdup** [comment]
**Feedback 1** done by @man-git007 

**Feedback 2**
- Add and Import option added in menu "Add / Import Activity"

@SauravSilwal10

**Comment by praweshsth** [comment]
manually closed
