### ISSUE TITLE
Bug : No negative validation for budget 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#706]
Context
- Desktop
- Chrome 106.0.5005.61

Precondition
- https://iatipublisher-dev.yipl.com.np/
- Username: testing
- Password: 12345678

**activity(Transaction,planned-disbursement,budget)
org-(total-expenditure,recipient-country-budget,recipient-region-budget,recipient-org-budget,total-budget)**

Actual Result
![Screenshot from 2022-11-03 13-54-34](https://user-images.githubusercontent.com/78422663/199673850-6d530d17-c97f-46ef-8254-a98ad212d3c0.png)
![Screenshot from 2022-11-03 13-55-52](https://user-images.githubusercontent.com/78422663/199673870-42c1966e-6ce2-47c8-93ee-86bfd53a2afa.png)
Expected Result
- A proper validation should be in the form

**Comment by praweshsth** [comment]
Manually closed
