### ISSUE TITLE
Bug : Import Issue CSV

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#709]
- [x] **Issue 1: Default language is not working** 

**Actual Result**

https://user-images.githubusercontent.com/78422663/199946302-4ed31589-a9ad-4567-8d12-c4b10d181549.mp4

**Expected Result**

- language should be filled automatically with help of the default value 

- [x] **Issue 2: Default currency is not working**

**Actual Result**

https://user-images.githubusercontent.com/78422663/199943612-8a2d5465-828c-47c0-ae4d-67094e35e0cc.mp4

**Expected  Result**
- Currency should be filled automatically with help of default value 

- [x] **Issue 3: Sector issue in Transactions and vocabulary URI is not displaying on activity detail page**

**Actual Result**

https://user-images.githubusercontent.com/78422663/199953994-5b758acb-0888-45af-99c8-71ad45213ed2.mp4

**Expected Result**

Should not be an error message

- [x] **Issue 4: Uppercase validation in CSV file**

Actual Result

https://user-images.githubusercontent.com/78422663/200227336-d10a7a41-b2b6-4855-a31b-823c85750e2e.mp4

Expected Result
- Should not be Uppercase validation

- [x] **Issue 5: planned disbursement is not displaying on the activity detail page.**

**Actual Result**

https://user-images.githubusercontent.com/78422663/199937357-9ff111b0-008d-400c-bd10-f567d7c4ef62.mp4

**Expected  Result**

- Should import smoothly.

- [ ] **Issue 6: A toast message might be helpful to the user while a validation error message is displayed.**

- [x] **Issue 7: completed status is not working** 

**Actual Result**

https://user-images.githubusercontent.com/78422663/200239832-e93ee43f-a032-4902-9bf2-631a2a39f251.mp4

**Expected  Result**
- completed status  should work

- [x] **Issue 8: Doesn't understand indexing of conditions( Conditions Attached)**

- An error message is not displayed stating " cannot be multiple elements for  Conditions Attached" or indexing should be from the first rows which hasn't happened in this case.

https://user-images.githubusercontent.com/78422663/199948719-84261bc0-64cd-48ff-89f7-6e0c2db9543a.mp4

- [ ] **Issue 9: No validation for vocabulary URI in humanitarian scope**

Actual Result
![Screenshot from 2022-11-04 16-03-01](https://user-images.githubusercontent.com/78422663/199949313-1b58f75f-c0db-44a6-b4cc-1f04f98f2815.png)
**Expected Result** 
- Vocabulary URI should be present only if vocabulary is reporting org

- [x] **Issue 10: Country-budget-items are not displayed on the activity detail page**

Actual Result

https://user-images.githubusercontent.com/78422663/199951050-ac8865d4-391b-4e75-83c2-07dc4ee6f153.mp4

Expected Result

- should be displayed on the activity detail page

- [ ] **Issue 11: Loader is not available in import activity**

Actual Result

https://user-images.githubusercontent.com/78422663/199936887-39e3ee1d-7e1c-4e40-b6ea-053edf40364e.mp4

Expected Result
- Loader should be present

- [x] **Issue 12: Default -aid-type does not display on the activity detail page**

Actual Result

https://user-images.githubusercontent.com/78422663/199951953-61973c9e-9ceb-43cb-b0b3-b18b815af4e4.mp4

**Expected Result**
Should be displayed

- [x] **Issue 13: When a user enters a collaboration type an invalid error message is displayed** 

Actual Result

https://user-images.githubusercontent.com/78422663/199934550-d87aef58-64be-4154-91b3-287c13a6a49b.mp4

Expected Result
- Should import smoothly.

- [x] **Issue 14: Activity Scope is not displayed on the activity detail page**

**Actual Result**

https://user-images.githubusercontent.com/78422663/199952882-a0d0a267-d360-48ab-900f-e4a7affb4198.mp4

**Expected Result** 

- Should display on the activity detail 

- [ ] **Issue 15: No validation for Budget** 

**Actual Result**
![Screenshot from 2022-11-04 14-34-10](https://user-images.githubusercontent.com/78422663/199931330-f2d01dc9-a08d-4ad8-9e4f-cd99ae796c3d.png)

**Expected Result** 
Should be validate
The budget Period must not be longer than one year.
The start of the period must be before the end of the period.

- [ ] **Issue 16: No validation for the telephone in contact info** 

Actual Result
![Screenshot from 2022-11-04 14-32-34](https://user-images.githubusercontent.com/78422663/199930976-a0edf334-19e5-4c22-bb4f-3040ad265af2.png)
**Expected Result** 
Should be validate

- [x] **Issue 17: Invalid validation message for  Recipient Country or Region.**

**Actual Result**
An error message is displayed "You can only mention Recipient Country or Region either in Activity Level or in Transaction level. You can't have Country/Region in both Activity level and Transaction level."

https://user-images.githubusercontent.com/78422663/199929059-f2c00c96-fa35-4f50-9f29-d0763f431adf.mp4

**Expected Result**
There should not be an error message.

- [x] **Issue 18: Cannot test the transaction**

presence of issues 3 and 17 cannot test the transaction.

- [x] **Issue 19: Policy marker narrative and vocabulary URI is missing and code is not displaying on the activity detail page**

**Actual Result**

https://user-images.githubusercontent.com/78422663/199962488-bc532261-b756-457f-b736-f543d2b8c975.mp4

**Expected Result**

The narrative and vocabulary URI should be present and the code should be displayed.

- [ ] **Issue 20: enter invalid budget date and  budget value but our system cannot  find it** 

**Actual Result**

https://user-images.githubusercontent.com/78422663/199961351-d5623c21-dc44-403f-9e45-e988ae2268ee.mp4

**Expected Result**
Our system should detect an error

- [x] **Issue 21: Sector error gets a toast error message, instead of a validation message**

**Actual Result**

https://user-images.githubusercontent.com/78422663/199964865-6bc2f558-0053-40b3-9886-aa9d9afef876.mp4

**Expected Result**
should be a validation message instead of a toast message.

- [x] **Issue 22: When the user enters an upload blank CSV file our system does not show any error message.**
**Actual Result**

https://user-images.githubusercontent.com/78422663/200166738-102555fd-f9a4-441c-9f70-5f146b4470ca.mp4
**Expected Result**
Should display an error message.

- [x] **Issue 23: When user doesn't enter default value , our system doesn't import the activity.**
**Actual Result**

https://user-images.githubusercontent.com/78422663/200275545-6f9277b6-dddb-46fa-90da-47fb08fa07c7.mp4

**Expected Result**
It should display an error message rather than not import.

- [ ] **Issue 24 : Unnecessary validation in Description.**

**Actual Result**
![Screenshot from 2022-11-07 15-47-36](https://user-images.githubusercontent.com/78422663/200282530-6aa5382d-0e78-4543-b706-6002accb6baa.png)

**Expected Result** 
Multiple narrative should is allowed  for Description

- [x] **Issue 25 : Sector vocabulary-uri is not displaying on activity detail page.**

- [x] **Issue 26 : Without importing the file , a success toast message is displayed.**

**Actual Result**

https://user-images.githubusercontent.com/78422663/200292735-c257ce8c-fae0-440a-b2be-4287409afe8e.mp4

**Expected Result** 
error toast message should displayed.

- [x] **Issue 27 : Element with narrative Sub-element where user can upload multiple narrative but language will be same.**
- [x] **Issue 28 : When none of the activities is selected, the user can import the activity.** 
**Actual Result**

https://user-images.githubusercontent.com/78422663/200300764-a182edde-a140-4b08-b9b3-ffdfc3ed550a.mp4

**Expected Result** 
Import button should be disabled  until user mark on checkbox.

- [ ] **Issue 29: No chosen button work as choose button**
**Actual Result**

https://user-images.githubusercontent.com/78422663/200302847-63a2bb30-cbb2-40f8-92e7-87b7ffe1a7b9.mp4

**Expected Result** 
Shouldn't work as a chosen button

- [ ] **Issue 30: No validation for iati-identifier**

**Actual Result**
![Screenshot from 2022-11-08 10-26-35](https://user-images.githubusercontent.com/78422663/200476806-dad1828f-f3eb-4096-80c8-bc4809d22386.png)
**Expected Result** 
- should be validate

- [x] **Issue 31 : narrative is missing in those element (activity date ,recipient-country,recipient-region(vocabulary))**
- [x] **Issue 32 : transaction element is missing**

- [x] **Issue 33 : participating-org element Ref and CRS Channel Code is missing.**

**Comment by Sanilblank** [comment]
Regarding Issue 8: Doesn't understand indexing of conditions( Conditions Attached)

**Comment by SauravSilwal10** [comment]
@sriza issues are listed below 

- [ ] **Issue 1 : An unwanted error message on default-flow-type, collaboration-type, Related activity** 
![Screenshot from 2022-11-25 15-54-32](https://user-images.githubusercontent.com/78422663/203957924-2ab68536-3468-4e13-9ba9-ead664063d4e.png)

- [ ] **Issue 2: Location Administrative code has upper-case validation.**
![Screenshot from 2022-11-25 15-55-46](https://user-images.githubusercontent.com/78422663/203958138-9b26a081-3e9b-4258-bbc2-93be7423be30.png)

- [ ] **Issue 3: The tag is not displaying on the activity detail page.**
![Screenshot from 2022-11-25 15-57-06](https://user-images.githubusercontent.com/78422663/203958555-4fa6d2c9-dc95-4c8f-ac79-86a003fee1a3.png)

- [ ] **Issue 4: A default currency value is not displayed on the budget and planned disbursement.**

**Comment by SauravSilwal10** [comment]
Remaining  issue has move to the #828 .Closed Manually
