### ISSUE TITLE
Issue with verified email and activities 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#715]
- [ ] **Issue 1 : error message , resend verification email is displayed where email has been already verified.**
### Actual  Result

https://user-images.githubusercontent.com/78422663/200555938-89275a72-ddf4-4b39-b157-83561bd18727.mp4

### Excepted Result
- error message should not occur 

- [ ] **Issue 2 :  there is an activity, the activities not found message is displayed.**
### Actual  Result

https://user-images.githubusercontent.com/78422663/200559403-5301c898-234a-4296-9442-adf00dad6d52.mp4

### Excepted Result
- activity list should display

**Comment by SauravSilwal10** [comment]
unable recreate this issue

**Comment by sriza** [comment]
Unable to recreate this issue. Manually closed.
