### ISSUE TITLE
Activity Detail Page - Frontend development

### ISSUE THREAD

**Issue by jenishshrestha** [younginnovations/iatipublisher#72]
- [x] Front end development of activity detail page

**Comment by praweshsth** [comment]
@jenishshrestha @sriza 

1. When in detail page and clicked the back button, I am taken to sign in page. Take it to activity listing page instead
2. The title of the activity is not what I entered when I created the activity

**Comment by man-git007** [comment]
@jenishshrestha Can we close this issue?

**Comment by jenishshrestha** [comment]
> @jenishshrestha Can we close this issue?

Yes

**Comment by man-git007** [comment]
@jenishshrestha tick the tasks completed and close the issue
