### ISSUE TITLE
Validation issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#738]
- [ ]  **Issue 1 : Indicator  Validation Issue** 

1. When user doesn't enter a measure in indicator but our system display a validation error.

https://user-images.githubusercontent.com/78422663/201083069-7dda687c-2c0e-46f2-859e-596a48a36a0f.mp4

2. The value should be omitted for qualitative measures has not been followed.

https://user-images.githubusercontent.com/78422663/201083488-b36225c7-929c-4fcc-b24a-6ee08cb7defe.mp4

- [ ]     **Issue 2 : Recipient Region Validation Issue** 

1. Same vocabulary  hasn't add up to 100

https://user-images.githubusercontent.com/78422663/201083849-c6a82524-edb5-4ef1-9ec8-bee871ce9a47.mp4

- [ ]   **Issue 3 : Transaction Validation Issue** 

1. Server Error

https://user-images.githubusercontent.com/78422663/201084245-72c00e50-d6c0-4327-95c5-67b5aefe8510.mp4

- [ ]  **Issue 4 : Result Validation Issue** 

1. Server Error 

https://user-images.githubusercontent.com/78422663/201084609-ab20446d-02ed-477c-bb68-81dc3dc1ef1d.mp4

- [ ]   **Issue 5 : Sector Validation Issue** 

1. Sector vocabulary hasn't add up to 100

https://user-images.githubusercontent.com/78422663/201086290-b22b4364-16f9-4826-9304-ddaf304321b8.mp4

- [ ] **Issue 6 : Budget Validation Issue** 

1. Validation hasn't been done.

![Screenshot from 2022-11-10 17-43-16](https://user-images.githubusercontent.com/78422663/201085072-c5e83f50-ad51-4a59-a005-dfd9607a5ded.png)

**Comment by SauravSilwal10** [comment]
@man-git007 These are the issue found in validation branch

- [ ]  **Issue 1 Sector must only be reported at EITHER transaction level OR activity level**

https://user-images.githubusercontent.com/78422663/201601779-759b0857-6b55-4bca-b682-92513b4c41d9.mp4

- [ ] **Issue 2 :  User cannot enter a decimal period** 

https://user-images.githubusercontent.com/78422663/201602898-45a73ec0-01cf-45f5-bf1d-63ef7b6df6a9.mp4



- [ ] **Issue 3 :  Budget validation hasn't been completed** 

![Screenshot from 2022-11-14 13-30-20](https://user-images.githubusercontent.com/78422663/201603256-6f492c9a-eb13-428f-a1cc-acc2c5b5002b.png)

- [ ] Issue 4 : No negative percentage validation for recipient country.
![Screenshot from 2022-11-14 13-32-13](https://user-images.githubusercontent.com/78422663/201603609-e9a19f9d-98c9-4ad2-8920-dedfa576f503.png)

- [ ] **Issue 5 : User will get trapped in infinite Loop in recipient country and recipient region.**
### Step 
1. Fill recipient country =0  and recipient region=100 step by step 
2. now try to edit them 

https://user-images.githubusercontent.com/78422663/201606199-07b79380-31e1-46e1-8b80-ec0c70fa4488.mp4



- [ ] **Issue 6 : Period issue** 

https://user-images.githubusercontent.com/78422663/201607704-09d56c33-fca2-4003-a2bf-78fd415ca83d.mp4

![Screenshot from 2022-11-14 13-52-26](https://user-images.githubusercontent.com/78422663/201607751-c292f660-7f67-4523-a1b6-60be27f25237.png)

- [ ] **Issue 7 : When user enter string value in percentage field in recipient country, server error message in displayed.**


https://user-images.githubusercontent.com/78422663/201608118-da1f4f36-67ee-4bc1-a533-b5b5a82eff42.mp4

![Screenshot from 2022-11-14 13-50-23](https://user-images.githubusercontent.com/78422663/201608157-b6fcd281-31fa-4bf7-b848-ac0261d176d7.png)

**Comment by man-git007** [comment]
@SauravSilwal10> Below issues are solved. Could you please verify it?
Issue 1 : Indicator Validation Issue
2 The value should be omitted for qualitative measures has not been followed.
Issue 2 : Recipient Region Validation Issue
Issue 3 : Transaction Validation Issue
Issue 4 : Result Validation Issue
Issue 5 : Sector Validation Issue
Issue 1 Sector must only be reported at EITHER transaction level OR activity level
Issue 4 : No negative percentage validation for recipient country.
Issue 6 : Period issue
Issue 7 : When user enter string value in percentage field in recipient country, server error message in displayed.

**Comment by man-git007** [comment]
@SauravSilwal10 @praweshsth 
Regarding Issues:
Issue 2 : User cannot enter a decimal period
Issue 5 : User will get trapped in infinite Loop in recipient country and recipient region.

lets ignore for now.

**Comment by man-git007** [comment]
@Sanilblank
Can you look into this issue
Issue 3 : Budget validation hasn't been completed

@SauravSilwal10 @praweshsth Can you explain this issue to @Sanilblank

**Comment by SauravSilwal10** [comment]
@man-git007 
Issue 1: The recipient country, Recipient region, and  Sector must only be reported at the transaction level OR activity level is not working properly.

https://user-images.githubusercontent.com/78422663/201905878-86c71916-496f-4c6c-8124-578f92bc6ba2.mp4

**Comment by SauravSilwal10** [comment]
@man-git007 .These are  the issue left in validation.
- [ ] **Issue 1: The recipient country, Recipient region, and Sector must only be reported at the transaction level OR activity level is not working properly.**


https://user-images.githubusercontent.com/78422663/203044015-4eb2bed5-b555-4b17-8bb1-1ced5172d9e1.mp4


- [ ] **Issue 2 : Percentage values for recipient countries or regions, must add up to 100%.**


![Image](https://user-images.githubusercontent.com/78422663/203044299-d4144841-5dad-4981-b371-14aae1e22a14.png)


- [ ] **Issue 3 : UI issue** 



https://user-images.githubusercontent.com/78422663/203045643-d19297eb-2d9e-4308-9692-03020a28142e.mp4


**- [ ] Issue 4: Sector Percentage values for sectors, within a vocabulary (e.g. 1 - OECD DAC), must add up to 100%.**



![Image](https://user-images.githubusercontent.com/78422663/203045780-5129a38b-e561-4afb-9f4a-dc326639380c.png)

**Comment by man-git007** [comment]
Merged to the `main` branch and closed manually. If any other issue remaining will maintain in new issue
