### ISSUE TITLE
Necessary check and show error before activity publishing (single, bulk and republish)

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#740]
Check API token and email verification and organisation published

**Comment by SauravSilwal10** [comment]
@Sanilblank  @titungdup 
These are issues found in this feature.

- [ ] Issue 1: Toast messages Should be managed.


https://user-images.githubusercontent.com/78422663/202138063-88b0f8d3-67c2-45f8-a103-9c5c527f76aa.mp4



- [ ] Issue 2: System gets freeze when a user tries to publish the org data.

https://www.loom.com/share/813706520c43443da9df501baccb129b

- [ ] Issue 3: Inappropriate error  message 
 

https://user-images.githubusercontent.com/78422663/202137494-a3320c57-c9ae-4745-a8ee-ef70ae7478d1.mp4

- [ ] Issue 4: When a user wants to bulk republish the activity, the publishing process gets stuck.


https://user-images.githubusercontent.com/78422663/202144214-d83f2c03-a5b7-4b7c-8ca0-4744531184af.mp4

**Comment by titungdup** [comment]
@shreyaydi Please check issue 1.
