### ISSUE TITLE
Invalid toast message 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#745]
Context 

- Desktop 
- Chrome

Preconditions 

- https://iatipublisher-dev.yipl.com.np/
- Username : Testing 
- Password : 12345678

Actual Result

https://user-images.githubusercontent.com/78422663/201621628-e5983efa-5251-49c0-8966-44c2d3725b40.mp4

Excepted Result
- Toast message should be changed.

**Comment by Sanilblank** [comment]
This issue has been fixed in the branch 770-bug-validation-issue in commit bc6d227bd1411f40984f560b226ce9a647aaabb7
