### ISSUE TITLE
Fix activity detail sidebar sticky issue

### ISSUE THREAD

**Issue by titungdup** [younginnovations/iatipublisher#754]
Issue:
The sidebar on activity detail page overlaps with footer.

Task:
- [x] Fix the sidebar and footer overlap issue.

**Comment by SauravSilwal10** [comment]
Issue found in this branch @titungdup 

- [ ] **Issue 1: when the user clicks on the sidebar element, its gets overlap with the footer.**



https://user-images.githubusercontent.com/78422663/203474440-a3a0dc64-d851-424b-9b03-a4d310e3e857.mp4


- [ ] **Issue 2: When the user clicks on the element sidebar it scrolls to the top and then redirects it to the edit page.** 

Actual Result


https://user-images.githubusercontent.com/78422663/203475416-3c7bf451-209c-4fa3-b689-9f9cef391b3a.mp4


Expected Result
- Shouldn't scroll to the top, the process should be smooth.

**Comment by SauravSilwal10** [comment]
Issue Fixed. Closed Manually.
