### ISSUE TITLE
Bug : Validation issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#770]
- [x] **Issue 1: The recipient country, Recipient region, and Sector must only be reported at the transaction level OR activity level is not working properly.**

https://user-images.githubusercontent.com/78422663/203044015-4eb2bed5-b555-4b17-8bb1-1ced5172d9e1.mp4

- [x] **Issue 2: Percentage values for recipient countries or regions, must add up to 100%.**

![Image](https://user-images.githubusercontent.com/78422663/203044299-d4144841-5dad-4981-b371-14aae1e22a14.png)

- [ ] **Issue 3: UI issue** 

https://user-images.githubusercontent.com/78422663/203045643-d19297eb-2d9e-4308-9692-03020a28142e.mp4

- [x] **Issue 4: Sector Percentage values for sectors, within a vocabulary (e.g. 1 - OECD DAC), must add up to 100%.**

![Image](https://user-images.githubusercontent.com/78422663/203045780-5129a38b-e561-4afb-9f4a-dc326639380c.png)

**Comment by SauravSilwal10** [comment]
@Sanilblank  Issue found in this Fixes 

- [ ] **Issue 1 : Percentage values for recipient countries must add up to 100%.**


![Image](https://user-images.githubusercontent.com/78422663/204477565-b283ca0d-4ec4-4fbf-86be-573aa9ce4d45.png)

- [ ] **Issue 2 : The recipient country, Recipient region, and Sector must only be reported at the transaction level OR activity level is not working properly.**



https://user-images.githubusercontent.com/78422663/204479685-56b2c030-6137-4984-89e1-3c4d289eff2b.mp4

- [ ] **Issue 3 : Cannot enter a decimal point**



https://user-images.githubusercontent.com/78422663/204481340-6c29640d-c741-4af8-9d77-9dca9d392358.mp4



- [ ] **Issue 4 : @titungdup  Please look to issue 3.**

**Comment by Sanilblank** [comment]
Regarding 
- Issue 2 : The recipient country, Recipient region, and Sector must only be reported at the transaction level OR activity level is not working properly. => This doesn't seem to be happening anymore and system is behaving as intended.
- Issue 3 : Cannot enter a decimal point => The total sum of entered amount is actually greater than 50. One value must have the decimal ending with 6 instead of 7 to save the data
