### ISSUE TITLE
Missing  hover and help texts in inner pages of indicators and so others.

### ISSUE THREAD

**Issue by AbiChitrakar** [younginnovations/iatipublisher#778]
- [x] In Result form remove core icons.
- [x] In Indicator form remove core icons.
- [x] In Period form remove core icons.
- [x] In Result Detail view,remove core icons from menu side.
- [x] In Result Detail view,remove core icons from detail side.
- [x] In Result detail view hover over text is not present.
- [x] Indicator is not a core element.

**Comment by sriza** [comment]
Merged to main branch. Closed manually
