### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by rajkarnikar11** [younginnovations/iatipublisher#810]
- [x] The Hover Text of Identification are not visible.
![image](https://user-images.githubusercontent.com/72198302/207512062-660acf7a-532a-4925-9e35-fa79077d1b27.png)

- [x] The **Edit** Text is not visible and also it is not properly aligned. 
[Screencast from 14-12-22 11:02:57 पूर्वाह्न +0545.webm](https://user-images.githubusercontent.com/72198302/207512799-87ee8420-8d4c-4cb8-97ad-a019767f3b27.webm).

-[ ] After clicking **Edit** on **Activity-Identifier**, the Help Text field is not properly covering the overall space
![image](https://user-images.githubusercontent.com/72198302/207513542-acd4c991-558e-4baf-9d59-9b70f884f283.png)

**Comment by AbiChitrakar** [comment]
![image](https://user-images.githubusercontent.com/72198302/209063193-efb9e1d6-1242-4ff9-935a-d521993997ca.png)
-[ ] The desktop view has been altered althogh the responsive is correct.

**Comment by AbiChitrakar** [comment]
- [ ] "ADD ADDITIONAL RECIPIENT COUNTRY" text is not aligned.
![Screenshot from 2022-12-22 11-25-53](https://user-images.githubusercontent.com/72198302/209065374-a1754472-0b8f-4433-ab9e-2bc1f3632c88.png)

**Comment by PG-Momik** [comment]
This issue has been fixed.
