### ISSUE TITLE
UI Issue when user enter sector in both activity and transaction level.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#825]
- [x] **Issue 1 : Delete Button appears in transaction (sector ) ,Recipient Country,and Recipient region when their is only one element.**

https://user-images.githubusercontent.com/78422663/204739530-ba9fe458-1447-4c55-aed2-df0f52225c23.mp4

**Comment by sriza** [comment]
Merged to main branch. Closed manually.
