### ISSUE TITLE
Understanding the mandatory fields in a non-mandatory element

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#83]
Suppose a user started filling the element ‘transaction’. If the user has not filled any fields in it, there would not be an issue as this element is not mandatory. 

Now the user has to fill the sub-elements transaction type, transaction date and value and it’s attribute of value date for the element ‘transaction’ to be complete. 

But if he fills either one of fields in the sub-element ‘aid type’ that is required but the ‘aid type’ itself is not mandatory, the user need to complete both fields within it for the element ‘transaction’ to be complete. 

@k8hughes @titiolukole @nirvanalama @man-git007

**Comment by k8hughes** [comment]
@amy-silcock is the best person to answer this I think....

**Comment by praweshsth** [comment]
I have assigned the issue to her.

**Comment by amy-silcock** [comment]
Hi @praweshsth,

You're correct. As soon as a user adds **any** data within a transaction element they have to also add the:
- transaction-type/@code
- transaction-date/@iso-date
- transaction/value
- transaction/value/@value-date

**Comment by praweshsth** [comment]
Got it @amy-silcock Thank you.
