### ISSUE TITLE
Remaining CSV/XML Issue of Common validation.

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#863]
- [ ] **Issue 1: Default value is  not working**
![Screenshot from 2022-12-13 15-14-28](https://user-images.githubusercontent.com/78422663/207279949-a7d68c70-934f-45f0-a4a9-30d9f7cdc1af.png)

- [x] **Issue 2: Reporting org can have multiple narratives**
![Screenshot from 2022-12-13 15-17-02](https://user-images.githubusercontent.com/78422663/207280501-3338e6c3-a61b-4738-bf41-7a72bdfdcbc8.png)

- [x] **Issue 3: Country-Budget items Vocabulary is missing on the activity detail page.(P)**
![Screenshot from 2022-12-13 15-21-49](https://user-images.githubusercontent.com/78422663/207281594-9d636cfb-42c8-4907-88b9-167167ee650a.png)

- [x] **Issue 4: Conditions data is not displaying on the activity detail page. (P)**

https://user-images.githubusercontent.com/78422663/207298070-9a53446d-eb3b-4726-8bea-ceed3a10d81c.mp4

- [x] **Issue 5: If the user puts multiple values in an element-like condition and country-budget-items, the first value should be treated as the correct value.(P)**

- [x] **Issue 6: Header mismatch error message is missing. (P)**
- [x] **Issue 7: No validation for Title.(P)**
- [x] **Issue 8: Title edit form is not working** 
- [x] **Issue 9: When the reference is null in the transaction, the user cannot access the transaction detail page.**
- [x] **Issue 10: In the transaction recipient country code is not working.**
- [x] **Issue 11:Same reference for multiple transaction.(P)**
![Screenshot from 2022-12-12 10-04-49](https://user-images.githubusercontent.com/78422663/206959906-3cc030d7-d508-4f2f-a377-d05b42cc3329.png)

- [ ] **Issue 12: Complete status not working.**
- [ ] **Issue 13: UPDATED ON is not working properly. (Discuss)**

https://user-images.githubusercontent.com/78422663/206966648-06e17d1b-e195-499c-90a6-1b38e389a2fb.mp4

- [x] **Issue 14: A toast message is displayed on the error log. (P)**
![Screenshot from 2022-12-08 10-53-14](https://user-images.githubusercontent.com/78422663/206386291-3f48738b-cac8-49b7-b60b-5d7de120b582.png)

- [x] **Issue 15: Invalid error message in country-budget-items, when the percentage is not included.**
![Screenshot from 2022-12-09 10-40-56](https://user-images.githubusercontent.com/78422663/206627227-4f37044f-0576-4b3f-be83-7992322caf1e.png)

- [x] **Issue 16: error message of the budget is not understandable by the user.** 
- [x] **Issue 17: When a user doesn't enter a reference in a transaction, the user cannot get access to the transaction detail page. (P)**

https://user-images.githubusercontent.com/78422663/206968675-8bfebec0-364a-4686-b984-bf0ab5542962.mp4
- [x] **Issue 18: No validation for finance -type, aid-type in a transaction.**
- [x] **Issue 19: other-identifier "The narrative field is required with @xml: lang field" rule hasn't been followed.**

- [x] **Issue 20: In the indicator, when measure is saved but the indicator is not displayed on the activity detail page.(P)**
- [x] **Issue 21: Validation of code and reference in indicator is not working properly. (P)** 
- [ ] **Issue 22: Help text for a sequence of the XML tags.** (discuss)
- [x] **Issue 23: Help message for the user while importing the activity.** (discuss) 
- [x] **Issue 24: Loader/message so that importing process will be smooth** (discuss)
- [x] **Issue 25: If the user enters the wrong organization name or iati-identifier an error message should be displayed.**
- [x] - [ ] **Issue 26: Period is not displaying on the activity detail page(P).**

https://user-images.githubusercontent.com/78422663/207547164-7c210b18-561b-4379-ac9e-f774e0713a50.mp4

- [x] **Issue 27 : No validation for indicator(measure)**

- [x] **No validation for period date**

https://user-images.githubusercontent.com/78422663/207565248-da4cea6b-6e42-4df4-907a-88a51ed0b846.mp4

- [x] Issue 29:  **When the user enters multiple results, the result doesn't display on the activity detail page ** 

https://user-images.githubusercontent.com/78422663/207572815-b4cbabb9-ae33-4c8a-88e7-50f847343d5c.mp4

**Comment by sriza** [comment]
Merged to the main branch. Closed manually.
