### ISSUE TITLE
Organisation Mandatory Issue 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#866]
- [x] When the user publishes Organisation data mandatory element / mandatory field should be changed to core element/core field.
![Screenshot from 2022-12-14 14-53-50](https://user-images.githubusercontent.com/78422663/207553976-e630bf4c-4853-45c0-9088-b60f6357c13c.png)

- [x] Popup error should occur only when 2 core element is not completed.
- [ ] Org name should update automatically once the user registers the org name during the sign-up process.

**Comment by AbiChitrakar** [comment]
![Screenshot from 2022-12-21 17-48-24](https://user-images.githubusercontent.com/72198302/208902161-3148440c-b4ab-417f-a577-28fff3fd0f72.png)
- [ ] Issue in IATI Registry.

**Comment by sriza** [comment]
The issue with registration validation has been mentioned in branch #897. Further changes will be made after confirmation regarding the new validation with IATI Registry.
