### ISSUE TITLE
Feedback from Observation Log 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#880]
- [x] **Mandatory field has to be changed into the non-mandatory field in the transaction and changes the complete status accordingly.**

![Screenshot from 2022-12-19 13-14-34](https://user-images.githubusercontent.com/78422663/208371049-9d15ee89-2dcc-4c1e-8f17-d8b94f5aa4fd.png)
![Screenshot from 2022-12-19 13-14-54](https://user-images.githubusercontent.com/78422663/208371062-1bf68f31-a2c9-4227-ace8-763be029dc4b.png)

- [x] Issue 2: Filter on incomplete elements. The filter allows you to filter on core and all elements which is fine and also COMPLETED, but not incomplete elements - it makes sense to allow the latter filter to show what needs to be done.
![Screenshot from 2022-12-19 17-44-07](https://user-images.githubusercontent.com/78422663/208421315-50eb996f-cf74-4a9b-84f5-08333acba7fc.png)

- [x] **Issue 3: In location(point) help text opens in same tab.**

https://user-images.githubusercontent.com/78422663/209055880-b4005124-8f98-4ae1-8574-e013e089c345.mp4

- [x] **Issue 4: In location(location-id), placeholder text should enter a code instead of select a code.** 
![Screenshot from 2022-12-22 10-16-53](https://user-images.githubusercontent.com/78422663/209056531-fddf0bc7-12d1-4e4d-b26d-203a14334034.png)

**Comment by sriza** [comment]
Changes merged to the main branch. Closed manually.
