### ISSUE TITLE
User management feature

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#883]
**Organisation admin:**
- [ ] Manage other admin user or general user
- [ ] Edit own profile

**Organisation general user:**
- [ ] Edit own profile
- [ ] Don't allow to change organisation file and default values
- [ ] Allow to manage activity files, import, download activity files

**Super admin and IATI admin:**
- [ ] Manage other super admins
- [ ] Edit own profile
- [ ] Proxy as admin for any organisation and do what the admin can do

**Pages and messages:**
- [ ] User Listing pages
- [ ] Add/edit users
- [ ] Profile detail page
- [ ] Edit own profile 
- [ ] Messages - new user, edited user, deleted user, profile updated, password change, email verification sent, email/ username change

**Permissions:**
Superadmin and IATI Admin: 
- View the organization listing page
- Proxy as the organization admin
- View the user listing page
- Create iati_admin
- Update and delete users

Admin:
- Create, import, update, delete, and publish activity
- Update and publish the organization
- View user listing page
- Create, update and delete the admin and general user
- Update setting

General user
- Create, import, update, delete, and publish activity
- View organization
- View the user listing page
- View setting

**Comment by praweshsth** [comment]
@k8hughes @DaveEade49 please check if these requirements for user management we have added in this issue are sufficient. Please comment to add any missing items.

**Comment by sriza** [comment]
Here is the link to a flow diagram showing the interaction of users with different roles in the system:
https://drive.google.com/file/d/1qK1gvx01992aU2ocumOojElutpnkrx6N/view?usp=sharing

**Comment by DaveEade49** [comment]
Hi, is there any chance of getting a clearer version of the document?

The version in google doesn’t render very well and is hard to read.

Thanks
Dave

David Eade | Product Owner
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505 | M: +44 (7855 946589)

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives. If you have received this email in error, please delete it and notify the sender.

**Comment by praweshsth** [comment]
@DaveEade49 you have to click 'Open with diagram.net' link at the top
<img width="605" alt="Screenshot 2022-12-21 at 15 46 04" src="https://user-images.githubusercontent.com/2421695/208878009-08879dc0-1622-41fe-b32e-e1e1fec64bfe.png">

**Comment by DaveEade49** [comment]
Is that with google docs or the email?

I don’t seem to have that.

David Eade | Product Owner
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505 | M: +44 (7855 946589)

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives. If you have received this email in error, please delete it and notify the sender.

**Comment by praweshsth** [comment]
@DaveEade49 here's the pdf version of it. 

[User Management.drawio.pdf](https://github.com/younginnovations/iatipublisher/files/10277053/User.Management.drawio.pdf)

**Comment by DaveEade49** [comment]
Thanks

David Eade | Product Owner
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505 | M: +44 (7855 946589)

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives. If you have received this email in error, please delete it and notify the sender.

**Comment by DaveEade49** [comment]
One comment would be that the default settings can only be amended by the admin or an organisation – not a general user – not sure if that’s what’s meant by settings edit?

One other point – have we got a list of things we need to “tidy up” for go live?


  *   Change the support email address
  *   Change the URLs for links to things like “dashboard”
  *   Remove the FR and ES language options ( unless we get the copy in time )

Dave


David Eade | Product Owner
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505 | M: +44 (7855 946589)

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives. If you have received this email in error, please delete it and notify the sender.

**Comment by praweshsth** [comment]
@DaveEade49 Regarding the 'default settings', the user with admin role for an organisation in the tool can only make changes in default settings and the users with general user role for the same organisation will not be able to make changes in the default settings.

Regarding the Live, before going to Live, we will discuss with you those little changes and work on them.

**Comment by praweshsth** [comment]
completed and deployed
