### ISSUE TITLE
Issue found in Activity 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#884]
- [ ] Issue 1: Result Complete status is not working.

https://user-images.githubusercontent.com/78422663/208391299-eb04b8c2-2e7f-4707-a0ce-ff6d2c7305e1.mp4

- [x] Issue 2: In transaction value of humanitarian update automatically to true.

https://user-images.githubusercontent.com/78422663/208392864-71717a2e-eece-4454-a7bd-3e5ec5b9bd44.mp4

- [x] Issue 3: Period is missing on the Result detail page.
![Screenshot from 2022-12-19 15-15-29](https://user-images.githubusercontent.com/78422663/208393344-ba1ba483-2dbd-4a11-9bcf-b598cf05b2f0.png)

- [x] Issue 4: These buttons are not working properly.

https://user-images.githubusercontent.com/78422663/208395779-8487aca0-2dae-4d96-934f-a952ed838afa.mp4

- [x] Issue 5: Error bar is not dynamic. 

https://user-images.githubusercontent.com/78422663/208402810-6b9045ac-69c2-4367-94e0-d023b4f2e302.mp4

- [x] Issue 6: Remove  vocabulary repetition  in country-budget-items 
![Screenshot from 2022-12-19 15-24-31](https://user-images.githubusercontent.com/78422663/208395375-1b807095-31d2-4f63-b043-0c72aa8bca2a.png)

**Comment by AbiChitrakar** [comment]
Issue 5: Error bar is not dynamic.
 Test is remaining for this one.
