### ISSUE TITLE
Multiple language support in the system

### ISSUE THREAD

**Issue by Sanilblank** [younginnovations/iatipublisher#885]
TASKS

- [x] Create middleware to handle the language to be used to display texts in the system
- [x] Create a system for allowing users to change the language of the system
- [x] Create and maintain multiple language files
- [x] Translating lines
     - [x] VUE files
          - [x]  Web 
               - [x] Home
               - [x] About
               - [x] Publishing Checklist
               - [x] IATI Standard
               - [x] Support
               - [x] Password recovery
               - [x] Register Organisation
               - [x] Register Publisher
          - [x] Admin
               - [x] Activities
               - [x]  Activity Detail
               - [x] Organisation
               - [x] User mgmt
               - [x] Common
                    - [x] Buttons
                    - [x] Toasts/Stickies
                    - [x] Missing
                    - [x] Modal/Popup
                    - [x] Element common
     - [x] Blade files ]
          - [x] /admin
          - [x] /layouts
          - [x] /superadmin
          - [x] / web
     - [x] Php files 
          - [x] /Controllers
          - [x] /Middleware
          - [x] /Requests
          - [x] /laravel-form-builder (+jsonSchema)
          - [x] fix hover and help text issue 
       
- [x] Maintaining excel
- [x] Scripting
     - [x] Code to excel
     - [x] Excel to code 
     - [x] Modify scripts to log errors and warnings
- [x] Move language scripts to storage (1028)
- [x] Read write xlsx  (1028)
- [x] Implement laravel command  (1028)
- [x] Change log instance   (1028)
- [x] Implement SPANISH and FRENCH
     - [x] Download es and fr docx 
     - [x] Copy paste and fix to xlsx
     - [x] generate es and fr files
     - [x] simple test, check if lines are showing or not (check key implementation issues)
     - [x] bug fixes if found in QA
- [x] Maintain/update new translation lines (in docs and code)
     - [x] Updated changed rules.
     - [x] Add new translation lines for new rules.
     - [x] Add new translation lines for bulk publish cancellation and other completed work.
     - [x]  Implement translation keys after espanish and french values are returned.

**Comment by sarinasindurakar** [comment]
### French
- [ ]  Change the hover text of about according to document.
"La norme de l’IITA fournit des informations et des conseils concernant tous les domaines sur lesquels votre organisation peut publier des données conformes à l’IITA."
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/b8f6f231-e4a9-4abf-9137-358d65139228)

**Comment by sarinasindurakar** [comment]
- [ ] Reporting org not shown in french.

![image](https://github.com/younginnovations/iatipublisher/assets/65848732/83db44c1-3831-448e-87f1-ceb48c6c24a4)
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/a3c75649-77f8-434e-828a-ab0d4a96d3f3)

**Comment by amritlc** [comment]
- [ ] 'Multiple language support options' is only displayed in desktop sizes not in small sizes screen.
![new-7](https://github.com/younginnovations/iatipublisher/assets/52846176/161fc576-fc8e-4e23-be09-f8c927188214)
![2023-06-12_14-47](https://github.com/younginnovations/iatipublisher/assets/52846176/a94d8a80-cadc-4a7a-b317-00bf492bc7f9)
![2023-06-12_14-45](https://github.com/younginnovations/iatipublisher/assets/52846176/3b138216-dffb-4bdd-9080-377e3c18578d)

**Comment by amritlc** [comment]
- [ ] 'Download XLS' is not translating to the proper French
- [ ] 'Import Activities From XLS' is not translating to proper French
![2023-06-12_15-00_1](https://github.com/younginnovations/iatipublisher/assets/52846176/ec2fbc05-18b7-400b-8717-775dd415cb6b)
![2023-06-12_15-00](https://github.com/younginnovations/iatipublisher/assets/52846176/b6fbd875-bfd6-490c-a999-3f4ae0888961)

**Comment by amritlc** [comment]
- [ ] 'Publishing In Progress' is not translating to the proper French
![2023-06-12_15-06](https://github.com/younginnovations/iatipublisher/assets/52846176/09c6d4b5-690f-4288-9b64-5eb0765fb6cd)

**Comment by amritlc** [comment]
- [ ] Aligment issue in "Nous rejoindre maintenant" [FR] in Large and Small Sizes Screen 
![2023-06-13_11-43](https://github.com/younginnovations/iatipublisher/assets/52846176/507e87ea-57d6-46da-b1be-40dd6a31eb0a)

**Comment by amritlc** [comment]
- [ ] In Users Page in [FR] expected 'Adresse e-mail' actual 'ADRESSE ÉLECTRONIQUE'
![2023-06-13_14-57](https://github.com/younginnovations/iatipublisher/assets/52846176/37295158-85df-4797-b1e5-19b137716681)
![2023-06-13_14-58](https://github.com/younginnovations/iatipublisher/assets/52846176/601c7b38-778b-4455-bbf7-82626701bbf2)

**Comment by amritlc** [comment]
1. [FR] expected 'réel' actual 'actual'
![2023-06-15_11-12](https://github.com/younginnovations/iatipublisher/assets/52846176/2bca095a-571a-4586-ac20-17c9db18918f)

**Comment by amritlc** [comment]
1. 

- [ ] [FR,EN] Threr is extra 's' in transaction in activity page
![2023-06-16_09-42](https://github.com/younginnovations/iatipublisher/assets/52846176/1c2664a8-c1f6-4c27-9990-dfefaaea701e)

**Comment by amritlc** [comment]
1. 

- [ EN, FR] Help text is not showing instead some jargon text
-
![2023-06-14_10-04](https://github.com/younginnovations/iatipublisher/assets/52846176/4a1c34ed-841d-451c-8768-6a81d5079d5b)
![2023-06-16_13-53](https://github.com/younginnovations/iatipublisher/assets/52846176/768e35b2-7557-43d4-9f16-0ad4288e350a)
![2023-06-16_13-53_1](https://github.com/younginnovations/iatipublisher/assets/52846176/acb31af5-0cf9-4cd3-8f51-23af6f5211d4)

**Comment by amritlc** [comment]
1. 

- [ ] [FR,EN] In activity/iati_identifier hover text and icon is missing.
![2023-06-19_11-20](https://github.com/younginnovations/iatipublisher/assets/52846176/2a72fee2-23cc-4009-abad-c07c5c96f4ee)

**Comment by amritlc** [comment]
1. 
- [ ] [FR] In /import/xls navigation button is missing for ' IMPORT ACTIVITIES FROM .XLS' in [FR]
![2023-06-19_15-32](https://github.com/younginnovations/iatipublisher/assets/52846176/464a524d-dcd2-4885-9bd9-394b6eb70046)

**Comment by amritlc** [comment]
1. 

- [ ] [ES] In home page expected 'Publicador de la IATI' actual 'Herramienta para la publicación de la IATI' [ES]
![2023-06-20_10-51](https://github.com/younginnovations/iatipublisher/assets/52846176/2d398d7a-fbca-48f3-b17a-818fb00da7c2)

**Comment by amritlc** [comment]
1. 

- [ ] [ES,EN,FR] In activity_details page if we delelte default-tier-status in both "Staging" and "Dev" there are differences in toast message.
![2023-06-20_17-00](https://github.com/younginnovations/iatipublisher/assets/52846176/58bad1e1-8e2c-4180-937c-69ce6ba1ed13)
![2023-06-20_16-58](https://github.com/younginnovations/iatipublisher/assets/52846176/8bd8ebd1-55b2-4dd9-8b0d-47238466b068)

**Comment by sarinasindurakar** [comment]
- [ ]  Different message is shown n detail page in location section

![Image](https://github.com/younginnovations/iatipublisher/assets/65848732/ef43597b-64dd-46ca-abcf-449636699021)

**Comment by amritlc** [comment]
1. 

- [ ] [FR,ES] These texts are not translating.
![2023-06-22_14-22](https://github.com/younginnovations/iatipublisher/assets/52846176/06d2e332-ca20-439e-9b90-6b089106f2f1)
![2023-06-22_14-21](https://github.com/younginnovations/iatipublisher/assets/52846176/cf1839c6-1421-4ed4-9924-48ca85441bf7)

**Comment by amritlc** [comment]
1. 

- [ EN,FR, ES] In activity/2302/sector activities.sector.help_text is missing
![2023-07-05_11-50](https://github.com/younginnovations/iatipublisher/assets/52846176/d94f80c1-3c1e-438b-9f93-6a411681cba1)

**Comment by amritlc** [comment]
1. 

- [ ]  [ EN, FR, ES] In activity/2302/document_link hep text and icon is missing also the hover text icon also missing for document_link
![2023-07-07_10-20](https://github.com/younginnovations/iatipublisher/assets/52846176/f89793fd-9c61-4648-83c9-64125422a010)

**Comment by amritlc** [comment]
1. 

- [ ] [ EN, FR, ES] In activity/2302/planned_disbursement help text and hover text showing other code.
![2023-07-10_11-48](https://github.com/younginnovations/iatipublisher/assets/52846176/7f644af5-a71c-4144-a60e-520503e4550b)

**Comment by emmajclegg** [comment]
Closing this issue as work on #1477 replaces it
