### ISSUE TITLE
 Complete status is not working.

### ISSUE THREAD

**Issue by AbiChitrakar** [younginnovations/iatipublisher#891]
- [x] Issue 1: Result Complete status is not working.

https://user-images.githubusercontent.com/78422663/208391299-eb04b8c2-2e7f-4707-a0ce-ff6d2c7305e1.mp4

**Comment by sarinasindurakar** [comment]
- [ ] Complete status not working in other identifier. It is shown complete even when user does not fill the required sign attribute.
![image](https://user-images.githubusercontent.com/65848732/232733683-d2100833-1f99-4e78-8e8f-46bcdff80e41.png)

- [ ] Activity date 
![image](https://user-images.githubusercontent.com/65848732/232733887-46a78ece-f404-4fed-a7b7-1d80fd8171bb.png)
- [ ] Complete status is shown when user fill the percentage attribute but not the recipient region code .
![image](https://user-images.githubusercontent.com/65848732/232734410-a5ab3f85-9f89-4657-8143-9f2179c63612.png)

- [ ] Complete status shown when user fills the sector vocabulary only.
![image](https://user-images.githubusercontent.com/65848732/232735795-82b6103d-0442-447f-b959-e6542f039dea.png)

**Comment by sarinasindurakar** [comment]
- [ ] Complete status not working in condition

**Comment by sarinasindurakar** [comment]
- [ ] When user enters the percentage in recipient country, the tick is shown in recipient region.

https://user-images.githubusercontent.com/65848732/233539927-b6503e6c-8eaf-4d05-859e-d3c2aeb39b32.mp4

**Comment by sarinasindurakar** [comment]
- [ ] when user enters the recipient region 100% and enters the code in recipient  country then both are completed.
- [ ] When user adds the sector in transaction level, the sector in activity  level is not completed.
