### ISSUE TITLE
UI fixes

### ISSUE THREAD

**Issue by rajkarnikar11** [younginnovations/iatipublisher#899]

**Comment by SauravSilwal10** [comment]
@rajkarnikar11  issue found in this fixes.

- [ ] **Issue 1 : Text is overlapping.**
![Screenshot from 2022-12-26 16-56-00](https://user-images.githubusercontent.com/78422663/209542544-0631d576-772f-4154-8f51-994f73735055.png)

- [ ] **Issue 2 : Whenever user click on completed element , our system looks untidy** 

https://user-images.githubusercontent.com/78422663/209542696-4c1d3bdd-5073-4d3b-b1fa-2c9cdb710148.mp4


- [ ] **Issue 3 : Navbar should be sticky.**


https://user-images.githubusercontent.com/78422663/209542816-7342c89e-61bc-475c-8412-06557d84cc4b.mp4


- [ ]**Issue 4 :  Detail page should be scroll able when user close his/her inspect bar.**

https://user-images.githubusercontent.com/78422663/209543457-24ec1b1e-0398-46e6-8815-239039fb8115.mp4


- [ ] **Issue 5 :  Icon are hiding when user tries to make page responsive .**

https://user-images.githubusercontent.com/78422663/209544094-ed98e678-32cb-46c6-8854-251475b54c13.mp4


- [ ] **Issue 6 : When tries to view the error log , text is overlapping.**
![Screenshot from 2022-12-26 17-17-24](https://user-images.githubusercontent.com/78422663/209544387-eeb4466c-33b0-4e64-a566-296c5052de4e.png)


- [ ]**Issue 7 : Transaction, Result,Period,Indicator page are not responsive.**

https://user-images.githubusercontent.com/78422663/209544783-c435d82d-47e5-4e2c-8255-abb553ddcde8.mp4

**Comment by SauravSilwal10** [comment]
@rajkarnikar11 These are the issue found in this branch.

- [ ] **Issue 1: Toast Message should display in a better way.**

https://user-images.githubusercontent.com/78422663/209785810-f3416f66-56e1-4794-abc3-d02b9bf64f9c.mp4


- [ ] **Issue 2: Help text should be sticky or should display in the middle of the page.**

https://user-images.githubusercontent.com/78422663/209785413-15a33d54-19ae-4048-88dc-c290a345140d.mp4


- [ ] **Issue 3: When a user clicks on the sidebar element it should redirect to the title of the element.**

https://user-images.githubusercontent.com/78422663/209785157-cd0a2dc3-060b-491f-bfd2-95387169223a.mp4


- [ ] **Issue 4: In Org detail page size of the edit should increase.**

![Screenshot from 2022-12-28 14-31-44](https://user-images.githubusercontent.com/78422663/209784861-613e68a1-92cb-4d84-a8f3-0266aa34cd7c.png)

**- [ ] Issue 5: The sidebar is not sticky.**

https://user-images.githubusercontent.com/78422663/209784735-1f446e35-d468-4f63-9dd7-cf8d28c73824.mp4

**Comment by SauravSilwal10** [comment]
@rajkarnikar11  Reaming issues.

- [ ] **Issue 1: Whenever the transaction page gets responsive, an unnecessary core element icon gets displayed.** 

https://user-images.githubusercontent.com/78422663/210053945-ad69980c-27ff-4bf0-9820-9215836366fc.mp4


- [ ] **Issue 2: When a user clicks the activity hamburger, the page should not be scrollable.**

https://user-images.githubusercontent.com/78422663/210054070-94a42061-d3e1-4b4a-8ef5-1bc7150b0978.mp4


- [ ] **Issue 3: Breadcrumb and error message bar get overlap.**
![Screenshot from 2022-12-30 15-02-01](https://user-images.githubusercontent.com/78422663/210054189-f65f1c96-bd18-47ce-a361-c68f19e912b0.png)

- [ ] **Issue 4: The sidebar doesn't get sticky.**

https://user-images.githubusercontent.com/78422663/210054482-deb27c07-4d8f-4059-9957-c599b0f76e3e.mp4


- [ ] **Issue 5: Period page scrollable.**

https://user-images.githubusercontent.com/78422663/210054689-28714843-d297-4bbc-bf27-014d25ec10d9.mp4


- [ ] **Issue 6: Untidy way to display complete status**
![Screenshot from 2022-12-30 14-19-01](https://user-images.githubusercontent.com/78422663/210052720-4fc191ce-7624-4534-9464-df4f3f4d5ab4.png)

- [ ] **Issue 7: Please display 2 arrows after the sidebar is displayed.** 
![Screenshot from 2022-12-30 14-47-10](https://user-images.githubusercontent.com/78422663/210053128-8a0eafbf-6a56-432a-a74a-f5fe0da4d4df.png)

- [ ] **Issue 8: an inappropriate way to display toast message.**


https://user-images.githubusercontent.com/78422663/210054868-58681fbc-d869-4bde-bbd9-d05ef928a6e6.mp4



- [ ] **Issue 9: @rajkarnikar11 can't we seek for better alternatives?**
![Screenshot from 2022-12-30 15-11-57](https://user-images.githubusercontent.com/78422663/210054983-7e201532-e56f-4425-a098-b40334ce1727.png)

- [ ] **Issue 10: Unnecessary Space in the sidebar.**

https://user-images.githubusercontent.com/78422663/210055551-90de2cc0-cfed-4079-8d81-f1bbfddc3e85.mp4

- [ ] **Issue 11: When a user clicks on the sidebar element it should redirect to the title of the element.**

https://user-images.githubusercontent.com/78422663/210056072-120aaf61-3a95-4e34-8601-4838e18dd205.mp4

**Comment by man-git007** [comment]
The remaining issue will be done in the new ticket. So manually closed.

cc @rajkarnikar11 @praweshsth @SauravSilwal10
