### ISSUE TITLE
ui-responsive-fixes

### ISSUE THREAD

**Issue by rajkarnikar11** [younginnovations/iatipublisher#947]

**Comment by rajkarnikar11** [comment]
- [ ]  Issue 1: remove sidebar sticky
- [ ]  Issue 2:  Breadcrumb and error message bar get overlap.
- [ ]  Issue 3: Period page scrollable.
- [ ] Issue 4: Untidy way to display complete status
- [ ]  Issue 5: Please display 2 arrows after the sidebar is displayed.
![image](https://user-images.githubusercontent.com/57949422/212230305-be7b01d4-49ba-4c6f-85ed-86138108ca3b.png)
- [ ] Issue 6: an inappropriate way to display toast message.
- [ ] Issue 7: Unnecessary Space in the sidebar.
- [ ] issue 8 : spacing below nav bar user managament
- [ ] issue 9 : active ra inactive ra language bata green color remove
- [ ] issue 10 : download checkmark in pagination
- [ ]  issue 11 : usermanagement multiselect ui
- [ ] issue 11 : usermanagement multiselect scroll issue

**Comment by rajkarnikar11** [comment]
- [ ] table last element tooltip hidden
- [ ] loader in usermanagement
- [ ] regpage help text tool tip
- [ ] miltiselect dropdoen hover ui issue
- [ ] settings model scrollbar

**Comment by rajkarnikar11** [comment]
- [ ] no data component in tabe of transanction,period,result,indicator listing page

**Comment by SauravSilwal10** [comment]
@rajkarnikar11  Issue found this fixes.

- [ ] **Issue 1 : User cannot click on the activity name.**

https://user-images.githubusercontent.com/78422663/213396253-78faed63-ccb7-4eed-8ce4-718db9986d41.mp4


- [ ] **Issue 2 : Inappropriate way to display side bar**

https://user-images.githubusercontent.com/78422663/213396989-096c16c6-e830-49fc-9108-c45c8ea54686.mp4


- [ ] **Issue 3 : Inappropriate way to display name in profile**
![Screenshot from 2023-01-19 14-37-09](https://user-images.githubusercontent.com/78422663/213397326-1239c1ef-a6b7-4f3d-9ca2-931260b40c67.png)

- [ ]  **Issue 4 : Inappropriate way to display toast message.**

https://user-images.githubusercontent.com/78422663/213399035-02fd00ea-83d8-44d6-83fe-e6835d58ce1b.mp4


- [ ] **Issue 5 : Button gets overlap**
![Screenshot from 2023-01-19 14-38-51](https://user-images.githubusercontent.com/78422663/213397724-4c6ba0b5-cd17-4365-8777-6ebcbe6552b6.png)
