### ISSUE TITLE
performance-optimization

### ISSUE THREAD

**Issue by rajkarnikar11** [younginnovations/iatipublisher#962]
- [x] asyncronous css 
- [ ] [Serve static assets with an efficient cache policy](https://gtmetrix.com/reports/publisher.iatistandard.org/IxP09jYr/#)

**Comment by rajkarnikar11** [comment]
- [x] dropdown flickering in load
- [ ] text transitioning on load

**Comment by rajkarnikar11** [comment]
- [ ] seperate web portal pages css
- [ ] import script.ts page only in inside pages

**Comment by praweshsth** [comment]
completed
