### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by man-git007** [younginnovations/iatipublisher#966]
Update readme file

Things to add

- [x] redis info
- [x] codefactor link ([![CodeFactor](https://www.codefactor.io/repository/github/younginnovations/iatipublisher/badge)](https://www.codefactor.io/repository/github/younginnovations/iatipublisher))
- [x] new packages if installed
- [x] update postgres version from 12 to 14
- [x] Mention unit test commands
- [x] Mention queue listen commands

**Comment by sriza** [comment]
Merged to the main branch. Closed manually
