### ISSUE TITLE
Allow users to cancel ongoing bulk publishing

### ISSUE THREAD

**Issue by Sanilblank** [younginnovations/iatipublisher#972]
When the system has an existing ongoing bulk publish process, the user cannot cancel it or start another one. If there is some problem in the server then the user may be stopped from ever performing the bulk publishing. We need to implement a system so that the user is able to cancel the ongoing bulk publishing process if he wants to start another bulk publishing process.

Also, when superadmin proxies as a user and performs bulk publishing, maybe we need to stop the superadmin from switching back as the same bulk publishing progress modal seems to persist for all organizations if proxied.

TASKS

- [x] When ongoing bulk publishing is taking place, allow users to cancel the process
- [x] Show proper information about the tasks that are going to be cancelled
- [x] Get proper confirmation from the user for cancelling the process

**Comment by SauravSilwal10** [comment]
@PG-Momik  Issue found in this branch.

- [ ] **Issue 1 : User get trapped in loop if the bulk activity is in  processing.**

- [ ] **Issue 2 : When user try to publish a single activity ,bulk publishing popup is displayed.**  

- [ ] **Issue 3 : Cancel previous bulk publish button is not working** 
- [ ] **Issue 4 : Popup should not be scroll able.**
